### ISSUE TITLE
Add test for multicluster external control plane doc

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#10068]
The optional [second part of the exteranal control plane doc](https://preliminary.istio.io/latest/docs/setup/install/external-controlplane/#adding-clusters) does not have a corresponding doc test yet.
We need to extend the [existing test](https://github.com/istio/istio.io/blob/master/content/en/docs/setup/install/external-controlplane/test.sh) to test this section as well.

Once the test is there, we can remove the `experimental feature` warning from that section of the doc.

**Comment by ericvn** [comment]
Fixed by https://github.com/istio/istio.io/pull/10127
