### ISSUE TITLE
Makefile:39: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by browncrane** [istio/istio.io#10138]
```
➜  istio.io git:(master) make serve
Makefile:39: *** missing separator.  Stop.
```

```
git log
commit 4c57b9962fadb0b04d084bb097afb46202a06064 (HEAD -> master, origin/master, origin/HEAD)
Author: Istio Automation <istio-testing-bot@google.com>
Date:   Fri Jul 30 19:49:58 2021 -0700

    Automator: update istio.io@ reference docs (#10136)

docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df35096d
 Built:             Thu Jun  3 01:27:40 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
```

Working on mac darwin amd64.

**update 2021/8/4**:
Actually it's arm64

**Comment by ericvn** [comment]
I am using a Mac amd64, and have been for quit a while` and don't see any issues:
``` make serve
Start building sites …

                   | EN  | PT-BR | ZH
-------------------+-----+-------+------
  Pages            | 743 |     5 | 675
  Paginator pages  |   0 |     0 |   0
  Non-page files   | 373 |     0 | 325
  Static files     | 194 |   194 | 194
  Processed images |   0 |     0 |   0
  Aliases          |   1 |     0 |   0
  Sitemaps         |   2 |     1 |   1
  Cleaned          |   0 |     0 |   0

Built in 45100 ms
Watching for changes in /work/{archetypes,assets,content,data,generated,i18n,layouts,static}
Watching for config changes in /work/config.toml, /work/go.mod
Environment: "development"
Serving pages from memory
Web Server is available at http://localhost:1313/latest/ (bind address 0.0.0.0)
Press Ctrl+C to stop
```
I do have some other zsh settings, but line 39 seems to imply a shell issue. Are you using `bash`, `zsh` or some other shell?

**Comment by ericvn** [comment]
Do you see a similar message when trying to do a `make clean` in one of the other Istio repos like istio/istio?

**Comment by browncrane** [comment]
Yes, in this repo, `make clean` has same message, but I haven't clone other Istio repos.

**Comment by ericvn** [comment]
I use `zpretzo`, but that shouldn't make a difference.  I'll try and look into this more, but since I can't recreate, it might be a little more difficult. What version of `make` are you using:
```
make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by ericvn** [comment]
I do see some inconsistent indentation in `common/scripts/setup_env.sh` with some of the LOCAL_ARCH and TARGET_OS lines of 4 or 5 spaces. I'm not sure if being in the script would cause the error or not.

**Comment by browncrane** [comment]
The `make` version is as same as yours.

**Comment by ericvn** [comment]
You probably need to resolve the executions, $(...),  yourself. An example would be running `/Users/<your id>/work/go/src/istio.io/istio.io/common/scripts/setup_env.sh` from the root istio.io directory. For me it just returns a command prompt.

Do you have a KUBE_CONFIG env var set? Maybe the code that tries to parse that is having an issue.

**Comment by browncrane** [comment]
```
/bin/bash -c ./common/scripts/setup_env.sh
This system's architecture, arm64, isn't supported
```
If the path change to absolute path `<your pwd output>/common/scripts/setup_env.sh`, the message is same.

**Comment by ericvn** [comment]
So sounds like you have an arm64 machine, that's what `uname -m` returns as well as your `docker version` above shows. Although you say you have an amd64 system.

I'm no sure how our build system works on a M1 Mac and what one might have to do to get things working (I don't have access to one at the moment).

One thing to do is pull the latest version of the code. There was a change that was merged two days ago the added some arm64 support (it should fix the message above about arm64 not being supported).

**Comment by browncrane** [comment]
The `amd64 system` is my mistake. I should announce  about M1 earlier.
After pull the latest version, the error disappear.
