### ISSUE TITLE
Versioned document is not usability

### ISSUE THREAD

**Issue by cbl315** [istio/istio.io#10147]
# Proposal

It would be better if the version is displayed at the top of the page, and the user can select the version through the drop-down box instead of to be redirected to another single page.

## Current

![image](https://user-images.githubusercontent.com/6824860/128117469-1cf01011-d6d4-4297-9517-05661b6fa918.png)

## Nice to have

![image](https://user-images.githubusercontent.com/6824860/128117536-be14dd9c-383f-43e7-883d-22007ab051eb.png)

**Comment by ericvn** [comment]
Similar to #9877

**Comment by howardjohn** [comment]
lets track in https://github.com/istio/istio.io/issues/9877
