### ISSUE TITLE
Known Kubernetes versions won't work

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#10151]
Given we move to v1 API for CRD such as mutating webhook configuration, I think this means k8s 1.15 won't work with Istio 1.11.  If this is true, I prefer us add a statement around "Istio 1.11 won't work with k8s 1.15 or older" in release notes and platform support pages.

@howardjohn @ericvn @brian-avery thoughts?

**Comment by howardjohn** [comment]
We broke 1.15 support in Istio 1.10. I think it's already in the notes and platform setup

**Comment by ericvn** [comment]
I haven't looked at `preliminary.istio.io`, but at least `istio.io` doesn't list 1.15 as a supported version starting with 1.7, and is no longer listed as untested starting with 1.10: https://istio.io/latest/docs/releases/supported-releases/, so I'm not thinking we need to add one.

I recall in TOC mention of adding a banner that 1.9.x won't work with k8s 1.22 so maybe there is some combined statement?

**Comment by howardjohn** [comment]
The reason it's important to announce the 1.22 one is (1) it's the first
time a new Kubernetes version has broken an old Istio version and (2) users
Kubernetes clusters may automatically update to 1.22 and break Istio.

Old k8s versions not working I'd much less risky and better understood by
users

**Comment by brian-avery** [comment]
I agree with John  and Eric. Iirc, we had breaking changes with 1.16 as well, so there's already issues with older versions of Kubernetes and we state that we don't support them.

**Comment by linsun** [comment]
There is a difference between unsupported versions vs versions it won't work.  

If you look at our platform setup page(https://istio.io/latest/docs/setup/platform-setup/), we don't tell users k8s 1.15 won't work for Istio.  We did say k8s 1.17 or older is not supported.

If we know some versions won't work for sure, we should tell it.

**Comment by brian-avery** [comment]
Are you thinking we'll always keep the list of definitely broken, possibly broken, and supported updated based on user issues or our own testing? 

We can call out 1.15 and 1.16, but I'm not sure what that implies for the support of 1.17 or how deep we'd want to go on specific features that are broken. 

My feeling is it should be assumed that anything below the supported versions is "your mileage may vary".

**Comment by linsun** [comment]
You are right that anything below supported version is "your mileage may vary" but if there are versions we know for sure it won't work, it is good to call out.  I think around Istio 1.8, we broke people on k8s 1.15 (it was not on supported list and we didn't call it out either) and we got a lot of criticism about it.  We ended up revert some of our changes so that k8s 1.15 could work (even tho it is not supported).

**Comment by howardjohn** [comment]
@linsun the page you linked is just a bad doc. The source of truth is https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases which is clear (IMO)

**Comment by ericvn** [comment]
As @howardjohn notes we have two ways to show the data. The `Supported Releases` page lists two items, those k8s versions we support, and a second broader list for which we mention we test, they may work, but not supported. On some pages, like the `Platform Setup` page (a quick count is 8 English pages), we only list the first portion of those, the supported versions. We could change the list displayed to point them to another page, but I'm not sure I want to have to have them click to find the answers. Showing the `supported` versions on the page should be enough.

That said, I suspect we want to add a Banner, but with what text, parameters.  Do we show it like we used to do new releases? 7 days and max 3 times? 7 days regardless? I'm not even sure what the banner looks like with the new site.

Would it say something like "Warning Kubernetes 1.22 is not supported by Istio release 1.9.x. Do not upgrade you Kubernetes version if you are using older Istio versions."

**Comment by ericvn** [comment]
Banners seem to work fine:
<img width="1477" alt="Screen Shot 2021-08-05 at 12 52 08 PM" src="https://user-images.githubusercontent.com/10537847/128397768-38ff8e53-9ebf-455b-bf6c-4c4fbb003d49.png">

**Comment by linsun** [comment]
@howardjohn +1 agree the page you pointed is much clear, we should like from platform page to there.  

@ericvn your banner looks great!

**Comment by ericvn** [comment]
@linsun I created a third PR which will add a link to the supported releases to the text before calling out the supported versions. Hopefully, this satisfies your comment about having a link on the platform page (and others).

**Comment by ericvn** [comment]
PRS have been merged for the work identified in this issue. I'll let @linsun close this issue if the changes are acceptable. Else, let us know here.

**Comment by linsun** [comment]
Thank you @ericvn !  LGTM!!
