### ISSUE TITLE
Adding Middleware by Casbin to official Istio List 

### ISSUE THREAD

**Issue by ashish493** [istio/istio.io#10171]
The Casbin community has been building an Envoy Middleware which authorizes the requests based on Casbin Policies. This middleware could be integrated to Istio for further usage.

Link to the Middleware:- https://github.com/casbin/envoy-authz
Link to the docs:- https://casbin.org/docs/en/envoy

Is there any official list of 3rd party applications for Istio, where we could add it? I was initially thinking of adding it here :- https://istio.io/latest/blog/2021/better-external-authz/#background under the 3rd party solution bullet.

**Comment by craigbox** [comment]
Please see https://istio.io/latest/about/ecosystem/ and send a PR against that page.

The instructions for a project are the same for companies as laid out [here](https://github.com/istio/community/blob/master/CONTRIBUTING.md#promote-your-company-on-istioio).
