### ISSUE TITLE
High CPU usage on istio.io homepage

### ISSUE THREAD

**Issue by GregHanson** [istio/istio.io#10172]
Seeing at least 60% CPU usage on the Istio.io homepage on Safari, Chrome and Firefox browsers on my Mac.  No CPU spike on the other pages on the site, only the main page.  Similar .io website rarely hit double digits.

**Comment by craigbox** [comment]
It will be the particle animation (https://github.com/istio/istio.io/blob/master/src/ts/headerAnimation.js). It uses Three.js to draw the waves.

Options include: improve performance of the JS, convert it from canvas/JS to pure CSS rendering, replace it with a static graphic, remove it entirely.

Marking "help wanted" as the vendor who built this is not longer available to us.

**Comment by GregHanson** [comment]
@craigbox The graphic was my guess as well.  tetrate.io was one of the other sites I checked, and it has a moving graphic on the homepage and the site doesn't hit the double digits.  I didn't check their source to see how it was done but figured the CPU comparisons warranted opening an issue at least for tracking purposes.

**Comment by craigbox** [comment]
Theirs is a looping .webm video. 
Perhaps Tetrate have some frontend devs who could have a look at istio.io for us? 🙂 @ZackButcher

**Comment by ravikiranr26** [comment]
Hello, This is an intersting one and Would take this up and investigate further. As @craigbox mentioned, it should be caused due the animations and usage of high GPU and Rendering required to process for istio landing page.

Request to assign it to me.

<img width="824" alt="image" src="https://user-images.githubusercontent.com/1841796/151171366-b63f3005-04e1-4544-8830-7c14ab83f98b.png">

<img width="859" alt="image" src="https://user-images.githubusercontent.com/1841796/151172214-c5025de6-a5c5-49d8-ae99-9a3a83af51bb.png">

**Comment by craigbox** [comment]
Thanks for taking this on @ravikiranr26 !

**Comment by GregHanson** [comment]
this is still an ongoing issue

**Comment by leosarra** [comment]
My knowledge of Three.js is a bit rusty but I have an idea on why the cpu is affected.
I will take a look into this when I have a bit of time and I will rewrite it to work in a more efficient way

**Comment by craigbox** [comment]
Wonderful work @leosarra.  Thank you!
