### ISSUE TITLE
MeshConfig outline overlaps and makes reading difficult

### ISSUE THREAD

**Issue by totallyGreg** [istio/istio.io#10225]
![image](https://user-images.githubusercontent.com/283704/130690541-fb2efaf8-5354-4a50-bb8a-356e78ea51d8.png)

This seems to be an issue in latest Safari and Chrome on MacOS 11.5.2

**Comment by ericvn** [comment]
Duplicate of https://github.com/istio/istio.io/issues/9858?

**Comment by ericvn** [comment]
Should be fixed. Please reopen if you still see an issue.
