### ISSUE TITLE
[DOCS] The document for SPIFFE no longer exists

### ISSUE THREAD

**Issue by VariableDeclared** [istio/istio.io#10283]
Hi

The document linked at https://istio.io/latest/docs/ops/deployment/deployment-models/#trust-between-meshes not longer exists,

Cheers

Peter

**Comment by craigbox** [comment]
This is an old doc from a VMware/Google collab in 2019.  Can anyone recommend a better one?

**Comment by stevenctl** [comment]
cc @costinm, can you recommend a replacement resource?

**Comment by howardjohn** [comment]
now points to https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Federation.md
