### ISSUE TITLE
The doc for "Istio Operator Install" seems to contain incorrect info

### ISSUE THREAD

**Issue by syedrakib** [istio/istio.io#10321]
This issue is related to https://github.com/istio/istio.io/issues/9892#issuecomment-917119319

## Steps to reproduce the error

I deleted all istio namespaces from my GKE cluster

```bash
$ kubectl delete namespace istio-operator istio-system
```

Installed **istioctl version 1.10.2** in MacOS following https://istio.io/latest/docs/ops/diagnostic-tools/istioctl/?_ga=2.53425067.2032442266.1631216965-1634768249.1631055742#install-hahahugoshortcode-s2-hbhb

Then installed istio-operator

```bash
$ istioctl operator dump > operator_dump.yaml
$ kubectl apply -f operator_dump.yaml
```

Confirmed that the istio-operator is up & running

```bash
$ kubectl rollout status deployment/istio-operator -n=istio-operator
deployment "istio-operator" successfully rolled out
```

## The Error

The next step involves applying the IstioOperator CRD following https://istio.io/latest/docs/setup/install/operator/?_ga=2.63248428.2032442266.1631216965-1634768249.1631055742#install

```bash
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```

At this point i expect it to just work. But i got the following error:

```
Error from server (NotFound): error when creating "STDIN": namespaces "istio-system" not found
```

## But documentation says otherwise

The docs at https://istio.io/latest/docs/setup/install/operator/?_ga=2.233666461.2032442266.1631216965-1634768249.1631055742#install says 

> Prior to Istio 1.10.0, the namespace istio-system needs to be created before installing the operator. As of Istio 1.10.0, this is no longer required.

---

Looks like the istio operator needs a fix or the docs needs to be revised.

**Comment by craigbox** [comment]
@jacob-delgado @shamsher31 could you take a look?  I think you updated the comment/feature and it may not be correct.

**Comment by shamsher31** [comment]
Based on this change https://github.com/istio/istio/pull/31237, The namespace `istio-system` gets automatically created if you use the following command.
```
$ istioctl operator init
```
and then apply IstioOperator CRD

```yaml
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```

As mentioned in your command, the `kubectl apply` don't have knowledge of whether the namespace `istio-system` exists or not.

On the other hand `istioctl operator init` is smart enough to detect if namespace exists, and if it is not, it will automatically create those namespaces for you.

@syedrakib If you are using operator installation using `operator dump` command, you need to manually create the namespace `istio-system` and then apply IstioOperator CRD.

@ericvn The docs are written as per `istioctl operator init`, so I think it needs to be improved to cover other methods of installation?

**Comment by ericvn** [comment]
We could add a warning, or tip, to the doc mentioning that if you use something other than `istioctl operator init`, then the `Istio-system` namespace needs to be created. Also we could update the line to say something like: As of  Istio 1.10.0, the `istioctl operator init` will create the `Istio-system` namespace.

**Comment by craigbox** [comment]
I think that point 4 of Prerequisites isn't a prerequisite: it's more of a **requisite**.  Let's move it into the below heading.

**Comment by syedrakib** [comment]
I agree with @ericvn . The [current doc](https://istio.io/latest/docs/setup/install/operator/?_ga=2.233666461.2032442266.1631216965-1634768249.1631055742#install) says:

> Prior to Istio 1.10.0, the namespace istio-system needs to be created before installing the operator. As of Istio 1.10.0, this is no longer required.

That could be modified to add one more phrase

> ... if you are using `istioctl operator init`

This I think would be the quickest clarification.
