### ISSUE TITLE
Envoy debug example doesn't work in 1.10

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#10335]
https://istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/ says:

> **What Envoy version is Istio using?**
> To find out the Envoy version used in deployment, you can exec into the container and query the server_info endpoint:
> `$ kubectl exec -it productpage-v1-6b746f74dc-9stvs -c istio-proxy -n default -- pilot-agent request GET server_info --log_as_json | jq {version}`
> `{ "version": "2d4ec97f3ac7b3256d060e1bb8aa6c415f5cef63/1.17.0/Clean/RELEASE/BoringSSL" }`

As of 1.10, JQ isn't installed in the proxy container.  An ugly fix is to just change the pipe to grep for `'"version": "'`.  

You can get similar info from `istioctl proxy-config` but it's in a string marked `hidden_envoy_deprecated_build_version` which doesn't fill one with hope for longevity.

**Comment by shamsher31** [comment]
@craigbox I have 1.10.2 installed
```
$ istioctl version
client version: 1.10.2
control plane version: 1.10.2
data plane version: 1.10.2 (7 proxies)
```
and I can query the version using `jq`.

```
$ kubectl exec -it productpage-v1-6b746f74dc-4kvrr -c istio-proxy -n default  -- pilot-agent request GET server_info --log_as_json | jq {version}
{
   "version": "5952f5fb5f85f495ac6d0925539dcd445cd618a0/1.18.3/Clean/RELEASE/BoringSSL"
}
```


> As of 1.10, JQ isn't installed in the proxy container.

I think `jq` needs to be installed separately (at least on Linux) and it's not a part of the proxy container?

**Comment by craigbox** [comment]
Hmmm, looks like something I was confused and the error message came from the VM I was running on, not the proxy container.  Sorry!
