### ISSUE TITLE
Issue with _docs/concepts/traffic-management/pilot.md

### ISSUE THREAD

**Issue by eshwarne** [istio/istio.io#10388]
A link is broken : 
Pilot exposes APIs for **service discovery**, dynamic updates to load balancing pools and routing tables. These APIs decouple Envoy from platform-specific nuances, simplifying the design and increasing portability across platforms.

(https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/sds)

**Comment by ericvn** [comment]
I believe this is from versions of the docs prior or equal to 1.0. Those Istio versions and the docs are no longer supported or being built.

**Comment by ericvn** [comment]
Thanks for the issue. Based on the thumbs up emoji, this issue is for pages we no longer update. Thus I will close this issue.
