### ISSUE TITLE
disable mTLS instruction isn't accurate

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#1039]
I don't think the instruction is entirely correct after mTLS among istio components is enabled:  https://istio.io/help/faq/security.html#enabling-disabling-mtls

I followed the instruction but after I describe the pilot pod, I still see mTLS for the istio-proxy that is on the same pod as pilot container.

```
  istio-proxy:
    Container ID:  docker://ee1a8fe1cf49b30139e4e3f9cfa5f677cc1ae210cde9004f78e70f21f4f7c01e
    Image:         docker.io/istio/proxy:0.5.0
    Image ID:      docker-pullable://istio/proxy@sha256:3a9fc8a72faec478a7eca222bbb2ceec688514c95cf06ac12ab6235958c6883c
    Port:          15003/TCP
    Args:
      proxy
      pilot
      -v
      2
      --discoveryAddress
      istio-pilot:15003
      --controlPlaneAuthPolicy
      MUTUAL_TLS
      --customConfigFile
      /etc/istio/proxy/envoy_pilot_auth.json
```

**Comment by linsun** [comment]
I think we need to modify all containers that use istio-proxy image to use the following args:

      --controlPlaneAuthPolicy
      NONE

anything else?

**Comment by ldemailly** [comment]
that sounds like a pretty bad regression if that's the case, are you sure?

**Comment by linsun** [comment]
why is this a regression?  i think we just need to update the doc.

**Comment by costinm** [comment]
Things changed in 0.6:  now pilot has 2 ports, one with mTLS and one
without
(similar with how http/https work)

To avoid breakages, port 8080 and 15003 are left as they are in previous
versions.

Control-plane security is separate from dataplane security: if you have
data-plane
apps already using TLS it's very reasonable to disable istio mtls, but
talking to
pilot still needs to be secured, since pilot is controlling secure naming
and routing.

Regarding default value: I have strong opinions, but unfortunately on both
sides :-)

**Comment by ldemailly** [comment]
since 0.2 you could switch mtls on/off for the mesh with 1 edit of configmap and 1 restart of pilot, if now you have to edit all the deployments that seems like a regression to me but maybe I am missing something

**Comment by linsun** [comment]
>  if you have data-plane apps already using TLS it's very reasonable to disable istio mtls

That is a really corner scenario.  Most scenario is I want to get something working with istio, let me disable mTLS to get my app working first.  That is what I'm doing. I can't debug my app easily when the control plane security is enabled as I can't access my app using LB service ip or node port when the control plane security is turned on.  I think we are making users on board to istio much harder.

I ended up redeploy istio... delete my istio-auth.yaml and re-apply istio.yaml.

**Comment by ldemailly** [comment]
maybe move this to istio/istio as it's not really a doc issue

**Comment by wattli** [comment]
Lin, what version are you using? If you are using the lastest daily build, you should not see 15003.

**Comment by wattli** [comment]
Lin, i tested last week and do not see the error. And i used daily build of 03/13. And I will update the doc soon.

**Comment by wattli** [comment]
No activities for 23 days.

**Comment by linsun** [comment]
Dan tried this again on 0.7.1, still doesn't work when following the steps to change istio from non mTLS to mTLS

**Comment by linsun** [comment]
```there are many other places where the variables are referenced and are not taken from the config map
basically the entire control plane components have a hard coded environment variable in the deployment descriptor
only the injector uses the config map
but even after making the necessary changes and restarting I still cannot get it to work```
from @dcberg

**Comment by wattli** [comment]
See my comment above, i tested before and it worked. Will test it again and get back to you soon.

**Comment by wattli** [comment]
@incfly

**Comment by wattli** [comment]
@incfly , please help to verify, thanks.

**Comment by linsun** [comment]
yes, that was the prob.  @dcberg  also tried uncomment on `controlPlaneAuthPolicy: MUTUAL_TLS` too and he could not get it work.  As long as you can get control plane started fine after the configuration change to switch from non mTLS to mTLS, please go head update the doc and i will do another validation.

**Comment by incfly** [comment]
@jasmine-jaksic No, at least I didn't. 

But now with new model to turn on mTLS globally, [design doc](https://docs.google.com/document/d/1rM4TvMRwsvGx_qP0ysAHcFD7YN-QUn9AsIMIDt1aEPM/edit?ts=5b197f95#), and we discourage people to use `authPolicy` config map flag, and even deprecate it sometime https://github.com/istio/istio/issues/5900

I think we should document the new intended usage.
@diemtvu @wattli

**Comment by diemtvu** [comment]
I think the FAQ was  meant for data plane mTLS. Changing control plane auth policy should not be done by this.
Regardless, we could re-write the instruction only for > Istio 0.8, i.e using authentication policy + destination rule.

**Comment by diemtvu** [comment]
Instruction has been updated for 1.0. We don't have a way to change control plane mTLS at runtime (without restart pilot with new flag). Close this bug as it's different issue.

**Comment by linsun** [comment]
I agree, this scenario has been made a lot easier now.
