### ISSUE TITLE
clarify kubernetes support version for Istio 1.11

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#10550]
Folks, we have conflicts info in 2 places for Istio 1.11.  Can we reach agreement on which one is right and update them accordingly?

https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases: k8s 1.19-1.22 for Istio 1.11
https://istio.io/latest/news/releases/1.11.x/announcing-1.11/: k8s 1.18-1.22 for Istio 1.11

Based on TOC note, seems the prior one is correct?

cc @istio/technical-oversight-committee

**Comment by howardjohn** [comment]
Given we already announced 1.18 it would be a bit odd to walk that back IMO. Since we are already testing it anyways, I suggest we go with the conservative approach and stick to 1.18 for this release.

**Comment by ericvn** [comment]
I agree with @linsun that the TOC did approve the first range (1.19-1.22), but agree at this point (4 months after release) with @howardjohn that we could probably just extend the documented supported range, so my vote would be to be consistent on 1.18-1.22.

**Comment by linsun** [comment]
+1 I'm in favor of that as well. I'll send a small PR for this.

**Comment by ericvn** [comment]
One additional comment is that the actual 1.11 pages, like https://istio.io/v1.11/docs/setup/getting-started/, only call out 1.19-1.22 as supported (they use the values specified in the data/args.yaml). Since that release is archived, it's not an easy fix to also update them.

**Comment by linsun** [comment]
That may be okay, given not many users look at the archive docs.

**Comment by ericvn** [comment]
Fixed by https://github.com/istio/istio.io/pull/10608
