### ISSUE TITLE
Remove `Mutual TLS Migration` from the feature status page

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#10591]
This is not a feature in Istio Security but is simply a security task. In the [feature stage](https://istio.io/latest/docs/releases/feature-stages/#security-and-policy-enforcement) page for Istio, we show this as a beta feature. Referring to the discussion on the [feature status page created to track this feature in the enhancement repo](https://github.com/istio/enhancements/pull/83) as to why we decided to remove this as a feature mention. A corresponding PR will also be created in the enhancement repo to remove this from the features.yaml file.

**Comment by ericvn** [comment]
Note that the enhancement repo PR will drive the change in the istio.io repo.

**Comment by johnma14** [comment]
Made this change in the enhancement repo as well; https://github.com/istio/enhancements/issues/113

**Comment by johnma14** [comment]
Closing this as the change in the enhancement repo will suffice.
