### ISSUE TITLE
Maybe need to update the version of Hugo to the latest one?

### ISSUE THREAD

**Issue by Arhell** [istio/istio.io#10656]
Now https://github.com/istio/istio.io/blob/master/netlify.toml (0.61)
Latest https://github.com/gohugoio/hugo/tags

cc @craigbox

**Comment by craigbox** [comment]
Is there a specific problem that you're suggesting we fix by upgrading? 
The Docs WG doesn't have a lead at the moment, so we don't have a lot of time to spend here.
