### ISSUE TITLE
[docs] mirroring in traffic-management task has wrong sleep service images

### ISSUE THREAD

**Issue by mark4z** [istio/istio.io#10787]
https://istio.io/latest/zh/docs/tasks/traffic-management/mirroring/
Image tutum/curl has been deleted.

May be i can fix it.

![image](https://user-images.githubusercontent.com/36187602/149614805-10e2e4b2-5479-465c-93fb-38da7d961c2f.png)

**Comment by ericvn** [comment]
It looks like this was fixed in the English docs with https://github.com/istio/istio.io/pull/9830 and should just be a two line update (image and command).

**Comment by mark4z** [comment]
Yes, may I can fix it
