### ISSUE TITLE
Virtual Machine tests fail when run against 1.13

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#10814]
TestDocs/examples/virtual-machines/test.sh and TestDocs/setup/install/virtual-machines/test.sh fail when run in the new 1.13 branches.

I disabled the tests to get the branching PR https://github.com/istio/istio.io/pull/10808 merged, and opening this issue (release blocker for 1.13 since we broke the docs) to fix the issue before release.

Example failure: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/10808/doc.test.profile_none_istio.io/1484529181084618752

**Comment by ericvn** [comment]
This happened in an earlier release and in that case, after some time the tests started passing and not sure why.

**Comment by stevenctl** [comment]
Potentially related: https://github.com/istio/istio/issues/37056
