### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by zirain** [istio/istio.io#10862]
go to page https://istio.io/latest/docs/reference/config/networking/virtual-service/

scroll to the bottom, the link is broken with an error url `https://preliminary.istio.iodocs/reference/config/networking/virtual-service/`

![image](https://user-images.githubusercontent.com/4354057/152709901-1acd8d11-e357-4cb5-8a40-e26db3b9c548.png)

**Comment by zirain** [comment]
@ericvn may cause by https://github.com/istio/istio.io/pull/10842

**Comment by ericvn** [comment]
It looks like this is a problem across all the pages on istio.io where `next release` fails to get one to preliminary.istio.io. I also note that is you go from earlier releases, things are broken as well.

**Comment by zirain** [comment]
> It looks like this is a problem across all the pages on istio.io where `next release` fails to get one to preliminary.istio.io. I also note that is you go from earlier releases, things are broken as well.

only the root page is ok

**Comment by ericvn** [comment]
It looks like the change should probably have been in the code related to:
```
                {{ $fileDir := "" }}
                {{ with .File }}
                    {{ $fileDir = .Dir }}
                {{ end }}
```
where we leave  fileDir empty id Dir == `/`.
