### ISSUE TITLE
Slack Invite Link is Broken

### ISSUE THREAD

**Issue by jakexks** [istio/istio.io#10865]
https://istio.io/latest/get-involved/ invites visitors to join the Istio Slack, but the link has expired.

**Comment by linsun** [comment]
Which link is he clicking into?  It directs me to slack.istio.io which wfm

**Comment by ericvn** [comment]
@craigbox What needs to be done to set this up again? I know the link, under step #3, fails in an incognito browser tab.

**Comment by jakexks** [comment]
@linsun, my experience is the same as reported by @ericvn above, I get redirected to an "expired" invite.

**Comment by craigbox** [comment]
Each generated email link is only good for XXXX uses. I'll have to generate a new one and update the service.

**Comment by craigbox** [comment]
Updated, and documented [here](https://docs.google.com/document/d/1Pf6vS5SiYuSD55atbosoSHktIi1N08p-P480buzCrDk/edit#).
