### ISSUE TITLE
No space after countdown_days in sticker

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#11184]
https://istio.io/

<img width="197" alt="image" src="https://user-images.githubusercontent.com/132510/163745550-07b41a98-7f82-400e-a03b-23fc3d31f2e3.png">

generates this markup
```
<div class="wrap"><div class="content"><p><span class="countdown" data-type="days">7</span>days until IstioCon!</p></div></div>
```

However, on both my local Hugo preview (v0.94.2) and preliminary, it renders correctly, with 

```
<div class="wrap"><div class="content"><p><span class="countdown" data-type="days">7</span> days until IstioCon!</p></div></div>
```

Local Hugo and `release-1.13` are both still using `blackfriday`, prelim isn't, so I don't think that's part of the problem.

**Comment by ericvn** [comment]
Release-1.13 branch is using an older Hugo (0.61?). We only updated to a more recent Hugo in the main branch? Cerry-pick https://github.com/istio/istio.io/pull/11090 back and see what happens with the netlify output? Any concerns about updating Hugo in the middle of a release?

**Comment by ericvn** [comment]
This has been fixed by https://github.com/istio/istio.io/pull/11185.
