### ISSUE TITLE
Ecosystem pages (pro servces/integrations) and Get Involved on preliminary.isito.io have errors:

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#11240]
Not sure if this is because of a recent Hugo update. I believe `preliminary.istio.io` is using a newer version than `istio.io`

Example: https://preliminary.istio.io/latest/about/ecosystem (then select Pro Service or Integrations)

```
    <button class="panel panel--bordered" onclick="insertCompanyModalDetails({&#34;description&#34;:&#34;With over 8 years of cloud consulting experience, CloudZone provides consulting services and execution of end-to-end Kubernetes and DevOps projects including platform architecture, CI/CD automations, service meshes and more.&#34;,&#34;details&#34;:[&#34;At CloudZone, we’ve been actively involved with Kubernetes and Istio since the very first editions came out.&#34;,&#34;In today’s fast-paced, ever-changing world, we continue to research the field keeping up to date so that we can bring you the very latest thinking and solutions, whether we are supporting you through the provision of consulting, design, training or production support services.&#34;,&#34;Our certified Kubernetes administrators and cloud experts are highly skilled in building production-grade Kubernetes systems with the latest Cloud native tools for automating application deployment, scaling and management, together with the open source Istio service mesh for connecting, securing, controlling and observing services.&#34;],&#34;logo&#34;:&#34;/logos/cloudzone.svg&#34;,&#34;name&#34;:&#34;CloudZone&#34;,&#34;url&#34;:&#34;https://cloudzone.io/&#34;}); showModal()">

```
<img width="833" alt="Screen Shot 2022-04-28 at 9 52 08 AM" src="https://user-images.githubusercontent.com/10537847/165780879-a14f71fc-af20-471c-b222-60fa18b559d5.png">

**Comment by ericvn** [comment]
I did try `make serve` locally with the latest build image (has Hugo 0.97.3) and one I built with the older 0.95.0 Hugo release, and both showed this error. I was hoping to show that 0.95.0 would solve the issue.

**Comment by ericvn** [comment]
So likely related to BlackFriday removal in https://github.com/istio/istio.io/pull/11161?

**Comment by ericvn** [comment]
Also see https://preliminary.istio.io/latest/get-involved/

**Comment by craigbox** [comment]
@davidhauck are you able to have a quick look at this one?

**Comment by nandita-cloudscaleinc** [comment]
Can we raise this issue here https://github.com/gohugoio/hugo/issues/new as with Hugo update also this didn’t got resolved

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/pull/11333 opened to revert if needed.

**Comment by ericvn** [comment]
Closing as we reverted to Blackfriday. We will need to verify all pages before we move to the new generator.
