### ISSUE TITLE
istio oldies [1.0], perf concepts: restored some url to woking but iframe not showing

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.io#11311]
So 
https://github.com/istio/istio.io/blob/release-1.0/content/docs/concepts/performance-and-scalability/index.md

has iframes to showcase some fortio graphs, which we restored (they were broken for a while) - thanks a lot Craig for the DNS update (the new deployment is https://github.com/fortio/demo-deployment if anyone is curious)

e.g https://fortio.istio.io/?xMin=2&xMax=110&xLog=true&yMin=&yMax=&yLog=false&sel=qps_400-s1_to_s2-0.7.1-2018-04-05-22-06&sel=qps_400-s1_to_s2-0.6.0-2018-04-05-22-33 now works again for instance

but looking at the actual live site:

https://istio.io/v1.0/docs/concepts/performance-and-scalability/#synthetic-end-to-end-benchmarks

no iframes there somehow?

(also a couple of broken images)

This being said given this is 1.0 and super old it doesn't matter too much - I was hoping the dns was a quick fix, and maybe if that is also a super small fix otherwise I understand it's not worth fixing
 
Thanks!

**Comment by ericvn** [comment]
@davidhauck may know something of this as well.

**Comment by davidhauck** [comment]
Maybe this is something with how hugo compiled the site? You can take a look at the live html here, and you can directly edit it if you want. https://github.com/istio/istio.io/blob/master/archive/v1.0/docs/concepts/performance-and-scalability/index.html

Not sure how easy it will be to regenerate the entire 1.0 site since tooling has changed so much.

**Comment by ldemailly** [comment]
Thank you - is manually editing the generated file an option or it'd get auto overridden? and/or it wouldn't get pushed? (how is it pushed?)

**Comment by davidhauck** [comment]
The chances of getting it overwritten are pretty small since we don't really generate old releases any more. If you wanted to ensure the changes stick, you would have to check out the release-1.0 branch and add the changes there as well (to the md file).

**Comment by ldemailly** [comment]
The thing is the source is already good :) just fixing the html then:

https://github.com/istio/istio.io/pull/11312/commits/66b985998c85bed93d9be6da63246649c8ce9782
