### ISSUE TITLE
Docs need an update regarding Istio + Kind due to breaking changes in K8s 1.24

### ISSUE THREAD

**Issue by robertgartman** [istio/istio.io#11315]
The instructions about [Setup Dashboard UI for kind](https://istio.io/latest/docs/setup/platform-setup/kind/#setup-dashboard-ui-for-kind) need to be revised for K8s 1.24

[Breaking changes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#no-really-you-must-read-this-before-you-upgrade) related to `LegacyServiceAccountTokenNoAutoGeneration` require minor changes to acquire the K8s Dashboard auth token.

Related, though closed, issues kubernetes/dashboard#7101,  kubernetes/dashboard#7094 and kubernetes/dashboard#7081

**Comment by ericvn** [comment]
Will take a look to see if this is still an issue.

**Comment by dxps** [comment]
I can confirm that at the time of this writing (using kind 0.16.0 and kubectl 1.25.2), [Setup Dashboard UI for kind](https://istio.io/latest/docs/setup/platform-setup/kind/#setup-dashboard-ui-for-kind) does not work: at least no token can be retrieved.
