### ISSUE TITLE
DestinationRule reference and sidebar disappeared

### ISSUE THREAD

**Issue by merusso** [istio/istio.io#11365]
On the "Destination Rule" reference page (Documentation / Reference / Configuration / Traffic Management / Destination Rule), the DestinationRule reference (below the summary and examples) and sidebar TOC no longer appear.

Expected:
![image](https://user-images.githubusercontent.com/6686087/171505293-dacd2419-88dc-4a79-9cc7-7b2306692cda.png)

Actual:
![image](https://user-images.githubusercontent.com/6686087/171505181-975f79c5-c27d-406d-aa40-0e809eb7f07f.png)

Links:
* URL (reference missing): https://istio.io/latest/docs/reference/config/networking/destination-rule/
* cached URL (reference exists): https://github.com/istio/istio.io/blob/master/content/en/docs/reference/config/networking/destination-rule/index.html

**Comment by hobbytp** [comment]
yes, I also found find that.

**Comment by GregHanson** [comment]
This is part of https://github.com/istio/api/pull/2371

**Comment by GregHanson** [comment]
Until the fix gets fully merged, for now the changes can be viewed at https://preliminary.istio.io/latest/docs/reference/config/networking/destination-rule/

**Comment by kfaseela** [comment]
Hope it is all good now? https://istio.io/latest/docs/reference/config/networking/destination-rule/
