### ISSUE TITLE
spire-quickstart.yaml path is incorrect in doc "Install SPIRE Option 1: Quick start"

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#11374]
The current doc said the spire-quickstart path is incorrect.
```bash
kubectl apply -f @samples/security/spire/spire-quickstart.yaml
```
but it should follow other similar formats as below, 
```bash
kubectl apply -f samples/security/spire/spire-quickstart.yaml
```
refer https://istio.io/latest/docs/examples/bookinfo/ to get the correct example.

**Comment by frankbu** [comment]
#11387 has not fixed this issue. It fixed another similar problem with `@samples/security/spire/sleep-spire.yaml` in the same doc.
