### ISSUE TITLE
A typo in shared-gateways pages

### ISSUE THREAD

**Issue by lipingtababa** [istio/istio.io#11501]
In pages
https://istio.io/v1.2/docs/setup/kubernetes/install/multicluster/shared-gateways/
https://istio.io/v1.3/docs/setup/install/multicluster/shared-gateways/
https://istio.io/v1.4/docs/setup/install/multicluster/shared-gateways/

there is a typo in 
```
In cluster1, the gateway IP of cluster2 (192.23.120.32:15443) is logged when v2 was called and the instance IP in cluster1 (10.10.0.90:5000) is logged when v1 was called.

In cluster2, the gateway IP of cluster1 (192.168.1.246:15443) is logged when v1 was called and the gateway IP in cluster2 (10.32.0.9:5000) is logged when v2 was called.
```

The second `gateway` in line 2 should be `instance` just like it is in line 1.

In page
https://istio.io/v1.5/docs/setup/install/multicluster/shared/ 
there is a similar typo in
```
In the remote cluster, the endpoints are the gateway IP of the main cluster (192.168.1.246:443) and the pod IP in the main cluster (10.32.0.9:5000).
```
The second `main cluster` should be `remote cluster`.

Before v1.2 or after v1.5, there is no such typo.

**Comment by ericvn** [comment]
We typically don't make changes in archives, although we can for for substantially incorrect changes. Also these releases have been EOL and not supported for a long time.
