### ISSUE TITLE
Table width error

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#11516]
https://istio.io/latest/docs/releases/feature-stages/#feature-phase-definitions

<img width="922" alt="Screen Shot 2022-06-29 at 4 25 10 PM" src="https://user-images.githubusercontent.com/132510/176475030-9ddb48c0-903a-4032-8e5a-44d54d445bb5.png">

**Comment by craigbox** [comment]
Ihor, I wonder if you had time to look at this?

**Comment by Arhell** [comment]
> Ihor, I wonder if you had time to look at this?

This happened after edits on links that went beyond the block
https://github.com/istio/istio.io/pull/10501
But I'll see what I can do
