### ISSUE TITLE
sentence in Istio upgrade missing second option

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#1167]
https://github.com/istio/istio.github.io/blame/master/_docs/setup/kubernetes/upgrading-istio.md#L46
```
If there is any issue with the new control plane, you can rollback the changes either by applying the old version yaml files.
```

what is plan B?

**Comment by sdake** [comment]
cc @yusuoh

**Comment by ericvn** [comment]
Looking at this page, I see that the wording is now: `If there is any critical issue with the new control plane, you can rollback the changes by applying the yaml files from the old version.` so there is no longer a missing second option.

I think this issue can be closed unless we need to create a similar change in prior releases.
