### ISSUE TITLE
Minor formatting - search page button

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#11750]
The sort button text runs over: https://preliminary.istio.io/latest/search/?q=rate%20limit

<img width="206" alt="Screen Shot 2022-08-25 at 9 44 29 AM" src="https://user-images.githubusercontent.com/10537847/186696306-1930b773-f887-47ba-b51a-89e84f23b51e.png">

**Comment by ericvn** [comment]
Looks similar on istio.io, so not related to Goldmark.

**Comment by zirain** [comment]
this's an google cse bug
![image](https://user-images.githubusercontent.com/4354057/186836244-997f237b-b24e-4ca7-8b00-905302d9ab81.png)
