### ISSUE TITLE
headers in distributed tracing doc is confusing

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#1176]
I have 2 services (A -> B)  and I followed the doc to update the A's code so that i can see the 2 trace spans (A & B) in a single request.

What is confusing is that the doc (https://istio.io/docs/tasks/telemetry/distributed-tracing.html#understanding-what-happened) asked me to propagate these headers and I did.   Of course, stuff never works on first try :)   However, From capturing of headers, I noticed only certain headers are described in the doc is propagated from istio-ingress to my service A, thus my service A is only propagating the following headers to service B:

map[Content-Type:[application/json] 
X-Request-Id:[f395e25c-9026-9c39-b1b8-9459929f48c7] 
X-B3-Traceid:[ba82cc26ee25e908] 
X-B3-Spanid:[ba82cc26ee25e908] 
X-B3-Sampled:[1]]

It turned out these headers are fine, but took me quite a while to realize it and find trace spans for my req.

I think our doc needs to be updated to the latest headers that is relevant.

**Comment by linsun** [comment]
Or if we are missing headers in our ingress impl in 0.7.1

**Comment by douglas-reid** [comment]
We ask that you forward more than the minimal set to support the full range of b3 headers, etc.  I agree that we may need to reassess the use of `b3` as the openzipkin b3 header spec evolves. I'm going to close this for now. We can reopen when we support `b3` header.
