### ISSUE TITLE
Kubernetes ingress documentation is outdated and unsupported since 1.22

### ISSUE THREAD

**Issue by scarby** [istio/istio.io#11779]
The Following page needs to be re-written as it uses k8s ingress syntax deprecated in 1.19 and removed in 1.22:

https://github.com/istio/istio.io/blob/master/content/en/docs/tasks/traffic-management/ingress/kubernetes-ingress/index.md

I'll likely raise a PR for this but don't have time for the next week or so.

**Comment by johnma14** [comment]
This is the same as https://github.com/istio/istio.io/issues/12013 and will be fixed there. Closing this one. Thank you @scarby  for reporting this.
