### ISSUE TITLE
how to sync reference docs?

### ISSUE THREAD

**Issue by zirain** [istio/istio.io#11960]
follow up https://github.com/istio/istio.io/pull/11939#issuecomment-1251016538

let's try to find out a better way to sync reference docs

IMHO, I did not believe it's a good idea to translate reference doc to Chinese or other language,  a synced English doc is better than translated but old docs. 

WDYT cc @ericvn @windsonsea ?

**Comment by windsonsea** [comment]
Ok, noted, all right.

It's a good and relatively easy way to choose the automated reference docs.

**Comment by zirain** [comment]
closed as fixed
