### ISSUE TITLE
Performance doc charts are out of date.

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#11986]
https://istio.io/latest/docs/ops/deployment/performance-and-scalability/

Docs use {{< istio_release_name >}} so they state 1.15.

Chart svgs were last updated for 1.8 https://github.com/istio/istio.io/pull/8574

The results in the text are likely out of date as well.

**Comment by zirain** [comment]
perf site has down for a long time.

**Comment by ericvn** [comment]
Performance data is back.
