### ISSUE TITLE
Doc test framework _wait_for_istio function doesn't work any more

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#12056]
Every call to the `_wait_for_istio` is failing lately and printing messages in the log like this:

```
Error: invalid character 'P' looking for beginning of value
Failed distribution of virtualservice httpbin in namespace default
NAME                                                    CLUSTER        CDS        LDS        EDS        RDS          ECDS         ISTIOD                      VERSION
httpbin-74fb669cc6-mvqr2.default                        Kubernetes     SYNCED     SYNCED     SYNCED     SYNCED       NOT SENT     istiod-5d5f6bd4c8-t9tb6     1.16-alpha.f8b4dc7bccc1fd2044c6014aea29368d46f086cc
istio-eastwestgateway-6d47fc4ddf-h7hwh.istio-system     Kubernetes     SYNCED     SYNCED     SYNCED     NOT SENT     NOT SENT     istiod-5d5f6bd4c8-t9tb6     1.16-alpha.f8b4dc7bccc1fd2044c6014aea29368d46f086cc
istio-egressgateway-5df9b4644c-bbsfn.istio-system       Kubernetes     SYNCED     SYNCED     SYNCED     NOT SENT     NOT SENT     istiod-5d5f6bd4c8-t9tb6     1.16-alpha.f8b4dc7bccc1fd2044c6014aea29368d46f086cc
istio-ingressgateway-79598f8d56-jqvfc.istio-system      Kubernetes     SYNCED     SYNCED     SYNCED     SYNCED       NOT SENT     istiod-5d5f6bd4c8-t9tb6     1.16-alpha.f8b4dc7bccc1fd2044c6014aea29368d46f086cc
TEST: wait for failed, but continuing.
Duration: 1 seconds
```

The tests continue to run after these failures and pass because the config is ready, just the function isn't working.

Maybe we can now rewrite these functions using k8s wait instead of the experimental istioctl wait?

These messages appear in the log files of every test run, of every PR.
Example: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/12051/doc.test.profile_default_istio.io/1578018304595857408/artifacts/tests-setup-profile-default-f42/TestDocs/tasks/traffic-management/ingress/ingress-control/test.sh/test.sh/_test_context/test.sh_output.txt

The failing code is here: https://github.com/istio/istio.io/blob/ee4b0c8bc4fb17216d932731bad97a79c3661f24/tests/util/helpers.sh#L98

**Comment by ericvn** [comment]
https://github.com/istio/istio/pull/40561 has mention of the istioctl wait no longer functioning.

**Comment by ericvn** [comment]
This error is coming from this code in wait.go:
```
versionCount := make(map[string]int)
	for _, response := range pilotResponses {
		var configVersions []xds.SyncedVersions
		err = json.Unmarshal(response, &configVersions)
		if err != nil {
			return 0, 0, 0, err
		}
```
where the unmarshall of the response is broken.

**Comment by ericvn** [comment]
The istioctl experimental wait command returns the same error:
```
istioctl experimental wait gateway httpbin-gateway
Error: invalid character 'P' looking for beginning of value
```

**Comment by ericvn** [comment]
Dumping response: `Pilot Version tracking is disabled.  Please set the PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING environment variable to true to enable.Received poll result: 0/0`
