### ISSUE TITLE
istio-dashboard test times out occassionally

### ISSUE THREAD

**Issue by kfaseela** [istio/istio.io#12298]
Reference: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12295/doc.test.profile_default_istio.io/1595885674286813184

**Comment by kfaseela** [comment]
Latest one: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/12496/doc.test.profile_default_istio.io/1617553037616746496/artifacts/tests-setup-profile-default-2ab/TestDocs/tasks/observability/metrics/using-istio-dashboard/test.sh/test.sh/_test_context/test.sh_debug.txt

Looking at the logs, the curl command is failing occassionally. @zirain thoughts?

```
++query_request_for_all_workloads(): curl -L -s 'http://localhost:3000/api/datasources/proxy/1/api/v1/query?query=label_join(sum(rate(istio_requests_total%7Breporter%3D%22destination%22%2C%20response_code%3D%22200%22%7D%5B1m%5D))%20by%20(destination_workload%2C%20destination_workload_namespace%2C%20destination_service)%2C%20%22destination_workload_var%22%2C%20%22.%22%2C%20%22destination_workload%22%2C%20%22destination_workload_namespace%22)'
++query_request_for_all_workloads(): jq -r '.data.result[].metric.destination_workload_var'
++query_request_for_all_workloads(): sort
+__verify_with_retry(): out=
+__verify_with_retry(): local funcret=0
++__verify_with_retry(): sed 's/[[:space:]]*$//g'
```

**Comment by ericvn** [comment]
Yep. This is noted in the other test-flakes PR: https://github.com/istio/istio.io/issues/12464#issuecomment-1386081634. Wasn't as flakey (1/2 the tcpshift flake)
