### ISSUE TITLE
Issue with _docs/setup/kubernetes/ansible-install.md

### ISSUE THREAD

**Issue by mabushey** [istio/istio.io#1233]
>ansible-playbook main.yml

Sounds great, but where do I clone the repo from? Need to get main.yml from somewhere.

**Comment by mabushey** [comment]
The location is here: https://github.com/istio/istio/tree/master/install/ansible

**Comment by sdake** [comment]
@mabushey the files should be located in the release tarball.  Can you confirm one way or another this is not the case?   I don't want people to be required to clone the repository to access the installation tooling.

Cheers
-steve

**Comment by mabushey** [comment]
@sdake 
```
$ ls -l istio-1.0.2/install/
total 20
-rw-r--r-- 1 ubuntu ubuntu 1487 Sep  6 20:03 README.md
drwxr-xr-x 2 ubuntu ubuntu 4096 Sep  6 20:03 consul
drwxr-xr-x 3 ubuntu ubuntu 4096 Sep  6 20:03 gcp
drwxr-xr-x 5 ubuntu ubuntu 4096 Sep  6 20:03 kubernetes
drwxr-xr-x 2 ubuntu ubuntu 4096 Sep  6 20:03 tools
```

No, it is not in the 1.0.2 release tarball

**Comment by sdake** [comment]
@mabushey trying to "guess" at what this issue is - I suspect it has something to do with some of the ansible installation code not being packaged during deployment.  Uncertain.

**Comment by sdake** [comment]
The ansible implementation has been deprecated and removed from the documentation.  Closing this issue.  Thank you for your help.

Cheers
-steve
