### ISSUE TITLE
Making istio provider boxes more attractive

### ISSUE THREAD

**Issue by UtkarshMishra12** [istio/istio.io#12355]
Improvement - Making istio provider boxes more attractive 

Current State-
![image](https://user-images.githubusercontent.com/67385503/206892442-74166edf-b9cb-4f1b-b571-7e5f03a2df89.png)

Improved State-

https://user-images.githubusercontent.com/67385503/206892653-6583a18c-ed99-4f0c-ae75-47618c4405bf.mp4

**Comment by UtkarshMishra12** [comment]
@ericvn Let me know your thought on this

**Comment by ericvn** [comment]
Looking at the screenshots, I think the corner radius is too large. I'm not sure of @craigbox has any additional input.

**Comment by UtkarshMishra12** [comment]
@ericvn The corner radius can be changed as per the requirements.  The objective is to improve the look of the boxes.

**Comment by ericvn** [comment]
I do prefer the look of the boxes with a cover radius.

**Comment by ericvn** [comment]
From Slack:
```
Craig Box
  [link](https://istio.slack.com/archives/C03NZ7QCL2H/p1670965150241469?thread_ts=1670928134.163909&cid=C03NZ7QCL2H)
Boxes have square corners in our current design language.  I don't think we're looking to change that for one or two items.
```
