### ISSUE TITLE
How to test secure gateway from browser?

### ISSUE THREAD

**Issue by Huixxi** [istio/istio.io#12374]
When I tried to test ingress gateway with HTTPS following this doc https://istio.io/latest/zh/docs/tasks/traffic-management/ingress/secure-ingress/, but it seemed that it can only be tried with curl which also needed a --cacert param:  
```
curl -v -HHost:httpbin.example.com --resolve "httpbin.example.com:$SECURE_INGRESS_PORT:$INGRESS_HOST" \
  --cacert example_certs1/example.com.crt "https://httpbin.example.com:$SECURE_INGRESS_PORT/status/418"  
```
Is there a way to allow it with browser test?

**Comment by ericvn** [comment]
I'm not sure if someone form the Istio community will answer the question here or not, but I'll mention that the normal istio/istio issue template (this repo specifically relates to issues with the documentation at https://istio.io) has:
```
Is this the right place to submit this?
This is used to report product bugs:
To report a security vulnerability, please visit https://istio.io/about/security-vulnerabilities
To ask questions about how to use Istio, please visit https://discuss.istio.io/
 This is not a security vulnerability *
 This is not a question about how to use Istio *
```
