### ISSUE TITLE
Inaccurate documentation for egress tls traffic origination

### ISSUE THREAD

**Issue by sourabhdug** [istio/istio.io#12474]
This article describes configuring egress tls https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/

That doesn't seem to work however, this does:

https://istio.io/v1.1/docs/examples/advanced-gateways/egress-tls-origination/

**Comment by sourabhdug** [comment]
Is the documentation accurate?

**Comment by zirain** [comment]
please checkout https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases
v1.1 is EOL for a long long time.

**Comment by kfaseela** [comment]
@sourabhdug : can we close this issue?

**Comment by ericvn** [comment]
Closing this issue. Please re-open with additional information if we need to look at this some more.
