### ISSUE TITLE
Add documentations for OpenTelemetry tracing integration in tracing tasks

### ISSUE THREAD

**Issue by hanxiaop** [istio/istio.io#12612]
Istio already supports otel tracing. It will be great to add a task in the doc site about the integration.

**Comment by hanxiaop** [comment]
I'm writing a demo here https://github.com/istio/istio/pull/43041, which is in progress

**Comment by zirain** [comment]
> Pinging from [istio/istio#43041](https://github.com/istio/istio/pull/43041), I can try to work on a new page to illustrate how to configure it to send to a OTel collector via gRPC and now HTTP. Let me know and feel free to assign it to me.

thanks for taking this, ping me if you need any help.
