### ISSUE TITLE
Is the requirement to deploy ingress gw on each node when Local mode is used valid?

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#12629]
https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/

The question is if "you must run an ingress gateway pod on every node" valid with modern NLB who can do healthcheck to see if a node has health check port running. So if the node can't pass NLB health check, NLB won't send traffic to it thus no need to require ingress gateway pod on every node.

```
If you are using a TCP/UDP network load balancer that preserves the client IP address (AWS Network Load Balancer, GCP External Network Load Balancer, Azure Load Balancer) or you are using Round-Robin DNS, then you can also preserve the client IP inside Kubernetes by bypassing kube-proxy and preventing it from sending traffic to other nodes. However, you must run an ingress gateway pod on every node. If you don’t, then any node that receives traffic and doesn’t have an ingress gateway will drop the traffic. See [Source IP for Services with Type=NodePort](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport) for more information. Update the ingress gateway to set externalTrafficPolicy: Local to preserve the original client source IP on the ingress gateway using the following command:

$ kubectl patch svc istio-ingressgateway -n istio-system -p '{"spec":{"externalTrafficPolicy":"Local"}}'
```

**Comment by linsun** [comment]
Simple scenario:

Ingress gateway is deployed on node2 and node3, not on node1. Can NLB be configured smartly to send traffic only to node2 and node3?  If so, there is no need to require ingress gateway to be deployed on node1.

**Comment by linsun** [comment]
cc @howardjohn @bleggett 

cc @nmnellis in case you have any insight?

**Comment by dhawton** [comment]
I'd say at the minimum, the Round Robin DNS portion of that still holds true, as the only control as to what node is being hit depends on the DNS records and not the nodes that have a healthy gateway pod.

**Comment by frankbu** [comment]
Fixed by https://github.com/istio/istio.io/pull/12779.
