### ISSUE TITLE
Supported Releases page issues

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#12632]
I note that we say under Security patches: Same as a Patch, however, it will not contain any additional code other than the security fix from the previous patch. I'm not sure we follow that right now. We sometime have security updates and other patches.

The pointed to wiki is old: you can learn about our development builds on the [development builds wiki](https://github.com/istio/istio/wiki/Dev%20Builds).

**Comment by johnma14** [comment]
@ericvn I am assigning this to myself for the time being. I have few folks who are looking for a good first issue. Thanks. If anyone else wants to work on this before that, please feel free to leave a message and I will unassigned myself.

**Comment by ericvn** [comment]
The remaining item for this issue is to really update the dev wiki to make sure it's pointing to the commit builds.

**Comment by AndreaM12345** [comment]
made updates to wiki and closing the issue
