### ISSUE TITLE
Minor fixes to feature status  page

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#12697]
In the feature status page, under Istio Features,
-  [Core] Rename`In-Cluster Operator` to `Istio Operator`.
-  [Security]  `VM: Service Credential Distribution` and `Kubernetes: Service Credential Distribution` point to the same place:  https://istio.io/latest/docs/concepts/security/#pki
- [Extension] `Was Plugin Extension` needs to be linked to https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/

**Comment by johnma14** [comment]
Have few new contributors to assign this to.

**Comment by ericvn** [comment]
Note that the tables are simply representations from this yaml: https://github.com/istio/enhancements/blob/master/features.yaml

**Comment by johnma14** [comment]
Talked to @aryan16 about:
- [Security]  VM: Service Credential Distribution and Kubernetes: Service Credential Distribution point to the same place: https://istio.io/latest/docs/concepts/security/#pki

It seems the link points to the most generic page possible, and we don't have any docs for VM credentials - the status reflected is correct - K8s one is stable, VM is in beta. So it is what we have, so nothing to update there.
