### ISSUE TITLE
Duplicate reference docs overwriting each other

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#12693]
I noted an issue where an updated file in istio/api did not cause an update of it's `location` specified file in the reference docs.

I found that there are several pb.html files that have the same `location` specified so when updating the reference docs we get the last one processed:
```
networking/v1alpha3/workload_group.pb.html          https://istio.io/docs/reference/config/networking/workload-group.html
networking/v1beta1/workload_group.pb.html           https://istio.io/docs/reference/config/networking/workload-group.html
security/v1/authorization_policy.pb.html            https://istio.io/docs/reference/config/security/authorization-policy.html
security/v1beta1/authorization_policy.pb.html       https://istio.io/docs/reference/config/security/authorization-policy.html
security/v1/jwt.pb.html                             https://istio.io/docs/reference/config/security/jwt.html
security/v1beta1/jwt.pb.html                        https://istio.io/docs/reference/config/security/jwt.html
security/v1/request_authentication.pb.html          https://istio.io/docs/reference/config/security/request_authentication.html
security/v1beta1/request_authentication.pb.html     https://istio.io/docs/reference/config/security/request_authentication.html
```

**Comment by ericvn** [comment]
Some pb.html files have tabsets for the various versions and a single `location`.

**Comment by AndreaM12345** [comment]
it looks like in the case of the workload_group networking/v1alpha3/workload_group.pb.html   and networking/v1beta1/workload_group.pb.html   it seems like the v1beta1 yaml example was not defined.  As a test I manually propagated the worload_group.proto file and saw that the workload_group.pb.html file got updated.

**Comment by AndreaM12345** [comment]
it seems like location is the same for v1beta1 and v1alpha3 for the `service entry` and `workload entry` files in networking so the only different with `workload group` was that `workload group` never had a v1beta1 defined in any of the .proto files.

**Comment by AndreaM12345** [comment]
also should note the sync is taking the verbage and examples from the newer release and merging them with the definitions from the older release and putting them in the the newer release.  However what is published is the older release.  With the PR (https://github.com/istio/api/pull/2811) I fixed the duplicate reference docs but kept the same logic to be consistent.
