### ISSUE TITLE
Suggestions for Quick Start Guide

### ISSUE THREAD

**Issue by gargnupur** [istio/istio.io#1271]
1) Google Kubernetes Engine:
gcloud container clusters create <cluster-name> \
    --cluster-version=1.9.4-gke.1 \
    --zone <zone> \
    --project <project-name>
Cluster version above is incorrect.. update to 1.9.7-gke.0 or latest?

2) IBM Cloud Container Service 
Nit: Add link to IBM cloud kubernetes tools? -> https://console.bluemix.net/docs/containers/cs_tutorials.html#cs_cluster_tutorial

3) Open Shift Origin
Nit: Add link to Open Shift Origin Documentation on how to get cluster up: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md

4) AWS
Nit: AWS Kubernetes setup link: https://aws.amazon.com/blogs/compute/kubernetes-clusters-aws-kops/

**Comment by ymesika** [comment]
@gargnupur Thanks for your suggestions.
1. I'm not sure it's critical as long as it's +1.9
2/3. The title are links to the relevant provider. Do you suggest adding another link?
4. AWS link is indeed missing

**Comment by gargnupur** [comment]
@ymesika : Thanks for looking.. answers inline
1) https://cloud.google.com/kubernetes-engine/versioning-and-upgrades -> 1.9.4 is not a supported version :(
How about changing it to latest? so that we don't run into this problem again?
2+3) Links I suggested are basically how to setup these clouds with kubernetes.. do you think it would be good to add them?
4) I also didn't notice that.. to keep it uniform with the links of all other cloud we should add https://aws.amazon.com/ link there?

**Comment by PatrickAuld** [comment]
I created a PR for this #1291.

**Comment by ymesika** [comment]
Close suggestion - Fixed by #1291
