### ISSUE TITLE
Add headersToDownstreamOnAllow example in ext authz task page

### ISSUE THREAD

**Issue by hanxiaop** [istio/istio.io#12764]
Add `headersToDownstreamOnAllow ` to https://istio.io/latest/docs/tasks/security/authorization/authz-custom/#define-the-external-authorizer. Which is described in https://github.com/istio/istio/issues/36950 and implemented in https://github.com/istio/istio/pull/37677

**Comment by SuperAayush** [comment]
Hey @hanxiaop!!
I would like to work on this!!

**Comment by hanxiaop** [comment]
@SuperAayush Great I'll assign you
