### ISSUE TITLE
The AuthorizationPolicy documentation is rendering incorrectly

### ISSUE THREAD

**Issue by timflannagan** [istio/istio.io#12808]
The latest AuthorizationPolicy documentation appears to be rendering incorrectly. See the following screenshot for an example of this behavior:

![Screen Shot 2023-02-27 at 6 22 31 PM](https://user-images.githubusercontent.com/9899409/221711927-a015e9b2-3d0a-4a27-9a29-bd636ed5166b.png)

The YAML output and the commentary surrounding that example output are combined together.

**Comment by craigbox** [comment]
[This is the location I think that needs to be fixed](https://github.com/istio/api/blob/1bd2832732f3ab4ffff46f0db885351dbcfc03c2/security/v1beta1/authorization_policy.proto#L117), though I can't see how this section is different than any other which does render correctly

(Except it says `AuthorizaionPolicy` with no T)

I don't understand how all these relate, so I'm flagging @ericvn to teach me.

**Comment by kfaseela** [comment]
@craigbox : looks like this is already fixed on master, and it is rendered correctly: https://preliminary.istio.io/latest/docs/reference/config/security/authorization-policy/

(may be that is why you see the code looking all perfect) ?

**Comment by kfaseela** [comment]
https://github.com/istio/api/pull/2687/files this one fixed it. May be we can backport to 1.17 if needed

**Comment by ericvn** [comment]
There's actually been a number of changes in this file we might want to cherry-pick, but this is the one I remember for this issue: https://github.com/istio/api/pull/2658.

**Comment by kfaseela** [comment]
Fixed now: https://istio.io/latest/docs/reference/config/security/authorization-policy/
