### ISSUE TITLE
Diagram shows two discrete meshes as a single mesh

### ISSUE THREAD

**Issue by nickperry** [istio/istio.io#12811]
https://istio.io/latest/docs/ops/deployment/deployment-models/#trust-between-meshes

https://istio.io/latest/docs/ops/deployment/deployment-models/blue-green.svg

In this diagram, there are two clusters, with two Istio control planes and these Istio control planes only have access to the Kubernetes API Server in their local cluster. On that basis, surely that diagram is misleading in that it shows a single Istio Mesh.

Shouldn't the diagram show two discrete Istio meshes?

**Comment by frankbu** [comment]
I guess it is misleading. The doc is really just describing ways to keep traffic local to a cluster. It does say `each cluster is "effectively" operating as an independent mesh`. If you use VirtualService to control the routing, the control planes would still have access to both API Servers, so the diagram is wrong in that case too. I'm not sure what the best fix would be. Remove the diagram?
