### ISSUE TITLE
'feature-stages' page says it experimental features will not be shown

### ISSUE THREAD

**Issue by paddydoyle** [istio/istio.io#12829]
In https://istio.io/latest/docs/releases/feature-stages/#istio-features it says:

> Istio features
> Below is our list of existing features and their current phases. This information will be updated after every release. Experimental features are purposefully not listed on this page.

That is not the case. `Alpha` and `Experimental` features _are_ displayed.

What should be done to resolve this?

1. Remove the sentence `Experimental features are purposefully not listed on this page` OR
2. Fix the render to only show `Stable` and `Beta`?

**Comment by johnma14** [comment]
I would say remove the text that says `Experimental features are purposefully not listed on this page`. @ericvn thoughts?

**Comment by paddydoyle** [comment]
Raised https://github.com/istio/istio.io/pull/12851 for this.
