### ISSUE TITLE
Migrate telemetry and Wasm examples to first-class API away from EnvoyFilter.

### ISSUE THREAD

**Issue by kyessenov** [istio/istio.io#12830]

**Comment by ericvn** [comment]
Just making a release blocker for 1.18.

**Comment by zirain** [comment]
- [ ] https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/

**Comment by howardjohn** [comment]
we need to make a similar change as done in https://github.com/istio/istio.io/commit/2e8eff90e6074bfd408604ec983f48e0bfb6134f#diff-6705e9173dca912d428d536318808ffcc77e61265a51eacd7ae5fa1246d16480L56-L112 to the other EnvoyFilter on the same page.

**Comment by kyessenov** [comment]
https://github.com/istio/istio.io/pull/13296 done for classify metrics. Much simpler :)

**Comment by howardjohn** [comment]
We now only have these for rate limit, where it is required
