### ISSUE TITLE
Issue with EnvoyFilter Doc:  ListenerMatch.portNumber part 

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio.io#13169]
this part:

https://github.com/istio/istio.io/blob/c7ff0815fec156dd432098bcded3a389737b6b77/content/en/docs/reference/config/networking/envoy-filter/index.html#L683

Issue:

According to this part documentation configuration does not meet expectations, for inbound Listener, based on the actual environment verification, portNumber needs to be configured as service target port

Related issue:
   https://github.com/istio/istio/issues/44795

Related istio source code:

   
https://github.com/istio/istio/blob/c261604423395a95d0918fb75fb9999d14f98dc8/pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go#L749

**Comment by ericvn** [comment]
Note this file is copied from istio/api: 
https://github.com/istio/api/blob/release-1.18/networking/v1alpha3/envoy_filter.pb.html#L681
which is generated from:
https://github.com/istio/api/blob/release-1.18/networking/v1alpha3/envoy_filter.proto#L709

**Comment by zengyuxing007** [comment]
> Note this file is copied from istio/api: https://github.com/istio/api/blob/release-1.18/networking/v1alpha3/envoy_filter.pb.html#L681 which is generated from: https://github.com/istio/api/blob/release-1.18/networking/v1alpha3/envoy_filter.proto#L709

@ericvn Got it ! thanks
