### ISSUE TITLE
/docs/concepts/traffic-management/ incorrectly states round robin load balancing is used by default

### ISSUE THREAD

**Issue by clhuang** [istio/istio.io#13203]
As of istio 1.14, the default load balancing algorithm has been changed to LEAST_REQUEST https://istio.io/latest/news/releases/1.14.x/announcing-1.14/change-notes/

**Comment by kfaseela** [comment]
are you interested in making the docs change and push a PR for this? If so, please go ahead and do

**Comment by clhuang** [comment]
https://github.com/istio/istio.io/pull/13206

I'm not capable of making the changes in the other langauges, though

**Comment by kfaseela** [comment]
Thanks @clhuang :)
