### ISSUE TITLE
Wrong service name in better external authz blog

### ISSUE THREAD

**Issue by chay2199** [istio/istio.io#13267]
Blog link: [Better External Authz](https://istio.io/latest/blog/2021/better-external-authz/)

If you'll follow the better external authz blog and deploy OPA and httpbin separately then the service name in the Test OPA policy section should have an addition tab as `httpbin-with-opa` service no longer exist rather it is only `httpbin`

**Comment by kfaseela** [comment]
@chay2199 will you be interested in pushing a PR with the changes needed for fixing this?

**Comment by chay2199** [comment]
Sure @kfaseela. Please assign it to me.

**Comment by chay2199** [comment]
PR submitted: https://github.com/istio/istio.io/pull/13284

**Comment by craigbox** [comment]
#13284 merged and closes this.  Thanks!
