### ISSUE TITLE
Istio publishes results of 2022 security audit blog link problem confirmation

### ISSUE THREAD

**Issue by wilsonwu** [istio/istio.io#13263]
In blog: https://istio.io/latest/blog/2023/ada-logics-security-assessment/

Dose the [We] miss a link:
<img width="898" alt="image" src="https://github.com/istio/istio.io/assets/1269496/848c096b-5037-4203-bdbf-8e348effd246">

**Comment by windsonsea** [comment]
Not sure what the URL should be:

- https://github.com/orgs/istio/teams/wg-product-security-maintainers
- https://github.com/orgs/istio/teams/wg-security-maintainers
- https://github.com/orgs/istio/teams/release-managers

cc @ericvn

**Comment by wilsonwu** [comment]
From the context, is "We" means ADA Logics? Maybe: https://adalogics.com/

**Comment by wilsonwu** [comment]
From the context, is "We" means both ADA Logics and Istio Team?

**Comment by ericvn** [comment]
I did not find that exact quote in my limited looking at the Ada Logics blog and the report, but it does show that the quote was made by ADA Logics. Since they made the quote, it at least includes ADA Logics.

I did find in the report, something which is close to the quote:
```
Ada Logics started the fuzzing assessment by prioritising security-critical parts of Istio. We found that many of these had impressive test coverage with little to no room for improvement. We identified a few APIs in security-critical code parts that would benefit from fuzzing and wrote fuzzers for these.
In total, 6 fuzzers were written during this audit and have all been merged into the upstream Istio repository.
```
This makes me think this may solely be ADA Logics for the we.

**Comment by ericvn** [comment]
I should also note that the [We] was never meant to be a link in my mind. It was simply when writers insert or alter words in a direct quotation, square brackets, [ ], are placed around the change.

**Comment by wilsonwu** [comment]
Thanks for all, it is just a style, closed this issue with the PR merged.
