### ISSUE TITLE
Link for Wasm Plugin is not working 

### ISSUE THREAD

**Issue by visheshtha** [istio/istio.io#13311]
**Problem:**

While going through feature status page,I found that the given link([enhancements/features.yaml](https://github.com/istio/enhancements/blob/master/features.yaml#L169)) of `WebAsssembly Extension` under [extensibility ](https://istio.io/latest/docs/releases/feature-stages/#extensibility)is not working. It is due to the link used for WebAssembly Extension is not there in the [alias field](https://github.com/istio/istio.io/blob/dd8967e65513437389f7ed43a1657ff20153a32f/content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html#LL10C1-L10C1) of the Wasm Plugin docs.

The following mentioned link under the alias field is also not working and gives the `request cannot be found` error:
`https://istio.io/latest/docs/reference/config/extensions/v1alpha1/wasm-plugin`

So instead of the above link, we have to use the `/docs/reference/config/proxy_extensions/wasm-plugin/` link under the alias field, so that the link used to redirect to Wasm Plugin docs will work.

**Proposed Solution**
We have to change the link from` /docs/reference/config/extensions/v1alpha1/wasm-plugin`  to `/docs/reference/config/proxy_extensions/wasm-plugin/` under the alias field of Wasm Plugin docs

**Page to update**
https://github.com/istio/istio.io/blob/master/content/en/docs/reference/config/proxy_extensions/wasm-plugin/index.html

**Comment by visheshtha** [comment]
I would like to work on this issue 
/assign

**Comment by ericvn** [comment]
This change likely needs to be done in the enhancements repo and was likely introduced there in https://github.com/istio/enhancements/pull/143. I'm not sure if the link they referred to was removed (likely) and maybe that link needs to be updated.

**Comment by ericvn** [comment]
Not that the link does exist for 1.17: https://istio.io/v1.17/docs/reference/config/proxy_extensions/wasm-plugin/ so something removed the link in 1.18.

**Comment by ericvn** [comment]
Actually, I doin't see this issue you mention. If I go to https://istio.io/latest/docs/releases/feature-stages/#extensibility and click on the `[WebAssembly Extension](https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/)` link it goes to the correct page.

**Comment by visheshtha** [comment]
Closing this issue as it was already resolved
