### ISSUE TITLE
add more info to locality-load-balancing page 

### ISSUE THREAD

**Issue by AndreaM12345** [istio/istio.io#13358]
Looking at the locality-load-balancing page https://istio.io/latest/docs/tasks/traffic-management/locality-load-balancing/ it seems like more details should be added and the flow of the page modified.

It probably makes sense to take the task links at the top and move them to the bottom so that the user first understands what locality-load-balancing is before trying to implement it.

Also would like to give some more description about how to do traffic shifting between zones.  At minimum should add a `See Also` section with https://istio.io/latest/docs/tasks/traffic-management/traffic-shifting/ but would like to see if we can expand the pages to include how to do traffic shifting between zones.

**Comment by wei06159** [comment]
The code changes were approved and merged. I don't see I have the permission to link this ticket to the PR. I will close this ticket manually.
