### ISSUE TITLE
use hugo serve, preview site cannot find css/js 

### ISSUE THREAD

**Issue by SAMZONG** [istio/istio.io#13364]
```bash
hugo serve --baseURL http://127.0.0.1:1313/latest/ --bind 0.0.0.0 --disableFastRender
```

![20230614124249](https://github.com/istio/istio.io/assets/13782141/ab98d28d-e4bf-4e23-9a23-f9c95b902162)

**Comment by SAMZONG** [comment]
@ericbuehl need u help.

**Comment by zirain** [comment]
why not use `make serve`?

**Comment by SAMZONG** [comment]
> why not use `make serve`?

`make serve` is another question, #13363

**Comment by SAMZONG** [comment]
Duplicated, close this one.
