### ISSUE TITLE
Feedback on ambient announcements

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#13479]
hey everyone, in case it wasn't clear, ambient did make to Istio 1.18 - https://discuss.istio.io/t/did-ambient-mesh-make-it-into-1-8/15755, we will look into how to make it more clear

- if user reaches 1.18 change note, they don't see ambient in there, we should consider adding a reference pointing to the [announcement blog](https://preliminary.istio.io/latest/news/releases/1.18.x/announcing-1.18/) from the change note.
https://preliminary.istio.io/latest/news/releases/1.18.x/announcing-1.18/change-notes/

- need to be clear it is alpha status on the announcement blog: https://preliminary.istio.io/latest/news/releases/1.18.x/announcing-1.18/, perhaps making it a warning/bold.

**Comment by janvi01** [comment]
Hey @linsun I would like to work on this. Please assign me.

**Comment by pegasas** [comment]
Hi, @linsun ,
I created a PR to fix this.
ambient is a major feature in istio 1.18. 
I referred istio history major version like https://preliminary.istio.io/latest/news/releases/1.8.x/announcing-1.8/change-notes and directly add a reference here to highlight this feature.

Feel free to comments or modify directly if any concerns.

**Comment by pegasas** [comment]
See comments on https://github.com/istio/istio.io/pull/13749.
