### ISSUE TITLE
Consider enrich ambient architecture page

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#13480]
Consider enrich ambient [architecture page](https://preliminary.istio.io/latest/docs/ops/ambient/architecture/) with some contents from the [ambient announcement blog](https://istio.io/latest/blog/2022/introducing-ambient-mesh/):

for example: we should have the ztunnel and waypoint diagrams and explanation of these two components copied from announcement blog.

**Comment by ronitblenz** [comment]
I would like to contribute on this. Assign me :)

**Comment by linsun** [comment]
@ronitblenz any update on this?

**Comment by ronitblenz** [comment]
Hey @linsun - Apologies, I got caught up with few things... Will start working on this asap and make a PR for a review and make more changes accordingly.

**Comment by janvi01** [comment]
Hey @linsun I would like to work on this if the issue is still available.

**Comment by pegasas** [comment]
Hi, @linsun ,

I created a PR to fix this issue.
I mainly enrich the `Differences from sidecar architecture` part, 
I think this is the major architecture thinking of ambient mesh.

Also, I directly link the image to the blog to keep alignment.

Feel free to comment or modify directly if any concerns.

**Comment by howardjohn** [comment]
track in https://github.com/istio/istio.io/issues/14347
