### ISSUE TITLE
Need a page to explain HBONE

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#13482]
We have some contents out there from existing ambient blog but may need additional contents

@justinpettit thoughts? Would you be a good owner for this?

**Comment by srampal** [comment]
@linsun I would be interested in helping or working on this .. possibly in collaboration with @justinpettit or anyone else. Let me know.

**Comment by srampal** [comment]
@linsun @justinpettit  Open to helping with this if Justin needs any help.

**Comment by linsun** [comment]
no one asked about hbone doc outside of Istio contributors imho, could be deferred imho
