### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by mattkram** [istio/istio.io#13514]
Hi! I noticed a typo in the third code example of this section of the docs: https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPDirectResponse

I am passing through and unsure if the `index.html` is generated or hand-written, but here is the line: https://github.com/istio/istio.io/blame/140f5621a0c64a231932bd153efe9e0168c92ca3/content/en/docs/reference/config/networking/virtual-service/index.html#L2136

The content-type should read `application/json` (it's missing the `c`).

![image](https://github.com/istio/istio.io/assets/11037737/b71faa88-72e0-4edc-85a8-ff465feda5b8)

**Comment by kfaseela** [comment]
@mattkram : Thanks for pointing this out. The source for this index.html is https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L1584  and https://github.com/istio/api/blob/master/networking/v1beta1/virtual_service.proto#L1584. If you are interested feel free to make the changes and push a PR.
