### ISSUE TITLE
With two banners, you can't see the headings

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#13573]
<img width="1506" alt="Screenshot 2023-07-15 at 11 23 08 AM" src="https://github.com/istio/istio.io/assets/132510/241a5fbb-34f0-455a-b01e-1c05a46c411e">

**Comment by ericvn** [comment]
Related to https://github.com/istio/istio.io/issues/10304

**Comment by ericvn** [comment]
I can't seem to assign @mweiner so assigning to me while Michael works on it.
