### ISSUE TITLE
Has the path disappeared?

### ISSUE THREAD

**Issue by Douglas235** [istio/istio.io#13709]
Now why can’t we find this path " [istio.io/tools/cmd/license-lint](http://istio.io/tools/cmd/license-lint)"?

**Comment by ericvn** [comment]
As far as I know we only redirect /tools on a go get. In the past we've seeing gets fail for a period of time to start working again later. I'm not sure if that's your issue or not. I'd have to try some experimentation to see if the redirects would work to simply point to a file. Maybe Github changed something.

**Comment by ericvn** [comment]
That said, the directory does exist: https://github.com/istio/tools/tree/master/cmd/license-lint

**Comment by Douglas235** [comment]
Thanks,The problem has been solved!

**Comment by ericvn** [comment]
> Thanks,The problem has been solved!

Good to know. You can close this issue.
