### ISSUE TITLE
Ambient getting started missing Loadbalancer networking

### ISSUE THREAD

**Issue by afro-coder** [istio/istio.io#13756]
Hi, 

I was getting started with ambient and I see as of now kind is the only one supported, however by default kind doesn't install networking for leasing IP"s (Metallb) due to which(I'm assuming) the gateway created gets stuck with the following error

```
- lastTransitionTime: "2023-08-21T11:55:01Z"
    message: 'Assigned to service(s) bookinfo-gateway-istio.istio-system.svc.cluster.local:80,
      but failed to assign to all requested addresses: address pending for hostname
      "bookinfo-gateway-istio.istio-system.svc.cluster.local"'
```

I will add a metallb link/ Notice and submit a PR for this.

**Comment by dhawton** [comment]
A note that ambient isn't just limited to Kind. It supports minikube (when CNI is set to kindnet), AWS' EKS, and GCP's GKE (without DPv2) and there's work to expand that support as well.

**Comment by afro-coder** [comment]
Ah alright now it makes sense, the comment on the pull request also makes sense now, The reason I created this issue was that as a user I came on this page there was an entire kind install and then there was no clear message other than the hostname. But I'm a beginner so it may seem like an easy thing, but I'll leave this up to y'all.
