### ISSUE TITLE
perf and scalability followup

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.io#1377]
from @linsun https://github.com/istio/istio.github.io/pull/1076#issuecomment-392995416

- pls provide guidance to users on the values of synthetic e-2-e and realistic application benchmark.
- pls update Latency cost/overhead is approximately [10 millisecond] for 0.8, as this is 0.8 doc.  Else, the content should go into 0.7 doc.
- "* Split mixer check and report pods.".   Is there any value to mention this given this is the default setup?   
- "* Assuming typical cache hit ratio (>80%) for mixer checks: 0.5 vCPU per peak thousand requests per second for the mixer pods."  pls clarify if this is for check or report or both?  Would be good to know if this happens even if mixer rule isn't used.

**Comment by ldemailly** [comment]
fixing the diagram / fortio scenarios in
https://github.com/istio/istio/issues/6059

**Comment by ldemailly** [comment]
+ @jnativio

**Comment by geeknoid** [comment]
You can only assign members of the Istio org I believe.

**Comment by ldemailly** [comment]
can you add jose to the org (I thought he already was, at least for istio/istio)

**Comment by geeknoid** [comment]
Jose, you should have an invitation to join the Istio org in your mailbox.
