### ISSUE TITLE
[Documentation] Issue regarding FAQ prometheus scrape

### ISSUE THREAD

**Issue by Rei1010** [istio/istio.io#13789]
As https://istio.io/latest/about/faq/metrics-and-logs/#prometheus-application-metrics mentioned, the istio-telemetry already removed.
Now we refer https://istio.io/latest/docs/ops/integrations/prometheus/, just scrape data it mentioned. Shall we remove this part of just link it  the prometheus doc?

PS: https://github.com/istio/istio/blob/master/samples/addons/prometheus.yaml#L19

**Comment by kfaseela** [comment]
cc @zirain

**Comment by kfaseela** [comment]
@Rei1010 Are you talking about removing https://raw.githubusercontent.com/istio/istio/release-1.18/manifests/charts/istio-telemetry/prometheus/templates/configmap.yaml from https://istio.io/latest/about/faq/metrics-and-logs/#prometheus-application-metrics ?

**Comment by Rei1010** [comment]
@kfaseela yes. I'd like to linking https://istio.io/latest/docs/ops/integrations/prometheus/ instead, any idea?

**Comment by zirain** [comment]
Sorry, I still haven't figured out what's the problem?

**Comment by Rei1010** [comment]
@zirain in [metrics-and-logs](https://istio.io/latest/about/faq/metrics-and-logs/#prometheus-application-metrics), it linked to [istio-telemtry](url) which already removed from [istio](https://github.com/istio/istio/tree/master/manifests/charts). So i'd like to raise a PR to replace it wit [prometheus](https://istio.io/latest/docs/ops/integrations/prometheus/). Any idea about this?

**Comment by nicole-lihui** [comment]
> Sorry, I still haven't figured out what's the problem?

This document has some broken or incorrect links

**Comment by nicole-lihui** [comment]
<img width="1209" alt="image" src="https://github.com/istio/istio.io/assets/44200120/062d78fb-52d1-428a-9d1d-b4f2e1d4c271">

**Comment by zirain** [comment]
> @zirain in [metrics-and-logs](https://istio.io/latest/about/faq/metrics-and-logs/#prometheus-application-metrics), it linked to [istio-telemtry](url) which already removed from [istio](https://github.com/istio/istio/tree/master/manifests/charts). So i'd like to raise a PR to replace it wit [prometheus](https://istio.io/latest/docs/ops/integrations/prometheus/). Any idea about this?

Thanks for raising this up, you should do that.
