### ISSUE TITLE
Unclear how k8s ingress is to be used with 1.1

### ISSUE THREAD

**Issue by andraxylia** [istio/istio.io#1384]

**Comment by ebullient** [comment]
I found this really confusing. I _had_ an ingress defined before (to get things working without istio) .. what do I do if I'm adding istio now? Should I delete it? A little clarity would really help! For example: "If your application had a kubernetes ingress defined previously, the kubernetes ingress configuration can be replaced by an Istio Gateway, _following steps x, y, z_." .. something.

**Comment by linsun** [comment]
Agreed, this is very confusing.  A few paths we are exploring for documentation:

1. Recommend people to use the istioctl converter tool to convert their ingress to the new gateway and VS resources.   Then users can deploy the new resources and work with the new gateway, and delete the old ingress once they are happy with the new gateway.

2. Check if the ingress is working out of box with istio enabled services (as long as mTLS is disabled for the services).   Under the cover, the control plane is supposed to convert the k8s ingress to gateway and VS resources and this could work too.

I personally perfer the 1st path as user has more control.   2nd path has quite some magic and could be hard to debug issues.

**Comment by sdake** [comment]
@linsun i'm a bit out of the loop on the istioctl converter - I remember there being discussion on it, but not sure if it was implemented in 1.0.  Do you know?

cheers
-steve

**Comment by andraxylia** [comment]
For 1.1 this depends on the outcome of the discussion in istio/istio#12259 and actual support for k8s ingress, marking as P0 for now.

**Comment by geeknoid** [comment]
This is a P0 blocking the 1.1 release. When you believe this issue can be addressed? If you don't have time, please assign to someone else that can address this issue.

Thanks.

**Comment by frankbu** [comment]
I think we just tell people to convert their ingress to gateway + virtual service. We can point them at https://preliminary.istio.io/docs/reference/commands/istioctl/#istioctl-experimental-convert-ingress
which they can use to help get started. Does anybody disagree?

A blog entry to walk through a simple example would be nice, but I don't see that as P0 for 1.1. We can get it in a little later. Actually, didn't @esnible already have something like that?

**Comment by geeknoid** [comment]
OK, making this a P1.

**Comment by linsun** [comment]
there is a few patterns:
1. you can continue use k8s ingress with istio enabled services.  There is no mTLS in between k8s ingress to the entry of the istio enabled services.  This is perfectly valid, I believe a lot of users are still using this.
2. you can convert k8s ingress resource to istio ingress gateway + vs that @frankbu suggested.
3. you can chain k8s ingress with istio ingress gateway.  

I think @esnible had a draft blog however it was never published afaik.

**Comment by frankbu** [comment]
1. doesn't give users Istio functionality at the edge.
3. introduces an extra hop.

So, neither of these options seem practical for real production applications. That's why I think we need to recommend number 2.

If @esnible has a blog entry in the works, I think it would be great if he can finish it up. It could have a short intro that mentions options 1 and 3 as short term solutions to get started.

**Comment by sdake** [comment]
iirc @philrud has some instructions and information in this area.

**Comment by philrud** [comment]
here's what we currently have on k8sIngress via ingressgateway:
* https://preliminary.istio.io/docs/examples/advanced-gateways/ingress-certmgr/
* https://preliminary.istio.io/docs/tasks/telemetry/gateways/
