### ISSUE TITLE
Suggest change to: Documentation>OperationsDiagnostic Tools>Using the Istioctl Command-line Tool

### ISSUE THREAD

**Issue by ianzanderson** [istio/istio.io#13877]
I suggest a change in section [istioctl auto-completion](https://istio.io/latest/docs/ops/diagnostic-tools/istioctl/#istioctl-auto-completion) for macOS.

At the bottom of the section, there is a suggestion for a fix if the `brew install zsh-completions` results in the warning:

Zsh compinit: insecure directories

I think the solution should be:

`chmod -R go-w "$(brew --prefix)/share/zsh"`

not

`chmod -R go-w '$HOMEBREW_PREFIX/share/zsh'`

I believe the existing istioctl documentation comes from this page:
[Homebrew Formulae](https://formulae.brew.sh/formula/zsh-completions)

However, this seems to be an error. I believe this solution to be for bash, not zsh.

This link to the Homebrew Documentation appears to have the correct fix for the insecure directories warning:

[brew Shell Completion](https://docs.brew.sh/Shell-Completion)

I used `compaudit | xargs chmod g-w ` to fix it. But that was before I found the above documentation. Either way, the existing istio.io documentation is unhelpful. And I found the warning to be both alarming and annoying. I understand it was not the istioctl tooling. Instead, it was a `brew install zsh-completions` issue. But the resulting warning happened after using the istio documentation to set up the tooling. This may leave people with a wrong impression of the istioctl tool and Istio, in general.

**Comment by ericvn** [comment]
Just looking on my computer (note that I have not seen this particular failure here in a long time (several Macs ago)):
```> brew --prefix
/opt/homebrew
> env | grep HOME
HOME=/Users/ericvn
```
It makes sense that the later would be different if the environment value is not set (at it may have been a long time ago but not anymore).
