### ISSUE TITLE
[LFX Fall'23 Mentorship] Ambient Mesh Documentation for User Guide

### ISSUE THREAD

**Issue by fykaa** [istio/istio.io#13957]
This is a LFX mentorship project intended to run in Fall 2023

**Project Description**

Istio is currently developing an innovative operating mode called "Ambient Mesh." 
As part of this transition, our primary objective is to update and enhance Istio's documentation for Ambient Mesh User Guide. This revision aims to provide comprehensive user guide on the new Ambient Mesh model, explain the associated trade offs, and empower users to make informed decisions about its adoption.

**Expected Outcome:**
The project's expected outcome is a thorough overhaul of Istio's documentation to align with the introduction of Ambient Mesh. These updates will be maintained in a dedicated parallel branch of the `istio.io` documentation repository. This parallel branch will serve as a valuable resource for users during the Beta or General Availability (GA) phases of Ambient Mesh, ensuring that they have access to up-to-date information and guidance.

LFX Project Mentor: @linsun

**Comment by linsun** [comment]
Closing this as already finished
