### ISSUE TITLE
Adding some information about setting the value of $GATEWAY_URL in request timeout page

### ISSUE THREAD

**Issue by visheshtha** [istio/istio.io#14055]
While going through the tasks of traffic management,I found out that in[ request timeout ](https://istio.io/latest/docs/tasks/traffic-management/request-timeouts/) page ,in step 3,the information about setting the $GATEWAY_URL is not mentioned specifically i.e how to set the ip address $GATEWAY_URL.However,in other tasks of traffic management,it has been mentioned as "$GATEWAY_URL is the External IP address of the ingress, as explained in the [Bookinfo](https://istio.io/latest/docs/examples/bookinfo/#determine-the-ingress-ip-and-port) doc."
So in this document also,can we add the same so that for the new readers/users,it will become easy to perform and understand the task.

**Comment by visheshtha** [comment]
If it seems good,I will like to work on it

**Comment by ericvn** [comment]
Fixed by https://github.com/istio/istio.io/pull/14058
