### ISSUE TITLE
[Documentation Issue] Incorrect hyperlink leads to a page whose domain is for sale

### ISSUE THREAD

**Issue by Roofer92** [istio/istio.io#14069]
Hyperlink in Documentation Chapter [High Level Architecture](https://istio.io/latest/docs/concepts/security/#high-level-architecture) for Policy Enforcement Points is incorrect and leads to a page whose domain is for sale and does not contain any additional or useful information for PEPs.

**Comment by kfaseela** [comment]
May be the link can be replaced with https://csrc.nist.gov/glossary/term/policy_enforcement_point ? Will you be interested in submitting a pull request for the same? The line to modify will be https://github.com/istio/istio.io/blob/master/content/en/docs/concepts/security/index.md?plain=1#L64

**Comment by Roofer92** [comment]
I think it is a good replacement. i can submit the pull request for it
