### ISSUE TITLE
Please update the description of `ignore_uri_case` in the HTTPMatchRequest object

### ISSUE THREAD

**Issue by davidshen84** [istio/istio.io#14072]
From https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest, it says

> Note: Case-insensitive matching could be enabled via the ignore_uri_case flag.

The `ignore_uri_case` is the JSON property name when the object is serialized and should not be used in the yaml file. Users should use `ignoreUriCase` property which is mentioned several rows below that context.

I guess the text is extracted from the source description: https://github.com/istio/api/blob/master/networking/v1beta1/virtual_service.proto#L1035C14-L1035C14

**Comment by kfaseela** [comment]
Would you like to submit a pull request for this change?

**Comment by davidshen84** [comment]
So the string in the source code is the only place I need to update, right? If so, I can do it.

**Comment by davidshen84** [comment]
If I run `make gen`, it reverts my changes, like https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_api/2976/gencheck_api/1718919291463536640.

Is `virtual_service.proto` also a generated file?
