### ISSUE TITLE
Can not switch language from english to chinese

### ISSUE THREAD

**Issue by ycj-ymatrix** [istio/istio.io#14087]
Can not switch language from english to chinese, and the `/` after `latest` will be increaing each clicking.
![image](https://github.com/istio/istio.io/assets/37827830/0d3ea114-7616-4bdc-ba43-35cf26681057)
like this:
`preliminary.istio.io/latest///docs/reference/glossary`

**Comment by ericvn** [comment]
The English and Chinese selections at the bottom of the pages still seem to work. I had never known about this button before.
<img width="330" alt="Screenshot 2023-11-01 at 8 19 02 AM" src="https://github.com/istio/istio.io/assets/10537847/edcac9eb-9ab8-4a7c-a484-82543d79288d">

**Comment by rootsongjc** [comment]
This button only shows off on the preliminary pages. In the beginning, we translated the website, and there were a lot of pages that were not translated, so we let the language switch button only display on the preliminary pages. Now it is almost completed, we can enable these buttons now.

**Comment by craigbox** [comment]
Those are very ugly buttons!

We have the "Edit this page on GitHub" in the footer, and the language switch, so I'd advocate for removing them entirely.

**Comment by rootsongjc** [comment]
I agree. Since there is already a language switch link at the bottom, there is no need to keep the sidebar.

**Comment by AndreaM12345** [comment]
@ShabanaD thanks for looking into this

**Comment by GregHanson** [comment]
resolved by https://github.com/istio/istio.io/pull/14180
