### ISSUE TITLE
Is the glossary shortcode case sensitive?

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#14130]
Look at the rendered output here:  https://istio.io/latest/docs/releases/contribute/shortcodes/#glossary-terms

`{{<gloss>}}Envoy{{</gloss>}}` does not work, where `{{<gloss envoy>}}Envoy{{</gloss>}}` does.

**Comment by arijitvt** [comment]
The first section talks about how not to use this and so is the rendering ` {{}}Envoy{{}}`. The next section describes the  right way of rendering that. 
Let me know, if I did not get that right.

**Comment by arijitvt** [comment]
Does not look like it is case-sensitive. I tried both, 
```
The Istio component that programs the {{< gloss envoy >}}Envoy{{</ gloss >}} proxies, responsible for service discovery, load balancing, and routing.
```
and 
```
The Istio component that programs the {{< gloss Envoy >}}Envoy{{</ gloss >}} proxies, responsible for service discovery, load balancing, and routing.
```

They both render the same.

**Comment by ericvn** [comment]
Agree. IN an earlier version of the file the glossary item was adapters and they wanted to use adapter so that was the substitution.  Let me try a PR to better show this and fix the output in the earlier render.

**Comment by ericvn** [comment]
See https://github.com/istio/istio.io/pull/14134
