### ISSUE TITLE
lint test is flakey.

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#14155]
See https://prow.istio.io/job-history/gs/istio-prow/pr-logs/directory/lint_istio.io

**Comment by ericvn** [comment]
This seems to be in the master branch only. Related to tooling? Maybe Hugo...

**Comment by ericvn** [comment]
Failed again with the newer Hugo image. Curious what happens if we go back to the original at this point.

**Comment by ericvn** [comment]
Plan is to revert to the older version after Thanksgiving when I'm back in the office.

**Comment by ericvn** [comment]
Looking at the post-submits, we haven't seen a failure since 11/20. Will watch some more.

**Comment by SeanKilleen** [comment]
Working with linters that check URLs in the past, I've come across issues where once a site hit a certain size of links to the same host, the linter sometimes returned 429 (too many requests) from a host as a failure. You may want to check into whether that's happening with the linter (I couldn't see enough output to verify if that's actually the case). If that's the case, you'd want to ignore the 429s as an error or throttle the checking somehow.

**Comment by mike-weiner** [comment]
@ericvn - I did some looking.

Unfortunately, there was no clear "ah ha" moment looking at the logs from some of the recent failed [post-submit jobs](https://prow.istio.io/job-history/gs/istio-prow/logs/lint_istio.io_postsubmit?buildId=).

Agree that November 10th seems to be the day that this test started to become flaky: https://prow.istio.io/job-history/gs/istio-prow/logs/lint_istio.io_postsubmit?buildId=1723286801000435712

[Your update](https://github.com/istio/tools/commit/bec02d1500de2bedfda86c3093d3be4ce8be2656) to move to the newer `Hugo` image didn't happen until November 16th...so I would also agree that it probably wasn't that either. Looking at some of the other commits to the build-tools around November 10th...nothing stood out. 

We are currently running `linkinator v2.0.5`: https://github.com/istio/tools/blob/8eb5341d017c3a5b5928084e390ca76e04520090/docker/build-tools/Dockerfile#L367. The [current release](https://www.npmjs.com/package/linkinator) is `v6.0.2`. 

I went and looked at the README of `linkinator v2.0.5`: https://www.npmjs.com/package/linkinator/v/2.0.5. Unfortunately there is no verbosity option or retry option (both of these exist on the newer releases). 

The concurrency option caught my eye: 

> --concurrency
          The number of connections to make simultaneously. Defaults to 100.
          
It does **not** look like we set this argument: https://github.com/istio/istio.io/blob/8e4b10edb21ef92f614adb04e4cd851483f1c55a/scripts/lint_site.sh#L213, so it would be set to `100` (per the documentation).

I did some reading through issues in the `linkinator` GitHub repo around some closed issues about false positive broken links and stumbled across this: https://github.com/JustinBeckwith/linkinator/issues/135#issuecomment-623240879

That sounds very similar to what we are seeing. I would be curious if we have crossed a threshold of links to parse that we are right at the tipping point of overwhelming the Docker container running the linting. Maybe we try setting `--concurrency` to a lower value. `50`? `25`? 

If this is the problem - it would explain why there seems to be no rhyme or reason as to what pages report broken links & why it seems to be an intermittent problem. 

I wonder if we could re-create this problem locally be setting `--concurrency` to something absurdly high like `5000` to try and overload the local Hugo web server.

**Comment by ericvn** [comment]
Lower concurrency to 25: https://github.com/istio/istio.io/pull/14225

**Comment by mike-weiner** [comment]
I went back and looked at the logs. Seems like around October 31st ~5800-5900 links were being scanned. Logs for recent failures show ~5200 links being scanned...so at a first glance it doesn't seem like the number of links being scanned jumped up.
