### ISSUE TITLE
Document JWT auth a bit more

### ISSUE THREAD

**Issue by mcasimir** [istio/istio.io#1424]
I'm quite confused about https://preliminary.istio.io/docs/tasks/security/authn-policy/#setup-end-user-authentication.

Please explain more about the JWT end-user authentication. Just looking at the docs it seems the JWT just disappears after a successful verification. I really hope that is not the case cause it would make it just unusable, I assume the behavior is somehow what stated in https://github.com/istio/proxy/tree/master/src/envoy/http/jwt_auth but is difficult to figure.

Also in https://github.com/istio/proxy/tree/master/src/envoy/http/jwt_auth the token seems not to be mandatory, and a few configuration options are documented.

I feel generally some additional detail (even just a link to somewhere else) about how to configure the authentication is necessary.

**Comment by wattli** [comment]
@yangminzhu , can you help to take a look please? Thanks

**Comment by yangminzhu** [comment]
> I'm quite confused about https://preliminary.istio.io/docs/tasks/security/authn-policy/#setup-end-user-authentication.
> 
> Please explain more about the JWT end-user authentication. Just looking at the docs it seems the JWT just disappears after a successful verification. I really hope that is not the case cause it would make it just unusable, I assume the behavior is somehow what stated in https://github.com/istio/proxy/tree/master/src/envoy/http/jwt_auth but is difficult to figure.
> 

https://istio.io/docs/concepts/security/#origin-authentication has a bit more information on this. For JWT authentication policy, it will be applied on every request until you delete or modify the policy.

Would you mind to share some more detail what makes you think it just disappear after a successful verification? We need to fix this if it's somewhere in our documentation.

> Also in https://github.com/istio/proxy/tree/master/src/envoy/http/jwt_auth the token seems not to be mandatory, and a few configuration options are documented.
> 

I'm not sure I understand your question here, do you mean the documentation in the source code is not complete? Once configured in the authentication policy, the token is mandatory and this is enforced by istio authn filter, not in the jwt filter.

> I feel generally some additional detail (even just a link to somewhere else) about how to configure the authentication is necessary.

I think https://istio.io/docs/concepts/security/#authentication should provide a decent introduction to Istio authentication policy, please take a look at it, after that, you can follow the task (https://istio.io/docs/tasks/security/authn-policy/) to practice it in your Istio cluster, Once familiar with the above two, you can further take a look at the API spec https://istio.io/docs/reference/config/istio.authentication.v1alpha1/ for more information.

Hope this helps, let me know if you have any specific question here.
