### ISSUE TITLE
CLarify what hdrs is in the ambient L4 doc in HBONE

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14251]
https://istio.io/latest/docs/ops/ambient/usage/ztunnel/#hbonesection
- CLarify what hdrs is in the ambient L4 doc in HBONE
- HBONE (HTTP-Based Overlay Network Environment) - see announcement blog: https://istio.io/latest/blog/2022/introducing-ambient-mesh/

**Comment by Siddhipradamohapatro120503** [comment]
Can you provide more Details so the I can try to work on
