### ISSUE TITLE
Add ratelimit example for more advanced use cases

### ISSUE THREAD

**Issue by RicHincapie** [istio/istio.io#14263]
Problem:
Here https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/ we have a pretty simple use case for global ratelimit which does not let clear the use of more advanced features so new users can adopt ratelimit easily.

Solution:
It is needed an example which includes AND/OR logic aclaration and more complex PATH matching.

**Comment by kfaseela** [comment]
@RicHincapie will you be interested in pushing the PR with the changes for the same? Can help if you need any support in how to add the docs

**Comment by RicHincapie** [comment]
Yes, I'll work on this.
