### ISSUE TITLE
Cleanup section is missing for a task of observability

### ISSUE THREAD

**Issue by visheshtha** [istio/istio.io#14279]
Problem:
In a task of observability, [Classifying metrics](https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/),cleanup section is not there.But here we have created a yml file(attribute_gen_service.yaml),but its deletion is not mentioned in cleanup section as cleanup section is not present for this task.

Solution:
We can add a command `kubectl -n istio-system delete -f attribute_gen_service.yaml`,under cleanup section.

**Comment by GregHanson** [comment]
seems reasonable
