### ISSUE TITLE
update ambient get started guide for the inpod cni stuff once merged

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14355]
after https://github.com/istio/istio/issues/48212 PRs are merged, the cni limitations should be removed.

**Comment by linsun** [comment]
Bhavya Sachdeva pinged me offline that she is interested, I'll wait for her to comment in GitHub before assign to her.

Note: this is not merged yet.

**Comment by linsun** [comment]
This should be unblocked, please try latest master or release 1.21 build, or wait for the official 1.21 release. see https://github.com/istio/istio/issues/48212.

**Comment by linsun** [comment]
Sorry, just got confirmation from Eric that the change is not in beta 0 yet, but should be in -beta.1 since it was merged after beta.0 was released. I expect that the new build will be available in a day or 2.

**Comment by linsun** [comment]
beta 1 is already avail - anyone interested in helping this out?

**Comment by christian-posta** [comment]
What exactly is needed here? The current getting started correctly calls out that ambient mode can run on any cni that is supported by sidecar mode:

https://preliminary.istio.io/latest/docs/ops/ambient/getting-started/

**Comment by linsun** [comment]
I think this is already updated, and could probably be closed. cc @bleggett, if you agree, feel free to close it.LinSent from my iPhone On Mar 26, 2024, at 1:47 AM, Christian Posta ***@***.***> wrote:﻿
What exactly is needed here? The current getting started correctly calls out that ambient mode can run on any cni that is supported by sidecar mode:
https://preliminary.istio.io/latest/docs/ops/ambient/getting-started/

**Comment by christian-posta** [comment]
Actually, @nauticalmike had some suggestion to improve the guide based on the listing outputs. I'll let him comment here. Otherwise, I think we're in a good state for this issue.

**Comment by nauticalmike** [comment]
I'm working on this @linsun FYI

**Comment by nauticalmike** [comment]
https://github.com/istio/istio.io/pull/14788

**Comment by linsun** [comment]
Saw #14788 also merged, going to close this out, please reopen if I'm wrong. Thank you @nauticalmike for updating the tests!!
