### ISSUE TITLE
UX issue for resource annotation table

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14453]
This table is very hard to use - https://istio.io/latest/docs/reference/config/labels/:

1. for every resource, I have to scroll down to the bottom to scroll the bar to the right side then scroll up to read full description (last column).  Then I have to scroll down again, then scroll the bar to the left side, then scroll up to read the 1st column.
2. If I enlarge my browser window, the table doesn't become wider so still have to do 1.

Would appreciate creative ways to make this more usable. One idea is to use smaller tables, perhaps break by functions?

**Comment by zirain** [comment]
I have same feeling, I did an improvement on local it will looks like as following

![annotations](https://github.com/istio/istio.io/assets/4354057/812238e5-3690-48fe-b2c0-92d44d17348a)

**Comment by zirain** [comment]
see:
https://preliminary.istio.io/latest/docs/reference/config/annotations/
https://preliminary.istio.io/latest/docs/reference/config/labels/
