### ISSUE TITLE
Istio blogs should have convenient buttons (for example X and linkedin button)

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14504]
These are standards of blogs where each of them should have these convenient social site buttons to allow people to easily reshare.

saw it on cncf blog or cilium blog.

**Comment by shivamgupta2020** [comment]
From what I understand I suggest following:
- Implementing pagination in blogs helps users avoid long scrolling to reach the bottom of the page for social links. With pagination, users can easily access the end of the page and find social links without navigating through an extended scroll
- Changing style of icons to make it look more appealing
- moving social media links to top or side of the page.

Can u please clear what convenient meant here to better understand the issue?

**Comment by linsun** [comment]
For example, this blog is just published, and i want to share it on twitter or linkedin:

https://istio.io/latest/blog/2024/kubecon-eu/

Usually, there is a button for each social site (at top or bottom or side) that I can click which opens up the post ready to be shared.  (our button simply directs to X etc without the context of the blog.) If you check this cncf blog, and click on the X button, you'll know what I mean:

https://www.cncf.io/blog/2024/01/19/xline-command-deduplication-mechanism-part-one-introduction-to-rifl/

**Comment by shivamgupta2020** [comment]
I'm not sure which file to make changes in. While surfing through the istio directory, i found 
layouts/blog/single.html
above file to make changes in. Can u confirm this or if there is any other file please share path of that file.

**Comment by linsun** [comment]
cc @craigbox or @davidhauck who may know without digging

**Comment by craigbox** [comment]
That looks good.  You probably want to put social sharing into a partial like how 

`{{ partial "posts_navigation.html" . }}`

is.

**Comment by dhawton** [comment]
This should be fairly easy to implement as a partial as Craig mentioned. I can pick this up if @shivamgupta2020 is not able to.
