### ISSUE TITLE
Canary upgrades doc : same namespace appeared several times into a schema. 

### ISSUE THREAD

**Issue by blackpegaz** [istio/istio.io#14528]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

Hi, 

Into the [Stable revision labels](https://istio.io/latest/docs/setup/upgrade/canary/revision-tags-after.svg) section, [this schema](https://istio.io/latest/docs/setup/upgrade/canary/revision-tags-after.svg) shows the same namespace name (`app-ns-2`) tree times. 
-  In this case, does the namespace `app-ns-3` use the tag `prod-canary` or has it already been relabelled to use the tag `prod-stable` ?   

Doc page : [Canary Upgrades](https://istio.io/latest/docs/setup/upgrade/canary/)

Regards

Benjamin

### Version

```Text
Current
```

**Comment by windsonsea** [comment]
/assign
To fix the image in doc

**Comment by blackpegaz** [comment]
> > In this case, does the namespace app-ns-3 use the tag prod-canary or has it already been relabelled to use the tag prod-stable ?
> 
> It has been relabelled to prod-stable as you can see there's a command to overwrite the webhook:
> 
> ```
> istioctl tag set prod-stable --revision 1-20-2 --overwrite
> ```

Thank you @hanxiaop. I read this information previously. 

From my user perspective this part of the documentation gives a technical explanation on why and how to use "Stable revision labels"  in a canary upgrade context, but, when I read it for the first time, I asked myself:
- Is it possible to let the app workload points to the `prod-canary` tag at this step ?
- When to remove the `prod-canary` tag ? 
- What is the best practice ?

Regarding helm canary upgrade, trying and testing step by step helped me to understand the solution.

In the below schema the `prod-canary` tag still exists at step 3 to show a possible situation. Personally, I choose to delete this tag as soon as the canary upgrade is finished. 
 
![istio-canary-upgrade-nonofficial-14528](https://github.com/istio/istio.io/assets/5478034/b4fd558b-1ad4-428c-bb54-be5b59ba7d24)
