### ISSUE TITLE
kubecon EU blog should be updated with latest info

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14537]
The schedule is already out.

If anyone from @istio/steering-committee  has bandwidth, feel free to grab it before i get to it.

cc @craigbox or @kfaseela who might be interested.

**Comment by linsun** [comment]
blog link: https://istio.io/latest/blog/2024/kubecon-eu/
schedule: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/schedule/

**Comment by kfaseela** [comment]
https://github.com/istio/istio.io/pull/14539

**Comment by linsun** [comment]
Thank you Faseela!

**Comment by kfaseela** [comment]
closed by https://github.com/istio/istio.io/pull/14539

**Comment by craigbox** [comment]
Thanks @kfaseela!
