### ISSUE TITLE
Discuss the zh translation about minor version

### ISSUE THREAD

**Issue by windsonsea** [istio/istio.io#14565]
In the istio.io repo, `minor version` has 3 variants in Chinese:

- 26 小版本
- 16 次要版本
- 9 minor 版本

![image](https://github.com/istio/istio.io/assets/79828097/964f2da3-7630-493a-9c7c-ad904fb62e46)
![image](https://github.com/istio/istio.io/assets/79828097/8e7997a3-5beb-4f6e-b883-59effaa14aae)
![image](https://github.com/istio/istio.io/assets/79828097/29459fdf-5a39-4d57-8d6e-895d25d4ee92)

cc @hanxiaop @wilsonwu @zirain

**Comment by windsonsea** [comment]
It's necessary to use a consistent word to express `minor version` in Chinese.

Personally, I like 小版本

**Comment by wilsonwu** [comment]
I prefer 次要版本, I think it is more common for different version rules, for example: 1.2, 1.2.3 and 1.2.3.4, for these all, the minor can understand as the secend version number, but 小版本 seems hard to define, maybe the 3rd, maybe the 4th.

**Comment by hanxiaop** [comment]
> It's necessary to use a consistent word to express `minor version` in Chinese.
> 
> Personally, I like 小版本

I just searched Kubernetes docs, and seems like they do not have a consistent translation either. Are they going to do the same thing?

**Comment by windsonsea** [comment]
> > It's necessary to use a consistent word to express `minor version` in Chinese.
> > Personally, I like 小版本
> 
> I just searched Kubernetes docs, and seems like they do not have a consistent translation either. Are they going to do the same thing?

Just checked the k8s.io repo, the minor version has:

- 90 次要版本
- 26 小版本
- 2 minor 版本

I think yes for the recent 2 years docs.

**Comment by windsonsea** [comment]
Yes, seems 次要版本 is more popular
