### ISSUE TITLE
add a step for cleanup section of distributing webassembly modules

### ISSUE THREAD

**Issue by visheshtha** [istio/istio.io#14574]
In cleanup section of [distributing webassembly modules](https://istio.io/latest/docs/tasks/extensibility/wasm-module-distribution/),only cleanup of wasm modules is given.No cleanup of bookinfo app is given.
So could we add a step to cleanup the bookinfo sample app also as we have deployed the bookinfo app but not cleanedup.
If it seems reasonable,I would like to work on it

**Comment by visheshtha** [comment]
@kfaseela @ericvn @howardjohn PTAL,if it's worth adding or not?

**Comment by leosarra** [comment]
I feel there is no need to add the cleanup of bookinfo into the wasm page.
The page is already saying that bookinfo is a prerequisite for the verification and it is providing a link which points to the instruction for both installation and uninstallation of the application.

**Comment by visheshtha** [comment]
ok,thanks!
