### ISSUE TITLE
'setting up environment variables' link not working of  "using the codebase" of wiki

### ISSUE THREAD

**Issue by visheshtha** [istio/istio.io#14575]
In the wiki page of istio,when clicking on the `setting up environment variables` link under the [using the codebase](https://github.com/istio/istio/wiki/Using-the-Code-Base) page,it is not taking us to the content as the address of the link is incorrect.It should be `https://github.com/istio/istio/wiki/Using-the-Code-Base#setting-up-environment-variables` instead of `https://github.com/istio/istio/wiki/Using-the-Code-Base#setting-up-the-environment-variables`

**Comment by hanxiaop** [comment]
Updated, thanks

**Comment by visheshtha** [comment]
Hi @hanxiaop,thanks!
Also the link for delve tutorial in `debug an istio container with delve` is not working.Could we replace it to[ Delve tutorial](https://blog.ralch.com/articles/golang-debug-with-delve/) ?

**Comment by hanxiaop** [comment]
> Hi @hanxiaop,thanks! Also the link for delve tutorial in `debug an istio container with delve` is not working.Could we replace it to[ Delve tutorial](https://blog.ralch.com/articles/golang-debug-with-delve/) ?

@visheshtha Could you check it again? Thanks for improving the content!

**Comment by visheshtha** [comment]
yes,working now,thanks!
