### ISSUE TITLE
latency inconsistence between istio 1.20 and older releases prior to 1.20

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14585]
1.20 latency- https://istio.io/latest/docs/ops/deployment/performance-and-scalability/#latency-for-istio-120 < 0.4ms 
1.19 latency-https://istio.io/v1.19/docs/ops/deployment/performance-and-scalability/#latency-for-istio-119 2ms
1.18 latency: similar as 1.19's

Checked with @AndreaM12345 who believes the inconsistency is caused by running on IKS (in 1.19 and prior) vs 1.20 in CNCF provided baremetal hardware.

It would be really nice if we could have 1.19 and 1.18 numbers updated on the CNCF provided hardware if anyone has bandwidth as this inconsistency triggered a lot of questions from our users.

**Comment by kfaseela** [comment]
cc @leosarra

**Comment by Shuayb1** [comment]
Okay I'll look into it.

**Comment by linsun** [comment]
Thank you very much @Shuayb1!  Assign for you for now, please let me know if you won't have time for it.

cc @dhawton

**Comment by craigbox** [comment]
nope, though I would suggest we add "This testing was performed on the [CNCF Community Infrastructure Lab](https://github.com/cncf/cluster)." to all iterations
