### ISSUE TITLE
Istio injection doc could use a few clarifications

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14597]
Doc: https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy

What is not clear when it says `If either label is enabled, the pod is injected`, does the label include istio-injection, sidecar.istio.io/inject and 	istio.io/rev here? for example, if i have istio-injection=disabled on NS, and istio.io/rev=1.20 on the pod, would the injection happen?

**Comment by linsun** [comment]
cc @howardjohn @peterj

**Comment by howardjohn** [comment]
No, it would not due to the "If either label is disabled, the pod is not injected" part. Agree its a bit confusing with the 3 labels though

**Comment by linsun** [comment]
Thanks, we can clarify it. The other one is confusing is:

i also found odd you had to remove istio-injection=enabled on the NS when you have istio.io/rev configured on the pod.

Thinking it over, this is as designed because istio-injection=enabled implies the default CP to inject

**Comment by peterj** [comment]
Here are the scenarios is tested:

1. `istio-injection=enabled` & `istio.io/rev` set ==> default revision is used (not necessarily the one set in istio.io/rev)
2. No `istio-injection` label & `istio.io/rev` set ==> the revision set in `istio.io/rev` is used
3. `istio-injection=disabled` & `istio.io/rev` set ==> no injection happens

**Comment by howardjohn** [comment]
Here is basically every combination possible: https://github.com/istio/istio/blob/44c2f6312201a4172f138b1953e763ced3170cff/operator/cmd/mesh/manifest-generate_test.go#L1060

The reason things behave as they do is largely for backwards compatibility
