### ISSUE TITLE
image tag shouldn't force user to calculate a ratio, default should be to preserve original

### ISSUE THREAD

**Issue by ldemailly** [istio/istio.io#1460]
image tag shouldn't force user to calculate a ratio, default should be to preserve original

right now it's both cumbersome and error prone (not say under [documented](https://istio.io/about/contribute/writing-a-new-topic/#adding-images), is it X/Y or Y/X,...)

computers should do that if it's required by the underlying system

ps: normal HTML does not require both x/y specified, eg
```
<img src="/images/html5.gif" alt="HTML5 Icon" style="width:10%">
```
works fine

**Comment by ldemailly** [comment]
cool, 
```
 (image height / image width) * 100
```
the build phase could load the image (if only to check it exists/is valid etc....) and extract its size for us ?

**Comment by geeknoid** [comment]
Yes, in theory. The "build phase" is "run Hugo" and hugo doesn't support
plugins or other means of integration.

The alternative is to have a tool that grovels over the images and outputs
a global YAML file with the dimensions of all images. Hugo could consume
and consult this file for the sizes, and then we could derive the ratio
automatically.

**Comment by ldemailly** [comment]
maybe the imgbot could do that for us (check/fix ratios?)
