### ISSUE TITLE
zh: formatting error of docs content/zh/docs/tasks/traffic-management/ingress/gateway-api 

### ISSUE THREAD

**Issue by nicole-lihui** [istio/istio.io#14680]
The documentation of the Kubernetes Gateway API has a formatting issue.

![image](https://github.com/istio/istio.io/assets/44200120/22a38efc-a268-4886-88f0-34bb339f5ee9)
https://istio.io/latest/zh/docs/tasks/traffic-management/ingress/gateway-api/

**Comment by hanxiaop** [comment]
Fixed by https://github.com/istio/istio.io/pull/14681
