### ISSUE TITLE
Multicluster documentation uses the operator installation model

### ISSUE THREAD

**Issue by kbreit** [istio/istio.io#14765]
The documentation at https://istio.io/latest/docs/setup/install/multicluster/primary-remote/ shows how to install Istio using the operator model. However, the operator installation documentation at https://istio.io/latest/docs/setup/install/operator/ says

> Use of the operator for new Istio installations is discouraged in favor of the [Istioctl](https://istio.io/latest/docs/setup/install/istioctl) and [Helm](https://istio.io/latest/docs/setup/install/helm) installation methods. While the operator will continue to be supported, new feature requests will not be prioritized.

The documentation for installation should focus on recommended methods instead of deprecated methods.

**Comment by hanxiaop** [comment]
The `IstioOperator` resource is not equivalent to the operator mentioned in that document, although the operator controller reconciles that resource as well. The discouraged thing specifically meant to be the in-cluster operator controller. Using istioctl is acceptable and will continue to be supported. We are in the process of making the wording less confusing.
