### ISSUE TITLE
Concurrency proxyConfig definition need updating

### ISSUE THREAD

**Issue by RicHincapie** [istio/istio.io#14777]
As per the latest docs here https://istio.io/latest/docs/reference/config/networking/proxy-config/#ProxyConfig, concurrency settings are described as

> _The number of worker threads to run. If unset, defaults to 2. If set to 0, this will be configured to use all cores on the machine using CPU requests and limits to choose a value, with limits taking precedence over requests._

But, at code level here https://github.com/istio/api/blob/94d8c5322f50ffb0c70adb321c62603d1180e413/mesh/v1alpha1/proxy.proto#L458 says:

> _The number of worker threads to run.
  // If unset, this will be automatically determined based on CPU requests/limits.
  // If set to 0, all cores on the machine will be used._

Based on this PR https://github.com/istio/istio/pull/43865, the behavior is the one described at code level.

**Comment by kfaseela** [comment]
i think, this comes from: https://github.com/istio/api/blob/94d8c5322f50ffb0c70adb321c62603d1180e413/networking/v1beta1/proxy_config.proto#L119
