### ISSUE TITLE
Fix k3d setup instructions

### ISSUE THREAD

**Issue by krisztianfekete** [istio/istio.io#14797]
The current [k3d guide](https://istio.io/latest/docs/setup/platform-setup/k3d/#set-up-istio-for-k3d) mentions labelling `istio-system` for injection. That step shouldn't be needed, so I propose to remove it.
What do you think?

**Comment by linsun** [comment]
Agree on removing it.  I believe the requirement is not to have the namespace disable injection (istio-injection: disabled).
