### ISSUE TITLE
CNI install docs are have a few typos

### ISSUE THREAD

**Issue by ktarplee** [istio/istio.io#14799]
[This](https://istio.io/latest/docs/setup/additional-setup/cni/#installing-with-helm) section tells how to install istiod (for use with the CNI).  

The command is wrong.  First it has a space in front (which is just annoying because it make sit so you cannot use the up arrow).  The second issue is that it needs to have `--create-namespace`. The third and critical issue is the `values.` should not be in the `--set` argument. We want

```bash
helm install istiod istio/istiod -n istio-system --set istio_cni.enabled=true --wait --create-namespace
```

**Comment by kfaseela** [comment]
Feel free to open a PR with the fix if you are interested
