### ISSUE TITLE
TCP Traffic Shifting Task failure

### ISSUE THREAD

**Issue by adityasamant25** [istio/istio.io#14792]
I'm working with Istio 1.21.0 on a minikube cluster running on a Mac M1.

The TCP Traffic Shifting Task documented in the page below does not work well.
https://istio.io/latest/docs/tasks/traffic-management/tcp-traffic-shifting/

In the [Apply weight-based TCP routing](https://istio.io/latest/docs/tasks/traffic-management/tcp-traffic-shifting/#apply-weight-based-tcp-routing) section, at step 2 the `TCP_INGRESS_PORT` and `INGRESS_HOST` environment variables are set on the local machine.

In step 3, these variables are read from within the container:
`kubectl exec "$SLEEP" -c sleep -n istio-io-tcp-traffic-shifting -- sh -c "(date; sleep 1) | nc $INGRESS_HOST $TCP_INGRESS_PORT";`

However, these environment variables are not defined inside the container and they evaluate to empty strings.

As such, the netcat (nc) command fails.

```
export SLEEP=$(kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o jsonpath={.items..metadata.name}) 
for i in {1..20}; do \
kubectl exec "$SLEEP" -c sleep -n istio-io-tcp-traffic-shifting -- sh -c "(date; sleep 1) | nc $INGRESS_HOST $TCP_INGRESS_PORT"; \
done

command terminated with exit code 1
command terminated with exit code 1
```

I believe there is some step missing in this lab in order for the container to be able to evaluate the `INGRESS_HOST` and `TCP_INGRESS_PORT` environment variables, for the netcat command to succeed.

In case any more information is needed for investigation, please let me know.

Kind Regards,
Aditya.

**Comment by dhawton** [comment]
The environment variables are not supposed to be set in the container, they're evaluated by your shell when running the command and passed into the container not as variables, but the values. The values are set by step 2 of https://istio.io/latest/docs/tasks/traffic-management/tcp-traffic-shifting/#apply-weight-based-tcp-routing.

**Comment by adityasamant25** [comment]
Thanks @dhawton for the detailed explanation. You are right, it was a misunderstanding on my part.

However, I still think there is some issue in the instructions mentioned on the [tcp-traffic-shifting](https://istio.io/latest/docs/tasks/traffic-management/tcp-traffic-shifting/) page.

I have followed all the instructions and I am able to resolve the variables locally:
```
echo $TCP_INGRESS_PORT
31400

echo $INGRESS_HOST
127.0.0.1

echo $SLEEP             
sleep-7656cf8794-c5qvj
```

When I run the command, it fails with an exit code 1 (instead of a successful output):

```
for i in {1..20}; do \
kubectl exec "$SLEEP" -c sleep -n istio-io-tcp-traffic-shifting -- sh -c "(date; sleep 1) | nc $INGRESS_HOST $TCP_INGRESS_PORT"; \
done

command terminated with exit code 1
command terminated with exit code 1
command terminated with exit code 1
command terminated with exit code 1
```

I thought it could be an issue with the zsh terminal, but the same behaviour is present on using bash as well.

Using hardcoded values instead of variables leads to the same outcome:

```
kubectl exec sleep-7656cf8794-c5qvj -c sleep -n istio-io-tcp-traffic-shifting -- sh -
c "(date; sleep 1) | nc 127.0.0.1 31400";
command terminated with exit code 1
```

I thought it could be related to the fact that there is no instruction for sidecar injection on this page.
So I executed the steps after sidecar injection, using the below command:
`kubectl label namespace istio-io-tcp-traffic-shifting istio-injection=enabled`

But this leads to the same failure as well.

I am uncertain if I'm doing something wrong, or there is an issue with this tutorial.

**Comment by dhawton** [comment]
I am assuming the `127.0.0.1` is a mask of the real ingress host? If not, that can't be correct.

**Comment by adityasamant25** [comment]
> I am assuming the `127.0.0.1` is a mask of the real ingress host? If not, that can't be correct.

I'm following the instructions mentioned [here](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#determining-the-ingress-ip-and-ports).
I am using minikube. So I use the minikube tunnel command to mimic an external load balancer.
This assigns `127.0.0.1` as the `EXTERNAL-IP` of the `istio-ingressgateway` service

```
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
istio-ingressgateway   LoadBalancer   10.107.252.236   127.0.0.1     15021:32749/TCP,80:31857/TCP,443:31679/TCP,31400:30113/TCP,15443:30888/TCP   23h
```

The below command assigns `127.0.0.1` to the `INGRESS_HOST` variable:
`export INGRESS_HOST=$(kubectl -n "$INGRESS_NS" get service "$INGRESS_NAME" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')`

**Comment by dhawton** [comment]
127.0.0.1 would be invalid for the sleep pod since 127.0.0.1 to it would be itself. Note this part of the page:

If your environment does not support external load balancers, you can try [accessing the ingress gateway using node ports](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#using-node-ports-of-the-ingress-gateway-service).

**Comment by adityasamant25** [comment]
@dhawton You are absolutely right. Thank you so much for assisting me with this.

As I am using minikube, which does not use a real external load balancer, I tried using the node ports on the ingress gateway service as mentioned [here](https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#using-node-ports-of-the-ingress-gateway-service).

And it works just fine. I will close the issue. Really appreciate your help.

```
export INGRESS_HOST=$(kubectl get po -l istio=ingressgateway -n "${INGRESS_NS}" -o jsonpath='{.items[0].status.hostIP}')
export TCP_INGRESS_PORT=$(kubectl -n "${INGRESS_NS}" get service "${INGRESS_NAME}" -o jsonpath='{.spec.ports[?(@.name=="tcp")].nodePort}')
```

```
for i in {1..20}; do \                                              
kubectl exec "$SLEEP" -c sleep -n istio-io-tcp-traffic-shifting -- sh -c "(date; sleep 1) | nc $INGRESS_HOST $TCP_INGRESS_PORT"; \
done
one Tue Apr  2 17:28:48 UTC 2024
one Tue Apr  2 17:28:49 UTC 2024
one Tue Apr  2 17:28:50 UTC 2024
one Tue Apr  2 17:28:51 UTC 2024
one Tue Apr  2 17:28:52 UTC 2024
one Tue Apr  2 17:28:53 UTC 2024
```

**Comment by dhawton** [comment]
No problem, happy to help!
