### ISSUE TITLE
Document ways to configure trace sampling

### ISSUE THREAD

**Issue by joaopgrassi** [istio/istio.io#14831]
## Context

So far, there is 3 different ways to configure the [Runtime random sampling](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/runtime#config-http-conn-man-runtime-random-sampling) in Istio:

In order of precedence:

- `telemetry.RandomSamplingPercentage` https://istio.io/latest/docs/reference/config/telemetry/#Tracing
- `defaultConfig.tracing.sampling` https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Tracing
- `PILOT_TRACE_SAMPLING` env var / `values.pilot.traceSampling` https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/#customizing-trace-sampling (type in the env var name `PILOT_TRACE_SAMPLE`)

All these options, configure a percentage based sampling mechanism. Although this is something, more robust sampling approaches exist. For example, the OpenTelemetry project [defines several of them](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler).

In a recent PR, I introduced a feature that allows users to configure such more "advanced" samplers to the [OpenTelemetryTracingProvider](https://github.com/istio/istio/pull/50202). This now means we have yet another option to configure sampling. 

One of the discussion in the PR was that we should clarify and demonstrate to users all this options and how one affect each other. This issue is to then track this documentation work. 

### Option 1:

We have this page [Customizing Trace sampling](https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/#customizing-trace-sampling) which we show _some_ of the options. We could simply expand that there and show all options and how one affect the other (which ones has precedence)

Pros:
- No need for a new page

Cons:
- Will talk about the `OpenTelemetryTracingProvider` although that's not related to that page. So it's a bit out of context

### Option 2:

Introduce a new page under [Distributed Tracing](https://istio.io/latest/docs/tasks/observability/distributed-tracing/) tasks specific for sampling. There we can document all the ways:

1. New option for the `OpenTelemetryTracingProvider` with custom samplers: Takes precedence of all others and **override** [Runtime random sampling](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/runtime#config-http-conn-man-runtime-random-sampling) to 100%. This is so all spans arrive at the sampler for its decision.
2. `defaultConfig.tracing.sampling` default for everything
3. `telemetry.RandomSamplingPercentage` can be changed per namespace
4. `PILOT_TRACE_SAMPLING` is this still even worth documenting? The page here says it's discouraged https://istio.io/latest/docs/tasks/observability/distributed-tracing/mesh-and-proxy-config/#customizing-trace-sampling

I personally prefer option 2, as we can have examples and really drill down on the explanations, which I think will be very beneficial. When I started working with Istio I was **very** confused with all these different ways of setting this, and I didn't find any place that explained it. 

CC @zirain @howardjohn

**Comment by howardjohn** [comment]
Either one works for me. If we do 1 we need https://istio.io/latest/docs/tasks/observability/distributed-tracing/telemetry-api/ as well though.

Maybe we do 2, and make the "sampling" section in the current docs just link there

**Comment by zirain** [comment]
IMO, we should remove `PILOT_TRACE_SAMPLING` in the future, otherwise LGTM.

**Comment by joaopgrassi** [comment]
Alright! I will try to put something together for a new page. Once I have a draft I will ping you both. Thanks!

**Comment by joaopgrassi** [comment]
@howardjohn @zirain I created a draft PR https://github.com/istio/istio.io/pull/14856. Please let me know what you think. I'm open for ideas/suggestions. Thanks!
