### ISSUE TITLE
Istio 1.22 release announcement & blog tracking

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#14874]
Opening this issue to track major changes in 1.22 we should call out, and track blogs we should write alongside the release

Major changes in 1.22

* Ambient to beta
* Gateway API to GA
* Gateway API Mesh to Beta
* ~All Istio APIs to "v1"
* Distroless to GA
* Delta XDS and vtprotobuf. tl;dr better control plane performance

cc @linsun @craigbox @istio/release-managers-1-22

**Comment by keithmattix** [comment]
I started a doc to get assignments for these blogs: https://docs.google.com/document/d/1T7dEevIGEX6Smd1p_BPxNX8HljgCObRioOGJS-kssE0/edit#heading=h.c182c6n9ku8k
