### ISSUE TITLE
Update feature status page for ambient beta for 1.22

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14901]

**Comment by ericvn** [comment]
Note that this requires changes in https://github.com/istio/enhancements, namely a new document in features and a corresponding update in FEATURES.yaml. This will need to be cherry-picked to the release-1.22 branch so that it shows up in the docs.

**Comment by professorabhay** [comment]
Hey! So, Can I make changes in the `istio/enhancements` repo?

**Comment by craigbox** [comment]
done, pinged https://github.com/istio/istio/pull/52524 to get any updates for 1.23, which should only have been dual stack.
