### ISSUE TITLE
bookinfo gateway default yaml 

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14967]
In the get started ambient guide, we ask users to do the following cmd, why not just ship the updated bookinfo-gateway.yaml by default?  This cmd looks complex.  for namespace, i think we can just deploy into the istio-system namespace?

```
sed -e 's/from: Same/from: All/'\
      -e '/^  name: bookinfo-gateway/a\
  namespace: istio-system\
'     -e '/^  - name: bookinfo-gateway/a\
    namespace: istio-system\
' samples/bookinfo/gateway-api/bookinfo-gateway.yaml | kubectl apply -f -
```

**Comment by linsun** [comment]
@frankbu cc you for thoughts, you may have created the yaml originally?

**Comment by frankbu** [comment]
@linsun IIRC, this was a temporary workaround for a ztunnel bug where you couldn't create the gateway and route in the default ns (i.e., `kubectl apply samples/bookinfo/gateway-api/bookinfo-gateway.yaml` wouldn't work). Maybe that bug is fixed now, so the workaround can be removed?

**Comment by linsun** [comment]
Thanks @frankbu! I've tried to remove it and it works well - https://github.com/istio/istio.io/pull/14980
