### ISSUE TITLE
k3d doc should be clarified

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14970]
Took me a while to figure out the params mentioned in the doc is for istioctl, not for k3d.

https://preliminary.istio.io/latest/docs/ambient/install/platform-prerequisites/#k3s

Something like this cmd is what the doc is suggesting:

./istioctl install --set profile=ambient --skip-confirmation  --set values.cni.cniConfDir=/var/lib/rancher/k3s/agent/etc/cni/net.d --set values.cni.cniBinDir=/var/lib/rancher/k3s/data/current/bin/

**Comment by bleggett** [comment]
Should be fixed with https://github.com/istio/istio.io/pull/14990

**Comment by linsun** [comment]
Yes, thank you Ben!!
