### ISSUE TITLE
swap default and Gateway API instructions?

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#14975]
https://preliminary.istio.io/latest/docs/setup/getting-started/#download:

> Istio includes beta support for the Kubernetes [Gateway API](https://gateway-api.sigs.k8s.io/) and intends to make it the default API for traffic management [in the future](https://preliminary.istio.io/latest/blog/2022/gateway-api-beta/). If you would like to get started with Istio using the Gateway API, refer to the [future getting started instructions](https://preliminary.istio.io/latest/docs/setup/additional-setup/getting-started/) instead of the following.

The link reads

> Around the time of the v1 release of the API, we intend to make the Gateway API the default method for configuring all traffic routing in Istio - for ingress (north-south) and service-to-service (east-west). At that time, we will change our documentation and examples to reflect the recommendation.

Is it "the future" yet and should we switch these doc sets now?

**Comment by linsun** [comment]
I'd vote no as GAMMA API is still fairly limited for mesh to my understanding.

**Comment by craigbox** [comment]
Consensus from Slack is that we are still not ready; I'll address this in a refresh of the Concepts doc that we'll probably do after the launch of 1.22.
