### ISSUE TITLE
Add Waypoint Proxy Doc for Ambient Beta Istio 1.22 release

### ISSUE THREAD

**Issue by MorrisLaw** [istio/istio.io#14984]
We need to add documentation for Waypoint Proxy into the User guide. We can update the doc placeholder that already exists here: https://preliminary.istio.io/latest/docs/ambient/usage/waypoint/

We can probably borrow from this already existing doc as needed: https://deploy-preview-13954--preliminary-istio.netlify.app/latest/docs/ops/ambient/usage/waypoint/

**Comment by linsun** [comment]
I can work on this next.
