### ISSUE TITLE
Expose v1 examples for v1 API Docs

### ISSUE THREAD

**Issue by whitneygriffith** [istio/istio.io#14992]
The below API docs need to be updated to show the `v1` examples. 
[DestinationRule](http://istio.io/latest/docs/reference/config/networking/destination-rule/)
[Gateway](https://istio.io/latest/docs/reference/config/networking/gateway/)
[ServiceEntry](http://istio.io/latest/docs/reference/config/networking/service-entry/)
[Sidecar](http://istio.io/latest/docs/reference/config/networking/sidecar/)
[VirtualService](http://istio.io/latest/docs/reference/config/networking/virtual-service/)
[WorkloadEntry](http://istio.io/latest/docs/reference/config/networking/workload-entry/)
[WorkloadGroup](http://istio.io/latest/docs/reference/config/networking/workload-group/)
[Telemetry API](https://istio.io/latest/docs/reference/config/telemetry/)* 
[PeerAuthentication](http://istio.io/latest/docs/reference/config/security/peer_authentication/)

**Comment by professorabhay** [comment]
Hi, Can you provide additional context about that?

**Comment by whitneygriffith** [comment]
> Hi, Can you provide additional context about that?

If you look at the current [website](https://istio.io/latest/docs/reference/config/networking/destination-rule/), within the YAML examples you will see an example provided for the `v1alpha3` and `v1beta1` API versions. 

But since these APIs were promoted to `v1` the [website](https://preliminary.istio.io/latest/docs/reference/config/networking/destination-rule/) now shows only `v1beta` YAML examples. 

Ideally we would like for the `v1` examples to be shown as defined in the [proto](https://github.com/istio/api/blob/0d73c8a3d5a7dffa950de1fe5050c50c37a93a02/networking/v1/destination_rule.proto#L55)

**Comment by whitneygriffith** [comment]
The handwritten docs like [these](https://istio.io/latest/docs/tasks/observability/telemetry/) need to be updated as well.
