### ISSUE TITLE
Organize ambient architecture doc

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#15005]
Some discussion from https://github.com/istio/istio.io/pull/14994#discussion_r1585314434 where we may likely need to have multiple pages under ambient architecture.  Open this to capture thoughts and actions.

Architecture:
- Overview
- API
  - [Authorization Policy](https://github.com/istio/istio.io/issues/15006)
- Deep Dive

cc @craigbox @bleggett

**Comment by bleggett** [comment]
https://github.com/istio/istio.io/pull/15004 does this as a matter of course.

I think we do need at least 2 subheadings based on content we already have, as @craigbox 's doc already pointed out:

- Architecture
  - Traffic Redirection
  - HBONE

**Comment by craigbox** [comment]
* **Labels**: should move under a "Adding your workload to the ambient mesh" page under /docs/ambient/usage/
* **Layer 7 policy attachment to waypoints**: should move to an "Attaching policy to waypoints" under /docs/ambient/usage/waypoints/, but I'm confused as I would expect to attach policy to workloads, not waypoints
* **Traffic routing**: make this a sub-page of architecture?

**Comment by bleggett** [comment]
> Labels: should move under a "Adding your workload to the ambient mesh" page under /docs/ambient/usage/ ?

Yes please.

Something like

```
### Labels
#### Adding Workloads To Ambient Dataplane
(talk about adding `dataplane-mode` labels)
#### Enforcing L7 Policies In Ambient
(talk about adding `use-waypoint` labels) -> link to `Layer 7 Policy Attachment` subdoc
```

> Layer 7 policy attachment to waypoints: should move to an "Attaching policy to waypoints" under /docs/ambient/usage/waypoints/, but I'm confused as I would expect to attach policy to workloads, not waypoints

I think if we breadcrumb from "for L7 policy, add a waypoint with this label" -> "then see this doc for applying L7 policy (to that waypoint)" it will be clear.

**Comment by linsun** [comment]
Maybe complete now?

**Comment by craigbox** [comment]
https://istio.io/latest/docs/ambient/architecture/ is now only a table of contents with subpages, a good base to build from.
