### ISSUE TITLE
investigate opencensusagent doc tests (remove?)

### ISSUE THREAD

**Issue by dhawton** [istio/istio.io#15086]
The tests were broken when we bumped master back to istio/istio master. Attempted to fix through https://github.com/istio/istio.io/pull/15084 without much luck, so the test was disabled to unblock master.

We need to fix the test. In short, it appears that the sidecar does not start in the test which causes bookinfo to timeout on the deployment.

**Comment by howardjohn** [comment]
Opencensus is removed https://github.com/istio/istio/issues/50808#issue-2274429048 so we probably actually want to remove the doc.

cc @zirain @kyessenov @lei-tang to verify

**Comment by dhawton** [comment]
That would make sense.. the istio tag we were using was from 3 weeks ago, and broke when it got bumped to one from yesterday.. created this so I could follow up after unblocking master.
