### ISSUE TITLE
Confusing Steps in Ambient Getting Started

### ISSUE THREAD

**Issue by danehans** [istio/istio.io#15119]
Overall, I was able to successfully complete the steps in the [ambient getting started](https://istio.io/latest/docs/ambient/getting-started/) guide. However, a few stpes provided confusion that I would like to bring to the community's attention:

> Deploy an ingress gateway so you can access the bookinfo app from outside the cluster:
To get IP address assignment for Loadbalancer service types in kind, you may need to install a tool like [MetalLB](https://metallb.universe.tf/). Please consult [this guide](https://kind.sigs.k8s.io/docs/user/loadbalancer/) for more information.
Create a [Kubernetes Gateway](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1.Gateway) and [HTTPRoute](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1.HTTPRoute):
$ kubectl apply -f [samples/bookinfo/gateway-api/bookinfo-gateway.yaml](https://raw.githubusercontent.com/istio/istio/release-1.22/samples/bookinfo/gateway-api/bookinfo-gateway.yaml)

None of the proceeding steps actually test connectivity from outside the cluster. By default, the bookinfo Gateway creates a service of type `LoadBalancer` and therefore the Gateway status never reaches `Programmed=true` without running in a cloud environment or using a tool such as MetalLB to populate the Service status with a LoadBalancer IP. Istio supports annotating a Gateway with `networking.istio.io/service-type: ClusterIP` to create a ClusterIP service instead of a LoadBalancer service. I suggest updating the guide to use this annotation to simplify the UX.

>Update your AuthorizationPolicy to explicitly allow the sleep service to GET the productpage service, but perform no other operations:

The proceeding yaml removes the `- cluster.local/$GATEWAY_SERVICE_ACCOUNT` source from the L4 example that is being updated but makes no mention why. I believe this was done in error and should be re-added.

**Comment by danehans** [comment]
>Istio supports annotating a Gateway with networking.istio.io/service-type: ClusterIP to create a ClusterIP service instead of a LoadBalancer service. I suggest updating the guide to use this annotation to simplify the UX.

To fix this issue, I'm considering adding an example Gateway manifest similar to `https://raw.githubusercontent.com/istio/istio/release-1.22/samples/bookinfo/gateway-api/bookinfo-gateway.yaml` but includes the `networking.istio.io/service-type: ClusterIP`, e.g. `https://raw.githubusercontent.com/istio/istio/release-1.22/samples/bookinfo/gateway-api/bookinfo-internal-gateway.yaml` or do maintainers prefer adding a step that patches the current Gateway with the annotation?

cc: @frankbu @craigbox @linsun @howardjohn

**Comment by craigbox** [comment]
The guide explicitly tells you to run `kind`, so we should make the steps work in `kind`.  That does mean telling people to install [Cloud Provider `kind`](https://kind.sigs.k8s.io/docs/user/loadbalancer/), which is a hassle (requires Go installed, for example).

As long as you don't ever need to access the gateway from outside the cluster (or it's trivial to proxy to do so with kind) changing to `ClusterIP` seems like a good step.

How about `https://raw.githubusercontent.com/istio/istio/release-1.22/samples/bookinfo/gateway-api/bookinfo-gateway-kind.yaml` (to make clear what it's for).

---

wrt the service account policy being removed, does it enable this example?

`$ # this should fail with an RBAC error because the identity is not allowed`

**Comment by linsun** [comment]
I also run into this LB issue, but mainly because I was on Mac. Folks on Linux or using cloud env seems fine. 

Maybe we could have what you propose to add `networking.istio.io/service-type: ClusterIP` annotation as an optional step for envs don't support LB IP?

**Comment by linsun** [comment]
> The proceeding yaml removes the `- cluster.local/$GATEWAY_SERVICE_ACCOUNT` source from the L4 example that is being updated but makes no mention why. I believe this was done in error and should be re-added.

Because currently in ambient there is a limitation, traffic from ingress gateway to productpage doesn't go through waypoint so having the gateway service account is not going to do anything.  to answer @craigbox's q, it would not enable RBAC error due to this reason.

**Comment by linsun** [comment]
Another option: add a note like https://istio.io/latest/docs/ambient/install/helm-installation/#install-an-ingress-gateway-optional did.

**Comment by danehans** [comment]
> Another option: add a note like https://istio.io/latest/docs/ambient/install/helm-installation/#install-an-ingress-gateway-optional did.

^ is an option but not as preferable since a user may get confused or question why the gateway status is not as expected.

**Comment by danehans** [comment]
> I also run into this LB issue, but mainly because I was on Mac. Folks on Linux or using cloud env seems fine.

This is not an issue for cloud envs but it's still an issue for Linux. Since a Gateway creates a LoadBalancer service, a controller is required to assign an external IP. Using `networking.istio.io/service-type: ClusterIP` is required for kind unless MetalLB or [Cloud Provider kind](https://kind.sigs.k8s.io/docs/user/loadbalancer/) is installed. Using the annotation simplifies the guide and reduces the maintenance burden.

**Comment by danehans** [comment]
IMHO the key decision is whether a separate manifest is added for the internal Gateway or patch the Gateway with the annotation.

**Comment by howardjohn** [comment]
a LoadBalancer service also has a ClusterIP. We could just always use a LoadBalancer service, and just have users not use it if they don't get one allocated? 

Unless istiod complains...

**Comment by linsun** [comment]
> > I also run into this LB issue, but mainly because I was on Mac. Folks on Linux or using cloud env seems fine.
> 
> This is not an issue for cloud envs but it's still an issue for Linux. Since a Gateway creates a LoadBalancer service, a controller is required to assign an external IP. Using `networking.istio.io/service-type: ClusterIP` is required for kind unless MetalLB or [Cloud Provider kind](https://kind.sigs.k8s.io/docs/user/loadbalancer/) is installed. Using the annotation simplifies the guide and reduces the maintenance burden.

Yeah, forgot to mention on Linux, setting up metalLB is pretty straightforward so not an issue most times.

**Comment by linsun** [comment]
> a LoadBalancer service also has a ClusterIP. We could just always use a LoadBalancer service, and just have users not use it if they don't get one allocated?
> 
> Unless istiod complains...

Istiod doesn't complain. The prob is this cmd `kubectl wait --for=condition=programmed gtw/bookinfo-gateway` won't reach programmed and will hang for a while.

**Comment by linsun** [comment]
> IMHO the key decision is whether a separate manifest is added for the internal Gateway or patch the Gateway with the annotation.

I'd be good to tell folks to patch the gateway with annotation if their k8s cluster don't allocate LB IP.

**Comment by linsun** [comment]
> > traffic from ingress gateway to productpage doesn't go through waypoint so having the gateway service account is not going to do anything.
> 
> Thanks for the insight @linsun. With that said, should the document mention this point? Others may wonder, as I did, why the service account was removed while updating the auth policy for L7.

Probably good to document somewhere - I didn't because it would look a lot of caveats for a get started docs.

**Comment by craigbox** [comment]
> Yeah, forgot to mention on Linux, setting up metalLB is pretty straightforward so not an issue most times.

It's no longer the suggested option from the kind people. If we remain with an LB service we should be _very_ instructive about how people can detect if they need to install Cloud Provider kind or similar.  Basically, I think the status won't go green until you have programmed the external IP; I don't know if that means you can call it by the cluster IP at that point?

**Comment by linsun** [comment]
Yes, you can still call the cluster IP even if the condition won't have programmed as long as pod/service is healthy.  :) 

I'd be okay to either choice when cluster doesn't support LB IP.
1. Patch the gateway with annotation
2. Tell user not to wait for condition programmed.
