### ISSUE TITLE
Remove all mentions of Pilot, Galley, and Citadel

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#15233]
For example, diagram on https://preliminary.istio.io/latest/docs/ops/deployment/architecture/. These serve no purpose other than confusion at this point IMO. 

cc @craigbox

**Comment by craigbox** [comment]
I'm super up for this.
Do we ever expect to be able to do the same for things like container names and environment variables?

**Comment by howardjohn** [comment]
@craigbox that is a tricky one since those are pseudo-APIs. I want to, but I struggle with reconciling the backwards compat. I wish we had done it in 1.5 when we introduced istiod...

**Comment by peterj** [comment]
I can take a stab at this if none has started on it yet.

**Comment by craigbox** [comment]
@peterj let's do it in priority order perhaps? - getting nice new architecture diagrams (including one for ambient) will clean up some of the more obvious errors. A further search and replace is a good task for a rainy day!

**Comment by peterj** [comment]
sounds good - we can make this issue part of the other (diagrams one).
