### ISSUE TITLE
gke istio-cni additional steps update

### ISSUE THREAD

**Issue by ilrudie** [istio/istio.io#15270]
https://istio.io/latest/docs/setup/additional-setup/cni/#hosted-kubernetes-settings suggests gke users looking to run the istio-cni plugin need to complete some additional setup but https://github.com/istio/istio/pull/40547 adds an autodetect. Docs may need to be updated to clarify when this is still necessary and/or eliminate this section entirely as may be appropriate.

**Comment by bleggett** [comment]
This should be resolved in https://github.com/istio/istio.io/pull/15282
