### ISSUE TITLE
Mobile homepage icon issue

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#15334]
On mobile (android chrome, but probably just related to screen size) the "Trusted by" icons are all squished together. This is on preliminary 

cc @craigbox

**Comment by craigbox** [comment]
Yeah, that was a known issue in the preliminary (and will go live on prod as soon as approved.)

Needs someone with some CSS  skill. Paging @Arhell or @mikemorris to see if they have cycles

<img width="612" alt="Screenshot 2024-06-26 at 3 48 20 PM" src="https://github.com/istio/istio.io/assets/132510/f2c3f101-e9ae-42ca-ab9d-e054f5d96b5c">
