### ISSUE TITLE
FAQ missing ambient mode section

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#15331]
#15306 introduced this:

https://preliminary.istio.io/latest/about/faq#is-ztunnel-a-single-point-of-failure

<img width="1136" alt="Screenshot 2024-06-26 at 2 05 50 PM" src="https://github.com/istio/istio.io/assets/132510/ae5e5d2b-1c5e-458d-94d7-9c091430d41e">

This is supposed to be under an "ambient mode" section heading.

@ayushrakesh, please either fix or send a PR to revert #15306.

**Comment by ayushrakesh** [comment]
@craigbox I have raised this PR #15337 , which fixes this web page error.

**Comment by craigbox** [comment]
Closed by #15337
