### ISSUE TITLE
Verifying new certificates section.

### ISSUE THREAD

**Issue by ChingizMard** [istio/istio.io#1545]
I was going through the section [here](https://istio.io/docs/tasks/security/plugin-ca-cert/#verifying-the-new-certificates).

When I was trying to execute the following command:
`kubectl exec -it $RATINGSPOD -c istio-proxy -- /bin/cat /etc/certs/root-cert.pem > /tmp/pod-root-cert.pem` 

I got the following error: `command terminated with exit code 126`

After sshing into container and doing it manually I saw that the file system of `istio-proxy` container is read only. 

If you `describe` the container, you can find the following property: `readOnlyRootFilesystem: true`

 Is this is an Istio bug or outdated documentation?

**Comment by ymesika** [comment]
The command works for me.
Writing into `/tmp` should be permitted. It's the `/etc/certs/` which is RO.
