### ISSUE TITLE
Fix DNS Proxy Auto Allocation docs and tests

### ISSUE THREAD

**Issue by dhawton** [istio/istio.io#15461]
Some code has changed in istio/istio 1.23 that is causing the tests to fail in the Auto Allocation section of the DNS Proxying page. The docs and tests need to be reviewed and fixed.

For now the test is disabled to unblock the PR.

cc: @ilrudie

**Comment by ilrudie** [comment]
able to repro

**Comment by ilrudie** [comment]
https://github.com/istio/istio/issues/52150

It's just broken right now. Fix is already in master but auto-cherrypick failed
