### ISSUE TITLE
Istio Ambient Documentation

### ISSUE THREAD

**Issue by satrox28** [istio/istio.io#15522]
Istio Ambient Documentation has incorrect document links.

Verify with the sample application - https://istio.io/latest/docs/ambient/install/helm-installation/#verify-with-the-sample-application

> After installing ambient mode with Helm, you can follow the [Deploy the sample application](https://istio.io/latest/docs/ambient/getting-started/#bookinfo) guide to deploy the sample application and ingress gateways, and then you can [add your application to the ambient mesh](https://istio.io/latest/docs/ambient/getting-started/#addtoambient).

**Comment by ericvn** [comment]
Fixed by https://github.com/istio/istio.io/pull/15523
