### ISSUE TITLE
Broken link in the blog "Istio has deprecated its In-Cluster Operator"

### ISSUE THREAD

**Issue by able8** [istio/istio.io#15559]
The Classic Operator Controller link is 404.

A new ecosystem project, the [Classic Operator Controller](https://github.com/istio-ecosystem/classic-operator-controller), is a fork of the original controller built into Istio.

https://istio.io/latest/blog/2024/in-cluster-operator-deprecation-announcement/

**Comment by able8** [comment]
Also, i cannot find the classic-operator-controller repo on GitHub.

**Comment by howardjohn** [comment]
It seems the repo is private. I think this is an accident, but let me verify with the maintainers of the project to make sure.
