### ISSUE TITLE
In-doc header links broken in "tip" block

### ISSUE THREAD

**Issue by jaellio** [istio/istio.io#15624]
I found several instances where links in "tip" formatted blocks do not correctly redirect. This is specific to links to in doc headers. For example, the link to `optimizing metrics collection with recording rules` in the tip block on https://istio.io/latest/docs/ops/best-practices/observability/ is broken.

```
{{< tip >}}
The recording rules above only aggregate across pods and instances. They still preserve the full set of
[Istio Standard Metrics](/docs/reference/config/metrics/), including all Istio dimensions. While this
will help with controlling metrics cardinality via federation, you may want to further optimize the recording rules
to match your existing dashboards, alerts, and ad-hoc queries.

For more information on tailoring your recording rules, see the section on
[Optimizing metrics collection with recording rules](#optimizing-metrics-collection-with-recording-rules).
{{< /tip >}}
```

The link redirects to https://istio.io/latest/#optimizing-metrics-collection-with-recording-rules rather than https://istio.io/latest/docs/ops/best-practices/observability/#optimizing-metrics-collection-with-recording-rules. 

I am not positive this is related to the links being defined in a "tip" formatting block, but I have found several examples including `compatibility with CNIs` in https://istio.io/latest/docs/setup/additional-setup/cni/.

**Comment by craigbox** [comment]
https://discourse.gohugo.io/t/link-to-page-anchor/5013
