### ISSUE TITLE
Documentation unreadable in Chrome

### ISSUE THREAD

**Issue by cefn** [istio/istio.io#15648]
### Is this the right place to submit this?

- [X] This is not a security vulnerability or a crashing bug
- [X] This is not a question about how to use Istio

### Bug Description

The layout of tabular data within e.g. https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig prevents reading it. The fixed width is narrower than the contained table even on a very wide screen. Zooming in and out delivers no benefit since it consistently zooms all scaling, including both the fixed width and the font size. 

![image](https://github.com/user-attachments/assets/22f87172-8e7b-45fc-bb29-09969013e885)

A workaround on my Chrome was to open the inspector and edit the style for `.docs.container` to be `2000px`

![image](https://github.com/user-attachments/assets/69d15de1-d1fb-4441-9688-8efb0b3e49b7)

### Version

```Text
N/A
```

**Comment by kfaseela** [comment]
cc @Arhell

**Comment by Arhell** [comment]
@cefn 
I didn't find any problems, there is a table with horizontal scrolling, if you remove it it will be even worse.

The only thing I found is a very long title
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationRequestBody

I use chrome to

**Comment by cefn** [comment]
Can you send me a screenshot of the MeshConfig table, then? Here is my screenshot 

<img width="1712" alt="image" src="https://github.com/user-attachments/assets/da86c7c5-ed23-4823-ba4a-f958c0cb06a7">

**Comment by Arhell** [comment]
> Can you send me a screenshot of the MeshConfig and ProxyConfig tables, then? Here are screenshots.
> 
> The fact this table is too wide for the viewport makes this reference documentation unusable in my opinion (for my browser config). Take the ProxyConfig table. There is a whole invisible 'Requirements' column and no control to get to it.
> 
> <img alt="image" width="1712" src="https://private-user-images.githubusercontent.com/159819/365217596-da86c7c5-ed23-4823-ba4a-f958c0cb06a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzcwOTAsIm5iZiI6MTcyNTYzNjc5MCwicGF0aCI6Ii8xNTk4MTkvMzY1MjE3NTk2LWRhODZjN2M1LWVkMjMtNDgyMy1iYTRhLWY5NThjMGNiMDZhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNTMzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDYyNGY0Yjc1OTM4ZGU3YTMzNmU5ZWM4MzRmYzZlMTU3MGU2ZGE0MWVmMDk2MjQzZjQ2NTUzMjhkYzVkYzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XzQmYvrsPX5n702z1dc_akBqdZYoy1T7pBxSRKMriBQ"> <img alt="image" width="1132" src="https://private-user-images.githubusercontent.com/159819/365218899-9a0fde53-762a-4640-8944-9950fcf627ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzcwOTAsIm5iZiI6MTcyNTYzNjc5MCwicGF0aCI6Ii8xNTk4MTkvMzY1MjE4ODk5LTlhMGZkZTUzLTc2MmEtNDY0MC04OTQ0LTk5NTBmY2Y2MjdhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNTMzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzEzNjgzOTJiNDRkYmNjOWQzODQ4YWIzMzExYmMwOGUzMjA2M2Y2NTI3OWJmNWU2NzQwMjBmYzUwMzkwNDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fjyX0dRYlmwoZtAmXztJvP4eSncJBqHnFo9fpCiecSc">
> https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig

That's right, that's how it should work, there is a scroll bar for the table at the bottom, you should understand that everything depends on the content.

If you make a table without scrolling it will be like this
![Monosnap Istio _ Global Mesh Options - Google Chro](https://github.com/user-attachments/assets/771cac04-49e8-40c7-b399-39f1bf016529)

**Comment by Arhell** [comment]
If you are interested, I checked the same content at https://getbootstrap.com/docs/5.3/content/tables/#always-responsive in their tables, and there is a similar solution with scrolling.

**Comment by craigbox** [comment]
@cefn Thanks for the report.  I'm not sure we can do much more without a fundamental change to how we present this data (e.g. not having a TOC on the right).  I know we've had to do this to stop line breaking as [arhell pointed out above](https://github.com/istio/istio.io/issues/15648#issuecomment-2334332422). Do you see the scrollbar at the bottom of the table?

**Comment by cefn** [comment]
> If you make a table without scrolling it will be like this ![Monosnap Istio _ Global Mesh Options - Google Chro](https://private-user-images.githubusercontent.com/26163841/365225376-771cac04-49e8-40c7-b399-39f1bf016529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTg0MzEsIm5iZiI6MTcyNjIxODEzMSwicGF0aCI6Ii8yNjE2Mzg0MS8zNjUyMjUzNzYtNzcxY2FjMDQtNDllOC00MGM3LWIzOTktMzlmMWJmMDE2NTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA5MDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YWM1NjQ1YjI4N2FmYWFiYmFmZGZkNTk1ODU3NDQxYzMwNTNiNTI2NGUwZDg5OTdmY2M1ZGI1NDUyMjQ2NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QtO_QRZ2Tz_7IxiWq58u8n-7Dj6tLLFqGzGslIv6JhI)

CSS allows the designer to determine the width and sharing strategy for different 'cells'. Here, the `field` and `type` cells to the left need a minimum dedicated `em` and the text description needs to fill the remainder. With this change, in my view, it's trivial for everything to fit within the width. 

However, minimum width of the content section is already an optional design conceit and must have corresponding decisions about information layout or shouldn't be adopted. At the very least it could be fixed for wider screens by either introducing a wide-screen breakpoint or setting the default desktop breakpoint higher (1200 is reasonable these days) or ensuring that minwidth for the desktop breakpoint is determined by percentage not pixels. Then at least the typical display devices for software professionals can consume the information.

If you want to see how absurd the minwidth design conceit is, given the consequences for the core purpose of this page, consider this screenshot on my main monitor. Claiming there is no way for the text to fit horizontally in the screen is false. For this use case, the designer needs to reconsider the minwidth behaviour, which settles to approximately 900 pixels on my 3440 pixel viewport.

![image](https://github.com/user-attachments/assets/9068e3fe-1785-41b6-aeb7-6d4e31f0a700)

> Do you see the scrollbar at the bottom of the table?

Not in any real-world scenario, such as the ProxyConfig. Looking at any particular row (in the original view where you can see the name of it) you can then scroll several screen-heights to see the horizontal scrollbar, then scroll it horizontally, and when you scroll back vertically you can see the description, but no identifier, making it impossible to use as per the very first screenshot in this thread. 

I genuinely struggle to understand how this is considered to be usable or a good idea, maybe it's different in my browser or something but have you tried to read a `description` of any named parameter in ProxyConfig? After testing it, what was your experience?

As per my original report, fixing it for my viewport involves setting a single CSS property so I disagree with the claim ' I'm not sure we can do much more without a fundamental change to how we present this data'. The question is simply whether the individual involved in making the CSS design decisions is willing to reconsider their choices and identify a solution in the face of user experience testing.

**Comment by craigbox** [comment]
> the individual involved in making the CSS design decisions

As with so many open source projects, we don't really have one of those.
The site was created about eight years ago, and reskinned about four years
ago. None of the people involved are still around.

We have a couple of occasional volunteers, including Arhell, who will tweak
styles, but we don't have any regular contributor who knows CSS at the
level you are talking at.

That said, I am an individual with the ability to accept changes. If you're
able to  submit one, or give enough guidance to someone else that they can
make one, i will very happily shepherd it through!

**Comment by cefn** [comment]
Thanks for the offer and it's of course a very reasonable position for an open source project to take. I am the user population's worst nightmare when it comes to styling and formatting (I have no aesthetic sense whatever as my colleagues would attest). 

For now I have found a workaround, since if I make my viewport SMALLER than 1200 pixels the table seems to get the expected treatment (although the `Field` and `Type` columns are unnecessarily large at least everything is visible and readable and it's the description column that scales up and down to accommodate restricted width.

**Comment by craigbox** [comment]
I assume that resizing to that width removed the page table of contents on the right?

**Comment by craigbox** [comment]
Hey @cefn,

How do you feel about this? https://github.com/istio/istio.io/pull/16076

**Comment by craigbox** [comment]
The changes have landed.  Here is the result for the example shown earlier:

<img width="910" alt="Screenshot 2024-12-17 at 9 21 54 AM" src="https://github.com/user-attachments/assets/8fc76094-d7bd-43ba-a48c-474f269f8a33" />

Closing this particular issue. There will be more, especially around mobile (no attempt was made) and some URLs in text that should become anchor tags. Please open more issues for specific things if you wish.
