### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by MingYuanTomas** [istio/istio.io#15783]
https://istio.io/latest/docs/tasks/traffic-management/mirroring/

```shell
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
- httpbin
  http:
  - route:
- destination:
    host: httpbin
    subset: v1
  weight: 100
mirror:
  host: httpbin
  subset: v2
mirrorPercentage:
  value: 100.0
EOF
```
file content error

**Comment by zirain** [comment]
@kfaseela looks like same issue last time you ask me? related to the tabset?

**Comment by kfaseela** [comment]
> @kfaseela looks like same issue last time you ask me? related to the tabset?

Yeah looks like the same..

**Comment by kfaseela** [comment]
Duplicate of https://github.com/istio/istio.io/issues/15689
