### ISSUE TITLE
The latest Chinese version of doc site with a top blank

### ISSUE THREAD

**Issue by wilsonwu** [istio/istio.io#15819]
https://istio.io/latest/zh/

![image](https://github.com/user-attachments/assets/1b46f06a-bf72-47d0-94e9-f33c188ecf81)

**Comment by craigbox** [comment]
Does the zh site have banners?  That would be my first guess as to what is happening

**Comment by wilsonwu** [comment]
I compared the latest site of EN and ZH, for ZH:
![image](https://github.com/user-attachments/assets/6d9bbe0f-f763-429b-981c-27c5778fb2e2)

for EN:
![image](https://github.com/user-attachments/assets/0d77c206-6177-4b31-9f79-0ec65213e17c)

I think all contents are same, maybe some html pages with difference? Not sure it is the reason or not.
