### ISSUE TITLE
Error with "istioctl verify-install"

### ISSUE THREAD

**Issue by grnmeira** [istio/istio.io#15964]
I was following today the "getting started" guide using minikube. Everything went fine, though running `isitioctl verify-install` as proposed [here](https://github.com/istio/istio.io/blob/8bbbf9209d7327e084d88c3df74fb43eb81e2e3e/content/en/docs/ambient/getting-started/_index.md?plain=1#L56) issued me an error:

```
Error: unknown command "verify-install" for "istioctl"
Run 'istioctl --help' for usage.
```

Some extra info:

```
client version: 1.24.0
control plane version: 1.24.0
data plane version: 1.24.0 (1 proxies)
```

**Comment by kfaseela** [comment]
@howardjohn @hanxiaop @therealmitchconnors is this intentional? I do not see anything in the release-notes about this being removed

**Comment by UMMAN2005** [comment]
The istioctl verify-install command was deprecated in the newer versions of Istio and is not available. You can check whether your Istio installation is working or not using other methods.

```bash
kubectl get all -n istio-system
```

**Comment by grnmeira** [comment]
I've placed a one-liner PR moving from `verify-install` to the `kubectl` alternative.

https://github.com/istio/istio.io/pull/15979

**Comment by Unichron** [comment]
would have been nice to

- mention removal in release notes
- actually deprecate in previous version, e.g. by mentioning in release notes AND giving some deprecation notice in command output

**Comment by craigbox** [comment]
I believe it was primarily part of the Istio operator, which had all the notice you mention.  Still, we're sorry for not meeting your expectations here. I'll bring it to the Environments WG.

**Comment by cookie-s** [comment]
https://istio.io/latest/docs/setup/install/istioctl/#verify-a-successful-installation
This part also refers to `istioctl verify-install`
