### ISSUE TITLE
bug: the blog year selectors overflow

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#16012]
Istio is too old - we have too many years in our blog!

under 1200px:

<img width="1174" alt="Screenshot 2024-11-26 at 10 33 38 PM" src="https://github.com/user-attachments/assets/ded914c0-d589-4e8d-93a8-9c48b67e4a2a">

above 1200px:

<img width="953" alt="Screenshot 2024-11-26 at 10 34 39 PM" src="https://github.com/user-attachments/assets/cad15e0e-9733-4748-a7c0-fcef89aa30c7">

Perhaps we make these lovely pill-shaped buttons into a CSS grid?

**Comment by mike-weiner** [comment]
Hey, @craigbox! 👋🏻 I've got a fairly small PR out to fix this. https://github.com/istio/istio.io/pull/16022
