### ISSUE TITLE
Indentation on Mirror content is wrong

### ISSUE THREAD

**Issue by infa-pbailore** [istio/istio.io#16134]
Check this page

https://istio.io/latest/docs/tasks/traffic-management/mirroring/

Here indentation of mirror and mirror percentage is incorrect.

kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
- httpbin
  http:
  - route:
- destination:
    host: httpbin
    subset: v1
  weight: 100
mirror:
  host: httpbin
  subset: v2
mirrorPercentage:
  value: 100.0
EOF

**Comment by craigbox** [comment]
Duplicate; closing in favour of https://github.com/istio/istio.io/issues/15689.
