### ISSUE TITLE
Document the format of Duration and Timestamp values

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#1723]
Our protos use Duration and Timestamp values, in particular in adapter config, and yet we don't document the format operators are expected to use in order to specify such values.

**Comment by waterwoodsthu** [comment]
I was trying to report a log entry to Mixer using mixc and I got the error complaining about the timestamp:
```
$ mixc report --mixer  <mixerip:port> --timestamp_attributes request.time=1542904996000                      
parsing time "1542904996000" as "2006-01-02T15:04:05Z07:00": cannot parse "904996000" as "-"
```

**Comment by mandarjog** [comment]
@bianpengyuan Can you take this one too ?

**Comment by bianpengyuan** [comment]
Do we want to add more instruction about how to operate with timestamp/duration attributes or with duration field in adapter config?

For timestamp/duration attributes, we could add more to attributes description and examples in attributes manifest page. For duration field in adapter config, we could add more comments/examples to adapter configs in istio/istio repo. I am not sure if there is a better place to better document these..

**Comment by geeknoid** [comment]
I think a new section in https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/ would go a long way. You could add a link to that material in https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/expression-language/.

And adding more useful examples in the comments in istio/istio would also be useful, but I'd like a formal definition first.

**Comment by geeknoid** [comment]
Fixed
