### ISSUE TITLE
In Concepts, don't assume people new to Istio know what TCP layers are..

### ISSUE THREAD

**Issue by ebullient** [istio/istio.io#1939]
What is Istio? 

> Istio uses sidecar proxies to capture traffic and, where possible, automatically program the networking layer to route traffic through those proxies without any changes to the deployed application code

Traffic Management

> Istio enables protocol-specific fault injection into the network, instead of killing pods or delaying or corrupting packets at the TCP layer. The rationale is that the failures observed by the application layer are the same regardless of network level failures, and that more meaningful failures can be injected at the application layer (for example, HTTP error codes) to exercise the resilience of an application.
> ...
> Istio provides a simple configuration model to control how API calls and layer-4 traffic flow across various services in an application deployment. The configuration model allows you to configure service-level properties such as circuit breakers, timeouts, and retries, as well as set up common continuous deployment tasks such as canary rollouts, A/B testing, staged rollouts with %-based traffic splits, etc.

Some kind of reference to networking layers would help clarify these for people that aren't sysadmins or network admins with a background in operating systems or networking that want to give Istio a try. A cross-reference or footnote to https://en.wikipedia.org/wiki/OSI_model would suffice, at a minimum.

**Comment by rcaballeromx** [comment]
The latest version of traffic management no longer mentions TCP layers.

**Comment by rcaballeromx** [comment]
Fixed in #4545
