### ISSUE TITLE
Bad link to CORS

### ISSUE THREAD

**Issue by ebullient** [istio/istio.io#1958]
Broken link at docs/reference/config/istio.networking.v1alpha3/#CorsPolicy

> Refer to https://developer.mozilla.org/en-US/docs/Web/HTTP/AccesscontrolCORS

Functioning link: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS, or for all CORS references: https://developer.mozilla.org/en-US/docs/tag/CORS

**Comment by geeknoid** [comment]
This is a reference doc from istio/api

**Comment by frankbu** [comment]
Fixed in 1.1 docs
https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3/#CorsPolicy
