### ISSUE TITLE
Update the HTTPS egress traffic task, HTTPS requires ServiceEntry with VirtualService

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio.io#1964]
Once https://github.com/istio/istio/pull/7394 is merged.

**Comment by andraxylia** [comment]
@vadimeisenbergibm istio/istio#7394 has been merged a long time ago.

Is this PR about *removing* the need to create VirtualService for Https? We got another report #2645 where external service worked once VirtualService is removed. In what case we need SNI for external services? cc @vadimeisenbergibm @ostromart

**Comment by vadimeisenbergibm** [comment]
@andraxylia Sorry, I was on vacation.

As @rshriram wrote:

> If there is no virtual service, we will treat the port as a original destination port (443). This means, the application could access any arbitrary site (yahoo.com) over 443 and traffic will flow. If you specify a virtual service, then you can restrict the flow to those hosts defined inthe service entry.

Closing this issue since the documentation was updated in https://github.com/istio/istio.io/pull/2080. The issue is about documenting using VirtualService in addition to ServiceEntry.
