### ISSUE TITLE
Check the links in Chinese content to ensure them refer to the right place

### ISSUE THREAD

**Issue by rootsongjc** [istio/istio.io#2014]
As the Chinese content will be released at the same time as Istio 1.0, so we should check the links in it to ensure the links refer to the right place.

For example:
There is a link `/docs/reference/config/policy-and-telemetry/expression-language/`, if the Chinese content exist then replace the link as `/zh/docs/reference/config/policy-and-telemetry/expression-language/`.

This may be a lot of work to do.

**Comment by geeknoid** [comment]
Unfortunately, I see some new incorrect links in new content.

We should probably figure out a good way to add a lint check to prevent this from happening.

**Comment by geeknoid** [comment]
It's not that the links are broken, it's that the Chinese content has many
links pointing to English pages.

For example, content_zh contains many uses of "/docs and (/docs in .md
files. These should generally be "/zh/docs and (/zh/docs instead.

Once everything is translated, we could have a lint rule that makes sure
content_zh doesn't reference content, and vice-versa.

**Comment by fleeto** [comment]
in #2105 , I'd changed most links into  `/zh/`, except links to some documents - they had not been translated into Chinese yet. 

In this week end, I'm preparing some scripts  to scan, check and follow the difference between content & content_zh, now the team have a clearer vision, to keep up with the English version.
