### ISSUE TITLE
Document "catch-all" egress traffic control with monitoring

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio.io#2107]
Based on the request in https://groups.google.com/d/msg/istio-users/ILcOBnjetD4/61Q0SEJOCQAJ

**Comment by iam404** [comment]
Any update on this ?

**Comment by vadimeisenbergibm** [comment]
Documented here https://preliminary.istio.io/docs/examples/advanced-gateways/egress_sni_monitoring_and_policies
