### ISSUE TITLE
Envoy Sidecar vs. Sidecar proxy

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio.io#2367]
In cases where we need to write about Envoy Sidecars, as opposed to, for example, Envoys in gateways, why shouldn't we use the term "Sidecar proxy"? See this style guide item - https://istio.io/about/contribute/style-guide/#envoy.

The service mesh terminology becomes pretty standard, with the following three concepts:
1. Control Plane
2. Data Plane
3. Sidecar proxy

See https://blog.envoyproxy.io/service-mesh-data-plane-vs-control-plane-2774e720f7fc.

So why should not we use the "standard" terms to describe the sidecar proxy of a service mesh as "sidecar proxy", but to use "Envoy" or "Envoy sidecar"?

**Comment by vadimeisenbergibm** [comment]
Just sidecar can mean other things, not necessarily a sidecar proxy. See for example https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar.

Matt Klein in his blog calls the sidecar proxy "sidecar proxy", see https://blog.envoyproxy.io/service-mesh-data-plane-vs-control-plane-2774e720f7fc.

In a complex setting with gateways a-la carte, you can have one proxy in a gateway, e.g. NGINX, additional Istio Envoy proxy and then you can have sidecar proxies. So one proxy can talk to Envoy proxy in a gateway, and the Envoy proxy in the gateway can open mTLS to sidecar proxies. The discourse is about proxies, either sidecar proxies or gateway proxies. See an example of this proxy talk in my PR https://github.com/istio/istio.github.io/pull/1984/files#diff-f575cfe44a3c5c856818f557636cba53R219:

> In this subsection you deploy an egress gateway with an SNI proxy, in addition to the standard Istio Envoy proxy.
 
I propose to use the term "sidecar proxy" in the new documents.

**Comment by geeknoid** [comment]
Another terminology thing

**Comment by rcaballeromx** [comment]
Related to #4601
