### ISSUE TITLE
[translation] Issue with docs/setup/kubernetes/quick-start/index.md

### ISSUE THREAD

**Issue by cuisongliu** [istio/istio.io#2396]
kubectl apply -f install/kubernetes/istio.yaml

to

kubectl apply -f install/kubernetes/istio-demo.yaml

this version is  **1.0.1** not **1.1** ,please fix it.
in the 1.0.1 version,not exists   install/kubernetes/istio.yaml .its rename is  istio-demo.yaml.

**Comment by cuisongliu** [comment]
I'm sorry.I mean is chianese page.
![_20180902094747](https://user-images.githubusercontent.com/4150905/44951380-4b362580-ae95-11e8-8cf3-6dea1de5b116.png)

**Comment by cuisongliu** [comment]
look:
![_20180902094747](https://user-images.githubusercontent.com/4150905/44951391-8d5f6700-ae95-11e8-93c1-a62e40ee29b3.png)

**Comment by sdake** [comment]
@cuisongliu thanks - I am the wrong person to fix this as i don't speak Chinese.

I've assigned someone that can help.

/assign @gyliu513

**Comment by rootsongjc** [comment]
@sdake @geeknoid @cuisongliu This issue is out-of-date, this page has been updated. https://preliminary.istio.io/zh/docs/setup/kubernetes/quick-start/
