### ISSUE TITLE
Issue with docs/setup/kubernetes/helm-install/index.md

### ISSUE THREAD

**Issue by mabushey** [istio/istio.io#2486]
Docs show: `helm template install/kubernetes/helm/istio --name istio --namespace istio-system > $HOME/istio.yaml`

```
$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system > istio.yaml                                                                                                                                             
Error: stat install/kubernetes/helm/istio: no such file or directory
```

The docs skipped how to download install/kubernetes/helm/istio

**Comment by mabushey** [comment]
$ `helm repo update`
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
$ `kubectl apply -f install/kubernetes/helm/helm-service-account.yaml`
error: the path "install/kubernetes/helm/helm-service-account.yaml" does not exist

**Comment by mabushey** [comment]
$ `kubectl get all --all-namespaces | grep tiller`

kube-system   pod/tiller-deploy-895d57dd9-8jt6z                                         1/1       Running   0          21h
kube-system   service/tiller-deploy                    ClusterIP      100.67.119.55   <none>                                                                  44134/TCP                    21h

kube-system   deployment.apps/tiller-deploy                  1         1         1            1           21h
kube-system   replicaset.apps/tiller-deploy-895d57dd9                   1         1         1         21h

**Comment by mabushey** [comment]
How can anyone install istio with the doc pages being wrong/extremely incomplete?

**Comment by mabushey** [comment]
$ `helm version`
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

**Comment by mabushey** [comment]
Please add `git clone https://github.com/istio/istio.git && cd istio` into the directions. My guess is this was done on purpose to keep "noobs" away so I doubt anyone is going to pay attention this this report, but hopefully it will be indexed by Google and be able to help out the next person who finds the incomplete directions rather broken.

**Comment by sdake** [comment]
> Please add `git clone https://github.com/istio/istio.git && cd istio` into the directions. My guess is this was done on purpose to keep "noobs" away so I doubt anyone is going to pay attention this this report, but hopefully it will be indexed by Google and be able to help out the next person who finds the incomplete directions rather broken.

@mabushey thank you for the report.  Nothing was done intentionally to keep anyone away.  I think you will find the 1.1 docs much improved with relationship to installation.  Can you take a look at https://preliminary.istio.io?  We have worked very hard to make a significant improvement to the documentation for onboarding to Istio.  If you find the preliminary docs (or the 1.1 docs deficient in some way, please report back).

**Comment by sdake** [comment]
I believe these problems are resolved, however, escalating to a P0 for more visibility among the documentation wg.

**Comment by sdake** [comment]
@geeknoid - FYI I don't htink this is a blocker as it is resolved.  I have simply added this to the P0 list so we can as a team validate if this problem is solved.

Cheers
-steve

**Comment by sdake** [comment]
The original complaints in this PR were merged.  The current documentation has helm repo operations in addition to download steps.  We don't recommend operators install from git, and if they do, we recommend they use the wiki to set their environments up correctly.  As such, closing this issue.

**Comment by sdake** [comment]
closing pr.
