### ISSUE TITLE
Issue with docs/setup/kubernetes/platform-setup/aws/index.md

### ISSUE THREAD

**Issue by mabushey** [istio/istio.io#2549]
Is this page 100% obsolete?

Step 2 is completely invalid, after adding the definition here is the error:
```
 # Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# Found fields that are not recognized
#   apiVersion: kops/v1alpha2
#   kind: Cluster
# + kubeAPIServer:
# +   admissionControl:
# +   - NamespaceLifecycle
# +   - LimitRanger
# +   - ServiceAccount
# +   - PersistentVolumeLabel
# +   - DefaultStorageClass
# +   - DefaultTolerationSeconds
# +   - MutatingAdmissionWebhook
# +   - ValidatingAdmissionWebhook
# +   - ResourceQuota
# +   - NodeRestriction
# +   - Priority
#   metadata:
#     creationTimestamp: 2018-09-06T21:31:05Z
# ...
# 
#
```

**Comment by andraxylia** [comment]
I did not write the initial AWS, and I do not have access to an AWS cluster, somebody else needs to pick it up.

**Comment by geeknoid** [comment]
@linsun Do you think we should just remove the AWS stuff?

**Comment by geeknoid** [comment]
This is a P0 blocking the 1.1 release. When you believe this issue can be addressed? If you don't have time, please assign to someone else that can address this issue.

Thanks.

**Comment by sdake** [comment]
@geeknoid I'll take a look - no guarantees though.  One big question is AWS EC2, or AWS EKS?

Cheers
-steve

**Comment by sdake** [comment]
that doc recommends using kops - not familiar with that bootstrapping tool.  I can look into documenting running Istio after an EKS cluster is provisioned.  Most of the documentation for that is maintained by AMZN upstream.

**Comment by linsun** [comment]
@geeknoid yes, if no one is willing to step up to validate this, we should remove it. I'd prefer to have accurate working docs than wrong docs.

**Comment by sdake** [comment]
I attempted validating it - easier said than done.  I think the approach we should take here is to document what magic may be needed on EKS to get Istio to run.  As far as I can tell, there isn't anything specific to that platform.  The existing docs had to do with enabling automatic injection and galley support (webhooks).  I believe EKS has solved this for the general case.

I am submitting a PR to delete this page.

**Comment by sdake** [comment]
https://github.com/istio/istio.io/pull/3642

**Comment by geeknoid** [comment]
Deleted the page.

**Comment by pettervondolwitz** [comment]
@sdake @mabushey Can I ask which version of kops and kubernetes that was used to trigger this issue? I just tried to reproduce but I do not get the error you are seeing. We are using Kubernetes 1.11.7, Kops 1.11.0 and Istio 1.1.0-rc.3. We deploy on AWS EC2 only (i.e not using EKS). Is the admission control section not needed any longer?

**Comment by pettervondolwitz** [comment]
Seems like `enableAdmissionPlugins` is deprecated in https://github.com/kubernetes/kops/pull/5221 in favour of `admissionControl`. Both should be accepted though so I still don't understand how the error is produced.
