### ISSUE TITLE
Document list of ports in use and which can be completely blocked by the operator

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#2565]
Would be nice to check aspects of `ANSI T1.276-2003 Baseline Security Requirements for the Management Plane` off the Istio compliance list.

For each TCP/IP service provided by Istio (internally, as in within the pod network):

* The name of the service
* a brief description of the service, how it used by Istio, and the impact of disabling the service
* accessibility requirements (e.g. required by operator, required for internal use of control plane, required for internal use of data plane)
* name of the protocol in use
* port numbers used by the service

Table format would be good :)

The specific requirement expects the operator has a high degree of expertise with the implementation and may desire to firewall ports on individual nodes - possibly with hardware.

My initial (far from complete) analysis is here:

```
externally on the ingress nodes: 80+443
internally within the cluster:
80:http
443:http+tls
9125: statsd
9411: zipkin
9125: statsd
15000: Only necessary if you wish to inspect the details of Envoy
15005: pilot
8080: pilot
15010: pilot
15011: ingress
8060: ingress
15030: ingress
15031: ingress
9411: zipkin
9125: statsd
3000: grafana
9093: mixer
42422: mixer
9091: envoy
15054: envoy
15003: envoy
15005: envoy
15007: envoy
15011: envoy
9090: prometheus
8088: servicegraph
9411: jaeger
16686: jaeger
5775: jaeger
6831: jaeger
6832: jaeger
9102: statsd-exporter
9125: sstatsd-exporter
9093: galley
443: galley
```

**Comment by acobat** [comment]
Hi, yes, I would like to see also the ports spread by components, as customer needs to open exact port between segments.

**Comment by ericvn** [comment]
Some work was done in https://github.com/istio/istio.io/pull/3395. Closing this issue. Please reopen if additional work is needed.
