### ISSUE TITLE
tablegen.py should parse comments and add them to the generated documentation

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#2566]
The https://github.com/istio/istio.github.io/blob/master/scripts/tablegen.py script does not possess any logic to process comments.

The choice of YAML parser (ruamel) is a good one as it permits the ordering and consumption of comments (vs pyyaml which throws away comments and does not preserve ordering).

The code needs enhancements to read comments from the parsed yaml and store them in the appropriate dictionary https://github.com/istio/istio.github.io/blob/master/scripts/tablegen.py#L116-L117

Other enhancements could be made to this implementation as well - its not my finest wine :)

Cheers
-steve

**Comment by sdake** [comment]
Looking for community help across any issues in Istio, and especially this one :)

**Comment by johnma14** [comment]
@sdake I will take a look at this. Thanks for referencing this.

**Comment by sdake** [comment]
@johnma14 nice work on this area!  This really adds alot of value.  We plan to release the docs Friday for 1.1.  I'd like to see this in 1.1, but if it's not ready by Friday don't be concerned - we can easily backport this work.  I'd make this a P0, but it just doesn't block the release.

**Comment by johnma14** [comment]
@sdake I am pretty confident I can get this done by tomorrow. Will do my best towards that goal. Thanks.

**Comment by johnma14** [comment]
Hopefully this latest PR should clear all the related linter issues.

**Comment by johnma14** [comment]
The PR for this was merged, so closing this issue. Thanks.
