### ISSUE TITLE
Example of using certmanager

### ISSUE THREAD

**Issue by EddiG** [istio/istio.io#2584]
**Describe the feature request**
It would be very helpful to have an example of using the `certmanager` option in the documentation of Istio. 

**Additional context**
Currently, we have the [options](https://preliminary.istio.io/docs/reference/config/installation-options/#certmanager-options) for leveraging it, but there is no corresponding example/task in the [documentation](https://preliminary.istio.io/docs/tasks/traffic-management/secure-ingress/).

**Comment by JimmyCYJ** [comment]
There is one here https://istio.io/blog/2019/custom-ingress-gateway/. Please let us know if that is sufficient. Thanks!
