### ISSUE TITLE
Issue with Mesh Expansion setup page

### ISSUE THREAD

**Issue by jwb** [istio/istio.io#2599]
The [Mesh Expansion page](/istio/istio.github.io/blob/master/content/docs/setup/kubernetes/mesh-expansion/index.mdl) includes a warning that mesh expansion is broken in Istio 1.0.0. The [release notes for 1.0.1](https://istio.io/about/notes/1.0.1/#environment) indicate there are fixes. If 1.0.1 contains the necessary fixes, it would be good to update the Mesh Expansion documentation.

**Comment by munnerz** [comment]
What's the status on this? Does anyone know why it is *not* working in 1.0, and when it is fixed?

I see the notes about 1.0.1, I can see this issue was added to the 1.1 milestone and now it is seemingly in the 1.2 milestone.

It'd be great to get some clarity on the status of mesh expansion!

**Comment by mgfeller** [comment]
An update on the status status would be appreciated. 

Is mesh expansion supposed to be working in istio-1.1.0-snapshot.2?

I found this related PR [2089](https://github.com/istio/istio.io/pull/2089) (Updated mesh expansion instructions), but couldn't get it to work on GCP.

**Comment by ferrarimarco** [comment]
Also note that it should be `global.meshExpansion.enabled`
