### ISSUE TITLE
Add task for header manipulation in virtual services

### ISSUE THREAD

**Issue by cmluciano** [istio/istio.io#2640]
We are currently missing docs for adding and removing headers (else I can't find them easily) . We should add a simple task to show the format and explain where along the line something like https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L392-L393 happens.

**Comment by linsun** [comment]
@cmluciano what is the ETA for this?

**Comment by andraxylia** [comment]
@cm any update for this?

**Comment by cmluciano** [comment]
The implementation I added has been supplanted by https://github.com/istio/api/pull/709 . cc @itaysk

**Comment by frankbu** [comment]
I think a task for this is overkill. I would suggest instead that we add an example or two in the reference doc here: https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#Headers
