### ISSUE TITLE
"Deploy with Ansible" section redundant

### ISSUE THREAD

**Issue by rad91** [istio/istio.io#2642]
https://github.com/istio/istio.github.io/blob/master/content/docs/setup/kubernetes/ansible-install/index.md

Please consider the "Deploy with Ansible" and "Default Installation" sections to be merged for two reasons:
1) It seems redundant.
2) The "Deploy with Ansible" section assumes that OpenShift is used and is best-practice.

**Comment by sdake** [comment]
agreed is redundant.

**Comment by sdake** [comment]
Ansible has been deprecated and all mentions of it should be removed from the documentation.

**Comment by rcaballeromx** [comment]
Issue solved with #3422
