### ISSUE TITLE
Document open source alternatives to closed-source OIDC providers

### ISSUE THREAD

**Issue by aeneasr** [istio/istio.io#2687]
I think it's great that Origin Authentication works with JSON Web Tokens and that it is documented that closed source providers like Auth0, Google Auth, and Firebase Auth are compatible with this. I want to suggest to include well-adopted open source alternatives such as [Keycloak](https://www.keycloak.org) and [ORY Hydra](https://github.com/ory/hydra) as well. Both are OpenID Connect Certified for all [relevant OIDC flows](https://openid.net/certification/).

If this is to your liking, I'm happy to supply a PR.

**Comment by geeknoid** [comment]
Sounds like a great idea, please send a PR.

**Comment by aeneasr** [comment]
[Done](https://github.com/istio/istio.io/pull/2689)!
