### ISSUE TITLE
Clarify Calling external services directly

### ISSUE THREAD

**Issue by navinger** [istio/istio.io#2738]
The Calling external services directly section (https://preliminary.istio.io/docs/tasks/traffic-management/egress/#calling-external-services-directly) is confusing.

1. It assumes that you have Helm installed.
2. It assumes that you used Helm to install Istio. 
3. It requires Helm to change the Envoy sidecars to prevent them from intercepting the external requests.

I downloaded the latest Istio snapshot from the Istio release page. Unzipped it and used the following command to install Istio on GKE:
kubectl apply -f install/kubernetes/istio-demo-auth.yaml

I didn't use Helm for the Istio installation, and I haven't installed Helm yet. Is it really a technical requirement that you installed Istio using Helm? Or can you install the Helm client afterwards and use it to make the configuration change to the Envoy proxies?

The section is also very odd in that it tells users to restart Istio with the new config, and then later talks about how to configure per platform.

**Comment by navinger** [comment]
To recap, I have an existing GKE cluster with Istio, and I didn't use helm to install it. 

Subsequently:
1. I installed helm following instructions here: https://docs.helm.sh/using_helm/#installing-helm
2. Ran the following: helm init
3. Ran the following to get the IP ranges:
gcloud container clusters describe cluster-1 --zone us-central1-a | grep -e clusterIpv4Cidr -e servicesIpv4Cidr
4. In the root of my Istio installation directory ran the following (no flags since I didn't have any):
helm template install/kubernetes/helm/istio --set global.proxy.includeIPRanges="10.8.0.0/14\,0.11.240.0/20" -x templates/sidecar-injector-configmap.yaml | kubectl apply -f -

I got the following output:
configmap/istio-sidecar-injector created

I think it was successful, but the doc doesn't say what to expect on success.

This all started because I was testing this doc: https://preliminary.istio.io/docs/examples/endpoints/
After running the above helm template command, I still got a successful response from my sample Endpoints service.

**Comment by sdake** [comment]
@navinger when PR is ready please use the /assign sdake feature in the PR to assign to me for review so I know where to find it :)

Cheers
-steve

**Comment by vadimeisenbergibm** [comment]
My understanding of Istio installation is as follows:
1. If you want to quickly evaluate Istio, use one of the provided demo configurations.
2. If you want to seriously work with Istio for the long term, use helm. You can either use `helm template` to generate a Kubernetes config or use` helm install` to install Istio directly. There is no other choice, especially if you need to change installation parameters. 

The section is written correctly in my opinion. I think this issue can be closed. 

@sdake, @linsun, @navinger  any thoughts? Closing the issue, feel free to reopen it.
