### ISSUE TITLE
GKE Platform Setup uses an unsupported version 

### ISSUE THREAD

**Issue by askmeegs** [istio/istio.io#2751]
#### Problem 

Following the steps here: https://istio.io/docs/setup/kubernetes/platform-setup/gke/ 
With the Google Cloud SDK, version: `219.0.1`

I ran the `gcloud clusters create` command with the GKE version listed, and got this error:

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Master version "1.10.5-gke.4" is unsupported.
```

On the GKE [release notes](https://cloud.google.com/kubernetes-engine/release-notes), version `1.10.5-gke.4` is no longer available for new clusters as of 9/5/18. 

#### Suggested Fix 

use `--cluster-version=1.10` or `latest`. 

[Source](https://cloud.google.com/kubernetes-engine/versioning-and-upgrades#specifying_cluster_version) (Note that GKE will delete patch versions when bugs are discovered.)

**Comment by geeknoid** [comment]
Content updated to just use the latest version.
