### ISSUE TITLE
Add more references for service and pod requirements

### ISSUE THREAD

**Issue by esroberts** [istio/istio.io#2762]
Recently I was bitten by an issue related to service port names not meeting istio's port name spec expectations documented here https://istio.io/docs/setup/kubernetes/spec-requirements/.  Debugging why my services weren't showing up in any of the Grafana dashboards (https://istio.io/docs/tasks/telemetry/using-istio-dashboard/) was tough as a result.  

I'd like to help improve this by adding troubleshooting docs and pointers in places where this would be relevant.  Following is a list of places that come to mind immediately but I wanted to create this issue for discussion in case there are other places that might also benefit.

https://istio.io/help/faq/telemetry/
https://istio.io/docs/tasks/telemetry/using-istio-dashboard/

Thoughts?

**Comment by geeknoid** [comment]
@rcaballeromx We should move the current "Requirements for Pods and Services" page up one level, right below "Downloading the Release". This page shows clear requirements needed in Kubernetes before you can consider using Istio, it's not an "Additional Install Guide".

**Comment by geeknoid** [comment]
@frankbu FYI

**Comment by oaktowner** [comment]
+1 on this. I've seen many, many problems that boiled down to "not following the naming conventions."

Let's move this at the very top level of the Kubernetes section so it is _much_ more likely that people see it when they install.

**Comment by geeknoid** [comment]
Done
