### ISSUE TITLE
Issue with docs/setup/kubernetes/multicluster-install/index.md

### ISSUE THREAD

**Issue by Steiniche** [istio/istio.io#2763]
The docs say that to do the multicluster install the following must be exported:

`export STATSD_POD_IP=$(kubectl -n istio-system get pod -l istio=statsd-prom-bridge -o jsonpath='{.items[0].status.podIP}')`

However, docs and charts.yml/values.yml states that the statsd-prom-bridge is deprecated.
I can definitely create a PR removing it but I want to check if I am correct about that it should not be in there anymore?

**Comment by Dariusch** [comment]
https://github.com/istio/istio/issues/10523#issuecomment-447974370

**Comment by freegroup** [comment]
is there a way to deploy istio-remote without the `STATSD_POD_IP`?

I have the very same problem during the installation of the **Istio Multicluster** setup
