### ISSUE TITLE
Installation with helm fails on git master

### ISSUE THREAD

**Issue by rvandegrift** [istio/istio.io#2787]
The following works fine with istio 1.0.2, but fails on git master:
```
$ git clone https://github.com/istio/istio
$ cd istio
$ helm-2.11.0 init --service-account tiller --tiller-namespace istio-system
$HELM_HOME has been configured at /home/ross/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
$ helm-2.11.0 --tiller-namespace istio-system install install/kubernetes/helm/istio \
     --name istio \
     --namespace istio-system
Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, certmanager
```

Using GKE 1.11.7, helm 2.11.0.

**Comment by frankbu** [comment]
I fixed this by first running
```
helm dep update install/kubernetes/helm/istio
```
Which creates the following:
```
	install/kubernetes/helm/istio/charts/
	install/kubernetes/helm/istio/requirements.lock
```
After that I can do the helm install.

@sdake Do we need to commit these files to master, or is there another way to do it dynamically?

**Comment by rvandegrift** [comment]
Thanks for the tip @frankbu!  Just confirmed that this worked for me.

**Comment by sdake** [comment]
@frankbu the release process should ideally create a helm package via `helm package -u istio`, add it to a repository for `helm fetch URL`  or `helm install URL` or `helm upgrade URL` to use.  I have been on PTO this week so unclear on the progress of the T&R team towards this objective.

There is some documentation on this already here:
https://github.com/istio/istio/pull/9393

I will submit a doc change to istio.io today.

Cheers
-steve

**Comment by vnugent** [comment]
I pulled the latest istio master and ran the following as suggested:
`helm dep update install/kubernetes/helm/istio`

Error: no repository definition for https://raw.githubusercontent.com/istio/istio.io/master/static/charts. Please add them via 'helm repo add'

**Comment by jmazzitelli** [comment]
I'm having problems too - does installing via helm require Tiller now? I'm not doing that - I just want to create the yaml from the template command and `kubectl apply` it like I have been doing.

**Comment by linsun** [comment]
This is caused by the new optional cni.   You can delete that istio-cni in requirements.yaml before we fix this.   cc @tiswanso @john-a-joyce @hklai

**Comment by jmazzitelli** [comment]
Just to give details as to what I am seeing - I download 1.1.snapshot2, and run that helm dep update command:

```
wget https://github.com/istio/istio/releases/download/1.1.0-snapshot.2/istio-1.1.0-snapshot.2-linux.tar.gz
tar zxvf istio-1.1.0-snapshot.2-linux.tar.gz 
cd istio-1.1.0-snapshot.2/
helm dependency update install/kubernetes/helm/istio
```

which results in:

```
helm dependency update install/kubernetes/helm/istio
Error: Couldn't load repositories file (/home/me/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
```

OK, well, I don't want to use Tiller, so:

```
$ helm template --values install/kubernetes/helm/istio/values-istio-demo.yaml install/kubernetes/helm/istio --name istio --namespace istio-system
```

results in:

```
Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, certmanager
```

**Comment by tiswanso** [comment]
I think the root-cause is that the istio-ecosystem/cni repo moved to istio/cni and the istio.io repo charts weren't updated.

**Comment by tiswanso** [comment]
@jmazzitelli -- Actually, the issue is that you need to do the following prior to running the `helm dependency update install/kubernetes/helm/istio` step:

```
helm init --client-only
helm repo add istio.io https://raw.githubusercontent.com/istio/istio.io/master/static/charts
```

*NOTE* -- this will not install tiller since the `--client-only` flag is used.

**Comment by jmazzitelli** [comment]
@tiswanso - Ok. so my question is: (and if you think it best, we can move this discussion to the mailing list, but I'll ask here),

Is using Tiller (or at least helm init --client-only) now required to install Istio via Helm?

I'm looking here:
   
   https://preliminary.istio.io/docs/setup/kubernetes/helm-install.html#option-1-install-with-helm-via-helm-template

and I read about the two options. The non-Tiller option is no longer working. Is this going to go away? If so, we need to update the docs to remove those instructions.

Tangentially, I think I see a typo in those docs under the option 2:

https://preliminary.istio.io/docs/setup/kubernetes/helm-install.html#option-2-install-with-helm-and-tiller-via-helm-install

```
Install Istio:
   $ helm install install/kubernetes/helm/istio --name istio --namespace istio-system
If you want to enable global mutual TLS, set global.mtls.enabled to true:
   $ helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.mtls.enabled=true
```

Should that last command be "helm `install`" and NOT "helm `template`" ??

**Comment by linsun** [comment]
@jmazzitelli we'll continue to support the non tiller option via helm template. :).    Could you file a PR for that typo?

**Comment by tiswanso** [comment]
@jmazzitelli 
> Is using Tiller (or at least helm init --client-only) now required to install Istio via Helm?

Tiller isn't required.  `helm init --client-only` doesn't install tiller.  But it does initialize the helm client cache for dependencies.  The Istio helm chart has dependencies so those need to be updated.  
However, I think if the release tarball did contain pre-pulled dependencies, the `helm repo add ...` and `helm dep update` steps wouldn't be required.  
@sdake  ^^^ ?

>  Should that last command be "helm install" and NOT "helm template" ??

Yes, good catch

**Comment by jmazzitelli** [comment]
Ok, thanks to @tiswanso I got it working. Kiali has a hack script that installs Istio into OpenShift or K8s - I added those three commands to the script and it now works again. See: https://github.com/kiali/kiali/pull/611/files

**Comment by sdake** [comment]
> @jmazzitelli
> 
> > Is using Tiller (or at least helm init --client-only) now required to install Istio via Helm?
> 
> Tiller isn't required. `helm init --client-only` doesn't install tiller. But it does initialize the helm client cache for dependencies. The Istio helm chart has dependencies so those need to be updated.
> However, I think if the release tarball did contain pre-pulled dependencies, the `helm repo add ...` and `helm dep update` steps wouldn't be required.
> @sdake ^^^ ?

I think the proper way to handle this is helm package -u istio istio-remote istio-cni - which will produce a tgz with all of the required dependencies.  the -u flag is equivalent to helm dep update iirc.

I will work on some istio.io docs today to cover this a bit more in detail.

**Comment by jnativio** [comment]
The repo update command used to solve this problem until 2 days ago, but now it does not. It appears that istio-cni-0.1.0.tgz was removed from the chart repository:

root@dal10-vsi1:/mount/istio_regpatrol# helm dep update install/kubernetes/helm/istio
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Unable to get an update from the "istio.io" chart repository (https://raw.githubusercontent.com/istio/istio.io/master/static/charts):
        Failed to fetch https://raw.githubusercontent.com/istio/istio.io/master/static/charts/index.yaml : 404 Not Found
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 15 charts
Downloading istio-cni from repo https://raw.githubusercontent.com/istio/istio.io/master/static/charts
Save error occurred:  could not download https://raw.githubusercontent.com/istio/istio.io/master/static/charts/istio-cni-0.1.0.tgz: Failed to fetch https://raw.githubusercontent.com/istio/istio.io/master/static/charts/istio-cni-0.1.0.tgz : 404 Not Found
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://raw.githubusercontent.com/istio/istio.io/master/static/charts/istio-cni-0.1.0.tgz: Failed to fetch https://raw.githubusercontent.com/istio/istio.io/master/static/charts/istio-cni-0.1.0.tgz : 404 Not Found

**Comment by tiswanso** [comment]
Hi jnativo,

The chart release process was updated to conform to per-branch releases.  So, master was changed to alias the repo location in the istio helm requirements and point to a new location that is built nightly. "repo add  istio.io<http://istio.io> https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts”.  So, you should just be able to update your workspace and rerun `make generate_yaml` or another target that depends on that.

Thanks,

Tim

On Nov 7, 2018, at 10:53 AM, jnativio <notifications@github.com<mailto:notifications@github.com>> wrote:


The repo update command used to solve this problem until 2 days ago, but now it does not. It appears that istio-cni-0.1.0.tgz was removed from the chart repository:

root@dal10-vsi1:/mount/istio_regpatrol# helm dep update install/kubernetes/helm/istio
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Unable to get an update from the "istio.io<http://istio.io>" chart repository (https://raw.githubusercontent.com/istio/istio.io/master/static/charts):
Failed to fetch https://raw.githubusercontent.com/istio/istio.io/master/static/charts/index.yaml : 404 Not Found
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 15 charts
Downloading istio-cni from repo https://raw.githubusercontent.com/istio/istio.io/master/static/charts
Save error occurred: could not download https://raw.githubusercontent.com/istio/istio.io/master/static/charts/istio-cni-0.1.0.tgz: Failed to fetch https://raw.githubusercontent.com/istio/istio.io/master/static/charts/istio-cni-0.1.0.tgz : 404 Not Found
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://raw.githubusercontent.com/istio/istio.io/master/static/charts/istio-cni-0.1.0.tgz: Failed to fetch https://raw.githubusercontent.com/istio/istio.io/master/static/charts/istio-cni-0.1.0.tgz : 404 Not Found

**Comment by jnativio** [comment]
Tim,
does this repo works for both master and 1.1 builds?

**Comment by tiswanso** [comment]
the repo would work for both.  But, for 1.1, there's no istio-cni in the istio/istio helm charts requirements.yaml so it shouldn't be required for 1.1.

**Comment by hklai** [comment]
Nonetheless, charts are built in release-1.1 as well, and they can be found
at
https://storage.googleapis.com/istio-prerelease/daily-build/release-1.1-latest-daily/charts

**Comment by salrashid123** [comment]
@hklai 

What woudl be the format of the final URL for the helm repo when 1.1 is released?

I'm workign on updating the dm quickstart template for `1.1` and that too uses helm in `client-only` so while the following works

```
helm init --client-only
helm repo add istio.io https://storage.googleapis.com/istio-prerelease/daily-build/release-1.1-latest-daily/charts
helm dependency update install/kubernetes/helm/istio
```

i'd like to know what the URL "format" will look like for the remote repo (eg

```
helm repo add istio.io https://storage.googleapis.com/istio-$VERSION/charts
```

**Comment by hklai** [comment]
>i'd like to know what the URL "format" will look like for the remote repo (eg

Should be

`https://storage.googleapis.com/istio-release/releases/1.1.0/charts/`

**Comment by kyessenov** [comment]
Hit this issue as well.

Can someone document what the process is for changing the helm chart and testing it locally?
I can imagine we would need to modify the charts to add/remove flags and run the istio tests against them.

**Comment by ZackButcher** [comment]
Adapting https://github.com/istio/istio.io/issues/2787#issuecomment-439055137, here's how to get a working helm chart for `istio-1.1.0-snapshot.3`, and generally for any Istio release (the original post only worked for daily builds due to how Istio stores artifacts in GCS):

```sh
helm init --client-only
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.1.0-snapshot.3/charts
# assuming you're running in the istio release download directory
helm dependency update install/kubernetes/helm/istio
```
then you can install Istio or generate yamls as usual:
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
    -f install/kubernetes/helm/istio/values-istio-multicluster-gateways.yaml
```

To use any other release, swap out "1.1.0-snapshot.3" with the [name of the tag of the release you want](https://github.com/istio/istio/releases). E.g. Istio 1.0.4 is: `helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.0.4/charts`. If you point your browser at that URL you'll get a `NoSuchKey` error that's fine, it's working as intended.

-----
I agree with Kuat, we need better testing of the charts. We've had a few releases with broken installation artifacts. (Fortunately this is still a pre-release :) ).

**Comment by cabrinoob** [comment]
@ZackButcher 
Hi,
When I execute the `helm dependency update install/kubernetes/helm/istio` I have this error :

    Error: no repository definition for ../subcharts/sidecarInjectorWebhook. Please add them via 'helm repo add'

**Comment by vhosakot** [comment]
I saw the same error too when installing istio `1.1.0-snapshot.3` in https://github.com/istio/istio/releases/tag/1.1.0-snapshot.3:

```
wget https://github.com/istio/istio/archive/1.1.0-snapshot.3.tar.gz
gunzip 1.1.0-snapshot.3.tar.gz
tar -xvf 1.1.0-snapshot.3.tar
cd istio-1.1.0-snapshot.3

$ helm upgrade --install istio --namespace istio-system install/kubernetes/helm/istio/
Release "istio" does not exist. Installing it now.
Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, istiocoredns, certmanager

$ helm dep update install/kubernetes/helm/istio/
Error: no repository definition for @istio.io. Please add them via 'helm repo add'
```

The following steps in https://github.com/istio/istio.io/issues/2787#issuecomment-443688642 in this ticket from @ZackButcher worked. Thanks @ZackButcher.

```
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.1.0-snapshot.3/charts
helm dep update install/kubernetes/helm/istio/
helm upgrade --install istio --namespace istio-system install/kubernetes/helm/istio/

$ helm repo list | grep istio.io
istio.io	https://storage.googleapis.com/istio-release/releases/1.1.0-snapshot.3/charts

$ helm list istio
NAME 	REVISION	UPDATED                 	STATUS  	CHART      	APP VERSION	NAMESPACE   
istio	1       	Wed Dec 19 19:44:20 2018	DEPLOYED	istio-1.1.0	1.1.0      	istio-system
```

**Comment by cabrinoob** [comment]
@vhosakot : https://storage.googleapis.com/istio-release/releases/1.1.0-snapshot.3/charts does not exists

try copy/paste in my browser and it says : 

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: istio-release/releases/1.1.0-snapshot.3/charts
</Details>
</Error>
```

**Comment by marcstreeter** [comment]
For the service mesh noobs who wanna try out istio.  I followed a couple ways that are listed in many places both here and on the web, what has worked for me consistently is

> git clone https://github.com/istio/istio.git
> cd istio
> helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.1.0-snapshot.5/charts
> helm dep update install/kubernetes/helm/istio/
> helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
> helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
>   --set grafana.enabled=true \
>   --set servicegraph.enabled=true \
>   --set tracing.enabled=true \
>   --set gateways.istio-ingressgateway.type=NodePort \
>   --set gateways.istio-egressgateway.type=NodePort 

which gets me istio (with Grafana, Prometheus, Jaeger, and no load balancer). This has been helpful for me thus far with regard to getting an onprem set up.  I am leaving out some of the helm steps, but I'm going to assume that helm is not what's blocking here.

**Comment by jmazzitelli** [comment]
> --set servicegraph.enabled=true

FYI: Service graph is going away. In fact, for the 1.1 snapshots, I think it did go away - I doubt that setting does anything.

Replacement would be kiali.enabled.

See: https://preliminary.istio.io/docs/tasks/telemetry/kiali/

**Comment by sdake** [comment]
this issue has alot of subissues in it, but I think all is fixed.  It needs a more thorough look though.

**Comment by rvandegrift** [comment]
I just reviewed the preliminary docs for 1.1, the original issue with helm+tiller deployment has been fixed.  Thanks!
