### ISSUE TITLE
Document how to create child/follows-from spans in Distributed Tracing

### ISSUE THREAD

**Issue by adinunzio84** [istio/istio.io#2800]
The [docs for distributed tracing](https://istio.io/docs/tasks/telemetry/distributed-tracing/) show how to pass headers along from one service to another so the proxies can stitch together traces. However, it is not clear how to create child spans from the spans that Istio gives us.

It would be helpful to have an example that demonstrates:
* How to configure the necessary tracer (Jaeger in this case) to send spans to the collector directly
* How to configure it to use Zipkin B3 codec for HTTP_HEADER carrier injection/extraction (necessary to create child spans)
  * How to extract the context from the HTTP headers with the OpenTracing API (instead of the implementation-specific header-passing). It should instead use HTTP_HEADER carriers.
  * How to inject the context into outgoing HTTP requests with OpenTracing API with HTTP_HEADER carriers. There are a couple headers that still have to be manually propagated (the non-b3 ones I think?).
* How to create a "child" span and have it show up in the Jaeger dashboard as a child span from the one that Istio passes in for us. What exactly needs to be configured in the tracer / spans to work well with Istio?
* Similarly for a "follows-from" span

This is for the docs, but maybe it would be good to submit a PR to Jaeger for an Istio-specific HTTP_HEADER carrier, since it's apparently not a vanilla Jaeger tracer.

**Comment by adinunzio84** [comment]
For anyone trying to get this working, I had to
1) Change the Jaeger all-in-one docker image version from 1.5 to 1.7
1) Modify it so the pod template exposes port 14268 in the Deployment (the port that the service sends the spans to)
1) Configure my reporter to send directly to the collector by setting `reporter.collectorEndpoint` to "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"

**Comment by douglas-reid** [comment]
If you are looking for examples on how to configure a Jaeger tracer that creates child spans and has them show up in the dashboard, look no further than the tracing package within Istio codebase and the example of Mixer.

Mixer operates as an application and handles trace span generation internally.  Please see: https://github.com/istio/istio/blob/master/mixer/pkg/runtime/dispatcher/dispatchstate.go#L116. That shows one part of the codebase for adding spans.

For configuring header parsing, see: https://github.com/istio/istio/blob/master/pkg/tracing/config.go#L92-L144

**Comment by adinunzio84** [comment]
Thank you for the info - I'll need some time to look over this, but I want to point out: my concern is not just creating child spans with Jaeger, but the Istio-specific portion: creating spans from a SpanContext that I extract from headers that Istio provides.

The links you provided (the second one more-so) do seem like they will be helpful in correctly creating the child spans in the context of Istio though.

**Comment by douglas-reid** [comment]
I'm going to close this, as I'm unsure of any future actions. Istio uses b3 headers to carry trace information. There is a doc on [b3 propagation](https://github.com/openzipkin/b3-propagation). Further, there are several client libraries for extracting and injecting contexts.

**Comment by adinunzio84** [comment]
There are a couple of small caveats though that I think are worth mentioning in the docs:
* If you wish to make child spans in your app, you need to use the OpenTracing API with HTTP header carriers to extract the context and create a child span.
* You cannot do anything with the incoming SpanContext (like add tags, logs, etc. to it). Similarly, you cannot get a Span from a SpanContext. You have to create a child span in-process.
* When you make requests to other services, you need to inject them with the HTTP header carrier *but also need to forward `x-request-id` and `x-ot-spancontext'* (not sure if there's an extra hyphen in the latter).
* If you're using Jaeger as your OpenTracing implementation you need to use the ZipkinB3Codec but you still need to send to the regular endpoint/port on 14268, not the one on port 9411, which is a mistake I made a couple times.

I don't think the fine details are necessary in the docs, but the summary above would be nice for people who wish to do so.
