### ISSUE TITLE
Enable Chinese Support

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#2802]
Once the site is fully translated, we need to turn on the language selection menu within the site.

Additionally, we can configure Netlify to redirect Chinese users directly to the Chinese version by default if no selection has been made in the menu.

Let me know when you guys are ready.

**Comment by rootsongjc** [comment]
I prefer to have a language selection in the menu.

**Comment by supereagle** [comment]
Great, looking forward to this

**Comment by geeknoid** [comment]
@rootsongjc Are you saying you don't want the default language chosen for the web site to be based on the client's browser setting? The heuristic would be:

if cookie_is_set then use language from cookie
else if browser supplies the right header then use the browser's language
else use english

And then the menu selection is used to control the cookie,.

**Comment by rootsongjc** [comment]
@geeknoid Yes, that's right.

**Comment by geeknoid** [comment]
Sorry, I'm confused now :-) Are you saying yes to my question, or yes to the heuristic I showed?

**Comment by rootsongjc** [comment]
We can do as you said, based on the cookie or the default language of users' website to decide with language to show.
