### ISSUE TITLE
Issue with docs/tasks/traffic-management/circuit-breaking/index.md

### ISSUE THREAD

**Issue by l10xbin** [istio/istio.io#2819]
### Tripping the circuit breaker ### 

Requests number in command for "Bring the number of concurrent connections up to 3" is not aligned with the result

` kubectl exec -it $FORTIO_POD  -c fortio /usr/local/bin/fortio -- load -c 3 -qps 0 -n 20 -loglevel Warning http://httpbin:8000/get`
should be replaced with 
` kubectl exec -it $FORTIO_POD  -c fortio /usr/local/bin/fortio -- load -c 3 -qps 0 -n 30 -loglevel Warning http://httpbin:8000/get`

As the result log in the doc is 

> All done 30 calls (plus 0 warmup) 5.336 ms avg, 422.2 qps

**Comment by frankbu** [comment]
Fixed by #2820
