### ISSUE TITLE
Config reference for Traffic Routing doesn't indicate context for each property

### ISSUE THREAD

**Issue by shalako** [istio/istio.io#2833]
Looking at https://istio.io/docs/reference/config/istio.networking.v1alpha3/ to figure out how to write a VirtualService.

For each of the sections in this doc, there's no indication of nesting level of the property. For example, is `port` a top-level property under `spec` or only supported as a child of another?

Maybe part of the issue is that resource kinds are conflated with their supported properties all in one doc. It would be simpler to understand if VirtualService were its own doc and DestinationRule were its own doc. I would be happy to contribute this change, but it is impossible to understand which fields belong to which resource kinds.

**Comment by geeknoid** [comment]
I agree this is a problem. Fixing this however ends up being rather involved, since this documentation page is auto-generated from our source code. Improving the quality of our reference documentation is definitely important.

**Comment by shalako** [comment]
Auto-generation is only a viable solution if it produces something useful.
Another solution would be to manually generate the docs.

Shannon Coen
Product Manager, Cloud Foundry
Pivotal, Inc.

**Comment by rcaballeromx** [comment]
@shalako Does the content on this PR help? #2782
