### ISSUE TITLE
VirtualService - host or hosts?

### ISSUE THREAD

**Issue by shalako** [istio/istio.io#2834]
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService

The example suggests the resource supports a top-level field `host`.

The table below suggests the field is `hosts`. 

Which is it?

**Comment by frankbu** [comment]
Can you be more specific about how the example "suggests" a `host` field. The field in the example is `hosts` (not `host`).

**Comment by shalako** [comment]
I realize the example is of `kind:DestinationRule` and the table is for `VirtualService`. Closing.
<img width="318" alt="screen shot 2018-11-02 at 8 52 50 am" src="https://user-images.githubusercontent.com/156568/47926075-edb25b00-de7c-11e8-9be2-fc34e15ac1e7.png">
