### ISSUE TITLE
CI failed as broken external links

### ISSUE THREAD

**Issue by supereagle** [istio/istio.io#2849]
**Failed CI:**

* https://circleci.com/gh/istio/istio.io/7212?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
* https://circleci.com/gh/istio/istio.io/7186?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Broken external links**

* External link https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/cluster_outlier_detection.html failed: 404 No error
* External link https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/sds failed: 404 No error
* https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/cluster_ssl.html#config-cluster-manager-cluster-ssl failed: 404 No error

/cc @geeknoid

**Comment by geeknoid** [comment]
I fixed those yesterday morning.

Thanks.
