### ISSUE TITLE
Integrating istio with consul connect

### ISSUE THREAD

**Issue by kyessenov** [istio/istio.io#2873]
/label help-wanted

Given the interest in using consul with istio, it would be good to provide guidance how the integration may look like:
- using pilot with consul service entries (current situation)
- using mixer with pilot with consul service entries
- using mixer with consul connect managed envoys

It would be great for someone from consul community to help out here and share the expertise.

**Comment by ddska** [comment]
Agree, that would be very helpful and useful.
