### ISSUE TITLE
Problem running Mixer adapter

### ISSUE THREAD

**Issue by ksemba** [istio/istio.io#2900]
Hi all,

I'm trying to build my own Mixer adapter that should receive metrics from Mixer and process them further. As a start, I was following the instructions from here: 
https://github.com/istio/istio/wiki/Mixer-Out-Of-Process-Adapter-Walkthrough

I successfully got a custom Mixer adapter working locally but I cannot get it working on my GKE cloud account. 

I created a service that runs a single POD with a single container that holds the go app that is the adapter. The adapter is started through the dockerfile using a fixed TCP port of 8090:

> FROM scratch
ADD mygrpcadapter /
EXPOSE 8090
CMD ["/mygrpcadapter", "8090"]

This is the YAML to setup the service and deployment (running a single pod with a single container that runs the adapter):
[create-mygrpcadapter-service.txt](https://github.com/istio/istio.io/files/2596223/create-mygrpcadapter-service.txt)

The service seems to start up fine --> I can go to the service on the GKE UI, click on the pod, go the container and check its logs --> it shows the single log output which shows that the adpater started listening on port 8090.

Then I try to create the adapter/handler, metric instance and rule to bind the Mixer to my adapter using this YAML:

[kube_istio_deployment.txt](https://github.com/istio/istio.io/files/2596244/kube_istio_deployment.txt)

When I run this YAML I get:

> kubectl apply -f kube_istio_deployment.yaml
handler.config.istio.io "mygrpcadapter" configured
instance.config.istio.io "i1metric" configured
rule.config.istio.io "mygrpcadapter" configured

I can see that the rule was created:

>  kubectl get rules -o yaml mygrpcadapter -n=istio-system
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.istio.io/v1alpha2","kind":"rule","metadata":{"annotations":{},"name":"mygrpcadapter","namespace":"istio-system"},"spec":{"actions":[{"handler":"handler.mygrpcadapter","instances":["i1metric"]}]}}
  clusterName: ""
  creationTimestamp: 2018-11-19T14:28:25Z
  generation: 0
  name: mygrpcadapter
  namespace: istio-system
  resourceVersion: "3696114"
  selfLink: /apis/config.istio.io/v1alpha2/namespaces/istio-system/rules/mygrpcadapter
  uid: 5fd31cd9-ec07-11e8-979b-42010a800182
spec:
  actions:
  - handler: handler.mygrpcadapter
    instances:
    - i1metric

I can see that my custom metric has been created (although I don't know how to retrieve the details on this metric...):

> kubectl get --all-namespaces instances.config.istio.io
NAMESPACE      NAME       AGE
istio-system   i1metric   3h

When trying to retrieve a list of Mixer adapters I get this:

> kubectl get crd -listio=mixer-adapter
NAME                              AGE
adapters.config.istio.io          27d
bypasses.config.istio.io          27d
circonuses.config.istio.io        27d
cloudwatches.config.istio.io      5d
deniers.config.istio.io           27d
dogstatsds.config.istio.io        5d
fluentds.config.istio.io          27d
kubernetesenvs.config.istio.io    27d
listcheckers.config.istio.io      27d
memquotas.config.istio.io         27d
noops.config.istio.io             27d
opas.config.istio.io              27d
prometheuses.config.istio.io      27d
rbacs.config.istio.io             27d
redisquotas.config.istio.io       27d
servicecontrols.config.istio.io   27d
signalfxs.config.istio.io         27d
solarwindses.config.istio.io      27d
stackdrivers.config.istio.io      27d
statsds.config.istio.io           27d
stdios.config.istio.io            27d

So I thought that my adaper should be in adapers.config.istio.io but when I try to read that config, I get nothing:

> kubectl get --all-namespaces adapters.config.istio.io
No resources found.

So does this mean that my adapter is, for some reason, not getting registered as mixer adaper? 
Any hints would be appreciated - thanks!

**Comment by ksemba** [comment]
I did not yet apply the `config/mygrpcadapter.yaml` file before - thanks for the hint. I now applied it and I can see my adapter here:

> kubectl get adapters.config.istio.io -n=istio-system
NAME            AGE
mygrpcadapter   2m

But when I try to reload the bookinfo product page I still don't get any addional logs within stackdriver for that container (the handler should write a log line for each metric instance it receives). 

Anything else I need to do?

**Comment by kyessenov** [comment]
Did you also define a custom template? The template YAML is in the parent directory, and also needs to be deployed.

**Comment by ksemba** [comment]
No, I did not. Is this something like this: https://github.com/istio/istio/blob/master/mixer/template/metric/template.yaml
?
When I ran through the example adapter creation process, this file had to be create as well: 

> /src/istio.io/istio/mixer/adapter/mygrpcadapter/testdata/template.yaml

Can I simply use that?

Sorry for being so confused but it seems as this process requires a 1000 steps if you are a newbie to istio ;)

**Comment by kyessenov** [comment]
In mygrpcadapter there is a list of templates that the adapter supports. Make sure the template is available in Mixer configs. The file `template.yaml` has the definition of the template (by name), and you can try to load it to make it available.

You can also supply mixer logs. It should print warnings about inconsistent configs (missing template is an example of that).

**Comment by ksemba** [comment]
I applied the template.yaml but still the adapter didn't work. 

I then looked at the Mixer's telemetry logs using 

> kubectl -n istio-system logs $(kubectl -n istio-system get pods -lapp=telemetry -o jsonpath='{.items[0].metadata.name}') -c mixer | grep mygrpcadapter

and saw these messages:

> error   Handler not found: handler='handler.mygrpcadapter'

This syntax is defined in my rule so I changed it back to its original configuration: 

> mygrpcadapter.istio-system

and applied that rule again and... it now works!!! :)

Thank you very much @kyessenov for your quick and insightful support!
