### ISSUE TITLE
Running locally:'hugo serve',find some errors(maybe it is Type conversion's error),and solve this errors.

### ISSUE THREAD

**Issue by MJ-CJM** [istio/istio.io#2917]
## when I am running locally:'hugo serve',I found some errors,as follows:

    $ hugo serve
    Building sites …
    ERROR 2018/11/26 16:47:13 error processing shortcode "shortcodes/relnote_links.html"
    for page "about\\notes\\1.0.3\\index.md": template: shortcodes/relnote_links.html:12:85:
    executing "shortcodes/relnote_links.html" at <int (index $parts 2)>: error calling int:
    unable to cast "3\\" of type string to int
    ERROR 2018/11/26 16:47:13 error processing shortcode "shortcodes/relnote_links.html"
    for page "about\\notes\\1.0.2\\index.md": template: shortcodes/relnote_links.html:12:85:
    executing "shortcodes/relnote_links.html" at <int (index $parts 2)>: error calling int:
    unable to cast "2\\" of type string to int
    ERROR 2018/11/26 16:47:14 error processing shortcode "shortcodes/relnote_links.html"
    for page "about\\notes\\1.0.3\\index.md": template: shortcodes/relnote_links.html:12:85:
    executing "shortcodes/relnote_links.html" at <int (index $parts 2)>: error calling int:
    unable to cast "3\\" of type string to int
    ERROR 2018/11/26 16:47:14 error processing shortcode "shortcodes/relnote_links.html"
    for page "about\\notes\\1.0.2\\index.md": template: shortcodes/relnote_links.html:12:85:
    xecuting "shortcodes/relnote_links.html" at <int (index $parts 2)>: error calling int:
    unable to cast "2\\" of type string to int
    ERROR 2018/11/26 16:47:14 error processing shortcode "shortcodes/relnote_links.html"
    for page "about\\notes\\1.0.1\\index.md": template: shortcodes/relnote_links.html:12:85:
    executing "shortcodes/relnote_links.html" at <int (index $parts 2)>: error calling int:
    unable to cast "1\\" of type string to int
    Total in 1521 ms
    Error: Error building site: logged 5 error(s)

#### 3:five files are :
* content\\about\\notes\\1.0.1\\index.md
* content\\about\\notes\\1.0.2\\index.md
* content\\about\\notes\\1.0.3\\index.md
* content_zh\\about\\notes\\1.0.2\\index.md
* content_zh\\about\\notes\\1.0.3\\index.md

**Comment by geeknoid** [comment]
This seems to be a bug in Hugo for Windows, I think. My guess is that it is adding an extra \ at the end of the .Page.Dir variable that's being used [here](https://github.com/istio/istio.io/blob/2560a0df1d4501b2592a8580a3d2f12649844475/layouts/shortcodes/relnote_links.html#L1)

I can try a workaround.

In the meantime, can you try "make serve" instead of "hugo serve"? That will probably work correctly.

**Comment by MJ-CJM** [comment]
Thank you very much for your reply,I will accept your opinion and try it.

**Comment by MJ-CJM** [comment]
@geeknoid Thank you very much for your reply,I will accept your opinion and try it.
