### ISSUE TITLE
MeshPolicy is missing from API reference

### ISSUE THREAD

**Issue by pilhuhn** [istio/istio.io#2950]
https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls mentions `https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls`, but the reference section https://istio.io/docs/reference/config/istio.authentication.v1alpha1/ does not list it.

As this seems to be a (limited) sub-case of `Policy`, it could perhaps just be described there.

**Comment by wattli** [comment]
@diemtvu Can you take a look please? Somehow i can't reassign it to you.
