### ISSUE TITLE
Adding mention of Kiali's link to Grafana dashboard

### ISSUE THREAD

**Issue by abonas** [istio/istio.io#2952]
In this page:
https://preliminary.istio.io/docs/tasks/telemetry/using-istio-dashboard/

There are 2 things that can be added:
1. Kiali's metrics tab for each entity also shows selected metrics.
2. Kiali's metrics tab also provides a direct link to Grafana's dashboard

cc @jmazzitelli

**Comment by geeknoid** [comment]
@jmazzitelli How should we proceed?

**Comment by jmazzitelli** [comment]
@geeknoid This would be up to the upstream Istio community - does it make sense to mention Kiali features in this Grafana Task documentation? Or is the Grafana Task documentation solely for describing Grafana itself and not other integrations with it.

**Comment by geeknoid** [comment]
@douglas-reid ?

**Comment by douglas-reid** [comment]
@jmazzitelli Do we want a page on Kiali itself?  Would seem to make sense. I think we used to have a page on the old ServiceGraph.

**Comment by jmazzitelli** [comment]
> @jmazzitelli Do we want a page on Kiali itself? Would seem to make sense. I think we used to have a page on the old ServiceGraph.

@douglas-reid We have one - https://preliminary.istio.io/docs/tasks/telemetry/kiali/ 
Or are you asking about something else?

**Comment by douglas-reid** [comment]
@jmazzitelli ok. so, i would think that any mention of kiali metrics integration should live there, right?

**Comment by jmazzitelli** [comment]
We could. I punted on that subject when I first wrote those docs - as you see with the blurb "This task does not discuss Jaeger and Grafana."... but we could now put that on the TODO list and add a little subsection on the Kiali task to talk about the Grafana (and Jaeger) integration.
