### ISSUE TITLE
Can I create certification for citadel like sample/certs in istio?

### ISSUE THREAD

**Issue by DuoyueBa** [istio/istio.io#2953]
We want to use certification in citadel generated by ourselves like in https://istio.io/docs/tasks/security/plugin-ca-cert/.

But I do not know how to generated all certification files like  ca-cert.pem, ca-key.pem, cert-chain.pem, root-cert.pem in istio-1.0.4/samples/certs directory.

Could you provide a simple doc to describe how to generated certification files used by citadel when security.selfSigned is false?

Thank you!

**Comment by wattli** [comment]
@myidpt , are we already have the page?

**Comment by myidpt** [comment]
It's actually not quite trivial if you want to generate a "meaningful" cert. This one points you to a website with instructions on how to generate a cert chain:
https://github.com/istio/istio.io/pull/3443
But if you just want to test, take a look at this directory:
https://github.com/istio/istio/tree/master/security/pkg/pki/testdata/multilevelpki
