### ISSUE TITLE
Issue with doc /docs/tasks/telemetry/querying-metrics/

### ISSUE THREAD

**Issue by l10xbin** [istio/istio.io#2955]
Section **About the Prometheus add-on**
1 istio-mesh (istio-mixer.istio-system:42422): all Mixer-generated mesh metrics.
2 mixer (istio-mixer.istio-system:9093): all Mixer-specific metrics. Used to monitor Mixer itself.
3 envoy (istio-mixer.istio-system:9102): raw stats generated by Envoy (and translated from Statsd to Prometheus).

It looks like in nightly build,  Prometheus addon will pull metrics from envoy proxy directly now, and we may also need to update the service name in the bracket.

![image](https://user-images.githubusercontent.com/40697655/49634351-65087b00-fa37-11e8-938d-1b0a5c553cb8.png)

**Comment by douglas-reid** [comment]
@gargnupur can you take a look at fixing up the documentation here?

**Comment by gargnupur** [comment]
Sure..

**Comment by douglas-reid** [comment]
@gargnupur any updates here?

**Comment by gargnupur** [comment]
Looks like https://github.com/istio/istio.io/pull/2866 updated it...
