### ISSUE TITLE
Fix and sync "Before you begin" section for all tasks

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio.io#2975]
Multiple tasks in our docs contain the same "Before you begin" section. Over time, the section has been copied over and over without addressing the clarity and grammar issues. 
A focused effort to harmonize and improve the "Before you begin" section of all tasks is needed.

**Comment by rcaballeromx** [comment]
I've begone looking at all "Before you begin" sections of all tasks in an attempt to determine what prerequisites are shared across the board.

**Comment by vadimeisenbergibm** [comment]
@geeknoid Is it possible with Hugo to include a markdown file in other markdown files? I tried with partials or shortcodes, it seems the site builder expects HTML there and not .md files.

We have the same "Before you begin" section duplicated for several tasks/examples related to egress traffic, I counted seven of them.

**Comment by geeknoid** [comment]
See https://github.com/istio/istio.io/pull/3005 :-)

**Comment by vadimeisenbergibm** [comment]
@geeknoid Cool, thanks!

**Comment by rcaballeromx** [comment]
@vadimeisenbergibm I've changed the pipeline to P0 to complete this work for 1.3.
