### ISSUE TITLE
Issue with doc /docs/tasks/traffic-mangement/control-egress-traffic

### ISSUE THREAD

**Issue by yxun** [istio/istio.io#2982]
Because the current release samples sleep.yaml is using image: pstauffer/curl   . This image has no bash.

The doc : https://istio.io/docs/tasks/traffic-management/egress/
Paragraph "Make requests to the external services" has a typo in the kubectl exec command
It should be "kubectl exec -it $SOURCE_POD -c sleep sh"  instead of "kubectl exec -it $SOURCE_POD -c sleep bash"

Thanks.

**Comment by frankbu** [comment]
This is fixed in the 1.1 docs.
https://preliminary.istio.io/docs/tasks/traffic-management/egress/

**Comment by frankbu** [comment]
Fixed
