### ISSUE TITLE
Issue with doc /docs/task/security/authentication-policy

### ISSUE THREAD

**Issue by yxun** [istio/istio.io#2983]
The doc : https://istio.io/docs/tasks/security/authn-policy/

Paragraph "Request from non-Istio services to Istio services"
- for from in "legacy"; do for to in "foo" "bar";  ...
The result should not include the "sleep.legacy to httpbin.legacy: 200"
If you want the last line sleep.legacy to httpbin.legacy, the command should be:
for from in "legacy"; do for to in "foo" "bar" "legacy"; ...

Paragraph "Request from Istio services to Kubernetes API server"
- Both blocks of the kubectl exec command are not working. It looks like copy paste error.

The correct one should be : 
kubectl exec $(kubectl get pod -l app=sleep -n foo -o jsonpath={.items..metadata.name}) -c sleep -n foo -- sh -c 'curl https://kubernetes.default/api --header "Authorization: Bearer $TOKEN" --insecure -s -o /dev/null -w "%{http_code}\n"'

Somehow, without "-- sh -c" , that curl doesn't return 200 even after the api-server destinationrule being applied.

**Comment by geeknoid** [comment]
@liminw, can you take a look?

Thanks.

**Comment by liminw** [comment]
/cc. @diemtvu

**Comment by yxun** [comment]
I checked https://preliminary.istio.io/docs/tasks/security/authn-policy/
All above changes have been included in  https://preliminary.istio.io/docs/tasks/security/authn-policy/
So release 1.1 doc looks fine.
