### ISSUE TITLE
Issue with doc /docs/tasks/telemetry/kiali/

### ISSUE THREAD

**Issue by l10xbin** [istio/istio.io#2987]
Execute failed with information:
Error from server (NotFound): services "tracing" not found
Error from server (NotFound): services "grafana" not found

`helm template \
    --set kiali.enabled=true \
    --set "kiali.dashboard.jaegerURL=http://$(kubectl get svc tracing -o jsonpath='{.spec.clusterIP}'):80" \
    --set "kiali.dashboard.grafanaURL=http://$(kubectl get svc grafana -o 
jsonpath='{.spec.clusterIP}'):3000" \
    install/kubernetes/helm/istio \
    --name istio --namespace istio-system > $HOME/istio.yaml`

We may need to add namespace parameter for kubectl get in the command.

**Comment by geeknoid** [comment]
@jmazzitelli

**Comment by jmazzitelli** [comment]
yup. I see a PR already has been created to fix it: https://github.com/istio/istio.io/pull/2988

That PR looks good.

**Comment by geeknoid** [comment]
@jmazzitelli Can this issue be closed?

**Comment by jmazzitelli** [comment]
PR merged. We can close this.
