### ISSUE TITLE
Issue with docs/setup/kubernetes/helm-install/ 

### ISSUE THREAD

**Issue by quanjielin** [istio/istio.io#2992]
Build used:
latest daily build istio-release-1.1-20181218-09-16

Repro steps:
1. Follow https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template, run below command 
2. istio-release-1.1-20181218-09-16$ ```helm template install/kubernetes/helm/istio --name istio --namespace istio-system > $HOME/istio.yaml```
hit error
```Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, istiocoredns, certmanager, istio-cni, telemetry-gateway
quanlin@quanlin:~/integration/1218/istio-release-1.1-20181218-09-16$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system > $HOME/istio.yaml
Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, istiocoredns, certmanager, istio-cni, telemetry-gateway```

**Comment by quanjielin** [comment]
From makefile example, seems we need to run ```helm dep update --skip-refresh install/kubernetes/helm/istio``` then run ```helm template install/kubernetes/helm/istio --name istio --namespace istio-system > $HOME/istio.yaml```, the error will go away.

**Comment by sdake** [comment]
this issue is no longer relevant with the current state of the installation procedures as subcharts and `helm dep update` have been removedd.
