### ISSUE TITLE
add/update documentation of a GKE multicluster Setup in a (shared) VPC

### ISSUE THREAD

**Issue by Dariusch** [istio/istio.io#3080]
Hey guys,
I recently stubled upon this MR https://github.com/istio/istio/issues/10523 and was wondering if the documentation could possibly be updated.
I myself am recently digging into DevOps and was evaluating a [GKE multicluster setup](https://istio.io/docs/examples/multicluster/gke/) and stubled upon some deprecations regarding the `statsd-prom-bridge` as it is no longer in the helm chart or even the main project.

In case somebody is updating the documentation it would be nice to have an example regarding a (Shared) VPC on GCP.
All clusters in GKE are going to be VPC-native by default on March 31st (announcement by mail  on Mon, Nov 19, 2018).
The recent release of Istio as a direct integration into GKE is also a reason to update the documentation accordingly.

Dariusch

**Comment by geeknoid** [comment]
@salrashid123 FYI
