### ISSUE TITLE
[Kiali] the documented defaults are not correct

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio.io#3094]
The documented defaults are not correct here:

https://preliminary.istio.io/docs/reference/config/installation-options/#kiali-options

`kiali.enabled` is not true by default - it is false. See: https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/values.yaml#L85 The only time it is true by default is when using the [demo yaml](https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/values-istio-demo.yaml#L17-L18) or [demo-auth yaml](https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/values-istio-demo-auth.yaml#L24-L25). But I think this documentation is not for the demo/demo-auth defaults.

`kiali.tag` currently has the default value of `v0.12`. See: https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/subcharts/kiali/values.yaml#L7
  
`kiali.ingress.enabled` is not true by default - it is false. See: https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/subcharts/kiali/values.yaml#L10-L11  

There is no longer a kiali.dashboard.username or kiali.dashboard.passphrase. There are new settings for the secret. If we want document those defaults, it would be:

`kiali.dashboard.secretName`: kiali
`kiali.dashboard.usernameKey`: username
`kiali.dashboard.passphraseKey`: passphrase

These come from: https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/subcharts/kiali/values.yaml#L25-L28

We should document 3 other default settings for Kiali here:

`kiali.dashboard.jaegerURL` and `kiali.dashboard.grafanaURL` - these are not set by default but need to be set in order to complete the kiali integration with those two third-party components. They should be URLs that Kiali can redirect the user to when wanting to show Jaeger tracing and Grafana metrics. These need to be URLs accessible to client browsers. See: https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/subcharts/kiali/values.yaml#L30-L34

`kiali.contextPath` has a default of `/kiali` - this is the root context path of the kiali application. See: https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/subcharts/kiali/values.yaml#L8

**Comment by jmazzitelli** [comment]
PR merged.

**Comment by jansmets** [comment]
Is this reverted? Don't see it @ https://preliminary.istio.io/docs/reference/config/installation-options/#kiali-options
And when installing istio through helm+tiller the grafanaURL in the kiali ConfigMap is empty.

**Comment by jmazzitelli** [comment]
Hmmm... yes, it appears the jaeger and grafana settings have gone missing again.

**Comment by jmazzitelli** [comment]
@johnma14 can you put those back? Looks like you accidentally removed them in your PR https://github.com/istio/istio.io/pull/3188 -- see here where the lines are deleted but should not be:

https://github.com/istio/istio.io/commit/149f9ddfbc34dbbf65ff009d62f22a478a2edd3a#diff-d88b59ce29807bd5e0d25dcdcd678f46L183

Put back kiali.dashboard.jaegerURL and kiali.dashboard.grafanaURL

Rather than re-open this issue, I'll create a new github issue so this request is not lost.
