### ISSUE TITLE
How can we update Chinese version to istio.io?

### ISSUE THREAD

**Issue by fleeto** [istio/istio.io#3107]
Some document had been updated in `istio.io`, and its zh version had been updated in the `master` branch too, then how can we sync it to the main site, a PR or something else?

**Comment by geeknoid** [comment]
istio.io is published from the release-1.0 branch of this repo. To update content there, just submit a PR against that branch.
'

**Comment by fleeto** [comment]
Got it, thank you. 

cc @rootsongjc @gyliu513
