### ISSUE TITLE
Document default istio control plane ports and other reserved ports

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3113]
K8s currently provide this doc, folks have been requesting istio to have it.  We had users who had to spend a week to debug port conflict issues.

https://discuss.istio.io/t/change-our-default-monitoring-port/377

**Comment by linsun** [comment]
@ericvn could you take a stab at this?

**Comment by rafik8** [comment]
The link to Kubernetes doc: https://kubernetes.io/docs/setup/independent/install-kubeadm/#check-required-ports

**Comment by rafik8** [comment]
I can work on this as I need to provide a similar document for one project in the next few weeks.

**Comment by ericvn** [comment]
I have a good start on this already @rafik8 if you want to collaborate some. I've run through the helm charts and starting a table  looking something like the Kubernetes doc above.

**Comment by rafik8** [comment]
Great, that I was thinking about.

**Comment by ericvn** [comment]
I'm out of the office for a few days but wanted to at least put something here for people to maybe give some initial feedback on (I didn't want to get this into a PR that I couldn't work on for a bit). I do have some other columns for TCP/UDP (but it's all TCP and one UDP port for DNS (53)), as well as MTLS. There are still a few questions and maybe some discrepancies between code and yaml's.

Note that this is based on the _release-1.1_ branch plus a default port change.

If someone wants to massage this and get it in before I get back, that's fine too.

Component | Port | NodePort | Description
-- | -- | -- | --
  |   |   |  
Citadel | 8060 |   | The port number for Citadel GRPC server
Citadel | 15014 |   | The port number for monitoring Citadel.
  |   |   |  
Core DNS | 53 |   | DNS
Core DNS | 8053 |   | DNS plugin
Core DNS | 9153 |   | DNS
Core DNS |   |   |  
  |   |   |  
Egress gateway | 80 |   |  
Egress gateway | 443 |   |  
Egress gateway | 15090 |   | Proxy?
Egress gateway | 15443 |   | This is the port where sni routing happens
  |   |   |  
Galley | 443 |   | Validation port
Galley | 9091 |   | Mesh control Plane - Running mixer
Galley | 9094 |   | Profiling port (no longer used?)
Galley | 15014 |   | Monitoring
  |   |   |  
Grafana | 3000 |   | Grafana
Grafana | 15031 |   | Grafana
  |   |   |  
Envoy | 15000 |   | Envoy admin port (commands/diagnostics)
  |   |   |  
Ingress gateway | 80 | 31380 |  
Ingress gateway | 443 | 31390 |  
Ingress gateway | 15029 |   | Kiali
Ingress gateway | 15030 |   | Prometheus
Ingress gateway | 15031 |   | Grafana
Ingress gateway | 15032 |   | Tracing
Ingress gateway | 15090 |   | Proxy?
Ingress gateway | 15443 |   | This is the port where sni routing happens
Ingress gateway | 31400 | 31400 | Sample port - not used?
  |   |   |  
Mixer | 9091 |   | Policy/Telemetry
Mixer | 15004 |   | Policy/Telemetry
Mixer | 15014 |   | Policy/Telemetry monitoring port
Mixer | 15090 |   | Proxy?
Mixer | 42422 |   | Telemetry - Prometheus
  |   |   |  
Pilot | 8080 |   | Pilot service - Discovery - legacy
Pilot | 15003 |   | Pilot service - Proxy - Policy?
Pilot | 15004 |   | Pilot service - Proxy - Policy?
Pilot | 15005 |   | Pilot service - Proxy
Pilot | 15007 |   | Pilot service - Proxy
Pilot | 15010 |   | Pilot service - XDS pilot - discovery
Pilot | 15011 |   | Pilot service - mTLS - Proxy - discovery
Pilot | 15012 |   | Pilot service - mTLS - Proxy - disDiscovery service grpc address, with httpscovery (still used?)
Pilot | 15014 |   | Pilot service - Monitoring
  |   |   |  
Prometheus | 9090 |   | Prometheus
  |   |   |  
Service Graph | 8088 |   | Service Graph
  |   |   |  
Sidecar injector | 443 |   | Sidecar injector
  |   |   |  
Tracing | 80 |   | Tracing - Jaeger
Tracing | 9411 |   | Tracing - Other
Tracing | 15032 |   | Tracing - Jaeger
Tracing | 16686 |   | Tracing - Jaeger
  |   |   |  
Zipkin | 9411 |   | Zipkin collector

**Comment by sdake** [comment]
Cc @sdake

**Comment by sdake** [comment]
@linsun here is an audit I did for 1.0.  We can close my duplicate issue since it appears others are working on it:

https://github.com/istio/istio.io/issues/2565

**Comment by sdake** [comment]
I’d encourage whoever works on this to take a look at 2565.  This is an ANSI specification where other info is needed beyond the port list.  Most large firms require this for PCI compliance and others may generally have an interest in more aspects of the ports.

**Comment by ericvn** [comment]
@sdake Would you please review and add comments to #3183. Thanks.

**Comment by ericvn** [comment]
@linsun Do we want to provide more information? Or can we close this issue?

**Comment by ericvn** [comment]
No remarks, so closing this issue for now. Please reopen if additional work is needed.
