### ISSUE TITLE
Need to update install options table for 1.1

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3132]
Our tables is getting outdated... we need to get it updated, may likely require update of the py script.

https://preliminary.istio.io/docs/reference/config/installation-options/

py script:  https://github.com/istio/istio.io/blob/master/scripts/tablegen.py

**Comment by linsun** [comment]
@johnma14 can you help look into this?  I'll assign to me since you aren't a member and I can't assign to you.

**Comment by johnma14** [comment]
@linsun sure. will look at this one. Thanks.

**Comment by johnma14** [comment]
Opened a PR for this: https://github.com/istio/istio.io/pull/3173

**Comment by geeknoid** [comment]
@douglas-reid Turns out this is already tracked.

**Comment by geeknoid** [comment]
See #2735

**Comment by douglas-reid** [comment]
We should make sure that we run this after the dust has settled on the release.

**Comment by linsun** [comment]
yes, I've opened an issue for this.  Mariam did one first pass of updating  #3173

see https://github.com/istio/istio.io/issues/3575
