### ISSUE TITLE
Vault CA integration

### ISSUE THREAD

**Issue by jsenon** [istio/istio.io#3137]
Documentation for How to configure Vault-CA with [istio 1.1](https://preliminary.istio.io/docs/tasks/security/vault-ca/) contains instruction with a reference to Google cloud `$ kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user="$(gcloud config get-value core/account)"`
Could we try to be more agnostic ?

**Comment by wattli** [comment]
"kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user="$(gcloud config get-value core/account)" is required for a k8s deployment in gCloud, just like everything else in istio.io
