### ISSUE TITLE
Provisioning Identity through sds

### ISSUE THREAD

**Issue by jsenon** [istio/istio.io#3138]
On [istio 1.1 Identity through sds](
https://preliminary.istio.io/docs/tasks/security/auth-sds/#service-to-service-mutual-tls-using-key-certificate-provisioned-through-sds) typo exist on code blocks:
```$ kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml) -n foo
$ ubectl create ns bar
$ kubectl 
```

**Comment by geeknoid** [comment]
Fixed
