### ISSUE TITLE
Performance information should be updated

### ISSUE THREAD

**Issue by clyang82** [istio/istio.io#3146]
Here is release 1.1 document about [Performance and Scalability](https://preliminary.istio.io/docs/concepts/performance-and-scalability/) 

> Latency cost/overhead is approximately 10 millisecond for service-to-service (2 proxies involved, mixer telemetry and checks) as of 0.7.1, we expect to bring this down to a low single digit ms.

There still mentions `0.7.1` . We should have an update about it.

**Comment by sdake** [comment]
I would encourage this as a p0.  IMO Istio lives and dies by performance results.  If the latency is 10msec, thats fine, if its 1msec, the documentation should reflect as much.

Cheers
-steve

**Comment by geeknoid** [comment]
I think we need more than just minor updates here, our scalability docs are sorely lacking. I opened #3532 to reflect this.

**Comment by mandarjog** [comment]
I am closing this in favor of #3532
