### ISSUE TITLE
Installing the sidecar doc refer to an yaml file which is not exist

### ISSUE THREAD

**Issue by rootsongjc** [istio/istio.io#3170]
This file doesn't exist `install/kubernetes/istio-sidecar-injector-configmap-release.yaml`but be refered on https://istio.io/docs/setup/kubernetes/sidecar-injection/ doc.

**Comment by geeknoid** [comment]
This is a P0 blocking the 1.1 release. When you believe this issue can be addressed? If you don't have time, please assign to someone else that can address this issue.

Thanks.

**Comment by rootsongjc** [comment]
@geeknoid Could you assign it to someone else, I am a little busy nowadays.

**Comment by sdake** [comment]
assign @howardjohn
