### ISSUE TITLE
Installation documentation refers to file which does not exist (crds.yaml)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#3176]
In the 1.1 docs, both the [K8S Quick Start](https://preliminary.istio.io/docs/setup/kubernetes/quick-start/) and [Minimal Install](https://preliminary.istio.io/docs/setup/kubernetes/minimal-install/) pages instruct to:

> Install Istio’s Custom Resource Definitions via kubectl apply, and wait a few seconds for the CRDs to be committed in Kubernetes API server:
> `$ kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml`

However this file no longer exists in v1.1. I am not sure if this has changed so that this step is longer needed or the file has just moved.

**Comment by sdake** [comment]
Thanks for finding these problems.  WIll work on submitting a bug fix.

Would be great if we could consolidate all of the helm installtion into one place so we don't have to maintain it all over the website.....  Not really sure how to do that.

Cheers
-steve

**Comment by theganyo** [comment]
There's an init chart here: `install/kubernetes/helm/istio-init`. Not sure how this dovetails into the doc's flow.

**Comment by rcaballeromx** [comment]
@sdake I can help with that. Do you know where all the pieces are? 
@theganyo Is that the path that should appear in the docs? Does it work?

**Comment by theganyo** [comment]
Well, it depends on what's intended on this page, I guess. The page flow will need to change, I think, as if you just run that, you'd need tiller installed.

**Comment by rcaballeromx** [comment]
Is there no way of doing it without Tiller? Could users apply the CRD with kubectl?

**Comment by theganyo** [comment]
I'm sure there's a way, I'm just not sure how it's intended to be run.

**Comment by theganyo** [comment]
Looks like `kubectl apply -f install/kubernetes/helm/istio-init/files` works.

**Comment by rcaballeromx** [comment]
Thank you @theganyo
@sdake @geeknoid What are your thoughts? I'm reluctant to add a dependency on Helm and Tiller to the  installation if it can be completed without it.

**Comment by theganyo** [comment]
@rcaballeromx Apparently @sdake already has a couple outstanding PRs to address the docs.

**Comment by sdake** [comment]
@rcaballeromx I believe this is the best approach to handling the install is here: https://github.com/istio/istio.io/pull/3276

The T&R team has started distributing our helm charts via google storage.  We can then pull this down via `helm repo add`.

We have to take a dependency of helm, but not on tiller.  This hasn't changed.

**Comment by ericvn** [comment]
Looking at the subject pages, and I believe the changes have already been made and possibly the issue could be closed. 

One question I have is if we want to use `kubectl apply -f install/kubernetes/helm/istio-init/file` or `for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done`. Today we have both and maybe we should standardize on one. The later would be better if we had files other than `crd*yaml` (maybe we did at one point).

**Comment by rcaballeromx** [comment]
@frankbu Can you confirm this is no longer a problem? I think you solved this with #3538 
If so, please feel free to close the issue.

**Comment by frankbu** [comment]
Yes, this has been fixed.

**Comment by chrisx01** [comment]
i run in the same problem, but it's should fixed, which command must I run on in my terminal window ?

**Comment by frankbu** [comment]
@chrisx01 follow these instructions: https://istio.io/docs/setup/kubernetes/install/kubernetes/

**Comment by riser101** [comment]
FYI, the link mentioned in last comment by @frankbu is dead.

**Comment by frankbu** [comment]
@riser101 thanks for pointing out the broken link. It should be fixed now.

**Comment by behrangsa** [comment]
Has this file disappeared again?
