### ISSUE TITLE
Default sampling rate doc is incorrect

### ISSUE THREAD

**Issue by sdaschner** [istio/istio.io#3178]
In the current [documentation](https://istio.io/docs/tasks/telemetry/distributed-tracing/#trace-sampling) of distributed tracing, the default sampling rate is described to sample all requests, However, this is not the case in version `1.0.5` or later. The sampling rate is set to `1.0` (1%) in the Helm install [values.yaml](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L37). This has been modified in Istio PR [9798](https://github.com/istio/istio/pull/9798).

AFAIK, the sampling rate was indeed at 100% at some point. Either one of the documentation or the default values should change, whatever makes more sense as default.

**Comment by douglas-reid** [comment]
The instructions at the top of that task include:

> Either use the istio-demo.yaml or istio-demo-auth.yaml template

Both of those yamls have sampling rate set at 100%.  See: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values-istio-demo.yaml#L6

Perhaps updating the trace sampling doc to say Istio *demo* by default samples at 100% ?
