### ISSUE TITLE
Apigee and Trace Span examples do not work

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#3212]
The example at https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/adapters/apigee/ does not work.  It refers to an apigee.config.istio.io CRD which does not exist.

The example at https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/templates/tracespan/
fails with `Error from server: error when creating "/Users/snible/Downloads/Trace Span.yaml": admission webhook "mixer.validation.istio.io" denied the request: json: cannot unmarshal bool into Go value of type string`

**Comment by esnible** [comment]
I don't expect the documentation CRD for Apigee to work.

I am concerned that _install/kubernetes/helm/istio-init/files/crd-10.yaml_ doesn't contain a CRD for Apigee.  The documentation suggests that Istio includes the ability to configure Apigee.  All of the other documentation on that page refers to CRDs from that file.

**Comment by theganyo** [comment]
I’ll update the documentation to make it  clear that a different image of mixer is required.

**Comment by theganyo** [comment]
Ok, docs are updated. The Apigee adapter now has a message near the top that reads:

> Important: The adapter is provided in an enhanced Mixer image. The default Mixer image must be replaced and the proper CRDs must be applied in order to use these features.

**Comment by geeknoid** [comment]
Doug, could you look into the trace span portion of this issue?

**Comment by douglas-reid** [comment]
@geeknoid sure. is the issue that the boolean just needs surrounding ""s?  cause that it is what it looks like...

@esnible can you try quoting the `false` in your local file?

**Comment by esnible** [comment]
@geeknoid Yes, `rewriteClientSpanId: "false"` is acceptable.

**Comment by geeknoid** [comment]
The field is defined a boolean in the proto. Then why are the quotas needed?

**Comment by esnible** [comment]
I looked at _mixer/template/tracespan/tracespan_handler_service.pb.go_.  There are three definitions of `RewriteClientSpanId` there.  Two are bool, **one is a string**!

**Comment by douglas-reid** [comment]
@geeknoid something about the yaml -> json -> proto translation in code generation?

Probably worth troubleshooting.

I've sent a PR to add quotes.

**Comment by douglas-reid** [comment]
@esnible @geeknoid https://github.com/istio/istio/pull/6559#discussion_r198649290
