### ISSUE TITLE
Galley should be added to the architecture diagram

### ISSUE THREAD

**Issue by abonas** [istio/istio.io#3223]
Galley is currently missing from
https://istio.io/docs/concepts/what-is-istio/arch.svg

**Comment by geeknoid** [comment]
Done.

**Comment by abonas** [comment]
where is this reflected? the website still shows the old one. thanks

**Comment by geeknoid** [comment]
https://preliminary.istio.io/docs/concepts/what-is-istio

This will be published to istio.io when 1.1 is released.
