### ISSUE TITLE
Update Chinese content to use new <warning>, <tip>, and <idea> annotations

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#3228]
Instead of blockquotes, Istio content now uses annotations to denote special kind of content:

{{< tip >}}
{{< idea >}}
{{< warning >}}

The Chinese content needs to have corresponding changes made.

You can find all places where block quotes are used by enabling the new lint check in scripts/lint_site.sh and then running "make lint".

**Comment by rootsongjc** [comment]
There are 51 files need to change. To change so many files will cost a lot of time.

**Comment by geeknoid** [comment]
All done. Thanks.
