### ISSUE TITLE
Add landing page for the Setup/Kubernetes section. 

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio.io#3239]
A clean landing page to point readers to the correct setup path is needed.
The documents themselves are to remain unchanged except for their titles and the folder they are in.
By grouping related documents, the goal is give readers clarity regarding what document or documents they need to follow.

**Comment by geeknoid** [comment]
Can we close this?

**Comment by rcaballeromx** [comment]
Fixed with: #3422
