### ISSUE TITLE
Chinese content won't validate with HtmlProofer 3.10

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#3244]
The latest version of htmlproofer produces a bazillion errors on the site's Chinese content, mostly relating to bad hash-related links. It's possible the tool is broken, I can't quite tell.

To repro this, you can change the -image field in .circleci/config.yml to:

      - image: gcr.io/istio-testing/website-builder:2019-02-06

Make a PR with this and submit it. CircleCi is then going to run with the new HtmlProofer and you should see the warnings.

Thanks.

**Comment by fleeto** [comment]
ok I'm on it.
