### ISSUE TITLE
https://preliminary.istio.io looks terrible on Chrome at the moment

### ISSUE THREAD

**Issue by theganyo** [istio/istio.io#3262]
Screen shot:
<img width="1350" alt="screen shot 2019-02-13 at 2 49 14 pm" src="https://user-images.githubusercontent.com/772731/52749646-aae54080-2f9e-11e9-8fd8-2710d86635e7.png">

I tried clearing cached images and files without effect. Also, the website looks fine on Safari.

**Comment by geeknoid** [comment]
@douglas-reid

**Comment by geeknoid** [comment]
Turns out this is a problem with the theming logic. I'll have a fix shortly. In the meantime, if you select one of the themes from the gear menu (Light Theme or Dark Theme), things should fix themselves.

**Comment by geeknoid** [comment]
All better now...
