### ISSUE TITLE
Generate diffs for helm value files between releases

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3282]
It would be really cool if we can have a tool to compare the release X and release Y tree and generate differences of the helm value yaml files APIs for our users in istio.io (probably in the upgrade page or guide).  For examples, we need the difference between 1.0.5 and 1.0.6, and 1.0.6 to 1.1.  And we probably need this updated for every single new releases :).

@johnma14 could you check if this is doable?

**Comment by johnma14** [comment]
@linsun will see what we can do. Thanks

**Comment by johnma14** [comment]
@linsun @sdake @geeknoid I have pushed a PR for this feature: https://github.com/istio/istio.io/pull/3420

**Comment by johnma14** [comment]
This was merged in 1.1, so closing it. Thank you
