### ISSUE TITLE
Istio 1.1 Configuring an Egress Gateway Doesn't work in Minikube

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#3311]
In the Configuring an Egress Gateway tutorial, you are instructed to create a network policy and test traffic flow afterwards to confirm that it no longer works. This does not work in Minikube due to the fact that it uses the "bridge" driver by default (https://github.com/kubernetes/minikube/issues/1572). Instead, when you execute the curl request, a 200 OK with content is returned. 

Minikube version: 0.33
Kubernetes version: 1.13

**Comment by brian-avery** [comment]
@vadimeisenbergibm @geeknoid Is this a concern? Should I just add a comment to this section that this isn't supported in minikube?

**Comment by geeknoid** [comment]
I don't know about whether this should work or not, Vadim would. But in terms of the site, using {{< warning >}} for this kind of stuff would be appropriate IMO.

**Comment by brian-avery** [comment]
@vadimeisenbergibm any opinions on this?

**Comment by vadimeisenbergibm** [comment]
@brian-avery Sorry, I missed this issue. I do not think we can support in the documentation examples all the possible Kubernetes environments with their peculiarities, it would make the documentation hard to read. Especially supporting all the examples on Minikube. Note also the motivation for the example, as appears in  
https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway/#use-case _"Consider an organization that has a strict security requirement that all traffic leaving the service mesh must flow through a set of dedicated nodes."_ The example describes a rather advanced setting.

So I would just add a warning "Does not work on Minikube".

**Comment by brian-avery** [comment]
Thanks. Opened PR to address this.
