### ISSUE TITLE
The namespace scoped policy name should be default

### ISSUE THREAD

**Issue by lbudai74** [istio/istio.io#3313]
https://github.com/istio/istio.io/blob/405ad98764975bca7965d0317e6f30d89b277ffe/content/docs/reference/config/istio.authentication.v1alpha1/index.html#L343

**Comment by geeknoid** [comment]
This is a bug in istio/api

**Comment by lbudai74** [comment]
I just wanted to draw attention that there is a bug in the doc. In the example the name field should have the value "default" on line 343.

**Comment by liminw** [comment]
Thanks for reporting it. The API documentation is inconsistent with Istio documentation. @diemtvu  Can you fix it?

**Comment by liminw** [comment]
I cannot reassign it to Diem. Leave it under my name for now.

**Comment by liminw** [comment]
The issue is fixed.
