### ISSUE TITLE
IBM Cloud quick start guide use istio helm repo

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3321]
In addition to #3285, I think we should switch to use the istio helm repo, vs the ibm chart repo because it was not kept updated.

@Rachael-Graham

**Comment by linsun** [comment]
@ericvn

**Comment by ericvn** [comment]
I believe this was tackled and completed in the 1.1 docs. Currently, we point to the base common Istio docs from the IBM Cloud Public which uses the Istio repo or download.
