### ISSUE TITLE
1.1 Egress Gateway TLS Origination Issues Updating Helm

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#3322]
I installed Istio via both istio-demo.yaml and the helm template and had issues when I got to "Generate the istio-egressgateway deloyment" on both of them. 

For istio-demo.yaml, obviously this won't work. There's no helm dependencies or other setup completed previously. 

For the helm template, I am getting the following error: 
kubectl apply -f ./istio-egressgateway.yaml
The Deployment "istio-egressgateway" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"istio-egressgateway", "chart":"gateways", "heritage":"Tiller", "istio":"egressgateway", "release":"istio-egressgateway"}: `selector` does not match template `labels`

Looking at my istio-egressgateway I see: 
oc get pod istio-egressgateway-6d5b8695d5-6lv54 -n istio-system --show-labels
NAME                                   READY     STATUS    RESTARTS   AGE       LABELS
istio-egressgateway-6d5b8695d5-6lv54   1/1       Running   0          21m       app=istio-egressgateway,chart=gateways,heritage=Tiller,istio=egressgateway,pod-template-hash=6d5b8695d5,release=istio

**Comment by brian-avery** [comment]
@geeknoid This doesn't work verbatim with two of our install options (istio-demo.yaml and istio-auth-demo.yaml). Should there be a workaround? Perhaps a pre-generated yaml that can be executed in the case that you used either of those install options?

**Comment by frankbu** [comment]
@brian-avery Which instructions are you referring to by `when I got to "Generate the istio-egressgateway deloyment"`?

`istio-demo.yaml` now includes the egressgateway, and for helm install, the gateway examples all point to this instruction to add it: https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway/#deploy-istio-egress-gateway

Does this address your issue?

**Comment by brian-avery** [comment]
Hi Frank,

I know the docs have gone through a lot of cleanup since this issue was opened. I think the problem I had originally was that the egress gateway was not enabled in istio-demo.yaml and the only instructions were helm specific. I'll try again and let you know. 

Thanks,
Brian

**Comment by sdake** [comment]
@brian-avery - any update on this issue?

Cheers
-steve
