### ISSUE TITLE
Helm install options should reflect warnings on security

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.io#3331]
Running through install, I got the following warning from helm:

```
Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
```

It feels like we should update our install instructions to use `--tiller-tls-verify` by default.

/cc @sdake @geeknoid @ostromart

**Comment by ostromart** [comment]
This is new, I think it comes in new versions of helm. I think it also only applies to tiller, not template.
I think we should mention it in the docs, although perhaps not necessarily recommend all users set it. 
Something like:
If you are using tiller, see https://github.com/helm/helm/blob/master/docs/securing_installation.md to determine whether you should use a secure installation for helm. 
wdyt?

**Comment by linsun** [comment]
Agreed, we should probably only mention in the tiller portion of the install.

**Comment by geeknoid** [comment]
This is a P0 blocking the 1.1 release. When you believe this issue can be addressed? If you don't have time, please assign to someone else that can address this issue.

Thanks.

**Comment by geeknoid** [comment]
This is a P0 blocking the 1.1 release. When you believe this issue can be addressed? If you don't have time, please assign to someone else that can address this issue.

Thanks.

**Comment by sdake** [comment]
@ostromart great suggestion, I have implemented your suggestion here: https://github.com/istio/istio.io/pull/3646

**Comment by geeknoid** [comment]
Fixed.

**Comment by sdake** [comment]
@ostromart great suggestion.  I have implemented that here:
https://github.com/istio/istio.io/pull/3646
