### ISSUE TITLE
Uninstall mixed up with install

### ISSUE THREAD

**Issue by andraxylia** [istio/istio.io#3336]
https://preliminary.istio.io/docs/setup/kubernetes/helm-install/

Option 1 steps 6 and 7 belong to an uninstall section.

I should not be tempted to copy-paste those steps right after I just installed.

**Comment by andraxylia** [comment]
Option 1 steps 6 and 7 belong to an uninstall section.

**Comment by frankbu** [comment]
This is fixed now: https://preliminary.istio.io/docs/setup/kubernetes/install/helm/
