### ISSUE TITLE
Introspection page lacks details on how to use ctrlz in a running cluster

### ISSUE THREAD

**Issue by ozevren** [istio/istio.io#3344]
@ozevren commented on [Thu Feb 21 2019](https://github.com/istio/istio/issues/11949)

https://preliminary.istio.io/help/ops/controlz/

It would be ideal to guide the user to reach the controlz page for the Kubernetes deployments as well. i.e. 

```
kubectl port-forward -n istio-system  <podname> 9876:9876
browse http://localhost:9876
```

**Comment by geeknoid** [comment]
Fixed
