### ISSUE TITLE
Demo Kiali default credentials not documented

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#3348]
https://github.com/istio/istio/pull/11715/files adds a new default admin/admin login for Kiali when using the demo. This is not documented anywhere on https://preliminary.istio.io/docs/tasks/telemetry/kiali/ or the rest of the website.

**Comment by geeknoid** [comment]
@jmazzitelli

**Comment by jmazzitelli** [comment]
@geeknoid see PR #3356

**Comment by jmazzitelli** [comment]
PR is merged. See: https://preliminary.istio.io/docs/tasks/telemetry/kiali/#create-a-secret

We can close this issue.

**Comment by geeknoid** [comment]
Thanks.
