### ISSUE TITLE
1.0 doc IBM helm chart version does not match istio release

### ISSUE THREAD

**Issue by stevekinder-ibm** [istio/istio.io#3388]
The documentation on the quickstart page for IBM cloud indicates that the istio helm chart version in the IBM repo can be used to identify the Istio release.   At the time of this writing, the IBM Istio helm chart is version 1.0.5, but it installs 1.0.2 release.   

Just because the helm change is updated, doesn't mean that the istio release was updated... and so the numbers drift apart.

That said, we should make sure that the user doublechecks the tags and documentation in the Helm release, which indicates which release of Istio will be installed.

**Comment by ericvn** [comment]
In the 1.1 documentation, PR https://github.com/istio/istio.io/pull/3327 changed to using the Istio Helm charts per https://github.com/istio/istio.io/issues/3321.

Do we want to put this change back in to 1.0 branch @linsun?

**Comment by linsun** [comment]
@gyliu513 @morvencao any objection for us to push this change back to 1.0?  We'd prefer that from IKS perspective.

**Comment by morvencao** [comment]
Okay for me.

**Comment by linsun** [comment]
this is only a 1.0 issue

**Comment by ericvn** [comment]
If this is only a 1.0 issue as @linsun indicated, and we are no longer creating 1.0 releases, I believe this issue can be closed.

That said, I understand where this could be an issue with the IBM Cloud Private catalog where it may include items were the chart version and Istio version don't match. I don't believe that code is within this repo for current releases.

I'm closing this issue for now based on the above. Feel free to reopen if you feel this was in error.
