### ISSUE TITLE
Nit: Capitalize "Envoy"

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#3394]
https://preliminary.istio.io/docs/reference/commands/istioctl/#istioctl-kube-inject says

```
kube-inject manually injects envoy sidecar into kubernetes
workloads.
```

Both "Envoy" and "Kubernetes" are being used here as trademarks and MUST be capitalized.

Also there is a missing space in

```
ConfigMap name for Istio sidecar injection, key should be "config".This option overrides
```

**Comment by ayj** [comment]
fixed by https://github.com/istio/istio.io/pull/3430
