### ISSUE TITLE
Egress Example Failing With Helm Install

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#3398]
Step 5 in https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway-tls-origination/ is failing if you use the helm install option due to the fact that values.yaml sets enabled to false. If you reinstall with the egress gateway enabled (helm template $HOME/istio-fetch/istio --name istio --namespace istio-system --set gateways.istio-egressgateway.enabled=true | kubectl apply -f -), then this step passes successfully. 

Also, the docs concerning validating the installation also indicate that the egress gateway should be present, but in the case of a helm install, the deployment is never created.

**Comment by andraxylia** [comment]
@vadimeisenbergibm I marked issues related to the installation as P0 for 1.1 since this can impact UX.

**Comment by duderino** [comment]
@vadimeisenbergibm we need to know whether you can work on this or whether we should find another owner

**Comment by brian-avery** [comment]
@duderino @andraxylia I know this area will be rewritten to better encompass the install options, but is https://github.com/istio/istio.io/pull/3399 good enough for now? Clarifies that helm is disabled and where to go to figure out how to enable it.

**Comment by vadimeisenbergibm** [comment]
@andraxylia @duderino @brian-avery This issue will be handled by 
https://github.com/istio/istio.io/pull/3444, and then referencing the instructions in it in other examples. 

I am waiting for https://github.com/istio/istio.io/pull/3444 to be merged, then will submit a PR to update all other examples.

**Comment by vadimeisenbergibm** [comment]
I've updated the documentation, closing the issue.
