### ISSUE TITLE
Issue with docs/tasks/traffic-management/ingress/index.md

### ISSUE THREAD

**Issue by zuxahiz** [istio/istio.io#3402]
```bash
$ export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="**http**")].nodePort}')
$ export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}')
```
Document in Chinese version is "http", however the original English version it is http2. New learner don't know why.

**Comment by rootsongjc** [comment]
@zuxahiz Can you list the addresses of these errors in order we can fix them?

**Comment by zuxahiz** [comment]
> @zuxahiz Can you list the addresses of these errors in order we can fix them?

Hi, the address is [确定使用 Node Port 时的 ingress IP 和端口](https://istio.io/zh/docs/tasks/traffic-management/ingress/#%E7%A1%AE%E5%AE%9A%E4%BD%BF%E7%94%A8-node-port-%E6%97%B6%E7%9A%84-ingress-ip-%E5%92%8C%E7%AB%AF%E5%8F%A3). Please help to check it. Thanks.

**Comment by loverto** [comment]
https://preliminary.istio.io/zh/docs/tasks/traffic-management/ingress/#%E7%A1%AE%E5%AE%9A%E4%BD%BF%E7%94%A8-node-port-%E6%97%B6%E7%9A%84-ingress-ip-%E5%92%8C%E7%AB%AF%E5%8F%A3

可以看这里

**Comment by zuxahiz** [comment]
For the issue I reported it's OK now. Thanks.
