### ISSUE TITLE
Another install doc nit - Helm version instructions seem to be backwards.  (1.0.6)

### ISSUE THREAD

**Issue by stevekinder-ibm** [istio/istio.io#3416]
Page in question: https://istio.io/docs/setup/kubernetes/helm-install/

Related to customresourcedefinitions...  When I tried to install the helm chart with v2.9.1, it seems like the "CRD install" is not necessary, but the uninstall is.   The documentation says, you need v2.10 for the installs to happen, but if you try to install the crds and the helm chart; the helm chart install complains about the CRDs being created already.  On the flipside, if you uninstall the istio chart, it does **_NOT_** install the CRDs, you have to do this manually.

```root@test1-istio-master:/IBM# helm version --tls
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1+icp", GitCommit:"843201eceab24e7102ebb87cb00d82bc973d84a7", GitTreeState:"clean"}```

**Comment by frankbu** [comment]
Closing this issue because I think the latest doc explains the CRD create/delete procedure better, and hopefully works properly.

https://preliminary.istio.io/docs/setup/kubernetes/install/helm/

Feel free to reopen if you are still seeing this problem.
