### ISSUE TITLE
Change the CNI Installation guide to better convey what the feature is and how to use it.

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio.io#3431]
Mixing up CNI in the Alibabi/IBM/Google instructions doesn't make any sense.  CNI is like istio-init - except that it is optional and comes with all of the madness of installing with or without tiller. The guide needs to reflect that fact and be moved to a better suited location. Ideally as an example.

**Comment by frankbu** [comment]
Fixed in #3538. It is now moved to additional guides and referenced from the helm install instructions.
