### ISSUE TITLE
Find and use a consistent alternative term to call the Installation "Paths"

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio.io#3433]
The meaning of the word "Paths" can be different for readers and feels clunky.

**Comment by geeknoid** [comment]
Approaches
Techniques
Models

**Comment by frankbu** [comment]
I would suggest the title can just be `Installation`, and change:
```
Choose the path that best suits your needs and platform.
```
to
```
Choose the instructions that best suit your needs and platform.
```
I would also move `Mulicluster Installation` to the `Additional Setup Guides` subsection and then rename `Additional Setup Guides` to `Advanced Guides` (or something similar to mean not just your basic install).

The overall layout would then look pretty clean IMO:
* Downloading the Release
* Platform Setup
* Installation
* Upgrading
* Advanced Guides
    * Multicluster Installation
    * Mesh Expansion
    * ...

**Comment by geeknoid** [comment]
Installation Strategies

**Comment by rcaballeromx** [comment]
"Installation Flows"
That was the consensus in my tech. writing team.
It conveys a sense of easy progress forward to readers.
The first sentence would become:

> Choose the flow that best suits your needs and platform.

@frankbu "Instructions" is problematic because some readers use the it to refer to "commands".
I don't disagree with your structure suggestion but I think that is something we can tackle post 1.1

@geeknoid @frankbu Do we have consensus around "Installation Flows?

**Comment by geeknoid** [comment]
Flow sounds pretty good to me.

**Comment by frankbu** [comment]
Actually, path is growing on me. Since #3538 I think it looks fine as is. There aren't so many paths/flows/whatever now that the instructions have been consolidated. I think there's really just a choice between the quick-start or helm installation. The other things are (or should be, after further cleanup) really just additional details for specific cases, not really a different path/flow

**Comment by geeknoid** [comment]
I don't like "path" since it makes me instantialy think of file system
paths.

**Comment by rcaballeromx** [comment]
For 1.1 #3577 implemented "flow" consistently. We can revisit after.
