### ISSUE TITLE
Install on a Kubernetes Cluster section uses nonexistent yaml files

### ISSUE THREAD

**Issue by m-eaton** [istio/istio.io#3453]
Option 1 and Option 2 on the [Install on a Kubernetes Cluster page](https://preliminary.istio.io/docs/setup/kubernetes/install/kubernetes/#installation-steps) instruct the user to `kubectl apply -f install/kubernetes/istio-demo.yaml` and `install/kubernetes/istio-demo-auth.yaml` respectively, when neither of those config files are included in the 1.1 release. I believe that the instructions need to be updated to use `helm template` to create similar manifests for the user to apply.

**Comment by frankbu** [comment]
I thought that `istio-demo.yaml` and `istio-demo-auth.yaml` are supposed to be there for users that want to try out Istio without needing to download Helm. Is there a bug in the release build that should be generating and adding them to the release?

**Comment by linsun** [comment]
@mandarjog is it possible your recent clean up that removed these 2 files?

We need to have these generated yaml for quick start per the last env WG mtg.  @sdake @costinm

**Comment by frankbu** [comment]
@m-eaton The two yaml files are in the latest 1.1 candidate: https://github.com/istio/istio/releases/tag/1.1.0-rc.2, so it must have been a bug in the particular build you were testing.

**Comment by m-eaton** [comment]
I just confirmed that the two demo manifests are in the latest release candidate - there must've been a bug in the build somehow when I originally downloaded RC-1.
