### ISSUE TITLE
Various installation instructions need to say what's included/excluded

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#3460]
The install instructions for the various installation profiles (minimal, demo, standard) need to say what exactly they install. The minimal install instructions, for example, currently says `This minimal install provides traffic management features of Istio`, which doesn't say what components are/aren't included.

Related to this, all the instructions should have a `Verify Installation` step. Currently only the kubernetes demo profile instructions have it. This would be confirmation that the components that are supposed to be included in the profile are there.

There should also be some generic boilerplate (that all the instructions can include) to tell people how to enable/disable various standard addons that may or may not be included in the profile they are selecting. These generic instructions could also be referenced from tasks and examples, as suggested [here](https://github.com/istio/istio.io/pull/3444/files#r261768707).

**Comment by frankbu** [comment]
Another thought: we need a (ideally generated) table that lists all the components in rows, and the columns correspond to the various Istio profiles (minimal, demo, standard, other?) with an `x` in each row if the component is included. This table could be referenced from the install instructions.

I also wonder if instead of having different install instructions for the various profiles, all we really need is one "Install using Helm", with one of the steps being "Pick the profile you want to install".

**Comment by linsun** [comment]
@frankbu i think having a table is a good idea.  We have a few profiles and it is good to highlight what is unique about each profiles.

To find out what is different than each profiles, you can refer to its corresponding values.yaml file, e.g. values-istio-{profile}.yaml and compare the difference from the base values yaml file.

**Comment by ericvn** [comment]
I will see if I can come up with an acceptable table.

**Comment by rcaballeromx** [comment]
@frankbu Do you think it would be more useful if the table had features instead of components?
The components are implementation details, readers usually care more about what features the installation enables.

**Comment by frankbu** [comment]
Maybe both or some combination in the future, but most urgently, for the purposes of installation, I think what components are installed needs to be clear so that we can have a verification step that checks what's running, and other tasks that need certain components (e.g., egressgateway) can refer to the table.

**Comment by ericvn** [comment]
A very quick table I put together by looking at the yamls. Still working on details on how to generate this file. I wasn't sure of a good feature/component breakdown.

  | Citadel (Security) | CoreDNS | CNI plugin | Egress Gateway | Enable Tracing | Galley | Gateway | Grafana | Ingress | Ingress Gateway | Kiali | Mixer | CPSecurity enabled + mTLS | NodeAgent | Pilot | Policy | Prometheus | Proxy Policy Checks | SDS | Security | ServiceGraph | Sidecar Injector Webhook | Telemetry | Tracing (Jaeger)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Normal | Enabled | Disabled | Disabled | Disabled | Enabled | Enabled | Enabled | Disabled | Disabled | Enabled | Disabled | Enabled | Disabled/Disabled | Disabled | Enabled | Disabled | Enabled | Disabled | Disabled | Enabled | Disabled | Enabled | Enabled | Disabled
Demo values |   |   |   | Enabled |   |   |   | Enabled |   |   | Enabled |   | Disabled/Disabled |   |   |   |   | Enabled |   |   | Enabled |   |   | Enabled
Demo auth - Demo+ |   |   |   |   |   |   |   |   |   |   |   |   | Enabled/Enabled |   |   |   |   |   |   |   |   |   |   |  
Minimal | Disabled |   |   | Disabled |   | Disabled | Disabled |   |   | Disabled |   |   |   |   | Enabled -  Sidecar disabled? | Disabled | Disabled |   |   |   |   | Disabled | Disabled |  
Remote | Enabled |   |   |   | Disabled | Disabled | Disabled |   |   |   |   |   |   |   | Disabled | Disabled | Disabled |   |   |   |   |   | Disabled |  
SDS-Auth |   |   |   |   |   |   |   |   |   |   |   |   | Disabled/Enabled | Enabled |   |   |   |   | Enabled |   |   |   |   |

**Comment by rcaballeromx** [comment]
I wouldn't advice starting the install instructions with such a large complex table.
@ericvn Is there a way to generate the table in such a way, that only the columns with a value are shown for a specific row?
That way we could add to the minimal installation guide, for example, only the "Minimal" row with only the columns that show values in your table, Citadel, Egress Gateway, etc.

**Comment by linsun** [comment]
+1 on generate the table content... seems we'll need it like the helm options.

It may be as simple as a list of components that are enabled using comma, like 
minimal: pilot
demo: all
default: pilot, citadel, etc

**Comment by ericvn** [comment]
@rcaballeromx, @linsun  I agree the table as I posted above is too big. I can generate it any way we want. Let me manually create something based on the comments and get some feedback. Then I can work on coding that piece.

**Comment by frankbu** [comment]
I suggest switching the rows and columns.

The columns should be profile names: **default** (is that "Normal" in your table?), **demo**, **minimal**, etc.

I imagine the rows that show only the controlplane services that you will get (e.g., pilot, mixer, etc). This kind of table would not be nearly as big, so the sparseness issue with your current table would probably go away.

Maybe another table which shows all the features (like your table) would be useful, but its not as important IMO. Maybe two different tables labeled with tabs at the top (components, features) would be nice in the future.

**Comment by ericvn** [comment]
I created some mock ups (hoping the lists are actually correct but they are manual at the moment) @rcaballeromx @linsun @frankbu 

Some questions:
 - We have both an `Ingress Gateway` and `Egress Gateway`. Does it make sense to keep them separate (they aren't by each other alphabetically? Maybe we change to `Gateway - Egress` and `Gateway - Ingress` or maybe it's `Gateway(Ingress)` & `Gateway (egress, ingress)`, they later used when both.
 - Which mockup makes sense? Or maybe we need two in different spots in the doc.
 - Do we still have too many components listed? Or am I missing some?
 - Related to the last question, should I include `Mixer` in all?

Simple list:

Default: Citadel, Galley, Ingress Gateway, Pilot, Prometheus, Sidecar Injector, Telemetery
Demo: Citadel, Egress Gateway, Galley, Grafana, Ingress Gateway, Jaeger, Kiali, Pilot, Prometheus, Service Graph, Sidecar Injector, Telemetery
Demo-Auth: Citadel, Control Plane Security, Egress Gateway, Galley, Grafana, Ingress Gateway, Jaeger, Kiali, mTLS, Pilot, Prometheus, Service Graph, Sidecar Injector, Telemetery
Minimal: Pilot (no sidecar injection)
Remote:
SDS_Auth: Citadel, Galley, Ingress Gateway, mTLS, Node Agent, Pilot, Prometheus, SDS, Sidecar Injector, Telemetry


Chart:

Component | Default | Demo | Demo-Auth | Minimal | Remote | SDS-Auth
-- | -- | -- | -- | -- | -- | --
Citadel | X | X | X |   | X | X
Control Plane Security |   |   | X |   |   |  
Egress Gateway |   | X | X |   |   |  
Galley | X | X | X |   | X | X
Grafana |   | X | X |   |   |  
Ingress Gateway | X | X | X |   | X | X
Jaeger |   | X | X |   |   |  
Kiali |   | X | X |   |   |  
mTLS |   |   | X |   |   | X
Node Agent |   |   |   |   |   | X
Pilot | X | X | X | X (no sidecar) |   | X
Prometheus | X | X | X |   |   | X
SDS |   |   |   |   |   | X
Service Graph |   | X | X |   |   |  
Sidecar Injector | X | X | X |   | X | X
Telemetry | X | X | X |   |   | X

**Comment by frankbu** [comment]
This looks much better!

I would:
* use the actual controlplane service name for the component, e.g., `istio-pilot` instead of Pilot.
* only include services in the rows (remove Control Plane Security, mTLS, SDS).
* order the services (core components first, addons second). Btw, isn't "Service Graph" obsolete?
* by only including services in the rows, I think that the auth/no-auth profiles become the same thing, so I would not include `-auth` profies in the rows. The auth vs. no-auth differences can be described separately (i.e., not in this components-profile table).

**Comment by frankbu** [comment]
Also, why does it say X (no sidecar) for the minimal profile. I think the fact that there is no X for the Sidecar Injector covers that.

**Comment by frankbu** [comment]
Btw, I would put this table around here: https://preliminary.istio.io/docs/setup/kubernetes/#installing-istio-for-production

@ericvn maybe you can send a PR to add it (manually created) for now (1.1) but then you can look at a way to generate it (and maybe a similar feature-profile table) for the future. WDYT?

Then we can also point to it from the install instructions (e.g., tell users to check that services corresponding to their chosen profile are running).

**Comment by rcaballeromx** [comment]
> This looks much better!

Agreed.

> 
> I would:
> 
> * use the actual controlplane service name for the component, e.g., `istio-pilot` instead of Pilot.

I'm fine with that, particularly since we want the table to be generated from the YAML, but it the components should be inside back-ticks: \`component\`

> * only include services in the rows (remove Control Plane Security, mTLS, SDS).

I think it is useful to readers to know what security features are available. I would leave them in but maybe group related rows together.

> * order the services (core components first, addons second). Btw, isn't "Service Graph" obsolete?

Agree, the release note clearly state that it's been deprecated. Please remove it.

> * by only including services in the rows, I think that the auth/no-auth profiles become the same thing, so I would not include `-auth` profies in the rows. The auth vs. no-auth differences can be described separately (i.e., not in this components-profile table).

However having them there can be very useful to readers. That said, ordering the rows to have the services at the top and the security features at the bottom of the table would be better. 
Also if the profiles are similarly organized. Core profiles first and auth/no-auth to the right.

I'm all for adding the table manually for 1.1 and figuring the automated version for 1.2

**Comment by frankbu** [comment]
> I think it is useful to readers to know what security features are available. I would leave them in but maybe group related rows together.

Let me clarify what I meant. I don't think you can cleanly display one table that mixes components and security features. If it was possible, I do agree that the security features are important, and we should show them. But I'm pretty sure that will complicate this particular table, defeating it's main purpose.

I'm suggesting we treat security features as an orthogonal concern. They are not different profiles (e.g., **demo** and **demo-auth**) there is just one profile (**demo**). Some profiles, have auth vs. no-auth flavors, which users can chose, but for this table all we care about is which profile is being selected, and what components that will enable on the control plane.

**Comment by ericvn** [comment]
Let me through yet another intermediate table in here as I was just going to start putting this in. Not sure how it'll look yet on the markdown page. I moved the add-ons down and was thinking of adding a section at the end for the security features.


Component | Default | Demo | Minimal | Remote | SDS
-- | -- | -- | -- | -- | --
`istio-citadel` | X | X |   | X | X
Gateways |   |   |   |   |  
`istio-egressgateway` |   | X |   |   |  
`istio-ingressgateway` | X | X |   | X | X
`istio-galley` | X | X |   | X | X
`istio-pilot` | X | X | X |   | X
`istio-sidecar-injector` | X | X |   | X | X
`istio-telemetry` | X | X |   |   | X
`istio-nodeagent` |   |   |   |   | X
Add ons |   |   |   |   |  
`prometheus` | X | X |   |   | X
`istio-tracing` |   | X |   |   |  
`grafana` |   | X |   |   |  
`kiali` |   | X |   |   |  
  |   |   |   |   |  
Authentication adds |   |   |   |   |  
Control Plane Security |   | X |   |   |  
mTLS |   | X |   |   | X
SDS |   |   |   |   | X

**Comment by ericvn** [comment]
Note that this page talks about the configuration profiles.

**Comment by frankbu** [comment]
I think this is getting close!

Should remove the yaml files, too noisy and the install instructions will include them in the commands.

What is the "Gateway" row? Move it up and say "Core Components" would make sense.

I still say don't include the auth rows, we'll cover that in other places.

Maybe the all the `istio-` prefixes should be removed, since it's a bit noisy. Maybe we should look at how the table looks embedded in the .md doc before we decide.

**Comment by ericvn** [comment]
@frankbu Is there anything else we need for this issue? Can it be closed?

**Comment by ericvn** [comment]
No remarks, so closing this issue for now. Please reopen if additional work is needed.
