### ISSUE TITLE
Have a syntax to refer current release

### ISSUE THREAD

**Issue by incfly** [istio/istio.io#3496]
I encountered a problem where we ask users to download a mesh expansion sdiecar debian package. The download URL has release version encoded, which requires manually updated very time we ship even a minor release, 1.1-rc0 to 1.1-rc1.

```bash
curl -L https://storage.googleapis.com/istio-release/releases/1.0.0/deb/istio-sidecar.deb > istio-sidecar.deb
```

Would be great if we have a website level settings for this strings or a syntax to do this. Instead of hardcoding and manually remember to update.

**Comment by geeknoid** [comment]
We do already. Checkout https://preliminary.istio.io/about/contribute/creating-and-editing-pages for the right form for your use.

**Comment by incfly** [comment]
@geeknoid hmm, the download URL I used for now are "1.1.0-rc.0". But I assume once we have a official 1.1 release, the suffix "rc" part will disappear? And we can then replace with the syntax you linked above?

Am I right?

**Comment by geeknoid** [comment]
Yes, I believe so.
