### ISSUE TITLE
"Work in progress" banner?

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#3502]
Hi there,

Looks like should be able to release Istio 1.1 soon. I expect there to be a large number of doc checkins in the next couple days, leading up to the release. Even though you guys have been doing a great job in keeping up with all the docs, I'm afraid that when 1.1 launches, the Chinese docs will still be somewhat out of date with the latest English docs.

Should we put a disclaimer somewhere on the Chinese version of the site warning users about this? Something like:

"The Chinese version of this site may be slightly out of date compared to the English version. Please consult the English version if you experience any problems".

WDYT?

**Comment by rootsongjc** [comment]
As it's really a lot of docs not sync with the English version, check [here](https://github.com/servicemesher/istio-official-translation/issues), I think it's ok but the key point is where to show this message? After all, not all of the Chinese docs are out of date.

**Comment by fleeto** [comment]
There are 34 new/moved documents and 51 updated documents in the queue.
I think this may be a normal, we should let the reader know that the Chinese document may be out of date.

**Comment by geeknoid** [comment]
How about we put this in the footer on every page then? 

I'll add a spot for that, and a new translated string that you guys can fill out.

**Comment by rootsongjc** [comment]
Do you mean put it here? OK for me.
![image](https://user-images.githubusercontent.com/3328185/53815585-e4f1a300-3f9c-11e9-959d-f0b7cd090317.png)

**Comment by geeknoid** [comment]
Exactly.

**Comment by geeknoid** [comment]
OK, the change to support this is in. Just update the advisory string in zh.toml with whatever you'd like you say.

For now, I just left that string white. We can tweak the color if you'd like, just let me know.

Thanks!
