### ISSUE TITLE
Need to produce the release notes for 1.1

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#3517]
I've checked the current version of the 1.1 release notes. Many more changes are necessary. Please submit PRs accordingly.

@linsun @sdake @frankbu Can you address the remaining Helm items?

@liminw I added a new suggested items in the security section with a TBD. Please tell me what that needs to be, or we can delete the entry.

@costinm @sdake Can you suggest the needed stuff for the multicluster section?

@douglas-reid @mandarjog Lots of tweaks needed in the policy and telemetry content.

**Comment by duderino** [comment]
@linsun @sdake @frankbu @liminw @costinm @sdake @douglas-reid @mandarjog 

Heads up, we need this by end of day Friday 3/15

**Comment by duderino** [comment]
@rcaballeromx @geeknoid ^^

**Comment by linsun** [comment]
anything else we need besides https://github.com/istio/istio.io/pull/3558 which is merged?

**Comment by linsun** [comment]
nm, i saw many todos.

**Comment by sdake** [comment]
@geeknoid I have a list of helm changes formulated.  Will submit a PR after hotdogs.

**Comment by sdake** [comment]
release notes for install: https://github.com/istio/istio.io/pull/3704

**Comment by liminw** [comment]
Adding @myidpt @wattli See the last TBD bullet in https://preliminary.istio.io/about/notes/1.1/#security.

TBD: How about adding 11667 as well? As this is also a significant feature for security which can enable end user to set different CA and Certs for different namespaces.

**Comment by myidpt** [comment]
The multi-namespace security feature isn’t mature yet, and it should be part of the Istio multi-namespace solution. I think we can remove it from the release notes. Maybe claim it in the next release would be better.
