### ISSUE TITLE
"Installing the sidecar" verification step incorrect

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#3521]
https://preliminary.istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/

The step says "Verify that the sidecar has been injected into the deployment."

```
$ kubectl get deployment sleep -o wide
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINERS          IMAGES                             SELECTOR
sleep     1         1         1            1           2h        sleep,istio-proxy   tutum/curl,unknown/proxy:unknown   app=sleep
```

I tested with _kubectl_ version 1.13 against a server running 1.13.  Although the injection was correct, the IMAGES and CONTAINERS fields show only one container because the injection happens to the _pod_, not the _deployment_.

This is what I actually see:

```
$ kubectl get deployment sleep -o wide
NAME    READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES           SELECTOR
sleep   1/1     1            1           8d    sleep        pstauffer/curl   app=sleep
```

A better way to check might be `kubectl get pod <pod> -o jsonpath='{.metadata.annotations.sidecar\.istio\.io\/status}'`

**Comment by linsun** [comment]
how about this?

```
$ kubectl get pod  -l app=sleep
NAME                     READY   STATUS    RESTARTS   AGE
sleep-64c6f57bc8-f5n4x   2/2     Running   0          24s
```

**Comment by linsun** [comment]
BTW, this returned nothing because I didn't use the annotation to inject sidecar.

```
$ kubectl get pod  -l app=sleep -o jsonpath='{.metadata.annotations.sidecar\.istio\.io\/status}'
(⎈ |linistio9:default)
```
