### ISSUE TITLE
Need content around scaling

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#3532]
The doc web site contains almost no information about scaling Istio. The only page we have right now is https://preliminary.istio.io/docs/concepts/performance-and-scalability/ which isn't very good as a high-level customer-oriented concept page. It talks about Go microbenchmarks for example. The page contains pointers back to the developer wiki on github. Etc.

We need:

- A real customer-oriented concept page

- A full scalability section in the ops guide.

- A full scalability section in the FAQ.

- Maybe some scalability tasks.

**Comment by geeknoid** [comment]
This is a P0 blocking the 1.1 release. When you believe this issue can be addressed? If you don't have time, please assign to someone else that can address this issue.

Thanks.

**Comment by mandarjog** [comment]
@geeknoid We are working on it. 
https://docs.google.com/document/d/1-1G-e38WzrTNNKQY6JwCTks08bMebAlkiRC8mVXeCVo/edit#heading=h.e1r1ew2wioo8 
This is for the concepts page and here is the tuning guide doc. https://docs.google.com/document/d/1-1G-e38WzrTNNKQY6JwCTks08bMebAlkiRC8mVXeCVo/edit#heading=h.e1r1ew2wioo8 

PRs should be coming shortly.

**Comment by linsun** [comment]
Could the doc be made avail to public?  I don't have permission to view either

**Comment by suryadu** [comment]
We are working on a 3-pronged strategy for Performance and Scalability. 1) We are revamping the main Performance and Scalability Section cleaning it up and updating with v1.1 data(almost done) 2) We are creating a new short blog (almost done) to highlight v1.1 performance and host it on istio.io and socialize this through various channels when we release v1.1 3) We are working on a tuning guide to help provide tuning guidance on v1.1 with the new knobs etc., and will be pointing this from our scalability section on istio.io (almost done)4) We also will have a tech blog that will be released next week highlighting v1.1 performance, sizing and capacity planning guidance answering common questions around Istio performance from the field (almost done)

**Comment by suryadu** [comment]
@geeknoid Mandar and I have another meeting to review and finalize all these later today. @linsun

**Comment by mandarjog** [comment]
1.1 perf blog: https://github.com/istio/istio.io/pull/3710
perf and scale page: https://github.com/istio/istio.io/pull/3657

**Comment by suryadu** [comment]
@mandarjog can you also add the Tuning guide PR that we have created for 1.1?

**Comment by geeknoid** [comment]
Dropping this to a P1, since the concept page and blog posts are in. The tuning guide can come after launch since it doesn't represent a day 1 kind of thing.

**Comment by geeknoid** [comment]
Is the ops tuning guide still coming?
