### ISSUE TITLE
Document incompatible changes in 1.1

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#3536]
We need to clearly document things that have changed such as disabling policy checks.

This probably should be captured as a FAQ entry, probably an ops guide section, a mention in the release notes, and a stand-alone page in the setup & upgrade section.

**Comment by geeknoid** [comment]
This is a P0 blocking the 1.1 release. When you believe this issue can be addressed? If you don't have time, please assign to someone else that can address this issue.

Thanks.

**Comment by kyessenov** [comment]
We should also document how to "unbreak" the change, e.g. steps to enable policy checks.

**Comment by sdake** [comment]
This is a pretty solid diff of the API changes in Helm: https://github.com/istio/istio.io/pull/3420.  Analyzing these changes will take some time and probably won't be ready by Friday.  Any suggestions?

Cheers
-steve

**Comment by linsun** [comment]
i agree it is good to put everything on one page.  a few i have in mind: 1) helm api change in #3420 that @johnma14 is working on and @sdake has menioned 2) outbound traffic is changed to all allowed.  3) service graph is now deprecated in favor of kiali 4) egress is off by default in addition to mixer off.

**Comment by costinm** [comment]
1) Gateway resources should be configured in the namespace where the ingress service is running ( istio-system with the default installer). The VirtualService should use GATEWAY_NAMESPACE/GATEWAY_NAME ( example "istio-system/ingressgateway") when binding.
This mode is activated for any namespace that has a Sidecar.

2) In case of multiple DestinationRule for a service, the lookup order will start with local namespace, namespace where service is defined and istio-system.

**Comment by costinm** [comment]
@rshriram  - please confirm (2) (DR lookup path), it went in different directions...

**Comment by duderino** [comment]
@sdake @geeknoid @linsun @linsun @costinm @rshriram @mandarjog  please fill in your sections in https://docs.google.com/document/d/1usQiZgj43em9HiPTud-rj0RGNwX13vYmIDozNQ6oTCk/edit#

We'll worry about formatting later.  Right now I'm just trying to get all the content in so someone has a fighting chance of making it look nice later.

We need this asap.  Sorry

**Comment by sdake** [comment]
@duderino thanks to @johnma14 's essential work, producing this list of changes was relatively easy.  I need a little help on the list - not sure what lightstep iis, not sure how to enable k8s ingress initeegration.

**Comment by sdake** [comment]
@duderino note the doc you link has incompatible and compatiible changes merged together.  I think we can just copy & paste (after wordsmithing) these to the release notes.  As for incompatible changes, I'll separate those in a different buckets, and we can list the incompatible changese in a separate document.

Would help to have pointers to the files in the repo where these two related topics are to be merged.

**Comment by sdake** [comment]
> i agree it is good to put everything on one page. a few i have in mind: 1) helm api change in #3420 that @johnma14 is working on and @sdake has menioned 2) outbound traffic is changed to all allowed. 3) service graph is now deprecated in favor of kiali 4) egress is off by default in addition to mixer off.

pr #3420 wont be ready for merge by tomorrow.  We will need to backport that.  Not a blocker.

**Comment by geeknoid** [comment]
Here's what I'd like to do:

- Create a stand-alone page with the breaking changes and associated procedures. We can put this in docs/setup/upgrade-notes

- Add a reference to this doc to the top of the release notes, in the 1.1 announcement, and at the top of the upgrade instructions.

**Comment by linsun** [comment]
https://github.com/istio/istio.io/issues/3705

**Comment by sdake** [comment]
https://github.com/istio/istio.io/pull/3704

**Comment by geeknoid** [comment]
Done

**Comment by duderino** [comment]
Addressed by https://github.com/istio/istio.io/pull/3724
