### ISSUE TITLE
regenerate install options page for 1.1

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3575]
Mariam, could we regenerate the install options page for 1.1?  Ideally - we want to avoid manual editing of it, for example:  [istio/istio.io] Clarify that egress gateway is disabled by default if Helm was used to install (#3399)

cc @frankbu

**Comment by linsun** [comment]
cc @douglas-reid @sdake @geeknoid

**Comment by johnma14** [comment]
@linsun @douglas-reid @sdake @geeknoid I have opened a PR for this: https://github.com/istio/istio.io/pull/3592. Thanks

**Comment by geeknoid** [comment]
Does #3592 completely address this or is there more work remaining for 1.1?

**Comment by sdake** [comment]
@geeknoid lgtm - I took a look at the options in the PR - looks like they represent 1.1 release with all the stuff we removed over the weekend gone.

Thanks @johnma14 !

Cheers
-steve
