### ISSUE TITLE
investigate auto generate of the install option page

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3576]
as part of istio.io build so that we don't need to do it manually.

**Comment by linsun** [comment]
for post 1.1 :)

**Comment by johnma14** [comment]
@linsun Closing this issue for now since @ostromart is working on an alternative way to generate this page.

**Comment by johnma14** [comment]
Reopening this issue since @geeknoid would like to run this script through the CI system.

**Comment by frankbu** [comment]
This has been replaced by operator config.
