### ISSUE TITLE
tcp-echo example should run docker with sudo

### ISSUE THREAD

**Issue by jamesyoungman** [istio/istio.io#3579]
Our test command at https://preliminary.istio.io/docs/tasks/traffic-management/tcp-traffic-shifting/ is this:

for i in {1..10}; do \
docker run -e INGRESS_HOST=$INGRESS_HOST -e INGRESS_PORT=$INGRESS_PORT -it --rm busybox sh -c "(date; sleep 1) | nc $INGRESS_HOST $INGRESS_PORT"; \
done

But for docker to work (on this machine at least) I have to run it as "sudo docker".    That makes the example work.

However, for what it's worth, this test command seems to work equally well:

$ for i in {1..10}; do sh -c "(date; sleep 1) | busybox nc  $INGRESS_HOST $INGRESS_PORT"; done
one Fri Mar  8 18:12:05 GMT 2019
one Fri Mar  8 18:12:06 GMT 2019
one Fri Mar  8 18:12:07 GMT 2019
one Fri Mar  8 18:12:08 GMT 2019
one Fri Mar  8 18:12:09 GMT 2019
one Fri Mar  8 18:12:10 GMT 2019
one Fri Mar  8 18:12:11 GMT 2019
one Fri Mar  8 18:12:12 GMT 2019
one Fri Mar  8 18:12:13 GMT 2019
one Fri Mar  8 18:12:14 GMT 2019

If you want to use the "real" nc instead of Busybox you have to use the -N flag to avoid an indefinite hang:

$ for i in {1..10}; do sh -c "(date; sleep 1) | nc -N  $INGRESS_HOST $INGRESS_PORT"; done
one Fri Mar  8 18:12:59 GMT 2019
one Fri Mar  8 18:13:00 GMT 2019
one Fri Mar  8 18:13:01 GMT 2019
one Fri Mar  8 18:13:02 GMT 2019
one Fri Mar  8 18:13:03 GMT 2019
one Fri Mar  8 18:13:04 GMT 2019
one Fri Mar  8 18:13:05 GMT 2019
one Fri Mar  8 18:13:06 GMT 2019
one Fri Mar  8 18:13:07 GMT 2019
one Fri Mar  8 18:13:08 GMT 2019

**Comment by venilnoronha** [comment]
The problem is that the `nc` installation can differ on different platforms and the command arguments don't match. This is the reason for choosing `busybox` for testing.
