### ISSUE TITLE
See also section is often confusing

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3580]
@rvennam raised this during doc day which I agree.  Our see also page appears to be auto generated from go, however it doesn't always reflect what we want users to do next.

For example:
see also on this page doesn't precisely suggest what users should do next.  
https://preliminary.istio.io/docs/setup/kubernetes/install/kubernetes/

**Comment by linsun** [comment]
@geeknoid @frankbu @rcaballeromx

**Comment by geeknoid** [comment]
See also is generated based on the keywords in each document's front-matter.

For any strange looking See also section, look at the document's keywords and make sure they are reasonable. Compare to other keywords to make sure the right things are there, using the right words.

**Comment by linsun** [comment]
Thanks @geeknoid!  

ok so we probably should go through each of the page's see also see if it makes sense. :) For the quick start, I'm thinking  inject side car, examples (or just point to bookinfo), telemetry, traffic management, security, policies

**Comment by rvennam** [comment]
On that page, it would make sense for these pages to be listed in the See Also section:
https://preliminary.istio.io/docs/examples/bookinfo/
https://preliminary.istio.io/docs/tasks/*
https://preliminary.istio.io/docs/concepts/
https://preliminary.istio.io/about/community/join/

**Comment by geeknoid** [comment]
Note that we only generate up to 6 items in See also
