### ISSUE TITLE
Inconsistent helm install page

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3587]
for 1.2, I'd like us to have some consistency for the helm install page

We have 2 helm options (template vs helm install).   one requires downloading istio binary, one doesn't but asks users to do helm fetch.

Then at the end we ask users to do helm fetch (which some of them already did earlier) to clean up CRDs. (https://preliminary.istio.io/docs/setup/kubernetes/install/helm/#deleting-crds-and-istio-configuration)

We need some consistency on this page:  https://preliminary.istio.io/docs/setup/kubernetes/install/helm

**Comment by sdake** [comment]
@linsun given the code muave, I suspect 1.2 will be some time after Helm v3 releases.  The securing Helm docs for Helm 2.10+ actually recommend using `helm fetch` with tiller, and tiller will be (hopefully) long gone from 1.2.  FWIW I  agree, the two workflows are not ideal and lead to inconsistency.  I'd like to just move on from helm or *only* use it as a templating engine.

Cheers
-steve
