### ISSUE TITLE
Control Egress Traffic - outbound traffic allowed by default

### ISSUE THREAD

**Issue by rvennam** [istio/istio.io#3589]
https://preliminary.istio.io/docs/tasks/traffic-management/egress/

The page currently says: "By default, Istio-enabled services are unable to access URLs outside of the cluster because the pod uses iptables to transparently redirect all outbound traffic to the sidecar proxy, which only handles intra-cluster destinations. " 

I believe outbound traffic is allowed by default in 1.1 @linsun

**Comment by linsun** [comment]
@frankbu I closed my PR because you said you'll take a pass at editing this.

see https://github.com/istio/istio.io/pull/3429

**Comment by linsun** [comment]
if you already have an in flight PR pls link it :)

**Comment by rvennam** [comment]
@frankbu says he has a PR in the world. I'll hold off
