### ISSUE TITLE
sidecar injection understand what happened

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3591]
page is confusing:  https://preliminary.istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#understanding-what-happened

it mentioned about `The sidecar injector pod(s) should be restarted after modifying the mutatingwebhookconfiguration` however, it didn't mention what/why someone needs to modify the mutatingwebhookconfiguration.

**Comment by linsun** [comment]
this is also confusing `The set of namespaces in which injection is applied can be changed by editing the MutatingWebhookConfiguration ` while the example earlier showed to use label namespace to indicate if a namespace should be auto injected.

**Comment by ostromart** [comment]
> it mentioned about The sidecar injector pod(s) should be restarted after modifying the mutatingwebhookconfiguration however, it didn't mention what/why someone needs to modify the mutatingwebhookconfiguration.

I propose text like: 
"The set of namespaces in which injection is applied can be changed by editing the MutatingWebhookConfiguration with kubectl edit mutatingwebhookconfiguration istio-sidecar-injector. For example, the MutatingWebhookConfiguration could be modified to always inject the sidecar into every namespace, unless a label is set. Note that editing this configuration is an advanced operation. Refer to the k8s documentation link above for MutatingWebhookConfiguration configuration API."

> this is also confusing The set of namespaces in which injection is applied can be changed by editing the MutatingWebhookConfiguration while the example earlier showed to use label namespace to indicate if a namespace should be auto injected.

Propose adding to this sentence: "For example, you could explicitly list "kube-system" and "istio-system" as namespaces to never inject a sidecar into, regardless of the label."

@rcaballeromx, I can make those changes if you have too much on your plate.

**Comment by rcaballeromx** [comment]
@ostromart I'm taking a pass at the entire section and pushing a PR later today. I'll try to integrate a version of your suggestions and will add you and @linsun as reviewers. Thank you for your patience.
