### ISSUE TITLE
Links inside warnings are not rendered

### ISSUE THREAD

**Issue by rvennam** [istio/istio.io#3604]
![image](https://user-images.githubusercontent.com/5502967/54074424-58770700-4260-11e9-8e3b-95159e532670.png)

Examples:
https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/
https://preliminary.istio.io/docs/setup/kubernetes/install/helm/#installation-steps

**Comment by geeknoid** [comment]
Shoot, that's due to a "bug fix" last week to support {{ text }} inside warnings. The warning code is assuming its content is HTML and so doesn't do any markdown conversion.

All right, back to the drawing board on that bug fix.
