### ISSUE TITLE
Issue with docs/reference/config/istio.networking.v1alpha3/index.html

### ISSUE THREAD

**Issue by garystafford** [istio/istio.io#3613]
The link https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing.html is broken. This is referenced in here:
Load balancing policies to apply for a specific destination. See Envoy’s load balancing [documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing.html) for more details.
May now be https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing/load_balancing# or https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing/overview

**Comment by geeknoid** [comment]
This might already be fixed (if the report was against istio.io instead of preliminary.istio.io). Check the proto in istio/api.

**Comment by frankbu** [comment]
Yes, this is fixed: https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#LoadBalancerSettings
