### ISSUE TITLE
need to validate this example iks and icp

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3621]
with 1.1 RC builds.

https://preliminary.istio.io/docs/examples/multicluster/iks-icp/

@ibm-jason can you help?

**Comment by ibm-jason** [comment]
### Status Update

I talked with @ericvn regarding this issue, and realized that the ICP platform will need to be installed in an environment accessible to IKS.  There are a couple of options for this:

1. Installing the ICP platform on IBM Cloud
2. Installing the ICP platform in the `VLaunch` environment (which I have access to).

He put me in contact with `Vikram Khatri  (vikram.khatri@us.ibm.com)`, who I've asked to assist me with getting ICP setup in either environment.

Once I have the environment setup, I will proceed with validating the example.

**Comment by ibm-jason** [comment]
# Status Update

@morvencao has been kind enough to assist me with getting access to a IBM Cloud Private instance to conduct the validation testing. I'll be validating this example this week.
