### ISSUE TITLE
Sidecar example invalid

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#3623]
The second sidecar example YaML at https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/sidecar/ is invalid.

To reproduce, find the second example.  (The example with `defaultEndpoint: unix:///var/run/someuds.sock`).  Click to copy it to clipboard; paste it to a file _/tmp/default.yaml); use `istioctl validate -f /tmp/default.yaml` to validate it.

The output will be
```
Error: 1 error occurred:

* error validating resource (networking.istio.io/v1alpha3, Kind=Sidecar Name=default Namespace=): sidecar: the egress listener with empty port should be the last listener in the list
```

**Comment by esnible** [comment]
Feel free to close as a duplicate of https://github.com/istio/api/issues/847

**Comment by esnible** [comment]
While we are on the subject, there are two examples in _api/networking/v1alpha3/sidecar.proto_ and the related .go and .html files that did not make it to preliminary.istio.io.  These are the Sidecar examples _no-ip-tables_ and _partial-ip-tables_.  I am not sure why.

**Comment by geeknoid** [comment]
I haven't update the snapshot of the reference docs in a while. I'm doing it now, so it'll bring in any new content.
