### ISSUE TITLE
addons need gateways + certmanager documentation

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#3644]
The addons need a new document for how to use certmanager to create certificates to replace the gateway implementation that was removed from release-1.0.  The toc and wg leads agreed this was a P0 blocker, but couldn't be fixed in code in a timely manner or at all.

The solution was to move this problem to documentation, where @philrud has a document in progress or completed that describes how this is done.   I don't know if @philrud has agreed to write docs for this work.  @philrud if you have agreed, it would be greatly appreciated.

See the discussion here:
https://github.com/istio/istio/issues/12301#issuecomment-470337204

Cheers
-steve

**Comment by douglas-reid** [comment]
@sdake i have a PR out for this right now. ptal at #3625
