### ISSUE TITLE
Add FAQ entry:  containerPorts must be explicitly declared to avoid Istio bypass

### ISSUE THREAD

**Issue by duderino** [istio/istio.io#3668]
From https://istio.io/docs/tasks/traffic-management/app-health-check/

```
Because the Istio proxy only intercepts ports that are explicitly declared in the containerPort field, traffic to 8002 port bypasses the Istio proxy regardless of whether Istio mutual TLS is enabled.
```

This needs to be called out prominently in https://istio.io/help/faq/security/

**Comment by wattli** [comment]
It's already documented in 1.1 https://preliminary.istio.io/docs/setup/kubernetes/prepare/requirements/
