### ISSUE TITLE
Introduce in-process adapter model depracation notices

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#3670]
We need to advertise that the in-process adapter model is being deprecated in 1.1 and will be completely removed in 1.2. So:

- Put advisory on the in-process adapter page wiki page.

- Put a bullet in the 1.1 release notes

- Add an entry in the feature status page.

- Post a note on discuss.istio.io

**Comment by douglas-reid** [comment]
I've posted a note, updated the wiki, and sent a PR for the other two action items.

**Comment by douglas-reid** [comment]
Since that PR has been merged I will close this issue.
