### ISSUE TITLE
Documentation Deprecated

### ISSUE THREAD

**Issue by ocontant** [istio/istio.io#3672]
The preparation step prior to install istio is using obsolete parameter for minikube. 
https://istio.io/docs/setup/kubernetes/platform-setup/minikube/

minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.10.0 \
->    --extra-config=controller-manager.cluster-signing-cert-file="/var/lib/localkube/certs/ca.crt" \
->    --extra-config=controller-manager.cluster-signing-key-file="/var/lib/localkube/certs/ca.key" \
    --vm-driver=`your_vm_driver_choice`

I was informed by @tstromberg from the kubernetes team, that these parameter starting with ->, are obsolete and cause minkube to fail starting with an error related to the initialization of the api-proxy pod. 

i tried running the start command by removing the parameters and it started successfully.

**Comment by geeknoid** [comment]
@frankbu I just assigned this to you, 'cause I'm not sure who should get this one.

**Comment by frankbu** [comment]
This has already been fixed: https://preliminary.istio.io/docs/setup/kubernetes/prepare/platform-setup/minikube/

**Comment by ocontant** [comment]
Hi @frankbu,

I noticed the URL are differents and some link in Internet point to the URL I provided which is misleading.

Would you mind to setup a redirect from the old URL, toward the new URL?  This will avoid other people being misled.

**Comment by geeknoid** [comment]
To clarify Frank's comment:

This issue has been fixed in our preliminary doc set which will be released as part of Istio 1.1 in a few days. The content on istio.io will be replaced by this fixed content then. No redirects needed.

**Comment by frankbu** [comment]
@geeknoid, actually the backward-compatibility aliases of some of the moved files are also wrong.

https://github.com/istio/istio.io/pull/3702
