### ISSUE TITLE
Add custom resource backup/restore procedure to the documentation

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#3679]
Upgrade in this scenario is super fragile.  I have a workflow that works well:

https://github.com/istio/istio/pull/12484#issuecomment-472702527

We need a page that documents this with copious warnings.

I hate to move the goal post, but this seems like a P0 given the dedication our early adoptors have placed in our product.

Cheers
-steve

**Comment by geeknoid** [comment]
Why haven't these early adopters upgraded to 1.0 in the last 8 months? I'm not inclined to bend over backwards to support someone that didn't upgrade in all this time.

Clearly 0.8 users aren't in a rush to upgrade, so if we do decide to support this, we don't have to rush to do it for the 1.1 release and it can wait until we have time. Right?

**Comment by sdake** [comment]
@geeknoid 0.8 folks have upgraded to 1.0.  But if they originally deployed on 0.8, and then upgraded to 1.0, there are ankle-breakers awaiting when they move to 1.1 because of various tiller bugs in the 0.8 and 1.0 release timeframes.

Cheers
-steve

**Comment by geeknoid** [comment]
Ah, that's different. Than yeah, we should help these folks.

**Comment by sdake** [comment]
One way to handle this is:

"If you have ever upgraded from 0.8 or prior when using Helm's Tiller, please read this".  We can add this as a warning to the upgrade page (and possibly the install page).

where this includes a description of gotchas and warnings about the upgrade procedure between 1.0 and 1.1.  The goal is to get people to *precisely* follow the instructions).

I can help today produce a low-quality page @frankb if you are willing to tidy up the page and make sure it is presentable.  I am really tight on time this week and next, or I'd finish the job on my own appropriately.  I do appreciate the flexibility if you're willing :)

Our install docs are probably our operator's biggest pain point so the more investment here the better.

Cheers
-steve

**Comment by sdake** [comment]
My original concern was less about early adopter upgrade and more about data loss.  I did not express that clearly, as it wasn't clear in my head until @howardjohn had a look at the workflow and verified my work.

Pasting this here from the review.

@frankbu I think @howardjohn and I are on the same page that the following corrective action should be taken with this issue:

- A problem description of CRD upgrades should be explained
- A CRD backup procedure should be documented for those wishing to apply an abundance of caution
It took two to come up with this idea - I am very paranoid about configuration data loss.

**Comment by frankbu** [comment]
@sdake Let me know if you still need any help.

**Comment by sdake** [comment]
@frankbu I think we need help on how to dump the custom resources into a file.  I think I know how to do this, but can't get it done today.

**Comment by sdake** [comment]
@howardjohn and I worked out a backup and restore technique.  They are both one-iners:

backup:
```
kubectl get crds | grep istio.io | cut -f1-1 -d "." | xargs -n1 -i sh -c "kubectl get --all-namespaces -oyaml {}; echo ---" > $HOME/ISTIO_RESTORE_DATA.yaml
```

restore:
```
kubectl apply -f $HOME/ISTIO_RESTORE_DATA.yaml
```

I would use verbiage such as the following:

```
Helm has significant defects in CRD handling with relationship to upgrade.  There is a wide variety of helm and tiller versions in Istio deployments from 2.7.2 to 2.12.2.  Further compoudning this problem, In many cases people have in the past deployed with different versions of helm and tiller.  We believe we have solved these problems with the introduction of the istio-init chart.  Given the wide variety of different versions of Helm in the field, we recommend an abundance of caution by backing up your custom resource data:

**Comment by howardjohn** [comment]
Actually think there may be an issue. When we have all the extra fields we can restore fine, but then it is messed up later. I did a backup and restore, then tried to apply some changes to a CRD I had and got error:  `metadata.resourceVersion: Invalid value: 0x0: must be specified for an update`.

We are close.. just need to get rid of all the extra fields (at least resource version?)
