### ISSUE TITLE
Inconsistent use of "workload" terminology in Istio 1.1 preliminary docs

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio.io#3686]
Authentication Policy [docs](https://preliminary.istio.io/docs/reference/config/istio.authentication.v1alpha1/) have always used the term "workloads" when describing targets:

```text
targets | TargetSelector[] | List rules to select workloads that the policy should be applied on. If empty, policy will be used on all workloads in the same namespace.
```

The workload as described in AuthenticationPolicy refers to services in the registry and you're only allowed to use short names as described [here](https://preliminary.istio.io/docs/reference/config/istio.authentication.v1alpha1/#TargetSelector).

With the addition of [SIdecar](https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/sidecar/) resource, workloads  refer to Pods and the selection is based of labels.

Going further, the default metrics have [workload labels](https://preliminary.istio.io/docs/reference/config/policy-and-telemetry/metrics/) which correspond to deployments but it's not explicitly mentioned in the docs.

This is really confusing & requires in-depth knowledge of Istio to understand the nuances.

I would propose making these consistent & define terminologies if they mean different things. Happy to fix the docs if we can settle on the terminology.

**Comment by rcaballeromx** [comment]
@nrjpoddar I've assigned this but to myself because I'm working on several consistency issues we want to address using glossary terms https://preliminary.istio.io/about/contribute/creating-and-editing-pages/#glossary-terms
I'll be addressing this post 1.1 Thanks for filing the issue.

**Comment by nrjpoddar** [comment]
Thanks @rcaballeromx, how can I help?

**Comment by geeknoid** [comment]
@esnible @rshriram 

Could we do a quick pass through the reference API to make sure we use consistent terms for this:

Workload is a deployment/replicaset
Workload Instance is a  pod/vm.

**Comment by nrjpoddar** [comment]
Thanks @geeknoid for jumping on this. May be this is for the security WG but I think we should revisit the use of *service* short name in the Target field of the Authentication policy. Can we instead use workload selectors there as eventually the workloads representing the service implement this functionality on the server side.

**Comment by geeknoid** [comment]
Yes, I do think we'll be consolidating things around workloads as appropriate.

When we started Istio, we didn't have a clear line between workloads and services and it has caused confusion on a number of occasions. Although our understanding here has progressed, our API definitions haven't all caught up yet...

**Comment by esnible** [comment]
I made an attempt to use "workload instance" for everywhere we are talking about selecting a pod.

In a few cases I was unsure what we meant.  We might want to further improve this change with additional examples.  I created a table of the places we use "workload":

```
File                                      Field                            Doc Example
-----------------------------------       ------------                     -----------
authentication/v1alpha1/policy.proto      targets                          productpage (should it be productpage-v1"?)
authentication/v1alpha1/policy.proto      labels                           NONE, but is hide_from_docs "Once implemented"
networking/v1alpha3/envoy_filter.proto    workloadLabels                   app: reviews
networking/v1alpha3/gateway.proto         selector                         app: my-gateway-controller
networking/v1alpha3/service_entry.proto   subject_alt_names                spiffe://cluster.local/ns/httpbin-ns/sa/httpbin-service-account
networking/v1alpha3/sidecar.proto         workload_selector.labels         app: productpage
networking/v1alpha3/virtual_service.proto HTTPMatchRequest.source_labels   NONE
networking/v1alpha3/virtual_service.proto L4MatchAttributes.source_labels  NONE
networking/v1alpha3/virtual_service.proto TLSMatchAttributes.source_labels NONE
rbac/v1alpha1/rbac.proto                  workload_selector.labels         app: product
rbac/v1alpha1/rbac.proto                  workload_selectors.labels        NONE (but field is hide_from_docs)
```

I didn't touch the source_labels docs because of outstanding issue https://github.com/istio/istio/issues/7787
