### ISSUE TITLE
incorrect # CRDs since 1.1.0-RC5

### ISSUE THREAD

**Issue by thomschke** [istio/istio.io#3687]
Since 1.1.0-RC5 there are (again :-) 56 CRDs (instead of 58) to check during helm install:
 
https://github.com/istio/istio.io/blame/master/content/docs/setup/kubernetes/install/helm/index.md#L123-L128
https://github.com/istio/istio.io/blame/master/content/docs/setup/kubernetes/install/helm/index.md#L242-L247

**Comment by sdake** [comment]
the actual issue here is that crds change depending on install procedure.  With --set certmanager.enabled=true they arer one value, without, they are another.

@frankbu attempted boilerplating this, but from my understanding it didn't work properly.

**Comment by brian-avery** [comment]
I don't see --set certmanager.enabled=true mentioned on  https://preliminary.istio.io/docs/setup/kubernetes/install/helm/ though. Is this a special install case? Are there any other arguments that change the number of CRDs when enabled? Perhaps something more in line with "by default you should see 56 CRDs, but enabling other options may install additional ones"

**Comment by sdake** [comment]
it (was) mentioned in a PR related to release notes as the certmanager option was  just merged thursday evening.  The only special option is --set certmanager.enabled=true for istio-init.  No other rarguments change the number of CRDs when enabled.  I believe the plan is to add a setup-update docs page that provides additional context.

Cheers
-steve

**Comment by sdake** [comment]
@brian-avery 

Can you try using boilerplate for this - @geeknoid has said it is fixed.  This will make maintenance alot easier going forward.

Cheers
-steve

**Comment by sdake** [comment]
@geeknoid should likely be a P0 as people will get jammed up on the CRD count.

Cheers
-steve

**Comment by geeknoid** [comment]
We've got a couple perf docs in flight that will land this morning. This is the only other P0 left. Let's do the most expedient change possible here, the boilerplate stuff can wait til after launch.

Thanks.
