### ISSUE TITLE
Need to produce helm repo related doc

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3703]
it was suggested in SRE doc by @sdake and @frankbu -- We'll need some doc on how to use helm repo.

from https://github.com/istio/istio.io/issues/3131

**Comment by geeknoid** [comment]
This can wait till after 1.1 launches, right?

**Comment by sdake** [comment]
post 1.1 is fine @geeknoid.  See https://github.com/istio/istio.io/issues/3131#issuecomment-473301078.

**Comment by tiswanso** [comment]
@howardjohn added some comments to #3852 that really belong here:

> recent issues that came out of not documenting the Helm repo:
>  istio/istio#12889
>  istio/istio#12879
> 
> Another one istio/istio#12923

**Comment by sdake** [comment]
@tiswanso had added a comment here:https://github.com/istio/istio.io/issues/3852#issue-425468176

That the location of the URL includes the version number.  This isn't correct.  All Helm charts for all versions should go in one directory and an index built for the files within that dir.

This permits an easy upgrade without having to reset the istio repo location.

@utka ^^

**Comment by tiswanso** [comment]
@sdake -- Could you clarify whether you're saying we need enhancements to the release process to push versioned charts to a common helm repo?  The current release process is creating versioned helm chart repos--which I made the download doc page refer to in #3894.

**Comment by sdake** [comment]
@tiswanso Thanks for the doc PR. That doesn't solve this particular problem.

This is incorrect in our current infrastructure:

 helm repo add istio.io https://storage.googleapis.com/istio-release/releases/{{< istio_full_version >}}/charts/
Instead, it should be

 helm repo add istio.io https://storage.googleapis.com/istio-release/releases/charts
All versions should be stored in that path, and a proper index file built to permit installing any supported version of Istio (this is especially necessary for upgrade from an helm repo

Thanks for the doc PR. That doesn't solve this particular problem.

Cheers
-steve

**Comment by howardjohn** [comment]
This is a build/release issue though, not a docs issue. 

` helm repo add istio.io https://storage.googleapis.com/istio-release/releases/{{< istio_full_version >}}/charts/` is correct today, we release the Helm repo versioned.

Right?

If so I agree, seems like all other Helm repos work this way, we should open another issue under istio/istio for that maybe.

**Comment by tiswanso** [comment]
@sdake -- I was just typing what @howardjohn said.  We need a istio/istio Issue to update the helm release to push the indexed charts to a common location (`https://storage.googleapis.com/istio-release/releases/charts` doesn't actually exist today).

**Comment by utka** [comment]
For now I can manually create .../releases/charts/ folder and add all the version files in there. 
Will it work for now? 
But we do need to add this step to release scripts for future releases.

**Comment by sdake** [comment]
> This is a build/release issue though, not a docs issue.
> 
> ` helm repo add istio.io https://storage.googleapis.com/istio-release/releases/{{< istio_full_version >}}/charts/` is correct today, we release the Helm repo versioned.
> 
> Right?
> 
> If so I agree, seems like all other Helm repos work this way, we should open another issue under istio/istio for that maybe.

Yes, I submitted this comment in the wrong issue.  I fixed that in the main issue on istio/istio.

**Comment by sdake** [comment]
> This is a build/release issue though, not a docs issue.
> 
> ` helm repo add istio.io https://storage.googleapis.com/istio-release/releases/{{< istio_full_version >}}/charts/` is correct today, we release the Helm repo versioned.
> 
> Right?
> 
> If so I agree, seems like all other Helm repos work this way, we should open another issue under istio/istio for that maybe.

Ya, perhaps I had a knee jerk reaction to the addition of the repo to `/charts/version` when instead it should just be `/charts`.  I will dig into this problem and file an issue on istio/istio if there is one.

**Comment by sdake** [comment]
> For now I can manually create .../releases/charts/ folder and add all the version files in there.
> Will it work for now?
> But we do need to add this step to release scripts for future releases.

Agreed.  At one point all this stuff was working.  Not sure why it isn't now :)

Here is the istio/istio issue tracker:

https://github.com/istio/istio/issues/12974

**Comment by howardjohn** [comment]
Documented at https://preliminary.istio.io/docs/setup/kubernetes/install/helm/#helm-chart-release-repositories and Steve already opened a followup issue, so I am going to mark this closed
