### ISSUE TITLE
update page update

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3705]
a couple of update I think we need to inform users:
1. link to the to be created compatibility page.  Highlight the need to look over this page and default required resource changes.
2. move  k8s rolling update before helm update

**Comment by sdake** [comment]
https://github.com/istio/istio.io/issues/3536#issuecomment-473139212

**Comment by sdake** [comment]
@linsun didn't your work here merge?  If so, can you close the issuee.

Cheers
-steve

**Comment by linsun** [comment]
yep, thanks @sdake !
