### ISSUE TITLE
Missing whitespace on Installation Options

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#3740]
In reference to https://preliminary.istio.io/docs/reference/config/installation-options/

There seem to be missing whitespace issues with this page. For example global.enableHelmTest is missing whitespace around punctuation, and global.meshExpansion.useILB links up some words.

**Comment by johnma14** [comment]
@esnible @geeknoid a PR has been created for this: https://github.com/istio/istio.io/pull/3762. Thanks.

**Comment by geeknoid** [comment]
Fixed
