### ISSUE TITLE
quick start install - use verify-install cmd

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3750]
Can we use verify-install cmd instead?  It is much easier than checking services and pods today:  https://preliminary.istio.io/docs/setup/kubernetes/install/kubernetes/

Example:
```
~/Downloads/istio-1.1.0 ⌚ 20:05:29
$ istioctl experimental verify-install --filename install/kubernetes/istio-demo.yaml
Istio is installed successfully
```

**Comment by frankbu** [comment]
I think we should consider it post 1.1, but before we use something like that in the official docs, I think it needs to:
1. not be experimental
2. report what it's checking: e.g., `deployed services: passed`, `pods running: passed`, etc., not just a single `Istio is installed` message.
3. I also think it's important to show what components are deployed, so if we don't tell the user to run `kubectl get po`, the verify command should print them: `pilot deployed: success`, `citadel deployed: success`, or maybe something like: `Deployed components: <list>` at the end.

**Comment by linsun** [comment]
Maybe there can be a --verbose option that prints out what (list of pods/services/crds etc) have been checked?    I am comfortable with a message installed successfully but others may want to see more.

I agree it needs to graduate from experimental.

@irisdingbj can you look into this improvement?

**Comment by linsun** [comment]
cc @esnible @rvennam

**Comment by frankbu** [comment]
As long as `--verbose` default is `true` :)

I also don't think it will work in general if the verify command requires the yaml file argument, because with helml users don't need or want to generate a yaml file, the config is just piped to kubectl apply or handled by helm install.

**Comment by esnible** [comment]
There is already a PR for more output https://github.com/istio/istio/pull/12174 waiting for 1.1.1 to open.

It might be nice to bake in a minimal list of deployments to check and make the .yaml parameter optional.  (It might also be nice to make the output more like `linkerd check` by checking other things like versions).

**Comment by linsun** [comment]
Agreed, I think we should make yaml file optional for folks who want to provide the yaml file for more thorough checking.  Then we can check against each builtin profiles and their associated list of deployments?

**Comment by frankbu** [comment]
> It might be nice to bake in a minimal list of deployments to check and make the .yaml parameter optional.

If there's no yaml provided, I would say it just checks that everything deployed in the `istio-system` namespace is up and running. Again, if the command produces output about what it checked, then it would be easy for the user to cross check the "verify results" against what was expected to be running.
