### ISSUE TITLE
How can I open the Jaeger UI in a remote browser, not the localhost machine 

### ISSUE THREAD

**Issue by qiaozhi58** [istio/istio.io#3757]
The official document said:
We can access the Jaeger UI by the following action:
kubectl port-forward -n istio-system $(kubectl get pod -n istio-system -l app=jaeger -o jsonpath=’{.items[0].metadata.name}’) 16686:16686 &

Then can use http://localhost:16686.
But the localhost is a Linux machine, there haven’t a browser.
I must open the browser on a remote machine.
How can I do?
thanks.

**Comment by linsun** [comment]
I ran into this too, see https://github.com/istio/istio.io/pull/3754

**Comment by linsun** [comment]
sorry read too fast :). one alternative is to wire it with our ingress gateway. https://preliminary.istio.io/docs/tasks/telemetry/gateways/

the other alternative is to expose it as a k8s node port service or load balancer service.

**Comment by douglas-reid** [comment]
I believe @linsun has done a good job summarizing the options.  Closing.

**Comment by qiaozhi58** [comment]
@linsun @geeknoid @douglas-reid 
thank you!
