### ISSUE TITLE
different definition of Gateway

### ISSUE THREAD

**Issue by abonas** [istio/istio.io#3786]
https://istio.io/docs/concepts/traffic-management/#rule-configuration
in this page, it says that Gateway "...most commonly operating at the edge of the mesh to enable ingress traffic for an application", but other pages like
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#Gateway
say that Gateway is "a load balancer operating at the edge of the mesh receiving incoming or outgoing HTTP/TCP connections".
So the first link says it's for ingress (incoming), but the second says it's for both ingress/egress.
I propose they should be aligned.

**Comment by frankbu** [comment]
Fixed by #3879
