### ISSUE TITLE
Image used in Grafana was removed with the 1.1 docs release

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio.io#3788]
Grafana displays the image at https://istio.io/img/istio-logo.svg on the Mesh Dashboard in 1.1. This was removed in the 1.1 docs.

I originally opened this on istio/istio but I think it's best to just make available again here to address for any existing users.

![image](https://user-images.githubusercontent.com/12174604/54644273-5f2b2880-4a6f-11e9-9e6d-1f16d15eb123.png)

**Comment by rcaballeromx** [comment]
@jaygorrell The logo was moved to keep the repo organized. You can find it here: https://github.com/istio/istio.io/blob/master/assets/inline_images/landing/istio-logo.svg

**Comment by geeknoid** [comment]
For now, you can find the following images in istio.io/img:

istio-bluelogo-nobackground-unframed.svg    
istio-bluelogo-whitebackground-unframed.svg
istio-whitelogo-bluebackground-unframed.svg
istio-whitelogo-nobackground-unframed.svg
istio-bluelogo-nobackground-framed.svg
istio-bluelogo-whitebackground-framed.svg
istio-whitelogo-bluebackground-framed.svg
istio-whitelogo-nobackground-framed.svg

I can add a legacy istio-logo.svg file in there too to address legacy links.

**Comment by geeknoid** [comment]
The image file is back now. 

Thanks.

**Comment by mjordan79** [comment]
> 
> 
> The image file is back now.
> 
> Thanks.

Hi geeknoid, even with the image file back, the rendering of the final image seems to be still problematic.
Following the link https://istio.io/img/istio-logo.svg, Firefox gives a blank page. Chrome is more explicative, it complaints about a missing style:
https://imgur.com/a/ZnFiNke

Hence, the problem doesn't seem to be fixed.

**Comment by geeknoid** [comment]
I update the image. I had stripped some of the XML needed to make it look like a stand-alone SVG file.
