### ISSUE TITLE
Document https://istio.io/charts

### ISSUE THREAD

**Issue by lblackstone** [istio/istio.io#3789]
https://istio.io/charts/ started returning a 404 today

**Comment by geeknoid** [comment]
@hklai Deleted the charts here: https://github.com/istio/istio.io/commit/d478874e98b562a44dec5805f23e0ae5d8102974.

What should we do? Should we continue to host these charts on istio.io/charts or do we have a better solution now? Any docs referencing istio.io/charts that need to be updated (perhaps some readmes in istio/istio?)

**Comment by sdake** [comment]
no docs reference istio.io/charts afaik.  It is still where people go to access ccharts.  I'd recommend reverting the removal.

**Comment by sdake** [comment]
after looking at @hklai 's solution, it looks correct.  I think what is missing is a release-1.1.0 chart at gcsweb.istio.io.

**Comment by linsun** [comment]
is this link (https://istio.io/charts/) referred somewhere?  I can't find any reference to it doing a code search.
@lblackstone how did you know this url?  our install doc doesn't mention it.

**Comment by lblackstone** [comment]
I'm not sure where the link originally came from, but it's used in one of our CI tests.

@hausdorff do you know?

**Comment by geeknoid** [comment]
@duderino @utka Looks like we need to drop some charts in gcsweb for 1.1

**Comment by geeknoid** [comment]
BTW, we can program a redirect from istio.io/charts to gcsweb.istio.io/*. And we could create a DNS entry pointing charts.istio.io to the same place.

**Comment by sdake** [comment]
@geeknoid that's great news!  I was going to suggest a redirect in my haze yesterday.  A CNAME for charts.istio.io sounds good as well.

**Comment by geeknoid** [comment]
OK, so the charts are at https://gcsweb.istio.io/gcs/istio-release/releases/1.1.0/charts.

I'll add a redirect from istio.io/charts to there in a way that automatically works for different releases over time without having to do some manual edits.

As for DNS, I could only point charts.istio.io to gcsweb.istio.io, which is not really useful. So I won't do that.

**Comment by geeknoid** [comment]
OK, there's now a redirect in place so istio.io/charts gets you to the right place.

@sdake @linsun Should we document the existence of istio.io/charts as the place to get our charts?

**Comment by sdake** [comment]
@geeknoid indeed - thanks for all the work here.  I will get on this in the next few days.

Cheers
-steve

**Comment by duanshiqiang** [comment]
In our CI/CD environment we are using https://gcsweb.istio.io/gcs/istio-release/releases/charts as the chart repo url. But after 1.1.3 is released, it's not been uploaded to this location so we can't use this url anymore.

**Comment by geeknoid** [comment]
@duanshiqiang Can you use https://istio.io/charts instead?

**Comment by duanshiqiang** [comment]
@geeknoid As of today, [https://istio.io/charts](https://istio.io/charts) still gives Error:

`Looks like "https://istio.io/charts" is not a valid chart repository or cannot be reached: Failed to fetch https://istio.io/charts/index.yaml : 404 Not Found`

And also there's a fundamental issue with [https://istio.io/charts](https://istio.io/charts) is that it only contains latest version of istio chart. By right, the repo should contain all released chart right?

**Comment by sdake** [comment]
@duanshiqiang I lost track of this issue.  https://istio.io/charts should contain all released versions of the charts.  I'll speak with test and release about getting the charts released properly if they have not already been rectified.
