### ISSUE TITLE
Recent change to Bookinfo example what's next section not acceptable

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#3794]
Part of the change in #3721 is very bad: the change in the "What's next" section. After starting the bookinfo application, what's next needs to point to some tasks that use the bookinfo application. It used to point to the "Inteligent Routing" example which used to walk through a set of tasks that were all using the bookinfo application, but now we are just pointing at other examples that have nothing to do with bookinfo. We need to change this what's next to point to the related tasks.

**Comment by geeknoid** [comment]
#3721 was a redo of #3635, do adding @douglas-reid .

**Comment by frankbu** [comment]
I'll send a PR to the `release-1.1` branch to fix this.

**Comment by douglas-reid** [comment]
Aren't the "What's Next?" sections auto-generated?

**Comment by douglas-reid** [comment]
Oh, nevermind, that's the "See Also" sections in the Tasks.

**Comment by frankbu** [comment]
Fixed by #3806
