### ISSUE TITLE
Simplify BookInfo install page using tabs

### ISSUE THREAD

**Issue by rvennam** [istio/istio.io#3802]
**Describe the feature request**
https://istio.io/docs/examples/bookinfo/ 
BookInfo install page is a bit long. There are two sections (Deploying and Clean up) which are broken apart with large If Kubernetes and If Consul sections.

**Describe alternatives you've considered**
Can we put `Kubernetes` and `Consul` in tabs? I've seen tabs being used for just code blocks, but they can used for steps as well?

**Comment by frankbu** [comment]
The problem with tabs is that you can't put section heading in them, and the Kubernetes version of the instructions has a few subsections because they need to be referenced from other docs.

**Comment by rcaballeromx** [comment]
I've added this issue to the development of a comprehensive Istio tutorial since installing the Bookinfo app is a part of it.

**Comment by frankbu** [comment]
This is fixed now. We have removed the Consul instructions from this doc.
https://istio.io/docs/examples/bookinfo/
