### ISSUE TITLE
Document configuring stdio log entries for Mixer

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio.io#3804]
since they are not created by default in 1.1

Maybe add a special helm chart for them and then use that chart, e.g. `charts/mixer/templates/stdio.yaml` like:
`helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set mixer.adapters.stdio.enabled=true -x charts/mixer/templates/stdio.yaml | kubectl apply -f -`

**Comment by douglas-reid** [comment]
This is already sort of documented in https://istio.io/docs/tasks/telemetry/logs/collecting-logs/.

Is this about turning on the "Istio default logs"?  If so, should we just update the existing to add a section on using the "default logging" configuration (with warnings, etc.)?

**Comment by vadimeisenbergibm** [comment]
@douglas-reid Right, this is about turning on the "Istio default logs": stdio logentries and rules.
