### ISSUE TITLE
Remove the "Platform Setup" pages from our doc set

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#3810]
The material in Platform Setup is not really Istio-specific, it just tells folks how to setup clusters on N different environments. We don't need to do this. We should trim this stuff out and only keep whatever nuggets of Istio-specific information there might be in there.

**Comment by sdake** [comment]
I'd encourage keeping the documentation on minikube - possibly in a developer-related section.  I think the wiki is a poor place to document our development processes, as it has low visibility and not many people are aware of it.

Cheers
-steve
