### ISSUE TITLE
Issue with about/feature-stages/index.md

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#3818]
The link for "Kubernetes: Service Credential Distribution" is the wrong and currently it is the same with "Service-to-service mutual TLS" (https://istio.io/docs/concepts/security/#mutual-tls-authentication), please correct it to point to the correct link,

**Comment by linsun** [comment]
@wattli can you handle this?

**Comment by wattli** [comment]
https://github.com/istio/istio.io/pull/3823

**Comment by wattli** [comment]
https://github.com/istio/istio.io/pull/3824
