### ISSUE TITLE
Add multicluster using split horizon EDS to install pages

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#3819]
Today, the multicluster mesh with a single control plane topology and using Istio’s Split-horizon EDS (Endpoints Discovery Service) is only documented under examples and isn't asked about under the Install-MultiCluster pages with the VPN and Gateway connectivity.

It is probably a split of the current example, moving the configuration portion under Install.

From Slack, this should be a 1.2 documentation item.

**Comment by esnible** [comment]
I ran into the same thing today.  https://istio.io/docs/setup/kubernetes/install/multicluster/ should know about https://istio.io/docs/examples/multicluster/split-horizon-eds/
