### ISSUE TITLE
Consolidate perf numbers

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#3822]
We currently have different perf numbers in the 1.1 announcement blog post as compared to the perf & scalability concept page.

We need to publish a single consistent of numbers.

If we decide to update the announcement blog, we'll also need to update the announcement post on discuss.istio.io

**Comment by geeknoid** [comment]
@rcaballeromx

**Comment by suryadu** [comment]
@geeknoid are you talking about this blog (https://istio.io/blog/2019/istio1.1_perf/) that we published on 1.1 and Scalability section on istio.io ? or are you talking about the tuning ops guide that is to be published (https://github.com/istio/istio.io/blob/c68a1570d23423206c93b8d81af5ad2a285d336b/content/help/ops/perf/index.md) ?

**Comment by geeknoid** [comment]
Sorry for being unclear. I mean the Istio 1.1 announcement blog: https://istio.io/blog/2019/announcing-1.1/
