### ISSUE TITLE
Bookinfo example drawing does not contain mongo

### ISSUE THREAD

**Issue by abonas** [istio/istio.io#3830]
there is a connection between ratings v2 and mongo in bookinfo, but the drawing does not show it

**Comment by frankbu** [comment]
@abonas which drawing are you referring to?

The drawing in the article that uses it does show ratings v2 and mongo: https://istio.io/blog/2018/egress-mongo/#use-the-external-database-in-bookinfo-application

**Comment by abonas** [comment]
@frankbu the 2 drawings here:
https://istio.io/docs/examples/bookinfo/

**Comment by abonas** [comment]
and it actually doesn't even show ratings has 2 versions...

**Comment by frankbu** [comment]
That's true, but there are actually 2 versions of the details service too, and the ratings service has more than one flavor of v2 (mongo, mysql, ...). These are all extensions of the basic sample, used in other examples/blogs.

The diagram in https://istio.io/docs/examples/bookinfo/ should, and does, only show services that are used in that example. It only deploys the services shown in the diagram (i.e., from bookinfo.yaml), as you can see [here](https://istio.io/docs/examples/bookinfo/#if-you-are-running-on-kubernetes).

**Comment by frankbu** [comment]
The diagram in the bookinfo example doc is intentionally not including versions used in other examples.
