### ISSUE TITLE
setupMeshEx.sh and setupIstioVM.sh deprecated in 1.1.0?

### ISSUE THREAD

**Issue by leecalcote** [istio/istio.io#3836]
Reference to and explanation of the `setupMeshEx.sh` and `setupIstioVM.sh` scripts have been removed from the 1.1 docs, but remain in the 1.1.0 release bundle.

_"An example script to help with Kubernetes setup is available as part of the release bundle called install/tools/setupMeshEx.sh. Check the script content and environment variables supported (like GCP_OPTS)._

_An example script to help configure a machine is available as part of the release bundle called install/tools/setupIstioVM.sh. You should customize it based on your provisioning tools and DNS requirements."_

**Comment by geeknoid** [comment]
Should we delete the scripts, or bring back the docs?

**Comment by sdake** [comment]
@geeknoid unclear perhaps @costinm can consult.
