### ISSUE TITLE
Issue with docs/setup/kubernetes/prepare/platform-setup/minikube/index.md

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#3837]
In this web, the command is as below, but it is incorrect to use " \` " to use your_vm_driver_choice, because it will cause the minikube start failed in windows powershell, I think it will also failed in other platform. So I recommend to use " instead of \` for this command.

In this link, the command is:
minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.13.0 \
    --vm-driver=\`your_vm_driver_choice\`

**Comment by sdake** [comment]
https://github.com/istio/istio.io/pull/3891

**Comment by frankbu** [comment]
Fixed by #3891
