### ISSUE TITLE
Issue with docs/tasks/traffic-management/egress/index.md

### ISSUE THREAD

**Issue by zuxahiz** [istio/istio.io#3841]
I noticed that the option global.outboundTrafficPolicy.mode=ALLOW_ANY is enabled by default, it's really help for beginners, thanks. But I have some confusions with the following expression: 

> For example, if you don’t register an HTTP service or define a service entry for port 8000 within the mesh, the sidecar proxy will forward requests to any external service on that port. **However, if you later create an HTTP service inside the mesh on port 8000 or define a service entry for any host on port 8000, Istio will block all external access to port 8000**; Istio will fall back to a blocking-by-default behavior for that port.

As I can see, a serviceentry is defined for allowing accessing an outside service, but why after defining a service entry for any host on port 8000, istio will **block** all all external access to port 8000? 
Anyone who can explain this please help. Thanks in advance.
[https://istio.io/docs/tasks/traffic-management/egress/#envoy-passthrough-to-external-services](url)

**Comment by frankbu** [comment]
This has been fixed by https://github.com/istio/istio/pull/12916
Docs will be updated soon.

**Comment by frankbu** [comment]
Fixed in #3973

**Comment by zuxahiz** [comment]
> Fixed in #3973

Thanks for your information, it's really helpful.
