### ISSUE TITLE
Little to no mention of controlPlaneSecurityEnabled, including the mTLS migration document

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio.io#3844]
The docs don't really cover `controlPlaneSecurityEnabled` or anything it controls as part of mTLS migration. Without it, or creating the components it would create, things like telemetry can't communicate with your sidecars and the Grafana dashboard will not show any traffic.

Enabling this flag modifies the `DestinationRule` for istio-policy and istio-telemetry, as well as many other things.

**Comment by kvudata** [comment]
Any updates on this?
v1.2 has been released but the current docs on [controlPlaneSecurityEnabled](https://istio.io/docs/reference/config/installation-options/#global-options) are quite meager and it's unclear to a user of Istio what the benefit is to enabling it or when to enable it.

**Comment by kvudata** [comment]
Ping on this, it looks like the docs still don't explain why someone should turn this on

**Comment by incfly** [comment]
I'll take this one when I have some time.  This require some doc and Helm template change probably.

Only reason I'm aware of not turning controlPlaneSecurity is someone install Istio without security component at all, e.g. no Citadel installed, so no security can be provided.

@linsun can confirm above.

Other than that, this should always be turned on by default to simplify installation and enhance the security.

**Comment by sstarcher** [comment]
I got here by looking at the install docs and noticing this is not part of the default profile.  Given @incfly comment, I would think it should be the default option and not something to add.

**Comment by tcdowney** [comment]
Found this issue while trying to figure out what `controlPlaneSecurityEnabled` actually does. A docs improvement would definitely be appreciated! 🙏

**Comment by incfly** [comment]
This option has been enabled by default in 1.5 as I just verified via
`bin/istioctl manifest generate   | grep controlPlaneSecurityEnabled`

**Comment by XanderStrike** [comment]
Still curious what this setting does over a year later. Does it mean anything at all in 1.6+ where there's only istiod?

**Comment by kyessenov** [comment]
@incfly @liminw is this option still used? I wasn't sure when I deleted the rest of Mixer flags in 1.8 release.

**Comment by Jeskz0rd** [comment]
@kyessenov I was asking myself the same question today. I went through the Operator api/docs for a custom 1.6 setup and I also checked the 1.5 [upgrade notes](https://istio.io/latest/news/releases/1.5.x/announcing-1.5/upgrade-notes/#automatic-mutual-tls) trying to figure it out more info about it, but this is still not clear at all.

```
Note: despite the naming, in Istio 1.5 when controlPlaneSecurityEnabled is set to false,
communication between the control plane will be secure by default.
```

**Comment by sdake** [comment]
the ControlPlaneSecurityEnabled flag has been removed. In past versions, it installed default permissive mtls rules (IIRC) via a CR install. Now, permissive is the default, the flag is no longer needed.


Cheers,
-steve

**Comment by andrewisplinghoff** [comment]
If the config value `controlPlaneSecurityEnabled` does not longer exist, the example for customizing the Istio installation with `istioctl install --set values.global.controlPlaneSecurityEnabled=true` should be changed to sth. else on https://istio.io/latest/docs/setup/install/istioctl/#customizing-the-configuration.
