### ISSUE TITLE
Spelling mistake in tool-tip(Copy to Clipoboard) in Docs web-pages

### ISSUE THREAD

**Issue by karthikmg** [istio/istio.io#3848]
Describe the bug
There is a Spelling mistake in tool-tip(Copy to Clipoboard) upon hovering over the clipboard icon in the code panel of the website.

Expected behavior
Correct the typo to "Copy to Clipboard".

Steps to reproduce the bug
Navigate to any documentation web page in the istio.io and hover over the "Copy to Clipboard" icon.

![Istio_Typo_Bug](https://user-images.githubusercontent.com/3976260/54979497-508dc580-4fc9-11e9-8d6d-13bbc2647d76.png)

**Comment by karthikmg** [comment]
This is my first time creating a bug or submitting a PR in open source.
I would also like to contribute to this project.
Shall I go ahead fix this typo and submit a PR?

**Comment by karthikmg** [comment]
This is my first time creating a bug or submitting a PR in open source.
I would also like to contribute to this project.
Shall I go ahead and fix this typo and submit a PR?

**Comment by geeknoid** [comment]
I just pushed in a fix. If I had read the whole issue, I would have seen your last note and let you handle the fix. Sorry about that.

If you'd like to help with our docs, check out https://istio.io/about/contribute.

Note that on every page in the site, you can go to the gear menu in the top right and select the option to edit the current page. This makes it easy to fix issues in an individual page and submit a PR for it.

Thanks.
