### ISSUE TITLE
Istio CNI install instructions broken due to Istio helm doc changes

### ISSUE THREAD

**Issue by tiswanso** [istio/istio.io#3852]
#3689  removed the helm documentation related to using the Istio release helm repository.  The Istio CNI instructions indicate the `helm repo add istio.io <release repo>` is a prerequisite.

This issue is to track changing the CNI doc to point to the helm repo instructions being tracked by #3703.

To use the Istio release 1.1.1 helm repo:
```
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.1.1/charts/
```
That will make the Istio CNI install instructions usable as written in https://istio.io/docs/setup/kubernetes/additional-setup/cni/#installation

**Comment by frankbu** [comment]
@tiswanso Can't/shouldn't we update the CNI instructions to also work using the charts in the downloaded release, or are they not included in the download? Seems to me we should make it easy for those users to try out the CNI plug-in too.

**Comment by tiswanso** [comment]
We can change the doc to instruct un-targz'ing  the CNI chart but would be nice to refer to helm repo usage instructions at the same time.

**Comment by howardjohn** [comment]
Two recent issues that came out of not documenting the Helm repo:
https://github.com/istio/istio/issues/12889
https://github.com/istio/istio/issues/12879

**Comment by howardjohn** [comment]
Another one https://github.com/istio/istio/issues/12923

**Comment by tiswanso** [comment]
@howardjohn -- I added your comments about other helm repo issues to #3703 where they really belong.  This is tracking the Istio CNI install doc getting back in sync with Istio's helm install doc (which moved away from using `helm repo`)

**Comment by howardjohn** [comment]
@tiswanso I think this is superseded by https://github.com/istio/istio.io/issues/4327, do we still need this?

**Comment by rlenglet** [comment]
Nope, let's close this.
