### ISSUE TITLE
Removed synced percentage (e.g. 50%) in `istioctl proxy-status` output

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#3853]
Our documentation at https://istio.io/help/ops/traffic-management/proxy-cmd/ gives the possible SYNC values.  It does not document what it means when there is a `SYNC (%)` and the number is not 100.

Our users are wondering: https://discuss.istio.io/t/eds-status-synced-50/1244

**Comment by esnible** [comment]
@liamawhite ^^

**Comment by liamawhite** [comment]
Agreed. @costinmor or @rshriram are probably the people who can best give a definition here.

**Comment by sdake** [comment]
fwiw I've asked this question in slack 4 or 5 times and haven't got an answer either.  Would be nice to know :)

Cheers
-steve

**Comment by Stono** [comment]
I've correlated this to the % of clusters the sidecar is interested in (based on its Sidecar spec)

**Comment by dwradcliffe** [comment]
(I asked the question on discuss) I read through the code and it did seem to be the ratio of clusters to eds clusters. I'm still not 100% sure what this means but I've observed that the percent goes way down when using a Sidecar to limit the scope, as @Stono said.

https://github.com/istio/istio/blob/fa1cf3ab6773b7bf8b0b7e37c02b55faa424a3e3/pilot/pkg/proxy/envoy/v2/ads.go#L554

**Comment by jaygorrell** [comment]
I see 50% on a bunch of services on one Pilot while a second Pilot has 100%. I still have no idea what it means but everything is functioning correctly. Not using Sidecar or anything.

**Comment by mehemken** [comment]
I'd rather not let this rot...

**Comment by rshriram** [comment]
I dont understand that computation at all.. @costinm wrote that area of code. May be @hzxuzhonghu has more context. It seems like some incorrect computation given that things are functioning correctly.

**Comment by esnible** [comment]
@costinm If values other than 100% are valid we should remove the numeric output from the CLI.  It confuses people.

If values other than 100% indicate problems, in correctness or performance, we should be able to describe those problems in our documentation.

**Comment by linsun** [comment]
I don't think our computation is correct in 1.1.  I'm also running into this 50% SYNCED, and I'm not using sidecar resource at all.  Everything appears to be working afaik.

**Comment by hzxuzhonghu** [comment]
Yes, the compute output is not right.

**Comment by linsun** [comment]
I think i know why some are 50% some are 100%.  both the pods (ingress or egress gateways) are in istio-system are 100%, while my deployed pods in default ns are ALL marked as 50% because we no longer push info from istio-system ns.

This should not be a doc issue, it should be 100% for all pods to indicate it is synced within the scope it is supposed to sync imho.

**Comment by Stono** [comment]
Ok so I do use this as a great indication as to how much config a sidecar
is pulling.

If you so change that behaviour (even if it is a side effect) I would
request another metric to represent that.

It basically helps us to identify sidecars without a refined egress list.

**Comment by linsun** [comment]
ok that is an interesting way to use it. :). If our SYNCED status is accurate and sufficient for users to rely on, perhaps users can use that info to determine if the config has been synced and all pushed from pilot to sidecar and then use the percentage to indicate how much have been pushed out of the total that includes whatever aren't supposed to push because of scoping or visibility.

would this work for folks?

**Comment by dwradcliffe** [comment]
While I have also been using it as a proxy for determining if the Sidecar is working, I don't think it's accurate. I have different values for each pod in the same Deployment.
Example (with Sidecar):
```
irs-client-5886cdf584-8d2mb.irs-client-staging            SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-5996947b5f-h9bjs     1.1.1
irs-client-5886cdf584-9pz2z.irs-client-staging            SYNCED     SYNCED     SYNCED (1%)       SYNCED       istio-pilot-5996947b5f-xlqdm     1.1.1
irs-client-5886cdf584-qgvgl.irs-client-staging            SYNCED     SYNCED     SYNCED (92%)      SYNCED       istio-pilot-5996947b5f-h9bjs     1.1.1
```

**Comment by esnible** [comment]
The documentation at https://istio.io/help/ops/traffic-management/proxy-cmd/ assumes the user is familiar with Envoy internals.  The column names are not self-explanatory.

If the EDS SYNCED percentage is intended to represent the scoping we should make the command output explicit.  I have seen the 50% back in 1.0 and I am dubious.  What should the column headings look like

Perhaps we replace

```
PROXY                                                  CDS        LDS        EDS               RDS          PILOT
details-v1-6dcc6fbb9d-wsjz4.default                    SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-75bdf98789-tfdvh
istio-egressgateway-c49694485-l9d5l.istio-system       SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-75bdf98789-tfdvh
```

with

```
SIDECAR POD                                      CLUSTERS        LISTENER        ENDPOINTS         ROUTES          PILOT POD ENDPOINT-SCOPE-VISIBLITY
details-v1-6dcc6fbb9d-wsjz4.default                    SYNCED     SYNCED     SYNCED      SYNCED       istio-pilot-75bdf98789-tfdvh          (100%)
istio-egressgateway-c49694485-l9d5l.istio-system       SYNCED     SYNCED     SYNCED      NOT SENT     istio-pilot-75bdf98789-tfdvh      (100%)
```

**Comment by linsun** [comment]
+1, the percentage is really scope of visibility.

@irisdingbj could you open an issue and drive a fix for this in istioctl?

**Comment by frankbu** [comment]
If it's just scope of visibility, then there also seems to be a bug as @dwradcliffe pointed out above: https://github.com/istio/istio.io/issues/3853#issuecomment-481093245

Also `ENDOPOINT-SCOPE-VISIBILITY` seems pretty wordy and not totally clear what value to expect, without some documentation explaining what it really means. So I would suggest just tweaking the output slightly, something like this:
```
PROXY                                                  CDS        LDS        EDS (PULLED)      RDS          PILOT
details-v1-6dcc6fbb9d-wsjz4.default                    SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-75bdf98789-tfdvh
istio-egressgateway-c49694485-l9d5l.istio-system       SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-75bdf98789-tfdvh
```
The doc just needs to say that the EDS % is the percentage of the total mesh endpoints that is needed in (pulled into) the sidecar.

**Comment by ardenxu** [comment]
we got similar status, and the circuite break rule did not work either, have no idea its rule sync problem or istio's envoy software bug.

![image](https://user-images.githubusercontent.com/20676860/57773320-53e03a80-774a-11e9-9d86-2c22fd915e79.png)

**Comment by frankbu** [comment]
Seems to me like there is more than one reason for % less than 100. Sometimes it's scope of visibility, in which case `SYNCED (X%)` seems fine even if X is less that 100. Other cases, esp. ones like @dwradcliffe described, above, where the percentage is different for different pods of the same service, seems like a bug. Something like `NOT SYNCED (X%)` would seem more appropriate in that case.

@costinm ^^^

**Comment by costinm** [comment]
Sorry, I am also not familiar with that code in istioctl. 
I worked on adding metrics for pilot events for prometheus/grafana - which I think is a good source of info about errors, and some of the endpoints that may be used by istioctl.

A bit busy with the installer - but I would guess it may be related to multiple replicas of the pilot ? Or is istioctl fetching from all pilots ?

**Comment by esnible** [comment]
@frankbu How about we remove the percentage from `SYNCED`?  Pilot could still report it through the `/debug` API, but `istioctl` wouldn't show it.  I seem to get at least one question a week from people who want to see 100%.

**Comment by frankbu** [comment]
@esnible I think it's fine to remove the % as long as @Stono's requirement is still covered some other way: https://github.com/istio/istio.io/issues/3853#issuecomment-481072899. I also wonder if there's a bug in the calculation that we don't want to lose track of.

**Comment by therealmitchconnors** [comment]
@costinm the istioctl code here is pretty thin.  It just calls /debug/syncz on every pilot instance and formats the output for the command line.  Can you think of any reason syncz would be reporting 50% synced?
