### ISSUE TITLE
hover over text bash,  scroll bar make the text invisible

### ISSUE THREAD

**Issue by zhongfox** [istio/istio.io#3861]
macOS 10.14.3 Chrome - Version 72.0.3626.121  (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/463772/55050930-26520b80-508e-11e9-8dd7-69e98122afcc.png)

after hover over the code block, the scroll bar show and cover the code
and remove mouse hover won't make text visible

### expected behaviour
the scroll bar should not cover text

**Comment by geeknoid** [comment]
I'm not able to repro this. Two questions:

- You say "after hover". Does that mean that when you load the page, the scroll bars are not initially visible and only show up after hover? For me, the scroll bars are visible as soon as the page is loaded. I'm also on a mac with Chrome.

- What are your browser's font defaults set to?

**Comment by geeknoid** [comment]
Ah, I can repro now. macOS has a setting to control whether scroll bars are displayed always or only on hover. When I flipped to "only on hover", I see the same problem as you reported.

I would put this as a bug in Chrome then. I don't control the height of the text boxes, beyond setting a maximum height of 32 lines visible. Hopefully, I can find a workaround.

**Comment by geeknoid** [comment]
Yeah, a Chrome bug. It doesn't happen in Safari, and it doesn't happen with the vertical scroll bar. When the vertical scroll bar is needed, it shows up and then disappears when you're done. But the horizontal scroll bar stays permanently once displayed.

**Comment by geeknoid** [comment]
And confirmation: https://meta.stackexchange.com/questions/321136/cannot-dismiss-scrollbar-in-code-box-blocks-view

**Comment by zhongfox** [comment]
I see, I changed "scroll bar behavior"  to "always" and fixed this.
Thanks for your work @geeknoid

**Comment by zgfh** [comment]
@zhongfox I have same problem, how to changed ?

**Comment by zgfh** [comment]
@geeknoid should we add one more blank line to work around?

**Comment by zgfh** [comment]
it work,how to change:
mac: System Preferences. (Look in General or search for scroll bar behavior.)
mac的 系统偏好设置->通用->显示滚动条，选择始终
![image](https://user-images.githubusercontent.com/11729624/60571098-80f1b680-9da5-11e9-8dde-bae25be7fef3.png)
