### ISSUE TITLE
Release notes 1.1 missing egress traffic policy change

### ISSUE THREAD

**Issue by sdaschner** [istio/istio.io#3904]
[1.1 Upgrade Notice](https://istio.io/docs/setup/kubernetes/upgrade/notice/) describes the change in the egress policy, which now defaults to `ALLOW_ANY`.

I originally only read the [1.1 Release Notes](https://istio.io/about/notes/1.1/) and was missing a description of that feature / change entirely. Is it there and I'm just failing to see it on that page? IMO users should be made aware of the egress behavior change, on that page, since the behavior differs from previous Istio versions.

Edit: _If_ that is what is meant by **Policy Checks Off By Default**, then we should make it clearer what implications that has for the users (no need for dedicated `ServiceEntry`s).

**Comment by vadimeisenbergibm** [comment]
cc @linsun @frankbu

**Comment by frankbu** [comment]
The release notes do include an [upgrades section](https://istio.io/about/notes/1.1/#upgrades) that points to the upgrade notice, which covers the (breaking) changes from 1.x.

Maybe this doesn't indicate clearly enough that the 1.1 release includes 2 sets of changes, new features and breaking changes? @sdaschner Would saying something like this at the very top of the release notes have helped?

**Comment by linsun** [comment]
good point, I think it was there then got removed/moved to upgrade section.  I agree we should have it in release note as it impacts new users as well.

**Comment by sdaschner** [comment]
@frankbu Yes, that would be helpful to at least make the users somehow aware of it. I've just discovered the upgrades section as well, but somehow didn't see it before (and that may happen to someone else as well...).

**Comment by frankbu** [comment]
Fixed by #3930
