### ISSUE TITLE
scripts/Dockerfile fails to build

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#3917]
Gives error:

```
ERROR: unsatisfiable constraints:
  gnu-libiconv (missing):
    required by: world[gnu-libiconv]
```

I removed the line installing this and later got an error saying npm was not found

**Comment by geeknoid** [comment]
I just fixed that this weekend. Could you rebase and try again please?

I've rebuilt the image a couple times in the last few days, so I do know it grossly works :-)

**Comment by howardjohn** [comment]
Looks like only on 1.1 branch which is why I missed it. 1.1 branch seems to work

**Comment by geeknoid** [comment]
Yeah, this will be merged to master on April 20. So I'm closing this issue.
