### ISSUE TITLE
Callout looks strange in 1.1 blogpost

### ISSUE THREAD

**Issue by aackerman** [istio/istio.io#3932]
https://istio.io/blog/2019/announcing-1.1/

<img width="1680" alt="Screen Shot 2019-04-03 at 6 24 25 PM" src="https://user-images.githubusercontent.com/786640/55519527-d353f780-563d-11e9-85ee-38702bb52b7a.png">

You can see in the attached image, the callout is strangely sized and the warning icon is breaking outside the bounds. This is desktop chrome 72.0.3626.121 on macOS.

**Comment by geeknoid** [comment]
All callouts have the icon 1/2 out of the box, that's a purposeful design element. As for the size, I think its inline with all the other callouts. So what do you mean by strangely sized? Too big, too small, vertically, horizontally?

BTW, you can go to istio.io/test/callouts to see a bunch of test cases...

**Comment by aackerman** [comment]
@geeknoid just that I would expect it to be the full width of the paragraphs on the page instead of the width of the text inside the callout. 

Generally the composition of the screen looked broken when I was looking at this, the icon 1/2 out of the box, the box wasn't the width of the paragraphs and the "Download 1.1" and "1.1 Release Notes" buttons looked to me like they were supposed to be in the box and were somehow escaping the bounds.

Overall minor issues, and if this is the way they are supposed to be we can go ahead and close this issue, but I wanted to share my impressions.

**Comment by geeknoid** [comment]
This is now much nicer. The callouts aren't there anymore, and you instead get a popup when you click on the download button.
