### ISSUE TITLE
active health check doc is wrong

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#3933]
reported by our user:  https://discuss.istio.io/t/active-health-checking/1685

also confirmed on slack networking channel that it is not correct.  We don't support envoy active health check.  We rely on users to provide health check (liveness prob) in their pod.

**Comment by linsun** [comment]
@frankbu could you take this?

**Comment by frankbu** [comment]
Related issue: https://github.com/istio/istio/issues/10537

**Comment by frankbu** [comment]
Fixed as part of #4321

**Comment by frankbu** [comment]
Closing as it's fixed in #4321
