### ISSUE TITLE
Issue with help/ops/misc/index.md

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#3943]
By following section "Verifying connectivity to Istio Pilot", I found there is not "curl" in the ingressgateway, I also can not find curl in any folder, thanks,

**Comment by frankbu** [comment]
@hobbytp What version of Istio are you using? I just tried it with Istio 1.1.3, and the curl command is available and working as documented.

**Comment by hobbytp** [comment]
Sorry, it is my fault, the curl command is available, please close this issue.
