### ISSUE TITLE
istio-demo.yaml and istio.yaml are missing

### ISSUE THREAD

**Issue by viktorpeacock** [istio/istio.io#3946]
https://github.com/istio/istio/releases/download/1.1.1/istio-1.1.1-win.zip release does not contain yaml files referenced in the setup guide. I cannot progress with the setup.

**Comment by sdake** [comment]
On mobile atm but this sounds like a test and release issue.

@utka?

**Comment by utka** [comment]
Look under istio-1.1.1/install/kubernetes/istio-demo.yaml
From https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#disabling-or-updating-the-webhook
To create istio.yaml run helm template, for example:
helm template --namespace=istio-system --set sidecarInjectorWebhook.enabled=false install/kubernetes/helm/istio > istio.yaml

If it does not help, which setup guide are you looking at?

**Comment by sdake** [comment]
Note when you unzip or untar a version of istio, it is placed in `istio-${VERSION}`.  I suppose the documentation strongly assumes the reader is aware of this.

Looking at the win zip file specifically, it does contain the correct file:

```
sdake@beast-01:~/r112-win$ curl -L https://github.com/istio/istio/releases/download/1.1.2/istio-1.1.2-win.zip -o istio-1.1.2-win.zip
sdake@beast-01:~/r112-win$ unzip istio*
Archive:  istio-1.1.2-win.zip
   creating: istio-1.1.2/
  inflating: istio-1.1.2/README.md   
<... stuff deleted ...>
sdake@beast-01:~/r112-win/istio-1.1.2/install/kubernetes$ ls
ansible                            istio-citadel-plugin-certs.yaml       istio-demo-auth.yaml  namespace.yaml
global-default-sidecar-scope.yaml  istio-citadel-standalone.yaml         istio-demo.yaml       README.md
helm                               istio-citadel-with-health-check.yaml  mesh-expansion.yaml
sdake@beast-01:~/r112-win/istio-1.1.2/install/kubernetes$ pwd
```
As can be seen, the `install/kubernetes/istio-demo.yaml` file is present.

**Comment by viktorpeacock** [comment]
Hello, 

I've downloaded the files again and it's all there. Not sure what happened. Attaching screen of an extract from 05/04/2019. 
![image](https://user-images.githubusercontent.com/44648849/55863011-92923c00-5b71-11e9-959c-4d264aed9e2b.png)

**Comment by sdake** [comment]
@viktorpeacock good to hear things are sorted out.

I'll close this issue now.  If you believe this issue was closed in error, please feel free to reopen.

Cheers
-steve

**Comment by koulf** [comment]
istio-demo.yaml file, not present in any of the install asset files (https://github.com/istio/istio/releases/tag/1.9.7)
