### ISSUE TITLE
Fix Istio release page

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio.io#3969]
In the [Release notes](https://istio.io/about/notes/). There is an Istio 1.0.7, which is duplicated from Istio 1.1.2, and it appears above Istio 1.1.2.

**Comment by pitlv2109** [comment]
Not sure if this is related https://github.com/istio/istio/issues/13176

**Comment by howardjohn** [comment]
There is an Istio 1.0.7 that was released and has the same change as 1.1.2 so it has the same description.  I think this is working as intended.

**Comment by pitlv2109** [comment]
Thanks. If that's the case, /close
