### ISSUE TITLE
`{{< text bash json >}}` rendering incorrectly in master branch

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio.io#3985]
The `"` becomes `&quot;`, broken in master branch: https://preliminary.istio.io/about/contribute/creating-and-editing-pages/#command-lines

Work in 1.1 branch: https://istio.io/about/contribute/creating-and-editing-pages/#command-lines

**Comment by geeknoid** [comment]
This'll get fixed when 1.1 is merged into master next week.

**Comment by geeknoid** [comment]
Merge happened, so closing.
