### ISSUE TITLE
Tabs CSS is confusing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#3992]
Example: https://istio.io/docs/setup/kubernetes/install/kubernetes/

I find the tabs to be really confusing, specifically understanding which tab is selected. The unselected one has a shadow making it seem like it is in the foreground and is active, when it is actually the opposite

**Comment by rvennam** [comment]
I think it's a bit better, but still difficult to identify which tab is selected:
![image](https://user-images.githubusercontent.com/5502967/56298764-bcfb7080-6100-11e9-8024-1d9dfc5dc2dd.png)

I think this is worth tapping a visual designer for input.

**Comment by howardjohn** [comment]
Mine has some purple color (using chrome)

**Comment by rvennam** [comment]
thoughts on adding a border-bottom on the selected button?
![image](https://user-images.githubusercontent.com/5502967/56299463-131ce380-6102-11e9-8d7d-34f5a23f4f10.png)

**Comment by geeknoid** [comment]
@rvennam What browser are you using? With Chrome, Safari, and Firefox, the selected tab is highlighted as seen here:

<img width="331" alt="Screen Shot 2019-04-18 at 14 21 06" src="https://user-images.githubusercontent.com/22780957/56392110-5f8d1f80-61e5-11e9-9a90-718481fff404.png">

**Comment by SpencerReynolds18** [comment]
@geeknoid it isn't a problem when there are 3 tabs in view because you can see which is the odd one out. When only showing 2, it is not clear. Take a look at the example of a common mistake with tabs given here under number 5 (it matches this scenario exactly): https://www.nngroup.com/articles/tabs-used-right/

**Comment by geeknoid** [comment]
I thought the triple-whamy of

1) different background color
2) different text color
3) thick underline

would be sufficient, while still not being too jarring. But if someone with
an eye for design can suggest some improvements, I'll be happy to
incorporate 'em.

**Comment by rvennam** [comment]
How does this look? I can send a PR if you like it
2 tabs:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/5502967/64735682-a9d1ae80-d4ae-11e9-9c7e-3fe7b3d462ff.png">

3 tabs:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/5502967/64735801-e69da580-d4ae-11e9-8461-22f1244fe0c5.png">

**Comment by geeknoid** [comment]
I find that considerably harder to distinguish personally, as you've removed the special coloring and underline.

@frankbu has definite opinions about this as well.

**Comment by rvennam** [comment]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/5502967/65184846-5f16e000-da34-11e9-9ddf-3bbff81e13a0.png">
