### ISSUE TITLE
Issue with docs/tasks/security/authn-policy/index.md

### ISSUE THREAD

**Issue by yanivroz** [istio/istio.io#4016]
in "Cleanup part 1" section I see 2 problems.
1. the `default` `DestinationRule` which was created in part 1 is not being deleted.
2. the `default` `MeshPolicy` which existed before part 1 is being deleted. (it should have been returned to `mode: PERMISSIVE` as it was prior to part 1

**Comment by sushicw** [comment]
The first part is fixed in master / 1.2 by https://github.com/istio/istio.io/issues/4410
