### ISSUE TITLE
Issue with docs/examples/advanced-gateways/egress-gateway/index.md

### ISSUE THREAD

**Issue by zuxahiz** [istio/istio.io#4024]
When doing with example "Configure an Egress Gateway" with mtls enabled, I found that after applying DestinationRule: egressgateway-for-cnn, the tls-check between sleep pod is failed:
```
$ istioctl authn tls-check sleep-57f9d6fd6b-7w2sw istio-egressgateway.istio-system.svc.cluster.local
HOST:PORT                                                 STATUS       SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
istio-egressgateway.istio-system.svc.cluster.local:80     CONFLICT     mTLS       HTTP       default/         egressgateway-for-cnn/default
```

It seems that after applying DestinationRule: egressgateway-for-cnn, the mtls on the egressgateway side is set to disabled infact.
Has someone face the same problem or you can give some advises on debugging?
https://istio.io/docs/examples/advanced-gateways/egress-gateway/#egress-gateway-for-http-traffic

**Comment by vadimeisenbergibm** [comment]
The conflicting cluster is not used, another cluster is used to communicate with the egress gateway service and that cluster has mTLS enabled. In any case, I fixed the documentation so `istiocl authn tis-check` will not complain.

```
istioctl authn tls-check $SOURCE_POD istio-egressgateway.istio-system.svc.cluster.local
HOST:PORT                                                 STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
istio-egressgateway.istio-system.svc.cluster.local:80     OK         mTLS       mTLS       default/         egressgateway-for-cnn/default
```

**Comment by zuxahiz** [comment]
@vadimeisenbergibm Thanks for your quick response! This problem has been solved.

But I still have something unclear: Sometimes I found it doesn't work and got a "**_HTTP/1.1 503 Service Unavailable_**" error. That means if you combine those commands into a script and execute it many times, it will fail sometimes. 
Due to my limited knowledge of mtls, I am not sure if is because of the cleanup procedure don't  sweep all the configuration of this example, or mtls connection don't closed before re-connection? 
Also I noticed that the second response from "http://edition.cnn.com/politics" is "**_HTTP/2 200_**" now, rather than "**_HTTP/1.1 200 OK_**", maybe the website has upgrade their http version to http2. The docs may need to change. And do you think it will influence the above matter?

**Comment by vadimeisenbergibm** [comment]
@zuxahiz What you are saying is that when you execute the commands in a script, you get 503 errors? I do not know why it happens, I would try to add `sleep` commands to the script, to let the Istio configuration be propagated. Note that it takes some time from the defining an Istio artifact, for example a VirtualService, to propagate into the sidecars. I guess it is a general Istio mode of work, not related to this specific issue.

Regarding the output of curl, I do not think it is very important and must be updated. The output is given as an example output, and the important part there is the status code 200. The protocol version is irrelevant to the example.

**Comment by zuxahiz** [comment]
@vadimeisenbergibm Thanks for your explanation, it turns out the reason why the case is sometimes got 503 error is because of the resources quota is not enough in my environment, after increasing the cpu and memory limit, the case is ok now.
I think you are right and thanks for your patiences and efforts.
