### ISSUE TITLE
`https://git.io/getIstio` returns 404

### ISSUE THREAD

**Issue by abelsromero** [istio/istio.io#4041]
The installation method piping curl + bash proposed in https://istio-releases.github.io/v0.1/docs/tasks/installing-istio.html#installation-steps does not work because the url returns 404.

Should it be `https://git.io/getLatestIstio`?

**Comment by geeknoid** [comment]
$ curl -L https://git.io/getLatestIstio | ISTIO_VERSION=X.Y.Z sh

Should work, where X.Y.Z is the full version number. In your case that would be 0.1.0.
