### ISSUE TITLE
Issue with docs/setup/kubernetes/install/kubernetes/index.md

### ISSUE THREAD

**Issue by mukundha** [istio/istio.io#4064]
Is Installation Step 1 specified on the page really needed?
```$ for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done```

look like `install/kubernetes/istio-demo.yaml` already includes all the CRDs

**Comment by frankbu** [comment]
Closing as this is a duplicate of #3993
