### ISSUE TITLE
bookinfo curl blank

### ISSUE THREAD

**Issue by joshuacox** [istio/istio.io#4068]
After installing istio on a minikube cluster, and then following the directions [here](https://istio.io/docs/examples/bookinfo/) and then [here](https://istio.io/docs/tasks/traffic-management/ingress/#determining-the-ingress-ip-and-ports)  I get:

```
$ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
details-v1-79c6548b59-qh2fr      2/2     Running   0          16m
productpage-v1-95d579cd5-sgn8p   2/2     Running   0          16m
ratings-v1-7665579b75-5b5rh      2/2     Running   0          16m
reviews-v1-67446f7d9b-p4nxn      2/2     Running   0          16m
reviews-v2-6bc7b4f678-jtxx7      2/2     Running   0          16m
reviews-v3-59b5b6948-6bdwd       2/2     Running   0          16m
$ kubectl label namespace default istio-injection=enabled
error: 'istio-injection' already has a value (enabled), and --overwrite is false
$ kubectl get gateway
NAME               AGE
bookinfo-gateway   10m
$ export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}')
$ export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
$ export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
$ echo $GATEWAY_URL
192.168.99.104:31380
$ kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage | grep -o "<title>.*</title>"
<title>Simple Bookstore App</title>
$ curl -s http://${GATEWAY_URL}/productpage | grep -o "<title>.*</title>"
$ curl -s http://${GATEWAY_URL}/productpage
```

notice the `kubectl exec` statement returns the `<title>` block, but neither curl statement returns anything.

I get the same results when duplicating the same steps on a full running multinode cluster.  Is something amiss?

Of note, I have a forum topic on this as well [here](https://discuss.istio.io/t/bookinfo-curl-is-blank/2072).  However, I do believe this is a bug in the documentation, there are some inconsistencies, for example the [before you begin](https://istio.io/docs/examples/integrating-vms/#before-you-begin) lists:

1. Deploy the Bookinfo sample application (in the bookinfo namespace).

But the bookinfo app at the end of the [example](https://istio.io/docs/examples/bookinfo/) is running in the 'default' namespace not the 'bookinfo' namespace.  I think I've accounted for that, but I still get no curl from above, and I've duplicated the steps on multiple fresh clusters (both minikube and full multinode baremetal clusters).  Consistently I am left with the `kubectl exec` statement working, but none of the external curls.

If I follow the [cert-manager](https://istio.io/docs/examples/advanced-gateways/ingress-certmgr/) guide I have no problem curl'ing the 'hello' service through the gateway.  So I am at a loss for what is wrong.

**Comment by joshuacox** [comment]
My installation script was written around the [cert-manager guide](https://istio.io/docs/examples/advanced-gateways/ingress-certmgr/) and looks like this:

```
    helm install \
      --name=istio \
      --namespace=istio-system \
      --set gateways.istio-ingressgateway.sds.enabled=true \
      --set gateways.istio-ingressgateway.loadBalancerIP=$LOAD_BALANCER_IP
      $LOAD_BALANCER_IP_SET \
      --set global.k8sIngress.enabled=true \
      --set global.k8sIngress.enableHttps=true \
      --set global.k8sIngress.gatewayName=ingressgateway \
      --set certmanager.enabled=true \
      --set certmanager.email=$LETSENCRYPT_EMAIL \
      istio
```

would any of that conflict with what is going on in the bookinfo example?  On the fresh clusters I have not performed any of the cert-manager steps, only the helm install is changed as included above.

**Comment by Tushar120120** [comment]
Do you have external load balance? if not, you can change the bookinfo.yaml file like below and try to access the 30105 (NodePort). 

spec:
  ports:
  - port: 9080
    name: http
    nodePort: 30105
  type: NodePort 
  selector:
    app: productpage

**Comment by joshuacox** [comment]
@Tushar120120 I do have metallb as external load balancer on the bare metal clusters, 

On the nodeport something is wrong on that:

```
error: error validating "/tmp/bookinfo.yaml": error validating data: ValidationError(Service.spec.ports[0]): unknown field "type" in io.k8s.api.core.v1.ServicePort; if you choose to ignore these errors, turn validation off with --validate=false
```

Regardless, that does not fix the issue that istio does not appear to be routing to my service.

**Comment by joshuacox** [comment]
Adding a bunch of yaml data [here](https://gist.github.com/joshuacox/7a7d7fbdc52dd2710deb693987d96a07)

**Comment by frankbu** [comment]
It looks like you have 2 conflicting Gateway configs, `bookinfo-gateway` and `istio-autogenerated-k8s-ingress`. Both of them are configured to handle any host (that is, host `*`). The `bookinfo-gateway` is the simple Gateway used for the bookinfo app. The second one, I'm guessing has been created because you have ingress enabled:
```
      --set global.k8sIngress.enabled=true \
      --set global.k8sIngress.enableHttps=true \
      --set global.k8sIngress.gatewayName=ingressgateway \
```
If you remove the k8s-ingress one, I'm guessing the bookinfo gateway will start working.

**Comment by joshuacox** [comment]
@frankbu tyvm good spot, that was it.

```
 kubectl delete gateway -n istio-system istio-autogenerated-k8s-ingress
```

now the curl works properly:

```
 curl -s http://${GATEWAY_URL}/productpage |grep title
    <title>Simple Bookstore App</title>
        <h4 class="modal-title">Please sign in</h4>
```

Closing, all good here.
