### ISSUE TITLE
Issue with docs/tasks/traffic-management/egress/index.md

### ISSUE THREAD

**Issue by zuxahiz** [istio/istio.io#4127]
Hi experts,
when exec the command in [Configuring the proxy bypass](https://istio.io/docs/tasks/traffic-management/egress/#configuring-the-proxy-bypass) :
```
helm template install/kubernetes/helm/istio <the flags you used to install Istio> --set global.proxy.includeIPRanges="10.0.0.1/24" -x templates/sidecar-injector-configmap.yaml | kubectl apply -f -
```
it didn't have a `-n NAMESPACE` param, and will create a new istio-sidecar-injector configmap in default namespace. While istio is installed in istio-system namespace default, I thinks maybe add a  `-n istio-system` param is what we really needed?
Please help to check, thanks.

**Comment by frankbu** [comment]
The configmap should get installed in the `istio-system` namespace. Notice the namespace is set to `Release.Namespace` in the [template](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml).

@zuxahiz Did you try it and it did not work? Did you set `<the flags you used to install Istio>` correctly?

**Comment by zuxahiz** [comment]
> The configmap should get installed in the `istio-system` namespace. Notice the namespace is set to `Release.Namespace` in the [template](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml).
> 
> @zuxahiz Did you try it and it did not work? Did you set `<the flags you used to install Istio>` correctly?

Hi @frankbu , do you mean that I should add a param in helm template, just like "--set xxxxx=xxxx"? But I didn't find a param related to Release.Namespace in [Installation Options](https://istio.io/docs/reference/config/installation-options/), or add `-n istio-system` manually? what should I do?
