### ISSUE TITLE
Kiali instructions for jaeger URL don't work when installing Jaeger with Istio

### ISSUE THREAD

**Issue by adinunzio84** [istio/istio.io#4146]
Looking at ["Visualizing Your Mesh"](https://istio.io/docs/tasks/telemetry/kiali/#install-via-helm), the instructions mention what to do if you already have Jaeger / Grafana installed. If I try to extend this to install both with Istio like this:
```
helm template \
    --set tracing.enabled=true \
    --set grafana.enabled=true \
    --set kiali.enabled=true \
    --set "kiali.dashboard.jaegerURL=http://jaeger-query:16686" \
    --set "kiali.dashboard.grafanaURL=http://grafana:3000" \
    install/kubernetes/helm/istio \
    --name istio --namespace istio-system > istio.yaml
```
the URLs don't seem to work (Kiali page fails to load the "distributed traces" page when doing a query). This was done when port-forwarding to Kiali.

Looking at an [abandoned PR](https://github.com/istio/istio.io/pull/3669/files), it mentions that this is conditional on the services being accessible by client browsers. But the URLs given in the example look like Kubernetes ClusterIP services that are created by Istio, so I figured somehow Kiali rendered this server-side so the client browser did not need access to these services directly.

This might also apply for Grafana, but I only looked at the traces, since I did not see the link to Grafana in the Metrics page within Kiali that was mentioned elsewhere.

**Comment by douglas-reid** [comment]
@jmazzitelli can you take a look?

**Comment by jmazzitelli** [comment]
> onditional on the services being accessible by client browsers. But the URLs given in the example look like Kubernetes ClusterIP services that are created by Istio, so I figured somehow Kiali rendered this server-side so the client browser did not need access to these services directly.

Yes, those were just example URLs - but for sure, these URLs *must* be client-accessible. Kiali does nothing server-side to make them renderable on the client - the URLs themselves must be exposed and accessible to client browsers for this to work. So, if on OpenShift for example, create a route for Jaeger and use the route URL. For Kubernetes you would have to do something (ingress perhaps) to expose Jaeger and Grafana.

Note: in a future Kiali version, these URLs are going to be attempted to be auto-discovered by Kiali if you are on OpenShift so the onus won't be on the user to do this at install time for OS. See [this PR](https://github.com/kiali/kiali/pull/1022). We haven't figured out a good way to auto-discover these for Kubernetes environments - we would be interested in community submissions for that capability.

> This might also apply for Grafana, but I only looked at the traces, since I did not see the link to Grafana in the Metrics page within Kiali

Right the Grafana URL is not set or seems invalid, Kiali hides the Grafana links from the user. That's probably why you didn't see them.

The workaround today is - after Kiali has been installed by helm and you have exposed Jaeger and Grafana, you can edit the Kiali configmap and put the correct URLs in there, then restart the kiali pod.

**Comment by adinunzio84** [comment]
Okay thanks for the info. I think this can be closed then. I was just a bit confused since it sort-of seemed like I could use the service names and it would work with the ClusterIP services.

**Comment by pawelprazak** [comment]
Problem I see is the query:
```
/search?end=1564484796369000&limit=20&lookback=3600&maxDuration=&minDuration=&service=istio-ingressgateway.istio-system&start=1564481196369000&uiEmbed=v0
```
vs
```
/search?end=1564477736142000&limit=20&lookback=1h&maxDuration&minDuration&service=istio-ingressgateway&start=1564474136142000
```

If I change `service=istio-ingressgateway.istio-system` to `service=istio-ingressgateway` it works.

Kiali `v0.21`
Jaeger `1.9`
Istio `1.2.2`

**Comment by nvprasad2003** [comment]
Hi..

I am trying  Istio deployment in our new kubernetes cluster with helm template and heml/tiller but istio inbuild grafana and jaeger not working.

since we are using nodeport and want to utilize inbuild grafana and jaeger do you recommend to modify the config map file as per above port by Mr.pawelprazak.

 getting message in kiali 

grafana URL is not set in Kiali configuration
Jaeger URL is not set in Kiali configuration

existing versions are : 
Istio
1.3.0
Prometheus
2.8.0
Kubernetes
v1.15.1
GrafanaURL
undefined
JaegerURL
undefined
Kiali-ui
1.4.2 (991840f85af4586b0dc98970051f55318f22ac73)
Kiali
v1.4.2 (3e5b0da9f58862532baa2c88ccdc4a12728c2ff7)

**Comment by huegelc** [comment]
Same issue here with istio 1.3.1 and Kiali 1.4.2
