### ISSUE TITLE
Docs should include additional caveats around sidecar injection

### ISSUE THREAD

**Issue by Niksko** [istio/istio.io#4253]
Docs for sidecar injection should mention the following two caveats:
* Sidecar injection seems to be impossible in `kube-system` and `public` namespaces, as per the declaration of `ignoredNamespaces` [here](https://github.com/istio/istio/blob/13cb3422ae47f95dfbc829a327724a56929cab3b/pilot/pkg/kube/inject/initializer.go#L28) and the call to `injectRequired` [here](https://github.com/istio/istio/blob/13cb3422ae47f95dfbc829a327724a56929cab3b/pilot/pkg/kube/inject/webhook.go#L558).
* Sidecar injection doesn't work for pods on the host network, as per code [here](https://github.com/istio/istio/blob/13cb3422ae47f95dfbc829a327724a56929cab3b/pilot/pkg/kube/inject/inject.go#L403)

Both these facts seem to be undocumented. Happy to provide a PR tomorrow.

**Comment by linsun** [comment]
Yes, please submit a PR for this, good catch!
