### ISSUE TITLE
i18n: using Crowdin

### ISSUE THREAD

**Issue by amorist** [istio/istio.io#4257]
### Crowdin Integration Features
* Syncing a repo with Crowdin via their [Github integration process](https://support.crowdin.com/github-integration/)
* Syncing and managing l10n project resources directly with the [Crowdin CLI interface](https://support.crowdin.com/cli-tool/)

### Crowdin l10n Features
* [In-context translation for web apps](https://support.crowdin.com/in-context-localization/)
   - Translation can be done by selecting an app's text in the UI, and live translating it directly.
* [Proofreading & voting of translations](https://support.crowdin.com/online-editor/#proofreadingvoting-mode)
  - Translations can be proofread and/or voted on by project peers before being approved.

### Electron use cases we can learn from
* API translation: The Electron [i18n repo](https://github.com/electron/i18n) pulls markdown files in from their API docs for translation.
* A [crowdin.yaml](https://github.com/electron/i18n/blob/master/crowdin.yml) file is maintained to map source files to their translation location.
* Crowdin uses a yaml file as well to map to the source and target resources it needs to manage. In theory you should be able to manage that with git, however at this point in time it must be [generated and added](https://support.crowdin.com/configuration-file/#introduction) within a Crowdin project itself.
* l10n project resources live under a directory labeled by their associated [ISO standard locale code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

**Comment by geeknoid** [comment]
Sorry I closed this issue, but it look like an advertisement.

If I understand correctly, this is a suggestion that the translation process switches to use Crowdin?

**Comment by amorist** [comment]
You're right. 
sorry, I did not describe it clearly.

**Comment by amorist** [comment]
Electrojs successfully used Crowdin for multilingual translation. 
https://electronjs.org/languages
https://github.com/electron/i18n
