### ISSUE TITLE
CRD Backup command fails on mac OS

### ISSUE THREAD

**Issue by oresot** [istio/istio.io#4258]
The command used shown here to backup CRD data https://istio.io/docs/setup/kubernetes/upgrade/steps/#control-plane-upgrade doesn't work on mac OS:

```
➜ kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | cut -f1-1 -d "." | xargs -n1 -i sh -c "kubectl get --all-namespaces -oyaml {}; echo ---" > $HOME/ISTIO_1_0_RESTORE_CRD_DATA.yaml

xargs: illegal option -- i
```

The `-i` option in xargs is deprecated in favour of `-I`: https://www.gnu.org/software/findutils/manual/html_node/find_html/xargs-options.html

Using the replace argument as `-I{}` works, and should work in other environments as well.

This one worked for me:

```
kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | cut -f1-1 -d "." | xargs -n1 -I{} sh -c "kubectl get --all-namespaces -oyaml {}; echo ---" > $HOME/ISTIO_1_0_RESTORE_CRD_DATA.yaml
```

**Comment by sdake** [comment]
@oresot thank you for the report.  I have submitted PR: https://github.com/istio/istio.io/pull/4290 to resolve this problem.

Thanks again!

Cheers
-steve

**Comment by sdake** [comment]
resolved, closing.
