### ISSUE TITLE
Missing 1.1 -> 1.2 upgrade notice

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#4259]
For 1.0 -> 1.1 we have a upgrade document listing the changes that are backwards incompatible at https://preliminary.istio.io/docs/setup/kubernetes/upgrade/notice/

We do not have this for 1.1 -> 1.2

**Comment by sdake** [comment]
@howardjohn - I'll add to the wg leads agenda meeting to produce this list.  I am not entirely aware of all the breaking changes that have been made in the 1.2 cycle.

We need better process tracking of these changes so this list can be automatically generated from the git repo.

Cheers
-steve

**Comment by geeknoid** [comment]
Can we address this issue today? This is a P0 blocking the 1.2 release which is planned for tomorrow.

**Comment by linsun** [comment]
I don't think we need an upgrade notice for 1.2 given the changes are very minimal.  The only breaking change I'm aware of is:

- **Removed** deprecated Adapter and Template CRDs by default. Configure `mixer.templates.useTemplateCRDs=true` and `mixer.adapters.useAdapterCRDs=true` to re-enable them.

**Comment by sdake** [comment]
Hi folks.  I was out most of yesterday.  I will address the two remaining PRs I have today.  I agree with @linsun - we can keep this page and just state there aren't many breaking changes.  Istio 1.2 was a 3 month cycle, Istio 1.1 was a 9+ month cycle, and Istio 1.2's main focus was on quality.

I do want to keep the structure in place for future revisions when we will likely have breaking changes.

Cheers
-steve

**Comment by linsun** [comment]
That is fine to keep the structure @sdake!  Let me know if you found other breaking changes!   Thanks.

**Comment by sdake** [comment]
reading the release notes, I don't notice anything beyond the useCRD thing for telemtry, and I don't understand why we even kept that :)

**Comment by sdake** [comment]
https://github.com/istio/istio.io/pull/4471#issuecomment-503131088
