### ISSUE TITLE
Missing 1.1 -> 1.2 upgrade steps

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#4260]
https://preliminary.istio.io/docs/setup/kubernetes/upgrade/steps/ refers to the steps to upgrade to 1.1, but we don't have any information on upgrading to 1.2

**Comment by sdake** [comment]
@howardjohn workflow should be the same - but needs verification.  I'm not convinced the upgrade gate is or was working correctly in all cases - hence a manual verification would make sense.

Can you take this on?

**Comment by howardjohn** [comment]
Related to https://github.com/istio/istio/issues/14630

**Comment by geeknoid** [comment]
Can we address this issue today? This is a P0 blocking the 1.2 release which is planned for tomorrow.

**Comment by linsun** [comment]
@sdake @howardjohn I went through the install options for 1.2 that @johnma14 produced today and believe there isn't much we should highlight other than:

 **Removed** deprecated Adapter and Template CRDs by default. Configure `mixer.templates.useTemplateCRDs=true` and `mixer.adapters.useAdapterCRDs=true` to re-enable them.

I don't think we should make a huge deal of upgrade in 1.2 given the breaking change is very minimal, primarily this one.  WDYT?

**Comment by howardjohn** [comment]
Agree, just what you have above and then keep the generic upgrade docs

**Comment by sdake** [comment]
@geeknoid addressing now.  I was out yesterday.

Cheers
-steve
