### ISSUE TITLE
Missing documentation for alpha istio/installer

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#4261]
We have some docs in https://github.com/istio/installer but that have not been ported to istio.io. This is an alpha feature so lower priority than other

**Comment by howardjohn** [comment]
There is some in the README and also the wiki https://github.com/istio/installer/wiki/

**Comment by sdake** [comment]
@howardjohn I believe in the leads meeting, we determined documentation of the next-gen installer can happen after the 1.2 deadline, although it would be helpful if individuals continued work on the next-gen installer - including documentation.
