### ISSUE TITLE
Move tab completion to a separate page

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#4267]
In our get started page now (https://preliminary.istio.io/docs/setup/kubernetes/getting-started/#enabling-istioctl-tab-completion), we spent over half of that page providing steps for tab completion.  This is not appropriate because tab completion is an optional config for istioctl.

We have decided on #docs that we should move this to More guides and add a link from get started page to link to it.  @frankbu suggested `Add a step 4 in the downloading the release section with a link would be nice: `4. If  you are using Bash or ZSH, [enable istioctl tab completion](link)``And ideally, user would like tabs for tab completion, like kubectl's

https://kubernetes.io/docs/tasks/tools/install-kubectl/#optional-kubectl-configurations

**Comment by linsun** [comment]
cc @ericvn @rcaballeromx

**Comment by linsun** [comment]
@frankbu if you think more guides is not the right home, can you suggest a place?

**Comment by linsun** [comment]
@ibm-jason while you are in there, i found the copied content is wrong, e.g. 

```
$ source < _istioctl

```

**Comment by frankbu** [comment]
How about here: https://preliminary.istio.io/docs/ops/setup/

**Comment by frankbu** [comment]
Ideally, we would have some kind of istioctl overview doc, that this would be part of. Right now all we have is the generated istioctl reference doc.

**Comment by frankbu** [comment]
This is fixed
