### ISSUE TITLE
docs/setup/kubernetes/platform-setup/gke/ latest GKE version fails to create a cluster

### ISSUE THREAD

**Issue by gargnupur** [istio/istio.io#4269]
$ gcloud container clusters create <cluster-name> \
  --cluster-version latest \
  --num-nodes 4 \
  --zone <zone> \
  --project <project-id>

command fails to create a cluster in gke 1.12 version. 
Works fine in gke 1.11 version.
This could be because Client certificates were on by default in 1.11 versions but are not from 1.12 versions.
Following command works  for creating the cluster
$ gcloud container clusters create <cluster-name> \
  --cluster-version latest \
  --num-nodes 4 \
  --zone <zone> \
  --project <project-id>
 --issue-client-cerificate
But getting the clusterrolebingings fails later for the above cluster with the following error:

Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "client" cannot create resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope

**Comment by sushicw** [comment]
Hello,

Did you run `gcloud config set container/use_client_certificate True` as was included in the ["Preparing for Development" wiki?](https://github.com/istio/istio/wiki/Preparing-for-Development/3c48484bf318efc05dbb7ee93114f37e0e115a0b). 

The guidance to do that was out of date, and is no longer included in the [latest version](https://github.com/istio/istio/wiki/Preparing-for-Development/934dfb487ec5336da59d40a00bdb3475c15f99ac) of the wiki. 

If you go to `~/.config/gcloud/configurations/config_default` and remove or comment out `use_client_certificate = true`, does the cluster creation command work as expected for you?

**Comment by gargnupur** [comment]
I thought I had it set to False. But just tried again and it works. Closing the bug...

That is the reason why we have it to False in this script too: https://github.com/istio/istio/blob/master/tests/integration/create_cluster_gke.sh
Probably the cleanup step which sets it back to True is not needed anymore..

**Comment by sushicw** [comment]
It looks like the test script is making the (not necessarily true) assumption that use_client_certificate was set to True before it began, which means it's actually mutating the state outside of runs in an unexpected way. That seems worth fixing. I don't think we need to set the config setting at all, we can just pass the flag with False directly when we create the cluster.

Keeping the ball, I'll make this fix.

**Comment by sushicw** [comment]
Fix pushed.
