### ISSUE TITLE
[New Installer] Telemetry gateways page needs updating

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#4275]
With https://github.com/istio/installer/pull/225#pullrequestreview-246653540 we have moved telemetry to using native Istio Gateway's, so the page will be outdated for the new installer

**Comment by sdake** [comment]
for 1.2, we must document the old and new installer - its a whole lot easier if these have the same semantics.  We can remove the gateway ports in 1.3, so this doc work should happen after 1.2 branches.

**Comment by douglas-reid** [comment]
I'm a bit confused by the message in this issue. https://istio.io/docs/tasks/telemetry/gateways/ is all about using istio gateways.

**Comment by sdake** [comment]
@douglas-reid - understood.  If you take a deeper look at the installer PR, there is a strong desire not to expose the addon ports on the gateways by default (15029, 15030, 15032, etc).  The requested change would be to expose these int he telemetry gateway steps on an addon by addon basis, which AFAIK is not done as the steps currently expect the gateway to expose these ports by default.

We ended up approving the PR that reintroduced the ports, so this is a noop for 1.2 (to maintain backward compatibility) but should be addressed for the 1.3 cycle.

**Comment by linsun** [comment]
Note:  we still need the page for the default installer.  There is currently no doc of the new installer in istio.io so many folks won't be using it.

**Comment by sdake** [comment]
@linsun right - we are keeping intact the gateway ports in the new installer until such time as istio.io is updated relating to this issue (The PR has already merged that reintroduced these gateways).  This implies this page will also remain intact and unedited for 1.2.

I really think this change is 1.3 work, so this page won't be modified for 1.2.  We can refine the ingressgateway ports (and documentation) for 1.3 when the next gen installer is stabilized.
