### ISSUE TITLE
rendering of the main concepts section with the ops guide doesn't look good for people with 20/30 vision

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#4289]
I have ~20/30 corrected vision and must magnify chrome to display text at a reasonable size.

<img width="199" alt="Screen Shot 2019-06-07 at 8 52 20 PM" src="https://user-images.githubusercontent.com/755849/59141656-46435c80-8966-11e9-9801-b9fbf3503b8c.png">

https://preliminary.istio.io/docs/

One solution is to call the section "Operations".  Another is to magically set the font size depending on the scaling factor.  The first is easy.  I suspect there are capabilities to do the second, but I have no idea how to do so.

**Comment by geeknoid** [comment]
Ops Guide is another option.

Wouldn't magically tweaking the font size defeat the magnification you're explicitly doing through Chrome?

**Comment by geeknoid** [comment]
@frankbu @rcaballeromx I've noticed this same wrapping when Frank was presenting the other day. Should we rename to Ops Guide or Operations?

**Comment by sdake** [comment]
@geeknoid re tweaking the font size, I tweak the font size for the text - not the nav bar, although, for people with worse corrected or uncorrected vision, they may suffer from a difference accessibility problem with this approach.  A rename might be best.

Cheers
-steve

**Comment by frankbu** [comment]
I prefer `Operations` to `Ops Guide`. I also think the top level titles in the nav bar could be smaller, regardless. They seem to be using a bigger font than the section titles in the nav bar. I think they should all be the same.

**Comment by geeknoid** [comment]
Done.
