### ISSUE TITLE
Feedback for Getting Started page

### ISSUE THREAD

**Issue by rvennam** [istio/istio.io#4315]
Feedback for the new Getting Started page:
https://preliminary.istio.io/docs/setup/kubernetes/getting-started/

Assuming that this is the entry point for any new users getting started with Istio, I have some feedback for this page.

1. This page should not be verbose or provide users with too many options. This should be opinionated happy path install that targets majority of our users... installing and trying out istio on an existing vanilla k8s cluster.
2. The page starts off with too many distractions and complexities. Information about CNI, multi cluster, mesh expansion and sidecar injection guide before the user even downloads Istio is not necessary and intimidates the users - get them started quickly.
3. The page only has one main section - “Downloading the release” and then abruptly ends. What should they do next? Point them to, or merge content from “Quick Start Evaluation Install”. Again, if we want majority of new users to use the demo profile, then just have them install it on this page instead of moving them around.
4. After the Download / Install section, the user should be guided to perform some easy and “high value” tasks. For example: Request Routing and Visualizing Your Mesh
5. The “See also” section is mostly content that is completely irrelevant to the user at this step.

**Comment by frankbu** [comment]
Fixed by #4359
