### ISSUE TITLE
Feedback on tasks/multicluster/split-horizon-eds page

### ISSUE THREAD

**Issue by gargnupur** [istio/istio.io#4317]
Environment: Google Kubernetes Engine.
While running through this page, I had to switch on auto-scaling for cluster1 as pilot and telemetry pods didn't get scheduled because of insufficient memory and cpu. 

Should we mention this in the doc?

Autoscaling is not on by default in our cluster setup page in "docs/setup/kubernetes/platform-setup/gke/"

**Comment by duderino** [comment]
P0, but a minimal fix (e.g,. raise memory and cpu) would be totally cool
