### ISSUE TITLE
Fault Injection Task has incorrect suggestion for fixing the bug

### ISSUE THREAD

**Issue by bhaskar-reddy** [istio/istio.io#4332]
The suggestion at the end of the section _Fault Injection Task - Fixing the bug_ from URL: https://preliminary.istio.io/docs/tasks/traffic-management/fault-injection/#fixing-the-bug seems to be incorrect:

> However, you already have this fix running in v3 of the reviews service, so you can simply fix the problem by migrating all traffic to reviews:v3 as described in the traffic shifting task.

Applying `kubectl apply -f samples/bookinfo/networking/virtual-service-reviews-v3.yaml` based on above suggestion doesn't fix the previously induced problem.

**Comment by frankbu** [comment]
It does fix the bug by reducing the reviews->ratings timeout to 2.5 seconds, which is less than the 3 second timeout of the downstream productpage->reviews timeout. Therefore with reviews:v3 a delay of any amount less than 2.5 seconds (e.g., 2 seconds) should work as expected (e.g., return normally after the 2 second delay.

Thanks for pointing out the confusing wording. I'll add some text to the task to explain this more clearly.

**Comment by bhaskar-reddy** [comment]
Yeah, I agree that the wording is really confusing. Especially, when there is no way of knowing what reviews:v3 is doing that could be "fixing" the problem. Besides, there is no mention of decreasing the 7s delay induced to a certain number to be able to get through to a successful request.
