### ISSUE TITLE
Docs for "Install Istio on the Google Kubernetes Engine" should link to GKE's OSS Istio install docs

### ISSUE THREAD

**Issue by rlenglet** [istio/istio.io#4337]
**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

The [Install Istio on the Google Kubernetes Engine](https://preliminary.istio.io/docs/setup/kubernetes/install/platform/gke/) page currently only refers to [GKE's doc for installing the managed Istio versions](https://cloud.google.com/istio/docs/istio-on-gke/overview), which currently only support Istio versions up to 1.1.3.

That page should also link to [GKE's proper tutorial to install OSS Istio](https://cloud.google.com/kubernetes-engine/docs/tutorials/installing-istio), which I tested works with Istio 1.2.0-rc.0. Both docs should be linked on that page.

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by geeknoid** [comment]
@ostromart Could you figure out the right story here and update the istio.io docs accordingly?

**Comment by ostromart** [comment]
We had some debate about this when Istio on GKE was launching and the consensus was that we want to have separate docs for the following reasons:
- the OSS docs are ok for someone familiar with Istio but require too much assumed knowledge. The target audience for Istio on GKE are users who may have very little Istio (or GKE) knowledge. The instructions have the be explicit and precise.
- Istio on GKE versions lag OSS so not all versions of OSS Istio are available there. The docs cover mappings between GKE cluster versions and Istio versions. 
cc @oaktowner. 
Regarding the clusterrolebinding @rlenglet , this is not required for Istio on GKE because it's installed by the addon manager from the master node.

**Comment by ostromart** [comment]
Closing this but feel free to reopen if anyone disagrees.

**Comment by rlenglet** [comment]
@ostromart, the GKE + OSS Istio doc I pointed to doesn't use the addon manager. Therefore, it needs the clusterrolebinding. The decision that needs to be made here is whether to point to the GKE doc that uses the managed Istio thing, as we currently do, or point to the GKE doc that uses OSS Istio. This question has not been answered.

**Comment by ostromart** [comment]
That's a good point but I think it should be assigned to internal docs group. I've created a bug in buganizer:
https://github.com/istio/istio.io/issues/4337 (specifically for the missing cluster role binding).
Regarding the duplicated docs, this has all been discussed in the past. @oaktowner and @lcarey do realize there are three separate places for the docs and they are ok with it as they each serve a different purpose. 
I'm not sure what to do with this bug other than create a meeting to go over that discussion again - lmk if you are interested.

**Comment by LisaFC** [comment]
The eventual arrangement for those three locations btw will be
- Generic K8s info on istio.io, will have links to both:
    - GKE-specific installation instructions on cloud.google.com (based on the doc that's currently a GKE tutorial, updated as appropriate). I think at this stage maintaining two versions of this doesn't make sense, especially after the recent reorg of the K8s instructions on Istio.io.
   -  Instructions for installing the Istio-on-GKE add-on, also on cloud.google.com

They both also point to each other, and the add-on docs tell you about when you might want to use the add-on versus just installing Istio yourself directly on GKE.

**Comment by ostromart** [comment]
@rlenglet I'm not sure which non-managed docs you are saying is missing the cluster binding step. Could you point it out again?

**Comment by rlenglet** [comment]
@ostromart It's in the description of this PR: https://cloud.google.com/kubernetes-engine/docs/tutorials/installing-istio

**Comment by ostromart** [comment]
Just synced with @rlenglet offline and there's just one action item out of this: we need some blurb that for 1.2 user should follow the OSS instructions for the time being since it's not yet out in managed Istio on GKE.
