### ISSUE TITLE
503 error after mTLS policy is applied on RBAC groups user guide

### ISSUE THREAD

**Issue by lei-tang** [istio/istio.io#4348]
503 error after mTLS policy is applied on RBAC groups user guide: https://preliminary.istio.io/docs/tasks/security/rbac-groups/.

Fix for this issue: a DestinationRule should be applied on sleep after httpbin requires mTLS.

**Comment by lei-tang** [comment]
Fixes for this issue: https://github.com/istio/istio.io/pull/4349, https://github.com/istio/istio.io/pull/4350

**Comment by pitlv2109** [comment]
Close?
