### ISSUE TITLE
Update supported k8s versions

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#4362]
Right now, we claim to support 1.11, 1.12, and 1.13. Should we update this to 1.14 in the context of Istio 1.2? I worry that we haven't actually been testing with 1.14

WDYT?

**Comment by duderino** [comment]
@JimmyCYJ Could you try running your perf tests with 1.14 and report the results here?

**Comment by JimmyCYJ** [comment]
My current perf tests are running against 1.12, I will keep them running for 1 day. At meantime, I will create four 1.14 clusters to run the perf tests.

**Comment by JimmyCYJ** [comment]
The highest version on GKE is 1.13.6-gke.6. I cannot choose 1.14 to create a cluster. 

Below is the full list of available versions.
$ gcloud container get-server-config --zone us-central1-a
Fetching server config for us-central1-a
defaultClusterVersion: 1.12.8-gke.6
defaultImageType: COS
validImageTypes:
- COS
- UBUNTU
- COS_CONTAINERD
validMasterVersions:
- 1.13.6-gke.6
- 1.13.6-gke.5
- 1.13.6-gke.0
- 1.13.5-gke.10
- 1.12.8-gke.7
- 1.12.8-gke.6
- 1.12.7-gke.17
- 1.12.7-gke.10
- 1.12.6-gke.11
- 1.11.10-gke.4
validNodeVersions:
- 1.13.6-gke.6
- 1.13.6-gke.5
- 1.13.6-gke.0
- 1.13.5-gke.10
- 1.12.8-gke.7
- 1.12.8-gke.6
- 1.12.7-gke.17
- 1.12.7-gke.10
- 1.12.7-gke.7
- 1.12.6-gke.11
- 1.12.6-gke.10
- 1.12.6-gke.7
- 1.12.5-gke.10
- 1.12.5-gke.5
- 1.11.10-gke.4
- 1.11.9-gke.13
- 1.11.9-gke.8
- 1.11.9-gke.5
- 1.11.8-gke.6
- 1.11.8-gke.5
- 1.11.8-gke.4
- 1.11.7-gke.18
- 1.11.7-gke.12
- 1.11.7-gke.6
- 1.11.7-gke.4
- 1.11.6-gke.16
- 1.11.6-gke.11
- 1.11.6-gke.6
- 1.11.6-gke.3
- 1.11.6-gke.2
- 1.11.6-gke.0
- 1.11.5-gke.5
- 1.11.5-gke.4
- 1.11.4-gke.13
- 1.11.4-gke.12
- 1.11.4-gke.8
- 1.11.3-gke.24
- 1.11.3-gke.23
- 1.11.3-gke.18
- 1.11.2-gke.26
- 1.11.2-gke.25
- 1.11.2-gke.20
- 1.11.2-gke.18
- 1.11.2-gke.15
- 1.11.2-gke.9
- 1.10.12-gke.14
- 1.10.12-gke.9
- 1.10.12-gke.7
- 1.10.12-gke.1
- 1.10.12-gke.0
- 1.10.11-gke.1
- 1.10.9-gke.7
- 1.10.9-gke.5
- 1.10.9-gke.3
- 1.10.9-gke.0
- 1.10.7-gke.13
- 1.10.7-gke.11
- 1.10.7-gke.9
- 1.10.7-gke.6
- 1.10.7-gke.2
- 1.10.7-gke.1
- 1.10.6-gke.13
- 1.10.6-gke.11
- 1.10.6-gke.9
- 1.10.6-gke.6
- 1.10.6-gke.4
- 1.10.6-gke.3
- 1.10.6-gke.2
- 1.10.6-gke.1
- 1.10.5-gke.4
- 1.10.5-gke.3
- 1.10.5-gke.2
- 1.10.5-gke.0
- 1.10.4-gke.3
- 1.10.4-gke.2
- 1.10.4-gke.0
- 1.10.2-gke.4
- 1.10.2-gke.3
- 1.10.2-gke.1
- 1.9.7-gke.11
- 1.9.7-gke.7
- 1.9.7-gke.6
- 1.9.7-gke.5
- 1.9.7-gke.4
- 1.9.7-gke.3
- 1.9.7-gke.1
- 1.9.7-gke.0
- 1.9.6-gke.2
- 1.9.6-gke.1
- 1.9.3-gke.0
- 1.8.12-gke.3
- 1.8.12-gke.2
- 1.8.12-gke.1
- 1.8.12-gke.0
- 1.8.10-gke.2
- 1.8.10-gke.0
- 1.8.9-gke.1
- 1.8.8-gke.0
- 1.7.15-gke.0
- 1.7.12-gke.2
- 1.6.13-gke.1

**Comment by duderino** [comment]
@ostromart advice ^

**Comment by ostromart** [comment]
1.14 is not GA yet, so you have to create an alpha cluster to use it: 
https://cloud.google.com/kubernetes-engine/docs/concepts/alpha-clusters

**Comment by JimmyCYJ** [comment]
Per discussion with @duderino and @ostromart, 1.14 is in early alpha stage, and I cannot create an alpha cluster with version 1.14 either through gcloud command or console. 
1.14 is a short lived cluster, will be deleted after 30 days, and it cannot be automatically upgrade to other versions. 
This would not be a blocker for release 1.12. I can test against 1.14 later with 1.12.x.

**Comment by geeknoid** [comment]
Can we address this issue today? This is a P0 blocking the 1.2 release which is planned for tomorrow.

Note this is about Istio, not Istio-in-GKE. Do we want to claim Istio supports 1.12, 1.13, and 1.14?

**Comment by linsun** [comment]
I have been using k8s 1.13 for my istio testing.  I can try spin a new 1.14 cluster.

I think @sdake mentioned he has been using k8s 1.14 for his testing.

**Comment by linsun** [comment]
in our cloud, we do support 1.14 as the latest k8s version.  however, if you feel strongly of lacking the testing, we can wait till more testing is done on 1.14 before adding it to the supported list.

**Comment by geeknoid** [comment]
If Steve's been testing with 1.14, I'd feel comfortable claiming that's
what we support.

**Comment by duderino** [comment]
A little bit flying by the seat of our pants, but OK, +1

**Comment by duderino** [comment]
Was just about to send a PR to update the versions, but I see someone already has done this on master:

```
# The list of supported versions described by the docs
supported_kubernetes_versions: ["1.12", "1.13", "1.14"]
```

**Comment by duderino** [comment]
assigning to @sdake to express his level of confidence in 1.14.  If not high then we should remove from data/args.yml and try to get it better tested for a 1.2.x release

**Comment by sdake** [comment]
I am very confident that istio 1.2 works well for me on K8s 1.14.2.  I am only one individual though so Ymmv.

**Comment by sdake** [comment]
Just to note, I always do all test/dev work with the latest version of K8s - but my lab only has 3 nodes and I don't run on a cloud provider with a load balancer (instead I use metallb).  The scope of what I test is limited, although Istio certainly isn't DOA on 1.14.2.  My kubecon demo of multicluster for example was based on K8s 1.14.2.

Cheers
-steve

**Comment by linsun** [comment]
Thank you @sdake, I'll search for our doc to update the versions if needed.

**Comment by linsun** [comment]
No update is needed, all taken care of.

**Comment by linsun** [comment]
and verify-install handles 1.14 too :)

```
$ istioctl verify-install

Checking the cluster to make sure it is ready for Istio installation...

Kubernetes-api
-----------------------
Can initialize the Kubernetes client.
Can query the Kubernetes API Server.

Kubernetes-version
-----------------------
Istio is compatible with Kubernetes: v1.14.1+IKS.
```

cc @irisdingbj @esnible :)
