### ISSUE TITLE
Circuit Breaking Task : fortio-deploy.yaml doesn't work well with istioctl

### ISSUE THREAD

**Issue by bhaskar-reddy** [istio/istio.io#4363]
[Adding a client](https://preliminary.istio.io/docs/tasks/traffic-management/circuit-breaking/#adding-a-client) section of _Circuit Breaking_ task, instructs user to inject the client with istio sidecar proxy so network interactions are governed by Istio.

> $ kubectl apply -f <(istioctl kube-inject -f samples/httpbin/sample-client/fortio-deploy.yaml)

But when I tried this command, I got the following error:

> service/fortio created
> error: error parsing /dev/fd/63: error converting YAML to JSON: yaml: line 1: mapping values are not allowed in this context

Upon inspection, the `istioctl` command to `kube-inject` appears to have some kind of special char in the annotation line. So when I ran it separately using
 `istioctl kube-inject -f samples/httpbin/sample-client/fortio-deploy.yaml` 
I saw the error
> 2019-06-12T01:06:38.853188Z     warn    Potentially misspelled annotation 'sidecar.istio.io/statsInclusionPrefixes' with value 'cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc' encountered
apiVersion: apps/v1

I got around it by creating the deployment without this annotation, and later on adding the annotations via `kubectl edit deploy`.

It will be a good idea to make sure the sample deployment `fortio-deploy.yaml` thats bundled with Istio 1.2 works fine with `istioctl` command.

**Comment by jotak** [comment]
I'm running in the same issues while trying to activate more envoy metrics as documented here: https://istio.io/docs/ops/telemetry/envoy-stats/

That's not just a doc issue ... should we open another ticket to fix this annotation processing bug in a first place?

**Comment by michelleN** [comment]
Yep, ran into this as well. I did the following to get around it.
```bash
# commented out the annotation from the deployment
$ istioctl kube-inject -f samples/httpbin/sample-client/fortio-deploy.yaml -o injected-deploy.yaml
# manually re-inserted the annotation into the deployment
$ kubectl apply -f injected-deploy.yaml
```
