### ISSUE TITLE
Create 1.2 release notes for security

### ISSUE THREAD

**Issue by duderino** [istio/istio.io#4370]
**Describe the feature request**

Fill out the security section in https://github.com/istio/istio/wiki/Release-Note-1.2-Draft

Also fill in the incompatible changes, upgrade, and installation sections if anything applies.

**Describe alternatives you've considered**

Silently shipping major features in 1.2 to the surprise and delight of our users.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by liminw** [comment]
Adding @wattli  

I don't think we added any new features in 1.2 release. We are mostly doing bug fixes and test improvements.

**Comment by linsun** [comment]
Is there anything notable?  Note sidecar.istio.io/rewriteAppHTTPProbers: "true" is added.

**Comment by liminw** [comment]
@linsun This should go to release notes for "traffic management", correct?

**Comment by liminw** [comment]
@duderino The release notes for security is updated. 

Thanks @wattli and @myidpt

**Comment by duderino** [comment]
Thank you @liminw
