### ISSUE TITLE
Installation options needs update for 1.2

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#4374]
https://preliminary.istio.io/docs/reference/config/installation-options/

There is a script that generates this semi-automatically but it isn't completely automatic, so we will need to rerun it. Also it references changes from 1.0 -> 1.1 and should now reference 1.1 -> 1.2 (which is hopefully very few changes)

**Comment by duderino** [comment]
@pitlv2109 since I ran out of flaky tests to assign, I'm hoping you can do this instead.  Thank you

**Comment by pitlv2109** [comment]
@howardjohn Hey John, where is the script that you mentioned above?

**Comment by howardjohn** [comment]
@pitlv2109 at least part of is in https://github.com/istio/istio.io/blob/master/scripts/tablegen.py

I am not sure what the state of it is though, I recall trying to get it automatically running a while ago but ran into some issues so it may need some tweaks

**Comment by pitlv2109** [comment]
@johnma14 told me she's been working on this and will push soon. She also has stuff ready for https://preliminary.istio.io/docs/reference/config/installation-options-changes/ which we also need.

/assign johnma14

**Comment by pitlv2109** [comment]
@duderino  Let me know if you want me to take a look at another issue

**Comment by johnma14** [comment]
@duderino @pitlv2109 I just pushed a PR with the latest changes which should reflect 1.2 changes. Thanks.

**Comment by duderino** [comment]
Thanks @johnma14 

@pitlv2109 please unassign yourself in future transitions.  You were getting the P0 nags since the github REST API continued to return your github handle as the owner.

**Comment by geeknoid** [comment]
Can we address this issue today? This is a P0 blocking the 1.2 release which is planned for tomorrow.
