### ISSUE TITLE
Issue with docs/concepts/what-is-istio/index.md

### ISSUE THREAD

**Issue by adammil2000** [istio/istio.io#4375]
On this diagram:
https://preliminary.istio.io/docs/concepts/what-is-istio/./arch.svg
the word certificates is mangled on the lower right side of the diagram.

**Comment by sdake** [comment]
@adammil2000 good eye!  I'll see if I can correct it.

**Comment by sdake** [comment]
In addition, all of the fonts are inconsistent with the rest of the website in this file.
