### ISSUE TITLE
Cluster-Aware Service Routing - call from cluster2 fails

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#4385]
```
kubectl exec --context=$CTX_CLUSTER1 -it -n sample -c sleep $(kubectl get pod --context=$CTX_CLUSTER2 -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl helloworld.sample:5000/hello


Error from server (NotFound): pods "sleep-754684654f-kvxql" not found
```

If I update the first context from 1 to 2, the call works.

**Comment by ericvn** [comment]
@gargnupur Did you see this same failure when you ran through the doc?

**Comment by gargnupur** [comment]
@ericvn : where all do you have sleep pod installed ?
In this doc(https://istio.io/docs/examples/multicluster/split-horizon-eds/#split-horizon-eds-in-action), sleep is only installed in cluster1 and hence it works for me from cluster1, the way it's in the doc.

**Comment by ericvn** [comment]
@gargnupur 

Ah.  You aren't using the 1.2 version of the doc which has it in both clusters:
```
$ kubectl create --context=$CTX_CLUSTER1 -f samples/sleep/sleep.yaml -n sample
$ kubectl create --context=$CTX_CLUSTER2 -f samples/sleep/sleep.yaml -n sample
```
from https://preliminary.istio.io/docs/tasks/multicluster/split-horizon-eds/

**Comment by gargnupur** [comment]
Ahh I did go through the 1.2 version of the doc and it worked for me there too..
I didnt see any errors...

**Comment by gargnupur** [comment]
@ericvn : not sure why it worked for me at that time, but looking at the command I should have gotten the error too.. its looking for sleep pod in cluster2 in cluster1, which should throw an error and your change looks good.
