### ISSUE TITLE
Follow up on SDS multicluster

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio.io#4395]
Follow up on https://github.com/istio/istio.io/pull/4394
SME: @ericvn

**Comment by ericvn** [comment]
@rcaballeromx, is this PR to test adding `--values install/kubernetes/helm/istio/values-istio-sds-auth.yaml` to the `helm template` commands within the Cluster-Aware Service Routing task and the other `multicluster installation` pages? Or did you have more mind, or maybe something different?

I could test the first portion if that's what you were thinking.
