### ISSUE TITLE
Feedback for Authentication Policy

### ISSUE THREAD

**Issue by rvennam** [istio/istio.io#4401]
Automatic encryption between services is one of the main attractions for users evaluating Istio. This task is currently a bit hidden and can be perceived to be complicated due to the verbosity of his page https://istio.io/docs/tasks/security/authn-policy/
Some low handing fruit improvements:
1. Rename title "Authentication Policy" to "Enabling mutual TLS"
2. Move "End-user authentication" to a different task as it's really a different task and targets a different persona
3. Section "Request from Istio services to Kubernetes API server" seems a bit repetitive. Remove?
4. The check for default mesh authentication policy in the system in the Setup is not required. I didn't have it but I was able to still do the task.

**Comment by pitlv2109** [comment]
@yangminzhu @diemtvu What do you think? 

As for point 4, we should remove the check for meshpolicy, since we ask users to apply a meshpolicy a step below anyway (or do some refactoring).
