### ISSUE TITLE
Documentation on SDS installation profile is unclear

### ISSUE THREAD

**Issue by Niksko** [istio/istio.io#4416]
A few issues with the doco around the SDS installation profile:

1. There must be a better way of explaining that there is no `sds` profile, only an `sds-auth` profile. Changing the text in the numbered list of profiles to be `sds-auth` instead of just `sds` would be a start, perhaps with something to explain further.
2. The table that explains which additional features are enabled with the `-auth` suffix further confuses the issue, because it's not so much that these are 'enabled' for `sds` when you add the suffix, it's that they're there by default with no option to not have them. Again, confusing, a note explaining that they are enabled by default would help.
3. Why is control plane auth disabled for the SDS profile? My (naive) take is that SDS is the maximally secure deployment strategy, so seeing control plane auth disabled is very puzzling. Is it incompatible? Is it not-required? Will everything break if I create a custom profile that enables both SDS and control plan auth? I actually don't know the answer to this one, would appreciate input.

Happy to submit a PR over the weekend.

**Comment by quanjielin** [comment]
@Niksko thanks for submit the PR; BTW, for 3, support sds on controlplane is WIP feature, /cc @costinm who owns this now.

**Comment by wattli** [comment]
Hi Niksko, please feel free to submit a PR and include me and @quanjielin as reviewers. Thanks.

**Comment by costinm** [comment]
The gradual sds and control plane with sds will only be supported in the
new installer.
