### ISSUE TITLE
Add section on multicluster upgrades

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#4422]
There are several type of multicluster deployment that we document. Do we need to document how to upgrade them between releases? 

For example, to upgrade the cluster-aware service routing example from what was deployed using the release 1.1 docs to what would be equivalent to the release 1.2 docs:

1. The cluster-aware service routing has been updated slightly to show traffic going both ways between clusters.
    To upgrade a cluster-aware service routing multicluster deployed in release 1.1 to 1.2 follows the upgrade steps
    with a few additional steps.
    1. Control Plane
        1. Cluster 1
            1. Update the CRDs per the Upgrade Steps.
            1. Create a new helm template per the cluster-aware service routing documentation.
            1. Use `kubectl apply` to apply the new template
                Ignore the `Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply` warnings.
                Both network addresses will be set to 0.0.0.0, so they need to be updated following the release 1.2 instructions.
            1. Wait for the istio pods to become ready.
            1. Update cluser 1 network address.
        1. Cluster 2
            1. Update the CRDs per the Upgrade Steps.
            1. Create a new helm template per the cluster-aware service routing documentation.
            1. Use `kubectl apply` to apply the new template
                Ignore the `Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply` warnings.
            1. Wait for the istio pods to become ready.
            1. Update cluser 1 network address.
    1. Sidecar
        1. Cluster 2
            1. The new task has an additional `sleep` app in cluster 2. Deploy per documentation.
            1. Delete the `helloworld` pod in the `sample` namespace
        1. Cluster 1
            1. Delete the `helloworld` and `sleep` pods in the `sample` namespace
    1. Call the `helloworld.sample` service per documentation

**Comment by rcaballeromx** [comment]
@ericvn Thank you for providing the general steps of the process.

**Comment by ericvn** [comment]
1.1 and 1.2 are no longer supported, not are there doc updates.
