### ISSUE TITLE
Update feature stages for 1.2 release

### ISSUE THREAD

**Issue by duderino** [istio/istio.io#4423]
Multiple areas in https://istio.io/about/feature-stages/ have become more stable.

**Comment by duderino** [comment]
@douglas-reid says:

Distributed Tracing to Zipkin / Jaeger | Beta --> Stable
Service Tracing | Beta --> Stable
Prometheus Operator | nothing --> Alpha
Mixer In-Process Adapter Authoring Model | Deprecated --> Removed???  << @douglas-reid need confirmation

**Comment by duderino** [comment]
@wattli says:

Cert management on Ingress Gateway | Alpha --> Beta

And more promotions may occur

**Comment by douglas-reid** [comment]
@duderino "Mixer in-process adapter authoring model" can be removed from the list of features, as we no longer are accepting any new contributions.

**Comment by duderino** [comment]
@howardjohn @louiscryan @rshriram @costinm, strawman for traffic management:

Sidecar API is still Alpha, but the runtime impl could be considered Beta
Add locality load balancing at Beta (should have been mentioned as Alpha for 1.1)

Anything else?

**Comment by duderino** [comment]
@ozevren @geeknoid: 

Announce Galley as Beta (should have been mentioned as Alpha for 1.1)

**Comment by liminw** [comment]
I think
* "Authorization (RBAC)" should be "stable"
* "End user (JWT) authentication" should be "stable"
* "TCP authorization" can be removed. It is part of "Authorization (RBAC)". Having a separate item makes it confusing. 

We probably do not need a feature called "authentication policy". It is covered by "mTLS" and "JWT authentication" features. 

@diemtvu @wenchenglu WDYT?

**Comment by duderino** [comment]
> I think
> 
> * "Authorization (RBAC)" should be "stable"

+1

> * "End user (JWT) authentication" should be "stable"

Who uses this in production?

> * "TCP authorization" can be removed. It is part of "Authorization (RBAC)". Having a separate item makes it confusing.
>

+1  it certainly confused me :)
 
> We probably do not need a feature called "authentication policy". It is covered by "mTLS" and "JWT authentication" features.
> 
> @diemtvu @wenchenglu WDYT?

**Comment by liminw** [comment]
> > * "End user (JWT) authentication" should be "stable"
> 
> Who uses this in production?

It's supported since Istio 1.0. I think it is a very popular feature since it is frequently asked in the discuss forum.

**Comment by rshriram** [comment]
Traffic management:

Sidecar API | Beta [we have seen +ve results from 1.1 and we have added more fixes]
SNI (multiple certs) at ingress | Stable -- why is this even a feature, when it has been around for over a year since 1.0 ?
and yes
Locality-based Load Balancing: Beta

**Comment by wenchenglu** [comment]
@liminw 
/lgtm
agreed to remove TCP authorization once it is at the same stage as Istio authorization

+1 to remove authentication policy as a feature. That sounds confusion. All policy has its own alpha/beta state. It is strange to call out authn policy only here.

**Comment by duderino** [comment]
> Traffic management:
> 
> Sidecar API | Beta [we have seen +ve results from 1.1 and we have added more fixes]

I agree beta quality, but @louiscryan says the API is still subject to change like alpha.  So I tried to capture that with my note below.

> SNI (multiple certs) at ingress | Stable -- why is this even a feature, when it has been around for over a year since 1.0 ?

ACK, will change.

> and yes
> Locality-based Load Balancing: Beta

+1
