### ISSUE TITLE
Follow up on Health checking docs

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio.io#4478]
Release PR: https://github.com/istio/istio.io/pull/4433
SMEs: @incfly, @linsun

**Comment by incfly** [comment]
Thanks for this! let me know if anything is needed from me.

**Comment by incfly** [comment]
Quote from @rvennam  in https://github.com/istio/istio.io/issues/4503
> https://istio.io/docs/ops/setup/app-health-check/#use-annotations-on-pod

> The Use Annotations on Pod section seems incorrectly sandwiched between the global install option. Moving this section to after Re-deploy the liveness health check app might make it flow better.

> Currently, Re-deploy the liveness health check app is a continuation of the feature to enable it globally.
