### ISSUE TITLE
Issue with Health Checking of Istio Services page

### ISSUE THREAD

**Issue by rvennam** [istio/istio.io#4503]
https://istio.io/docs/ops/setup/app-health-check/#use-annotations-on-pod

The `Use Annotations on Pod` section seems incorrectly sandwiched between the global install option. Moving this section to after `Re-deploy the liveness health check app` might make it flow better. 

Currently, `Re-deploy the liveness health check app` is a continuation of the feature to enable it globally. 

@incfly

**Comment by incfly** [comment]
Closing this one and using https://github.com/istio/istio.io/issues/4478 as a single tracking issue for doc improvements.
