### ISSUE TITLE
galley and istioctl command pages include mixer metrics

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.io#4504]
This is likely due to some strange library dependency (validation?).

We should work to eliminate this issue somehow (that doesn't involve hand-editing).

/cc @ozevren @kyessenov

**Comment by geeknoid** [comment]
Meanwhile, I will hand edit the files and republish.

**Comment by kyessenov** [comment]
That is right. Galley (and istioctl) depend on mixer validator library. Without declarative validation constraints, there is a need for either library call or RPC from galley to mixer.

**Comment by douglas-reid** [comment]
@geeknoid see https://github.com/istio/istio.io/pull/4505. that includes the hand edits.

**Comment by ozevren** [comment]
One of the things that i'd like to do for 1.3 is to improve the validation story. Most likely, we will need to create an independent top-level package for validation. That should decouple Galley code from other pieces of code and solve this problem as well.

**Comment by ozevren** [comment]
With @nmittler s refactoring work, this should not longer be an issue.
