### ISSUE TITLE
Automatic injection demystification page incorrect

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#4509]
I am concerned about the text in https://preliminary.istio.io/blog/2019/data-plane-setup/#automatic-injection

It says

```
In case you want to change the default behavior, like the namespaces where Istio applies the injection, you can edit the MutatingWebhookConfiguration and restart the sidecar injector pod.

The automatic sidecar injection depends on the namespaceSelector webhook but also on the default injection policy and the per-pod override annotation.
```

Users don't need to restart the injector when they wish to change the namespaces where Istio applies injection.  (They might need to restart the pod if they wish to shoot themselves in the foot with a custom and non-standard injection label scheme.)

There is no such thing as a "namespaceSelector webhook".  The sidecar injection depends on "the `_istio-sidecar-injector_ MutatingWebhookConfiguration".

**Comment by geeknoid** [comment]
@chugtum Care to update the post?

**Comment by chugtum** [comment]
@esnible @geeknoid 

From https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/ page:
_The default configuration injects the sidecar into pods in any namespace with the istio-injection=enabled label. The istio-sidecar-injector configuration map specifies the configuration for the injected sidecar. To change how namespaces are selected for injection, we need to edit the MutatingWebhookConfiguration. For example, you can modify the MutatingWebhookConfiguration to always inject the sidecar into every namespace, unless a label is set.

For this: You should restart the sidecar injector pod(s) after modifying the MutatingWebhookConfiguration._

Are you suggesting, that the statement (which seems incorrect) and was kind of summarizing the above is not clear and should be explained liked above. Or are you suggesting that even the above explanation is not a valid one. Just want to make sure I do understand the issue clearly before modifying.

From point 2:
Agreed - That's a good catch @esnible . I actually meant the webhoook's namespaceSelector mechanism, which is one of the 3 pieces of configuration, the other being default policy and annotation of per pod override. Are you fine with that update ?

**Comment by esnible** [comment]
This is supposed to be a "10 minute read" demystifying sidecar injection.  Consider dumping material related to changing injection behavior unless you can imagine a user needing to do that.

My comments also apply to the documentation https://preliminary.istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/ which is an "8 minute read".

If we must keep material related to editing the webhook config: are there any fields in `mutatingwebhookconfiguration istio-sidecar-injector` that the user must modify in the course of using Istio?  I've never had to do this.  Perhaps the `.webhooks[0].clientConfig.caBundle` needs to be updated yearly and would need this?  If we tell people they need to restart after changing the defaults for injection namespaces they may become confused.  Users change the injection namespaces through labeling, not through this mechanism.  The current content is about using non-standard injection labels.

Suggesting users might change how namespace injection labels work does not demystify the concept.

**Comment by chugtum** [comment]
It is more to do with making user aware of a possibility of doing that and if someone is interested, I am sure they can dig deeper to figure out how to get that done. That's why I just made a point about it (awareness more than de-mystifying, even it means doing a non-standard thing for advanced users). 

But I am fine dumping it, if you and @geeknoid feel it doesn't add much and is not a fit in this blog.

For the other page, @geeknoid can suggest on who should be updating that, if we agree on not keeping it.

@esnible for the point 2, I am assuming you are good with my change suggestion.

**Comment by chugtum** [comment]
@geeknoid 
Have raised the following PR for the updates as discussed. 
Updating Demystifying Istio's Sidecar Injection Model Page #4562.
