### ISSUE TITLE
Slash characters breaking commands reference docs

### ISSUE THREAD

**Issue by adammil2000** [istio/istio.io#4547]
Linter is failing due to a slash character that has been introduced into the id field of the metrics section of several command reference docs, breaking any attempt to link to them. Here is an example of a bad id (and table class is affected too):

```
<h2 id=\"metrics\">Exported Metrics</h2>
<table class=\"metrics\">
```

Note the slashes in front of the quote characters. Removing these slashes makes the links work again. Here's an example that works after being fixed:

```
<h2 id="metrics">Exported Metrics</h2>
<table class="metrics">
```

The following files are currently affected by this problem:

docs/reference/commands/istio_ca/index.html
docs/reference/commands/mixs/index.html
docs/reference/commands/galley/index.html
docs/reference/commands/pilot-discovery/index.html

**Comment by rcaballeromx** [comment]
@geeknoid This is an issue we might need to fix in either the script generating the content or on the API repo.

**Comment by adammil2000** [comment]
I found that most files under the reference/commands path affected by this.

**Comment by geeknoid** [comment]
I fixed this bug a while ago, but the updated version of the code hasn't made it to the istio/istio repo yet. I'll go hunt down why that . didn't happen yet.
