### ISSUE TITLE
MySQL faq instructions incorrect and hard-to-read

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#4564]
I went to https://istio.io/faq/security/#mysql-with-mtls and followed the instructions.

The Issue is that the syntax of the instructions is either incorrect or not compatible with the Bash 3.x on OSX.  Instead of `-f <<` it should be `-f - <<` for both the "Disable Mutual TLS" and "Enable mutual TLS in STRICT mode" paths.

It would also help to replace `- name: mysql-service` and `host: "mysql-service"` with something like

```
  - name: YOUR-MYSQL-SERVICE     # The name of *your* K8s Service
```

(Obviously I should have noticed the name customization requirement if I had been thinking.  I had just finished reading [an Issue](https://github.com/istio/istio/issues/10062) about hacks to fix this globally and I was expecting a global fix so I didn't even read what I was pasting.)

Also, nit, there is a period after "Enable mutual TLS in STRICT mode." but not after "Disable Mutual TLS" and they should be the same.

**Comment by geeknoid** [comment]
@esnible I hate to "shoot the messenger" you, but would you mind tackling this one?

Also, the description for this page says "Trouble shooting" which should be one word.
