### ISSUE TITLE
Organize our get started experience and flow

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#4579]
currently, our tasks are focused on having users start with traffic mgmt first.  for example:

if you visit get started page, https://istio.io/docs/setup/kubernetes/getting-started/, we ask users to do a bunch of traffic mgmt tasks before metrics and there is no task related to security in there.

Also, if you go to tasks section, traffic mgmt is always first.

What we have found out is the story we are telling users to follow with traffic mgmt is hard to understand with learning curve of VS, GW, DR and SE.  We should consider tell the story of observability/telemetry and security (as most users actually come to istio for security) before traffic mgmt.  You don't normally see value with traffic mgmt till you have 1+ versions for a given service and users typically start with services with 1 version each as they move to the mesh.  Further, observability/telemetry requires 0 learning of istio resources and mTLS as well (or at least we are trying to make it so).

This feedback was  discussed in steering committee this week, and I encourage the Doc WG to consider this.  cc @frankbu @geeknoid @rcaballeromx

**Comment by frankbu** [comment]
I agree observability should be moved ahead of traffic management in both tasks and concepts.

Security is complicated, so other than a high level explanation that service-to-service calls are mtls secured, not sure what kind of security tasks would be appropriate early in getting started. Not to mention, a large number of the traffic-management tasks are related to security of ingress and egress, where gateways and service entries are involved.

Maybe the only real issue is that version routing tasks should be later in the list?

**Comment by geeknoid** [comment]
Excellent feedback Lin.

**Comment by linsun** [comment]
@frankbu @geeknoid any possibility we target this for 1.3 or 1.4?

@frankbu agree security is complicated other than mTLS.  I think it makes sense to start with mTLS (out of security) first given that is stable and requires little or no configuration.

**Comment by frankbu** [comment]
@linsun, yes, I think we should be able to at least make some progress in this direction by 1.3. There's also @vadimeisenbergibm's tutorial coming, so that might also change how we structure the get started material.

**Comment by linsun** [comment]
That is @frankbu - I moved it to 1.3.   @vadimeisenbergibm assume this is your tutorial - https://github.com/istio/istio.io/issues/4697

**Comment by vadimeisenbergibm** [comment]
@linsun right, this is the first PR for the tutorial. We decided to proceed module by module, each module as a separate PR.
