### ISSUE TITLE
Clarify use of kubectl on non-Kubernetes Quick Start page

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#4592]
The Quick Start on Docker page at https://istio.io/docs/setup/consul/quick-start/ says to install and potentially run `kubetcl`.

Given that that `kubectl` is from Kubernetes, that use of `kubectl` seems to imply that the quick start demo, which is for the _non_-Kubernetes case, actually needs Kubernetes.

It would be helpful if that page clarified that `kubectl` will be talking to a server provided by Istio (the "API server"?).

(Note that that text "... ensure that you ran the `kubectl` config commands below and re-run the command from the previous step" suggests that those `kubectl` commands should be run before the `docker` command in the previous step, but of course they'll fail if run before the previous step, making it appear that the demo needs Kubernetes after all.)

**Comment by esnible** [comment]
We need something from the community who uses Istio outside Kubernetes to work on this.  I do not have the skill.  This repo has no tag requesting community help.  Who could do it?

I am willing to help with formatting but I can't write it.

**Comment by howardjohn** [comment]
This page no longer exists
