### ISSUE TITLE
Egress GW task - why is there a need in destination rule?

### ISSUE THREAD

**Issue by abonas** [istio/istio.io#4629]
The egress example task
https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/
states there is a need to create a Gateway and a Destination rule.
Can perhaps someone explain why DS is needed in this example?
Also, the ingress task does not list DS as needed:
https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/

**Comment by vadimeisenbergibm** [comment]
The Destination Rule is needed to enable mTLS on the traffic between the application pod and the gateway.

**Comment by abonas** [comment]
> The Destination Rule is needed to enable mTLS on the traffic between the application pod and the gateway.

thanks Vadim. But why is it needed only for Egress and not for Ingress?

**Comment by vadimeisenbergibm** [comment]
You are welcome. In the Ingress case, the internal traffic is from the gateway to the service inside the mesh. The destination rule regarding the traffic to the service inside the mesh should already be in place, either globally, or per namespace, or per the service. And you can define it explicitly as well.

See more about mTLS and destination rules https://istio.io/docs/tasks/security/authn-policy/.

Could you please close this issue?
