### ISSUE TITLE
Question: At which step or which istio component generates the ‘x-b3’ headers for application to propagate

### ISSUE THREAD

**Issue by tedli** [istio/istio.io#4705]
I learnt that applications must propagate a set of `x-b3` headers to achieve mixer based distributed tracing.

I’m curious about that, where did the initial values of these headers be generated. If there is no values, nothing can be forwarded, it’s meaningless to propagate.

I’ve searched in repository `istio/proxy`, but seems that no related logic.

Is there any docs talks about this? Or can some point me out where the related logic is, I can then dive the code myself.

Thanks.

**Comment by tedli** [comment]
Here ?
https://github.com/istio/istio/blob/2604938c2a7429c49c2f35388d241599cd1585e1/mixer/pkg/server/interceptor.go#L65

**Comment by objectiser** [comment]
Istio's proxy uses the [envoy proxy](https://github.com/envoyproxy/envoy).

When handling a request, if no trace context (i.e. `x-b3-*` headers)  is available, then it will create a new trace instance and [generate the appropriate ids](https://github.com/envoyproxy/envoy/blob/master/source/extensions/tracers/zipkin/tracer.cc#L30-L38).

**Comment by tedli** [comment]
@objectiser 
Thanks a lot. Great help. 😁
