### ISSUE TITLE
Wrong commands in setup instructions

### ISSUE THREAD

**Issue by Anonymous-Coward** [istio/istio.io#4714]
This page + section: https://istio.io/docs/setup/kubernetes/install/helm/#option-2-install-with-helm-and-tiller-via-helm-install

` helm install install/kubernetes/helm/istio-init ...` should be replaced by ` helm install istio.io/istio-init  ...` and `helm install install/kubernetes/helm/istio ...` by `helm install istio.io/istio ...`, since in the setup process described in that section no download happens, but the istio helm charts repo is added to helm.

The second replacement has to happen in several places - all commands in the last step (the table listing the various profiles).

**Comment by frankbu** [comment]
The release is downloaded in the prerequisites section, and the doc also mentions that those charts are used: https://istio.io/docs/setup/kubernetes/install/helm/#helm-chart-release-repositories 

This doc could maybe be improved, but it is at least correct as it is.
