### ISSUE TITLE
"Unknown directive proxy" when using coreDNS's configmap from documentation

### ISSUE THREAD

**Issue by Docteur-RS** [istio/istio.io#4715]
# Where
In page **Setup** -> **Kubernetes** -> **Install** -> **Multicluster installation** -> ***Multiple control planes*** and section **Setup DNS** the coreDNS configuration is invalid.

# What
When trying to create a multicluter installation using the documentation an error occurs when updating the coreDNS configmap.  
The given config ends with the coreDNS pods in state *CrashLoopbackOff*.  
Logs shows the following error : `/etc/coredns/Corefile:10 - Error during parsing: Unknown directive proxy`  

# Fix
This is due to the CoreDNS version 1.5.0 used by the image which does not support the **"proxy"** keyword anymore. It must be replaced by **"forward"** in order to the pod to boot properly.

This is the working configmap :
```yaml
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    global:53 {
        errors
        cache 30
        forward . $(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP})
    }
EOF
```

# Versions
Using Istio 1.2.2
Kubernetes : 1.14.3

**Comment by camille-rodriguez** [comment]
@Docteur-RS did this config really fix your problem? I am having the same issue but the coredns config map keeps reverting to the original config, so the fix doesn't stay.

**Comment by Docteur-RS** [comment]
@camille-rodriguez It did fix my problem... But on my end the CM was staying as I had set it.  
Maybe you should investigate which component rewrites your CM ?

**Comment by camille-rodriguez** [comment]
Found the culprit for the reversion of the coreconfig! Forward effectively replaces proxy and that error message disappears.

**Comment by Docteur-RS** [comment]
@camille-rodriguez Good news ;-)
