### ISSUE TITLE
Quick start page feedback

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#4719]
Flow I'm going through:
istio.io - click on get started button - gets me to get started page, which shows 3 things:

1. Setup your platform
2. Download the Istio release
3. Follow the quick-start installation instructions

I did 1 and 2, then when I go to 3, it also has prerequisites:
Download the Istio release.
These quick-start instructions will not work with a downloaded istio repository because the pregenerated yaml files, istio-demo.yaml and istio-demo-auth.yaml, are only available in release images. If you want to work with the latest Istio codebase, refer to the developer wiki for instructions.
Perform any necessary platform-specific setup.

which I already did earlier.  

Seems for "3 Follow the quick-start installation instructions", we should just link to https://istio.io/docs/setup/kubernetes/install/kubernetes/#installation-steps?

Also, do we really need this tip? 
"These quick-start instructions will not work with a downloaded istio repository because the pregenerated yaml files, istio-demo.yaml and istio-demo-auth.yaml, are only available in release images. If you want to work with the latest Istio codebase, refer to the developer wiki for instructions."

Seems unnecessary to me at here.  Maybe a FAQ will be sufficient for this.

@frankbu @geeknoid @rcaballeromx thoughts?

**Comment by linsun** [comment]
Also, this page (https://istio.io/docs/setup/kubernetes/) seems a duplicate of the quick start page (https://istio.io/docs/setup/kubernetes/getting-started/).

It is interesting in one doc there is 4 steps, in the other there is 3 steps.

**Comment by frankbu** [comment]
> Seems for "3 Follow the quick-start installation instructions", we should just link to https://istio.io/docs/setup/kubernetes/install/kubernetes/#installation-steps?

I'm not sure that would be better. It's good for readers to see the short intro at the top, so they understand what they're installing. Don't forget that the definition of prerequisite is something you need to have done first, before you proceed, so if the user already did it as part of the getting started instructions, that's fine. Anyway that's my opinion but I'm open to more people's thoughts.

> Also, do we really need this tip?

That tip was explicitly added to close a user issue. The user thought that he could download the repo and install from there, but it only works if you download an actual Istio release.

> Also, this page (https://istio.io/docs/setup/kubernetes/) seems a duplicate of the quick start page (https://istio.io/docs/setup/kubernetes/getting-started/), except it covers more profiles?

These are intended to be more general instructions, for NOT first time users. They will be expanded and changed over time. For new users, we point them at the streamlined getting started page, which is the fast path install and what to do next instructions.

> One thing odd is https://istio.io/docs/setup/kubernetes/#installing-istio covers the install-istio topic before the download-istio topic.

Good point, those two sections should be reversed.

**Comment by frankbu** [comment]
Fixed #4842

**Comment by linsun** [comment]
Thank you @frankbu!  Revisited the get started flow today from https://istio.io/docs/setup/getting-started/, I saw all my other feedback is also resolved (no need to mention repo, ordering)
