### ISSUE TITLE
Title and link changes related to Observability

### ISSUE THREAD

**Issue by navinger** [istio/istio.io#4730]
In PR https://github.com/istio/istio.io/pull/4448, the section title was changed from "Telemetry" to "Observability" and the URL changed to https://istio.io/docs/concepts/observability/ and links to the doc were updated.

We should make a similar change in the Tasks section of the docs.

**Comment by navinger** [comment]
On the Istio.io landing page, the "Observe" block goes to:
/docs/reference/config/policy-and-telemetry/

It should go to: 
/docs/concepts/observability/

**Comment by gtaylor** [comment]
Started work in a draft PR #4968.
