### ISSUE TITLE
Clarify mesh expansion concept

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#4735]
We are taking a pass of MC concept, would need to ensure our mesh expansion doc is current and concept is clear.

**Comment by linsun** [comment]
#4736

**Comment by linsun** [comment]
@irisdingbj @vadimeisenbergibm anything left here?

**Comment by vadimeisenbergibm** [comment]
@linsun I will work on it next week.

**Comment by howardjohn** [comment]
```
$ rg 'mesh expansion' -i conent/en
```
no results
