### ISSUE TITLE
Docs for operator CLI for 1.3

### ISSUE THREAD

**Issue by ostromart** [istio/istio.io#4744]
Several items are needed:
[ ] Operator CLI as one of the installation options. (@adammil2000)
This will be alpha for 1.3 so it should not be recommended for production, but this will be the preferred way long term. Explain why user would choose this option.
[ ] Operator landing page. (adammil2000, ostromart)
High level concepts/intro. Can use existing README, ARCHITECTURE and design docs as starting point here. 
[ ] CLI reference. (adammil2000)
Use https://docs.google.com/document/d/16SWW14zrwFKc9OzH6biMQD1u9INllzMa56jde9vgQkM/edit#heading=h.u2k8rqep28j3
Add this to istioctl subcommands.
[ ] Operator API. (ostromart)
This should be auto-generated from https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto
[ ] Helm API new docs (richardwxn)
Auto generated from 
https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/values/values_types.proto

**Comment by ostromart** [comment]
See also my draft for the first two items above:
https://docs.google.com/document/d/12Yj-8HbsggPc256eWxhtqx3vWZD2oGBBU_V6Mu5oz88/

**Comment by adammil2000** [comment]
Item one and two are #4790

**Comment by adammil2000** [comment]
@ostromart and @richardwxn : Are you blocked on the last two items in the issue description or are we all good?  Thanks!

**Comment by ostromart** [comment]
We have the docs but currently looking into whether they can be formatted in a nicer way than this:
https://raw.githubusercontent.com/istio/operator/master/pkg/apis/istio/v1alpha2/v1alpha2.pb.html

**Comment by howardjohn** [comment]
I think this is done?

**Comment by ostromart** [comment]
yes, we can close this.
