### ISSUE TITLE
Enhance the Diagram Creation guide

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio.io#4772]
This issue impacts both the [Google draw](https://docs.google.com/drawings/d/1f3NyutAQIDOA8ojGNyMA5JAJllDShZGQAFfdD01XdSc/edit) and the [SVG](https://istio.io/about/contribute/diagrams/) versions of the guide.

Add the following elements to the guide:

- [ ] A graphic representation for destination rules.
- [ ] A graphic representation for clusters.
- [ ] A graphic representation for networks.
- [ ] Improve the guidance around including the Envoy proxies to clearly state that they need to be included only if there is an actual hop.
- [ ] HEX values for the colors.

**Comment by nmittler** [comment]
@rcaballeromx a couple more...

- Service Registry: I was planning on representing this with a database symbol, but we could represent it the same way we do other istio components, I suppose. IIRC I only need this for a single diagram ... perhaps it's fine to just use a one-off symbol for this?
- Clarity on how to indicate multiple replicas of things by having multiple overlapping symbols slightly offset from each other.  Currently everything has a gray background with no border which looks a little odd when I do this.
