### ISSUE TITLE
Best practices for organizing resources across namespaces

### ISSUE THREAD

**Issue by rvennam** [istio/istio.io#4781]
Request for a topic/task/blog that covers common questions when users run Istio in production:
1. Should Istio resources be defined in the same namespace as my services?
2. What resources are namespace scoped vs cluster scoped?
3. Do my VS and Gateway resources need to be in the same namespace?
4. Can I isolate and protect my gateway resources under a separate admin control and allow my application developers to own the VS that bind to it?
5. Do I need to use additional RBAC for separation of roles?

**Comment by vadimeisenbergibm** [comment]
Regarding 5.: You can use Kubernetes RBAC to limit who can write configuration objects to a specific namespace.
