### ISSUE TITLE
Issue with docs/ops/telemetry/envoy-stats/index.md

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#4794]
The word "inclusion_list" and "stats_matcher" in following statement have been changed in envoy: inclusionList and "statsMatcher"

The original statement is:
"_Envoy only collects statistical data on items matching the inclusion_list within the stats_matcher JSON element._"

**Comment by douglas-reid** [comment]
I'm confused by this issue. Looking at the latest envoy docs, I still see `inclusion_list` and `stats_matcher` as the config names in the config.

See: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto.html

> stats_matcher
(config.metrics.v2.StatsMatcher) Inclusion/exclusion matcher for stat name creation. If not provided, all stats are instantiated as normal. Preventing the instantiation of certain families of stats can improve memory performance for Envoys running especially large configs.

and

> inclusion_list
(type.matcher.ListStringMatcher) Inclusive match. No stats are enabled except for those matching one of the supplied StringMatcher protos.
