### ISSUE TITLE
Issue with docs/setup/kubernetes/install/helm/index.md

### ISSUE THREAD

**Issue by jianglijie** [istio/istio.io#4818]
I find the count of crds is 53 in chinese(https://istio.io/zh/docs/setup/kubernetes/install/helm/), but it's 23 in english(https://istio.io/docs/setup/kubernetes/install/helm/). Which one is right?
And I installed ther 23 crds, It report ` no matches for kind "metric" in version "config.istio.io/v1alpha2"` and ` no matches for kind "prometheus" in version "config.istio.io/v1alpha2"` when I kubectl apply with `# 指标 instance 的配置
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: doublerequestcount
  namespace: istio-system
spec:
  value: "2" # 每个请求计数两次
  dimensions:
    reporter: conditional((context.reporter.kind | "inbound") == "outbound", "client", "server")
    source: source.workload.name | "unknown"
    destination: destination.workload.name | "unknown"
    message: '"twice the fun!"'
  monitored_resource_type: '"UNSPECIFIED"'
---
# prometheus handler 的配置
apiVersion: "config.istio.io/v1alpha2"
kind: prometheus
metadata:
  name: doublehandler
  namespace: istio-system
spec:
  metrics:
  - name: double_request_count # Prometheus 指标名称
    instance_name: doublerequestcount.metric.istio-system # Mixer Instance 名称（全限定名称）
    kind: COUNTER
    label_names:
    - reporter
    - source
    - destination
    - message
---
# 将指标 Instance 发送给 prometheus handler 的 rule 对象
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: doubleprom
  namespace: istio-system
spec:
  actions:
  - handler: doublehandler.prometheus
    instances:
    - doublerequestcount.metric`, how can I install `metrics.config.istio.io` and so on

**Comment by linsun** [comment]
english is correct.  the chinese version has not been updated lately.  In 1.2 release note, we did say many of the CRDs were removed as they are no longer installed by default.

**Comment by linsun** [comment]
another user also reported this https://github.com/istio/istio.io/issues/4823

**Comment by sdake** [comment]
I think the reporter was .mentioning after installing the crds, not all were present and didn't hve a working system, but i dont know ZH langauge.

**Comment by sdake** [comment]
please port https://github.com/istio/istio.io/pull/4917 to the chinese site prioir to releae.

**Comment by sdake** [comment]
this may be already fixed https://github.com/istio/istio.io/pull/4920 - although the simplification that @howardjohn submitted in https://github.com/istio/istio.io/pull/4917 should help tame this problem in a semi-permanent way :)

**Comment by sdake** [comment]
I believe this is fixed.  Please reopen if you see any issues here.
