### ISSUE TITLE
docs / operations / troubleshooting / Component Logging

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#4851]
Documentation unclear.  The documentation looks user-facing, but is written as though it is internal developer facing.

Says "You control these logging features by passing command-line options when starting the components."  Should say "You control these logging features by setting global.logging.level when installing via Helm" (or similar.)

Says "Pilot, Citadel, and Galley have their own scopes which you can discover by looking at their reference documentation."  Should say something like "Pilot, Citadel, and Galley have their own scopes which you can discover by looking at their reference documentation (the --log_caller attribute)."

The example "mixs server --log_output_level attributes=debug,adapters=warning" is no good because it assumes the user runs `mixs`.  The user is installing, typically via Helm, not running `mixs`, and the example should reflect that.

The "Controlling output", "Log rotation", and "Component debugging" sections have no user-facing equivalent.

**Comment by howardjohn** [comment]
I agree but for what it's worth not all users are using helm.. or deploying on kubernetes at all.
