### ISSUE TITLE
DOCS / OPERATIONS / TROUBLESHOOTING / COMPONENT INTROSPECTION not user-centric

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#4852]
DOCS / OPERATIONS / TROUBLESHOOTING / COMPONENT INTROSPECTION should be written from the point of the Istio user, not the Istio developer.

Remove

```
The --ctrlz_port and --ctrlz_address command-line options can be given when starting a component to control the specific address and port where ControlZ should be exposed.
```

because it is not exposed in Istio's helm charts.

Replace

```
$ kubectl port-forward -n istio-system <podname> 9876:9876
```

with

```
$ istioctl experimental dashboard controlz <podname>
```

**Comment by gtaylor** [comment]
I am admittedly out of my depth here, but I have hopefully followed your instructions in submitting PR #4966.
