### ISSUE TITLE
[istio-1.3] Sidebar cuts off content with no scroll ability

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#4853]
Depending on the screen resolution, the sidebar cuts off content and you can't scroll to see the rest. Make the window larger or smaller and it works fine, so I'm not sure that it's worth fixing. 

![image](https://user-images.githubusercontent.com/8484260/63800489-38093a80-c8dc-11e9-9462-8522500fcf3d.png)

**Comment by geeknoid** [comment]
This should be all better in preliminary.istio.io. It'll make its way to istio.io in the 1.5 timeframe.
