### ISSUE TITLE
Use istioctl verify-install in the doc

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#4871]
https://preliminary.istio.io/docs/setup/install/kubernetes/#verifying-the-installation

instead of asking users to manually validate?

@irisdingbj @frankbu WDYT?

**Comment by frankbu** [comment]
There was already a PR for this that seems to have stalled: #4251

**Comment by esnible** [comment]
@irisdingbj What is needed to get the PR going?

**Comment by esnible** [comment]
@irisdingbj What is needed to get this PR going?

**Comment by frankbu** [comment]
We are using verify-install in the general install instructions: https://preliminary.istio.io/docs/setup/install/operator/#verify-a-successful-installation

For the [quick-start doc](https://preliminary.istio.io/docs/setup/install/kubernetes/#verifying-the-installation), I'm inclined to leave it as kubectl get svc/pods. It's simple, and one less thing to explain.
