### ISSUE TITLE
Add an FAQ around disable auto detect inbound port

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#4872]
https://github.com/istio/istio.io/pull/4859
This issue was discussed in today's networking WG mtg, the consensus is that we need to put some note around how users can switch to the old behavior when the auto detect inbound port isn't working.

Thoughts @morvencao?

**Comment by morvencao** [comment]
@linsun I have raised a [PR](https://github.com/istio/istio.io/pull/4875) to add an FAQ for that.
