### ISSUE TITLE
Issue with docs/tasks/telemetry/logs/fluentd/

### ISSUE THREAD

**Issue by invertigo** [istio/istio.io#4873]
Multiple teammates have worked through these directions with negative outcome.  Installing in a new k8s cluster, no data ever gets into elasticsearch.

**Comment by douglas-reid** [comment]
I just attempted this task directly, using the following images: `gcr.io/istio-release/proxyv2:master-latest-daily` and `gcr.io/istio-release/mixer:master-latest-daily` (cluster age <7d).

I had success: 
![kibana-example](https://user-images.githubusercontent.com/21148125/64203464-51643680-ce48-11e9-8093-8ef1e7c23288.png)

The only hiccup was that the first time I pulled up the kibana UI, it said there was no data to index, but i was able to click on `Index Patterns` and then easily add an index pattern as described.

Can you explain where you are seeing failures?

**Comment by douglas-reid** [comment]
Closing, as there has been no new feedback and this issue is now OBE.
