### ISSUE TITLE
clicking envoy doesn't go to right location

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#4885]
<img width="1181" alt="Screen Shot 2019-09-03 at 9 52 08 AM" src="https://user-images.githubusercontent.com/755849/64192930-a1cf9a00-ce30-11e9-83e3-ecf2b285e023.png">

clicking "Envoy" shows this:

<img width="1411" alt="Screen Shot 2019-09-03 at 9 53 38 AM" src="https://user-images.githubusercontent.com/755849/64192986-bdd33b80-ce30-11e9-95a2-0b4cfd093be2.png">

**Comment by sdake** [comment]
this is a general problem with any link that links to a different glossary definition in the website.

**Comment by frankbu** [comment]
Yes, I see this is a general issue with glossary entries. The URL of a glossary entry, e.g., https://preliminary.istio.io/docs/reference/glossary/#cluster seems to go to the last line of the corresponding entry, not the title.

**Comment by geeknoid** [comment]
Although this behavior isn't great, it's also not a release blocker. It's been this way in the 1.1 and 1.2 releases, so it's not emergent behavior. As such, I've reprioritized to P1.
