### ISSUE TITLE
this use case seems awkward.

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#4887]
<img width="1151" alt="Screen Shot 2019-09-03 at 10 01 58 AM" src="https://user-images.githubusercontent.com/755849/64193596-f1629580-ce31-11e9-97f9-b9b6637d9849.png">

**Comment by sdake** [comment]
Additionally, the sentence above the awkward use case is hard to understand.

**Comment by frankbu** [comment]
Actually, why is all this info included in the glossary entry anyway? I think the first paragraph is all that belongs in the glossary, maybe with a (see more) link to the rest of the info which should be in the concepts somewhere.

@rcaballeromx WDYT?
