### ISSUE TITLE
documentation does not match code

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#4894]
https://preliminary.istio.io/docs/reference/glossary/#service-mesh

specifically the example:
```
Service names combined with a namespace are unique within a mesh. For example, the bar service in the foo namespace in cluster-1 is considered the same service as the bar service in the foo namespace in cluster-2.
```

While we would like this to be the case, the implementation for this is very complex and not yet implemented.

I attempted for some time to track down the related implementation issue.  The best I can find is our multicluster tracker here: https://github.com/istio/istio/issues/11731.  I didn't see the exact problem there and moving on with more validation of the glossary for now.

**Comment by frankbu** [comment]
This is just defining a requirement that must be met in a "mesh". If it is not true in some particular configuration, the configuration is not (by definition) considered a single mesh, but rather a multi-mesh federation. I think the new concepts section explains this.
