### ISSUE TITLE
"in Istio" is not right.  perhaps in a service mesh. ?

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#4900]
https://preliminary.istio.io/docs/reference/glossary/#workload

**Comment by gtaylor** [comment]
I may be lacking some context, but why is this incorrect?

**Comment by frankbu** [comment]
I agree it's a little confusing, `deliver some function in Istio` sounds like a workload is implementing an Istio feature, not an application service. Maybe something like this is better:
 
```
deliver some application functionality in a service mesh.
```
