### ISSUE TITLE
Troubleshooting Sections for envoy proxy of loading certs

### ISSUE THREAD

**Issue by singhujjwal** [istio/istio.io#4919]
Hi,
I am using istio 1.1.4 installed from the helm chart.
I am trying to configure TLS ingress gateway with file mount based approach as described [here](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/#configure-a-tls-ingress-gateway-with-a-file-mount-based-approach)

I followed the [troubleshooting](https://preliminary.istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/#troubleshooting) here.
In the step when I am trying to check if the certs are loaded by envoy proxy or not, I get an empty result
```bash
kubectl exec -ti $(kubectl -n istio-system get pods -l istio=ingressgateway -o json | jq -r .items[0].metadata.name)     -n istio-system -- curl  127.0.0.1:15000/certs
```
I get below results
```
{
 "certificates": []
}
```
Any help is appreciated. All the previous troubleshooting steps are passed. 
As a result of this I am not able to server TLS traffic using the gateway.

Thanks,
Ujjwal

**Comment by howardjohn** [comment]
This repo is for documentation bugs, looks like you are trying to debug a product bug. Can you file this in istio/istio if you still see issues on recent versions?
