### ISSUE TITLE
Where commands are available unclear in docs/reference/commands/_index.md

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#4921]
The command reference pages (`docs/reference/commands/_index.md` and child pages) don't seem to say anything about *where* (in what context) the commands are available.

The command `istioctl` is available via the executable at `./bin/istioctl` in the release tar files (at least in `istio-1.2.5-osx.tar.gz`), and it's mentioned in the installation instructions, so it's easy to find, and it's clear that it's a normal executable available in the local shell environment.

However, for the other commands (`galley`, `istio_ca`, `mixs`, `node_agent`, `operator`, `pilot-agent`, `pilot-discovery`, and `sidecar-injector`), there are no same-named executables in the release tar files, and it's unclear where (in which context) those commands are available.  

Are they "siblings" of `istioctl` (locally executable commands, implemented via executables in `/bin` directory) that aren't available until some add-on tar file is unpacked? 

Or are they commands that are available only inside some Istio pod/container/etc.? 

Or maybe are they subcommands of some other top-level command (as `istioctl version` is a subcommand of the overall `istioctl` command)?

**Comment by geeknoid** [comment]
All these commands are executables to support Istio at runtime in a cluster, they're generally not intended to be used directly at a command-line. The options are documented there so that customers can manipulate these options during diagnostics of in-cluster issues.
