### ISSUE TITLE
Corrections to Istio Operator Install guide

### ISSUE THREAD

**Issue by ostromart** [istio/istio.io#4935]
1. In "Install a different profile"
 istioctl experimental manifest apply --set profile=default
-> change default to demo, since default is the default (i.e. it's used if nothing is specified so it doesn't make sense to use it as an example)
2. In "Display the profiles list"
Remove everything including and after "Optionally, " in this section. We excluded support for https paths in this release.
3. istioctl manifest apply command section should be added back. It provides a much better user experience compared to applying using kubectl. In fact, I suggest dropping the kubectl approach altogether, since this is not the encouraged approach going forward.

**Comment by adammil2000** [comment]
Fixed in #4936

**Comment by adammil2000** [comment]
Merged
