### ISSUE TITLE
Document `istio-locality` label

### ISSUE THREAD

**Issue by maxbischoff** [istio/istio.io#4938]
The locality used for locality-based load balancing can be overwritten using the label `istio-locality` (see [code](https://github.com/istio/istio/blob/1aeca5f2bd3619072dc522574fc81825ac32d897/pilot/pkg/model/service.go#L110). This label is currently not documented on the website, I would expect it in [Locality Load Balancing](https://istio.io/docs/ops/traffic-management/locality-load-balancing/) or [Traffic Management](https://istio.io/docs/concepts/traffic-management/).

**Comment by howardjohn** [comment]
This feature is not something we test or necessarily want to support. It is intentionally not documented as such

**Comment by rolandkool** [comment]
The `istio-locality` label is useful for VMs that run on-premise and don't have access to region/zone metadata provided by a provider. Would this be a proper reason to document this useful but hidden label?

**Comment by boeboe** [comment]
Another use case for this label is to override the default behavior that is imposed by the combination of region, zone and sub-zone, as documented [here](https://istio.io/latest/docs/tasks/traffic-management/locality-load-balancing).
