### ISSUE TITLE
zh: There may need to fix the numbers of CRD which in the second plan. 

### ISSUE THREAD

**Issue by Aisuko** [istio/istio.io#4940]
There may need to fix the numbers of CRD which in the second plan. But I can not reopen my issue. So, there need to refer to the new issue.

_Originally posted by @Aisuko in https://github.com/istio/istio.io/issues/4823#issuecomment-529536767_

**Comment by Aisuko** [comment]
Please fix the numbers of CRD in the link below https://istio.io/zh/docs/setup/kubernetes/install/helm/#%E6%96%B9%E6%A1%88-2-%E5%9C%A8-helm-%E5%92%8C-tiller-%E7%9A%84%E7%8E%AF%E5%A2%83%E4%B8%AD%E4%BD%BF%E7%94%A8-helm-install-%E5%91%BD%E4%BB%A4%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85

**Comment by rootsongjc** [comment]
I think this issue is out-of-date, so close it.
