### ISSUE TITLE
Need SDS documentation

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#4943]
The documentation should describe:
1. SDS prereqs (apparently more then just K8s 1.13 is necessary)
1. What is SDS
1. Why would I want SDS
1. How do I enable or disable SDS

**Comment by howardjohn** [comment]
* https://preliminary.istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/
* https://preliminary.istio.io/docs/tasks/security/auth-sds/
* https://preliminary.istio.io/docs/setup/install/helm/
* https://preliminary.istio.io/blog/2019/trustworthy-jwt-sds/

This seems pretty thoroughly covered

**Comment by sdake** [comment]
@howardjohn thanks for the links.

**Comment by pitlv2109** [comment]
Thanks for the links John. Is it okay to close now?

**Comment by howardjohn** [comment]
I think this is done, SDS is an implementation detail
