### ISSUE TITLE
Consistent way to specify how to configure Istio values

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#4945]
We have a lot of docs that mention installing Istio with some setup

For example:

> The sidecar injecting webhook is enabled by default. If you wish to disable the webhook, you can use Helm to generate an updated istio.yaml with the option sidecarInjectorWebhook.enabled set to false. E.g.
> 
> $ helm template --namespace=istio-system --set sidecarInjectorWebhook.enabled=false install/kubernetes/helm/istio > istio.yaml
> $ kubectl create ns istio-system
> $ kubectl apply -f istio.yaml

It would be great if there was some canonical way to reference how to change an installation option. This will also be useful to transition to the operator as well.

Not sure if this would make sense as some sort of technical automation (templating?) method, or just having a standard to follow

**Comment by geeknoid** [comment]
We have support for boilerplate content in our docs for this kind of stuff...

**Comment by howardjohn** [comment]
This is not stale
