### ISSUE TITLE
Simplify "Visualizing Metrics with Grafana"

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#4954]
https://preliminary.istio.io/docs/tasks/telemetry/metrics/using-istio-dashboard/

Now that we have `istioctl dashboard` promoted out of experimental, replace Step 3 with `istioctl dashboard grafana <pod>` and replace `killall kubectl` in the Cleanup section with pressing control-C to terminate the dashboard port forwarding.

**Comment by rvennam** [comment]
same applies to other tasks such as Kali and Jaeger

**Comment by howardjohn** [comment]
This is done: https://preliminary.istio.io/latest/docs/tasks/observability/metrics/using-istio-dashboard/
