### ISSUE TITLE
deprecated sourceLabels in Chinese documentation

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#4974]
https://github.com/istio/api/commit/0e77ec00236554f76109f0e917c6a11de3fa97f7#diff-0820bb0406265ba9b9a9e11dcec06601 removed sourceLabels from the documentation.  They were to be marked as Deprecated, which was missed in the release notes, but will be made official soon.

Some documentation continues to use them, e.g. _content/zh/docs/concepts/traffic-management/index.md_ which has a YAML example using them.

**Comment by frankbu** [comment]
We decided not to deprecate sourceLabels after all. The documentation has been restored by https://github.com/istio/api/pull/1108.
