### ISSUE TITLE
Need clean up step for the new operator

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#4987]
We need some clean up step for the new operator.  https://preliminary.istio.io/docs/setup/install/operator/

I tried it and installed the demo profile but got lost on how to clean it up. Had to go back to other install's clean up doc to clean it up.

**Comment by ayj** [comment]
AFAICT, the only way to uninstall is with `istioctl manifest generate | kubectl delete -f -`. It might be too late to add an explicit uninstall command but we should document the alternative.

**Comment by ostromart** [comment]
Yes, that's something we overlooked - why would anyone want to uninstall it? :-)
I'll add something to the docs.
