### ISSUE TITLE
Istio 1.3 Egress-Egress Gateways task: 

### ISSUE THREAD

**Issue by bhaskar-reddy** [istio/istio.io#5004]
In the instructions of [Egress gateway for HTTPS traffic](https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-https-traffic), there are typos in couple of places :
1. Step # 2
> Verify that your ServiceEntry was applied correctly by sending an HTTPS request to http://edition.cnn.com/politics.

should be 

> Verify that your ServiceEntry was applied correctly by sending an HTTPS request to https://edition.cnn.com/politics.

2. Similar in step # 4 

Correct mention of `https` in the url for `https://edition.cnn.com/politics` is important in these two places.

**Comment by geeknoid** [comment]
@frankbu @vadimeisenbergibm Based on your comments on the #5016 , then we should close this issue?

**Comment by vadimeisenbergibm** [comment]
@geeknoid I see, the remark relates to the comment only, missing `s` in `https://`:

Verify that your ServiceEntry was applied correctly by sending an HTTPS request to http**S**://edition.cnn.com/politics.

**Comment by vadimeisenbergibm** [comment]
@geeknoid let me handle it

**Comment by frankbu** [comment]
Fixed by #5025
