### ISSUE TITLE
Document clusterName and external service registry naming requirements

### ISSUE THREAD

**Issue by ayj** [istio/istio.io#5050]
The clusterName in values.yaml should match the external service registry name. This name corresponds to the [remote cluster config](https://istio.io/docs/setup/install/multicluster/shared-vpn/#kubeconfig) and `global.meshNetworks.[*].[].FromRegistry` field. Without this change features such as port-sniffing may not function correctly.

**Comment by ayj** [comment]
cc @howardjohnm

**Comment by howardjohn** [comment]
I don't think this is applicable anymore
