### ISSUE TITLE
Revisit any unresolved comments on #5014 (Traffic Management concept guide update)

### ISSUE THREAD

**Issue by LisaFC** [istio/istio.io#5069]
Per discussion on https://github.com/istio/istio.io/pull/5014

**Comment by geeknoid** [comment]
@LisaFC Could you fill in this issue a bit? It's hard to tell what this involves, how much is done, etc.

**Comment by LisaFC** [comment]
Gotcha. There were some outstanding comments on #5014 that weren't resolved before it was published, this is just a reminder to revisit them when we have time.

**Comment by howardjohn** [comment]
Seems quite stale, not sure what to do here
