### ISSUE TITLE
RBAC ServiceRoleBinding Subject properties docs?

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#5071]
I am trying to understand RBAC Subject properties.

I read at https://github.com/istio/api/blob/master/rbac/v1alpha1/rbac.proto#L274 that `group` is deprecated and to "Use groups and not_groups instead."

I wanted to see how that looked on istio.io.  https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1/#Subject has a link to a “constraint and properties” page which doesn't mention group, groups, nor not_groups.

I understand all of the files except for `user` and `properties` are $hide_from_docs but it would be useful if the hidden text explained how to use `properties`.  It is also unclear if the hidden fields are intended to be deprecated, or are deprecated, or are unimplemented.

**Comment by howardjohn** [comment]
This API is removed
