### ISSUE TITLE
Issue with docs/ops/traffic-management/introduction/index.md

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#5089]
Where the text says:

"The final concept that is essential for the operator to understand is how Istio uses gateways to allow traffic into the mesh or requests originating in the mesh from accessing external services."

something went wrong near that occurrence of "from".

What that supposed to be "... allow traffic into the mesh or prevent requests originating in the mesh from accessing external services"?

Or maybe "to allow traffic into the mesh or requests originating in the mesh to access external services"?

**Comment by geeknoid** [comment]
@LisaFC
