### ISSUE TITLE
Issue with docs/reference/config/istio.operator.v1alpha12.pb/index.html

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#5091]
The indentation on the yaml is missing. This seems generated so not sure where the problem is

**Comment by geeknoid** [comment]
This content is derived from the proto files in istio/operator

**Comment by ostromart** [comment]
It's generated from the comment header in the proto file which has blocks like:
```text

1. Default Istio install

    ```yaml
    install:
      profile: default
    ```
```
There are several difference between that and known working examples like:
```text
//
// ```yaml
//  failover:
//    - from: us-east
//      to: eu-west
//    - from: us-west
//      to: us-east
// ```

```
I'm going to bet on the indentation of the block being the problem.

**Comment by ostromart** [comment]
Fixed via https://github.com/istio/operator/pull/320.

**Comment by ostromart** [comment]
Oops, looks like problem is still there.

**Comment by ostromart** [comment]
@geeknoid 's fix https://github.com/istio/operator/pull/337 solved the indentation but I still see some render errors (e.g. section with "Default install with each feature installed to different namespace and security components in separate namespaces"). I looked at the source proto but don't see anything suspicious like tabs, stray spaces, or blank lines that might mess this up.

**Comment by geeknoid** [comment]
Oh, yuk. I'll track it down...

**Comment by howardjohn** [comment]
I think this was fixed now
