### ISSUE TITLE
Issue trying to use GKE multi-cluster example with shared control plane setup.

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#5093]
Setup the following example on two IKS clusters:

https://istio.io/docs/setup/install/multicluster/shared-gateways/

This works as expected.

Tried to use the example from:

https://istio.io/docs/examples/multicluster/gke/

on top of the prior install. It does look like the Istio install in the later example matches what is done in the shared-gateways page, with the exception that it calls out GKE clusters to high I don't have access.

The example does not work as expected. One should see the product page load balance through the 3 reviews yielding no/black/red stars, however the red stars never appear (reviews-v3 is running on the second cluster).

I'm not sure the second example would actually run on GKE.

I was able to get the red stars to show up if I did two things:

- Update the reviews-v3.yaml to be more like the bookinfo.yaml (I took the review and ratings sections from bookinfo, removed the ratings, reviews-v1, and reviews-v2 deployments).
- Force an update by applying the default destination rules and removing them. Will the rules were active the app failed to run.

It may be that the former is all that's needed for GKE, but have doubts. I opened https://github.com/istio/istio/issues/17562 to understand why the second bullet is needed.

A third problem is that applying the destination rules causes the app to fail. I'm not sure why that is at the moment.

**Comment by frankbu** [comment]
https://github.com/istio/istio/issues/17562#issuecomment-537615736

**Comment by frankbu** [comment]
I think #5094 addresses the doc part of this, https://github.com/istio/istio/issues/17562 should address the other problems.

I do think it would be good to open another related doc issue (feature request) to add a new example, or otherwise incorporate running bookinfo on a multi-network MC configuration. Right now it's only documented for single-network MC (gke, specifically).
