### ISSUE TITLE
Issue with docs/setup/upgrade/steps/index.md

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#5102]
Please add one note for the following command (restart feature) was added from 1.15 kubectl

**kubectl rollout restart deployment --namespace default**

**Comment by frankbu** [comment]
@howardjohn Should we be using `rollout restart`, if it's not available prior to kubectl 1.15?

**Comment by howardjohn** [comment]
I think we have 3 options
* Keep it how it is
* Add a warning
* Revert it, and go back to the old way of linking to some random gist that is not even the correct to do a rolling restart (I guess we could also replace it with the "correct" way to do it before kubectl 1.15)

I think its pretty common for users to have later kubectl versions, given that package managers will generally install later ones and you can use recent kubectl with even very old kubernetes server versions.
