### ISSUE TITLE
telemetry/pilot pods stay in Pending status after upgrade

### ISSUE THREAD

**Issue by elfinhe** [istio/istio.io#5125]
Cluster Env: GKE --cluster-version=1.13.7-gke.24 --machine-type=n1-standard-2 --num-nodes=4. (8vCPUs)

After I ran the `kubectl apply` by following [the upgrade steps](https://istio.io/docs/setup/kubernetes/upgrade/steps/), telemetry/pilot pods got into endless Pending status. Both old (1.3.1) and new (1.3.2) versions exist in the cluster.

``` bash
kubectl create namespace istio-system
helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
helm template install/kubernetes/helm/istio --name istio --namespace istio-system | kubectl apply -f -
```

This may be caused by not enough CPU, or some intermittent concurrency bug.

Then I used --prune to upgrade. This issue disappeared for once.

Then I changed to use 32 vCPUs cluster. The issue disappeared until now.

 

$ istioctl version
client version: 1.3.1
citadel version: 1.3.2                                                                                                                                  
galley version: 1.3.2
ingressgateway version: 1.3.2
ingressgateway version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.1
pilot version: 1.3.1
pilot version: 1.3.2 
pilot version: 1.3.2
policy version: 1.3.2   
policy version: 1.3.2   
policy version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.1
telemetry version: 1.3.1

$ kubectl get pods -n istio-system
NAME                                      READY   STATUS      RESTARTS   AGE
istio-citadel-746b4cc66c-5nfdg            1/1     Running     0          4m40s
istio-cleanup-secrets-1.3.0-87mwp         0/1     Completed   0          43m
istio-galley-668765c7dc-7vbv2             1/1     Running     0          4m41s
istio-ingressgateway-76ff5cf54b-hsk87     1/1     Running     0          4m40s
istio-ingressgateway-76ff5cf54b-qt5hw     1/1     Running     0          4m32s
istio-ingressgateway-76ff5cf54b-z7bk7     1/1     Running     0          4m40s
istio-init-crd-10-1.3.0-s5vm6             0/1     Completed   0          44m  
istio-init-crd-10-1.3.1-45rmr             0/1     Completed   0          40m
istio-init-crd-11-1.3.0-tf47m             0/1     Completed   0          44m
istio-init-crd-11-1.3.1-mzghn             0/1     Completed   0          40m
istio-init-crd-12-1.3.0-k7jw5             0/1     Completed   0          44m
istio-init-crd-12-1.3.1-b2wkj             0/1     Completed   0          40m
istio-pilot-779bc5cd44-8rz9v              2/2     Running     0          7m26s
istio-pilot-779bc5cd44-g7zkf              2/2     Running     0          7m16s
istio-pilot-7b6f4b4498-bpm9q              0/2     Pending     0          4m15s
istio-pilot-7b6f4b4498-cd4c7              2/2     Running     0          4m30s
istio-pilot-7b6f4b4498-fzhw2              0/2     Pending     0          4m40s
istio-pilot-7b6f4b4498-kzmsk              0/2     Pending     0          4m   
istio-pilot-7b6f4b4498-rcdrh              2/2     Running     0          4m40s
istio-policy-8449665784-mf7xd             2/2     Running     0          4m40s
istio-policy-8449665784-vslg7             2/2     Running     0          4m32s
istio-policy-8449665784-zmtfk             2/2     Running     0          4m40s
istio-security-post-install-1.3.0-hlphk   0/1     Completed   0          43m  
istio-security-post-install-1.3.1-5j4tf   0/1     Completed   0          40m  
istio-security-post-install-1.3.2-8s2dd   0/1     Completed   0          4m42s
istio-sidecar-injector-7488c45bcb-6zlcq   1/1     Running     0          4m39s
istio-telemetry-56595ccd89-qcnsz          0/2     Pending     0          4m31s
istio-telemetry-56595ccd89-qsxsr          0/2     Pending     0          4m16s
istio-telemetry-56595ccd89-sjvfv          0/2     Pending     0          4m40s
istio-telemetry-56595ccd89-sk6xr          0/2     Pending     0          4m40s
istio-telemetry-56595ccd89-wx9t4          0/2     Pending     0          4m16s
istio-telemetry-768c56f5c7-7gwbf          2/2     Running     0          7m27s
istio-telemetry-768c56f5c7-f64mz          2/2     Running     0          7m17s
istio-telemetry-768c56f5c7-k7bcf          0/2     Pending     0          4m16s
istio-telemetry-768c56f5c7-zrqhx          0/2     Pending     0          4m31s
prometheus-5679cb4dcd-xs4sh               1/1     Running     0          43m

**Comment by howardjohn** [comment]
Your cluster is probably just not large enough to handle the rolling upgrade?

**Comment by elfinhe** [comment]
I used `kubectl top node` to track the CPU usage, which is always below 20%. 

```
NAME                                 CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
gke-c35-default-pool-008da879-l20g   148m         7%     1327Mi          23%
gke-c35-default-pool-008da879-lz7p   90m          4%     1453Mi          25%
gke-c35-default-pool-008da879-rcn8   99m          5%     1629Mi          28%
gke-c35-default-pool-008da879-xk8n   460m         23%    1758Mi          31%
```

@howardjohn, based on your experience, are we able to calculate the required CPUs, and memories for Istio upgrade or installation?

**Comment by howardjohn** [comment]
@elfinhe the cpu usage does not matter, what matters is the CPU requests. The requirement is ~2CPUS: 500m for pilot, 1100m for telemetry, 110m for policy, 50m for the rest

**Comment by elfinhe** [comment]
Yes, that makes sense.

The remaining question is around the number of pods. For the case in description, before upgrade, we had 1 pilot pod and 1 telemetry pod. After I applied the new version, suddenly we got 7 Pilot pods and 9 Telemetry pods. Is this the intended behavior? (Btw, I do not see this sudden increase of pod number when I upgrade istio in a big enough cluster.)

**Comment by howardjohn** [comment]
Thats not expected.. it seems like the HPA made those pods scale up somehow? I have never seen that happen

**Comment by howardjohn** [comment]
I don't think this is applicable anymore
