### ISSUE TITLE
need to access the file “etc/origin/master/master-config.yaml” on node? #istio

### ISSUE THREAD

**Issue by ajeetas** [istio/istio.io#5126]
Istio installation using docs “https://istio.io/docs/setup/platform-setup/openshift/“. How we can do WebhookAdmission in open shift cluster 4.1 on aws. file (etc/origin/master/master-config.yaml) should be present on master instance but its not.

**Comment by knrc** [comment]
@ajeetas That specific instruction is for OpenShift 3.x based installations, if you are using OpenShift 4.1 then the admission controllers are enabled by default.  I'm just back from PTO but will take a look at submitting a docs PR in the next few days.

**Comment by howardjohn** [comment]
This has been removed
