### ISSUE TITLE
Unescaped Asterisks in docs/reference/config/authorization/istio.rbac.v1alpha1/index.html

### ISSUE THREAD

**Issue by armsnyder** [istio/istio.io#5218]
The asterisks in the description for ServiceRole's `paths` field contain asterisks which are unescaped in the markdown, causing them to not appear in the rendered documentation.

istio.io/content/en/docs/reference/config/authorization/istio.rbac.v1alpha1/index.html

See missing asterisks here: https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1/#AccessRule

**Comment by geeknoid** [comment]
This needs to be fixed in the protos in istio/api.

**Comment by howardjohn** [comment]
This is removed
