### ISSUE TITLE
The download script is outdated and cannot be updated it appears

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#5220]
https://preliminary.istio.io/docs/setup/#downloading-the-release

In this step is a download script.  Their is no way to replace a git.io shorted url.  I'm unclear why we are using git.io as a service for url shortening if it can't be modified.  I think it would be far superior to include this script on Istio.io (in the static directory).

Additionally it would make sense to implement a similar script that retrieves istioctl for evaluations.

**Comment by geeknoid** [comment]
This is an old old link from the early days. It can't be modified, so the target on istio/istio has been kept up the date.

FYI @howardjohn @ericvn

**Comment by ericvn** [comment]
Note that I have an issue already for this: https://github.com/istio/istio/issues/17178

There is a PR for that issue which I can tweak some based on discussion yesterday (rc changed to beta with the server doc was one item). The follow-on to that PR was to use istio.io links (tested by @geeknoid earlier).

**Comment by geeknoid** [comment]
All fixed.
