### ISSUE TITLE
Update VM Bookinfo Doc 

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.io#5234]
AFAICT, `istioctl register` is deprecated -- and perhaps more importantly -- no longer required for mesh expansion.

We should update the Mesh Expansion docs to remove that step from https://istio.io/docs/examples/mesh-expansion/single-network/#running-services-on-a-mesh-expansion-machine, etc.

/cc @costinm

**Comment by rcaballeromx** [comment]
@douglas-reid Yes, we definitely should and we are working towards improving all VM-related content.
You can review the first step towards that goal in #5215

**Comment by stevenctl** [comment]
The only example left is this doc: https://preliminary.istio.io/latest/docs/examples/virtual-machines/bookinfo/
