### ISSUE TITLE
Call for keeping on the Chinese doc maintenance

### ISSUE THREAD

**Issue by rootsongjc** [istio/istio.io#5250]
Dear @istio/wg-docs-maintainers , as you all know, since last year the [ServiceMesher community](https://www.servicemesher.com) was responsible for the translation of istio website. The community has submit [700+ PR](https://github.com/istio/istio.io/pulls?q=is%3Apr+is%3Aclosed+label%3Atranslation%2Fchinese) merged. 

However, the translation work has been stuck in version 1.2 for a long time. Recently, people often ask me where the Chinese documents are? I had to tell them it was archived  [here](https://archive.istio.io/v1.2/zh). Today I asked how many people in the community want to participate the Chinese doc translation activities. There will be dozens of people involved. Now we intend to restart translation and maintenance. 

If you have no objection, we will make a plan and start the translation next week.

**Comment by malphi** [comment]
As the largest service mesh community in China, we've defined a detailed and effective plan to finish the translation mission with overconfidence.

**Comment by geeknoid** [comment]
This is great news. Keeping up with our fast moving docs is definitely a
challenge, I'm glad you're taking it on. Please let me know if we can make
any process improvements to make your job easier.

**Comment by owen-sun** [comment]
Glad to see there are so many volunteers willing to contribute the translation, this will benefit the large service mesh community in China.

**Comment by yuxiaobo96** [comment]
That sounds like a good news.
I want to be a member of the translation istio documentation.
Should I join the ServiceMesher community first?

**Comment by rootsongjc** [comment]
@yuxiaobo96 yes, you should join ServiceMesher community first. Look [here](https://www.servicemesher.com/contact/) to find how to join the community.

**Comment by yuxiaobo96** [comment]
@rootsongjc Okay thank you.

**Comment by sbilly** [comment]
support

**Comment by rootsongjc** [comment]
[Here](https://docs.google.com/document/d/1zhXz9dJeLOzD7lqQadwzQ06PrDdh0H8p2Osyz4baK28/) is the translation plan drafted by @malphi 

## Principles
1. We will follow the master branch to translate and every PR can preview on https://preliminary.istio.io/zh/ page just like before. @geeknoid Is the page disabled now?
1. Translate all of the contents for website, including document, blog, FAQ and about.
1. Define glossary for the unification of translation.
1. Translation task and process tracking [here](https://github.com/servicemesher/istio-official-translation)
1. Use Scrum and [this Github project](https://github.com/servicemesher/istio-official-translation/projects/3) as a tool to manage the process.
1. A translation task includes translating and 2 round reviewing processes to ensure the quality of translation. 
1. When the Chinese and English versions are almost synchronized, we can release the Chinese version on https://zh.istio.io or https://istio.io/zh

**Comment by rootsongjc** [comment]
@geeknoid We plan to uncomment these in `config.yaml` to make Chinese docs show up.
```
#    [languages.zh]
#        contentDir = "content/zh"
```
And copy the English docs to `content/zh`, translate every single page one by one. Can you make https://istio.io/zh bring out and preview on https://preliminary.istio.io/zh ?

If you think this is OK, I will make a PR.

**Comment by rcaballeromx** [comment]
@rootsongjc I'm very happy to see that the community is once again translating the content into ZH. 
If there is anything I can do to help, please let me know.

**Comment by rootsongjc** [comment]
@rcaballeromx Thank you if I or the ServiceMesher community need any help, I will let you know. 😄

**Comment by rootsongjc** [comment]
We already gathered 60 contributors since the translation activity restarted. So I'll close this issue if anyone wants to join us, you can find the way in https://github.com/servicemesher/istio-official-translation
