### ISSUE TITLE
Possibly revert `Kubernetes Services for Egress Traffic`

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#5255]
This was merged with merged with istio/istio.io#4710, but doesn't work as expected. See https://github.com/istio/istio/issues/18208. Either the underlying Istio problem,  https://github.com/istio/istio/issues/17112 ?, needs to be fixed, the task updated so that it works, or the page should be reverted.

**Comment by vadimeisenbergibm** [comment]
Should be fixed by https://github.com/istio/istio.io/pull/5261.

**Comment by jwendell** [comment]
Can we close this then?
