### ISSUE TITLE
Issue with docs/reference/config/installation-options-changes/index.md

### ISSUE THREAD

**Issue by elfinhe** [istio/istio.io#5259]
global.podDNSSearchNamespaces missing in installation-options.

But it is used by [multi-cluster example yaml](https://raw.githubusercontent.com/istio/istio/release-1.3/install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml) in [multi-cluster doc](https://istio.io/docs/setup/install/multicluster/gateways/).

Add a row for it?

**Comment by geeknoid** [comment]
@sdake We need to regen the helm tables for 1.4 (tablegen.py and tablegen_diff.py). Can you take a crack?
