### ISSUE TITLE
Fix istioctl manifest command which has an index

### ISSUE THREAD

**Issue by ostromart** [istio/istio.io#5275]
egress-gateway-tls-origination/index.md has an array index in the --set which doesn't work with istioctl. This command must be refactored to use a YAML input file instead.

**Comment by shamsher31** [comment]
Verified the following pages don't have `--set` command and is replaced by YAML examples.

https://preliminary.istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/
https://preliminary.istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination-sds/
