### ISSUE TITLE
Istio "Pods and Services" requirements do not specify how an app must listen

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#5278]
This came up discussing https://github.com/istio/istio/issues/17918 .

The Envoy sidecar needs to be able to talk to the pod.  Typically it talks on `localhost`, but this can be configured through a Sidecar configuration https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/#IstioIngressListener to use a Unix domain socket.

Can we add to https://preliminary.istio.io/docs/setup/additional-setup/requirements/ the requirement that the app listen on `localhost`, possibly with a link to a FAQ explaining that some apps might need to have their configuration tweaked?

**Comment by howardjohn** [comment]
Done https://preliminary.istio.io/latest/docs/ops/deployment/requirements/#application-bind-address
