### ISSUE TITLE
Deployment Models item seems out of place on Setup tab

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#5300]
I know this item was moved from the concepts tab, but it seems out of place relative to all the other setup items. I would think it should go back to the Concepts tab or maybe it could be put on a tab between Install and MultiCluster Installation (the later being a sub page to deployment models). I'm not sure I like the later idea, but still better that just hanging it out there.

**Comment by frankbu** [comment]
#5137 moved it to the Operations section.
