### ISSUE TITLE
Kiali page needs to be updated

### ISSUE THREAD

**Issue by jwendell** [istio/istio.io#5307]
https://preliminary.istio.io/docs/tasks/observability/kiali/

It needs to cover the new `istioctl manifest` method of installation.

When using the `demo` profile, kiali comes pre-installed. Otherwise, the user needs to install it after installing the control plane.

cc @jmazzitelli

**Comment by jmazzitelli** [comment]
https://github.com/istio/installer/pull/503 will upgrade Kiali. I will work on the docs page once I confirm everything is ready and working with istioctl
