### ISSUE TITLE
curl host-name--vs.--IP-address issue on docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#5310]
*WITHDRAWN*. (I was using the INGRESS_HOST setting from the Control Ingress Traffic task instructions page, which can result in setting INGRESS_HOST to the host name instead of the IP address. 

However, there may still be a problem on docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md: Its instructions to set `INGRESS_HOST` don't account (as the Control Ingress Traffic instructions do) for when "`kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}'`" doesn't return an IP address because only `.status.loadBalancer.ingress[0].hostname` exists).)

Regarding the section at
https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/#configure-a-tls-ingress-gateway-for-a-single-host, in particular it's "5. Send an HTTPS request to access the httpbin service through HTTPS:" step:

The `curl` command that includes:
```
  --resolve httpbin.example.com:$SECURE_INGRESS_PORT:$INGRESS_HOST
```
fails if INGRESS_HOST is a host name rather than an IP address e.g., if it's "`localhost`", taken directly from the "`export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')`" command on the page at https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/

Maybe the instructions should say to put the resolved address in the `curl` command rather than just what's in `INGRESS_HOST`.

Maybe the (upstream) instructions should set a `INGRESS_IP_ADDR` and that should be used in the `curl` command (and maybe in others too).

Maybe the `curl` command should be adjusted to use `$( ... )` to call a some subcommand to resolve the value from $INGRESS_HOST to an IP address in case it isn't an IP address already.

(That's at least for curl version 7.54.0 ("`curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.4 zlib/1.2.11 nghttp2/1.24.1`").)

**Comment by howardjohn** [comment]
Closing as "withdrawn"
