### ISSUE TITLE
OpenShift 4.x CNI settings should be documented

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio.io#5314]
I installed Istio 1.4 beta1 on OpenShift 4.2 using the helm charts (I did not try yet with the new istioctl as this is broken in 1.4 beta1, but I believe the same settings will be required).

My bookinfo demo was not collecting telemetry for any interior pods (only ingress gateway telemetry was collected - but no telemetry was collected for the pods inside bookinfo).

Turns out I needed to pass in two custom CNI settings when processing the istio-cni helm chart:

* `cniBinDir=/var/lib/cni/bin`
* `cniConfDir=/var/run/multus/cni/net.d`

So I had to run this to get it to work:

```
helm template "<istio-install>/install/kubernetes/helm/istio-cni" --name istio-cni --namespace kube-system --set cniBinDir=/var/lib/cni/bin --set cniConfDir=/var/run/multus/cni/net.d | oc apply -f -
```

I think these two cni settings should be documented in this table (add a row for OpenShift 4.x):

https://preliminary.istio.io/docs/setup/additional-setup/cni/#hosted-kubernetes-settings

**Comment by howardjohn** [comment]
its there now https://preliminary.istio.io/latest/docs/setup/additional-setup/cni/#hosted-kubernetes-settings
