### ISSUE TITLE
tablegen.py needs a rerun

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#5343]
Run tablegen.py for master

Related to this issue #5259

**Comment by geeknoid** [comment]
tablegen-diff.py also needs a rerun...

**Comment by howardjohn** [comment]
@geeknoid is this done by https://preliminary.istio.io/docs/reference/config/installation-options/?

**Comment by geeknoid** [comment]
This work is still pending: https://github.com/istio/istio.io/pull/5344

**Comment by sdake** [comment]
I am unable to make forward progress on this issue without a significant investment of time (writing a yaml parser... do we really need another one?). While it is unfortunate, any fields that people think are relevant for helm documentation should be manually updated.

Using the in-repo code that @johnma14 wrote should be workable for istiod. Please file any new bugs for istiod helm reference documentation and assign it to @johnma14.
