### ISSUE TITLE
Multi cluster installs are not working

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#5515]
At last check, all 3 of the multi cluster install scenarios are failing on istio.io. This issue is for changes required in the istio.io documentation. There was a beta.3 build last night but I now that the latest installer PR https://github.com/istio/installer/pull/517 is not in that. It is in the 1.4-alpha.b632400c69f127ae453352784567497ddbf05f3a build which I will test with today.

I know there was discussion during the Doc WG call yesterday that these 3, plus 2 platform specific examples, may be removed from the documentation and replaced with a new example based on the document by @ayj. There has been no testing of that documentation on platforms other than GKE (to my knowledge). I know @linsun want at least the `Replicated Control Plane` example to stay in the documentation.

There is a sister issue, https://github.com/istio/istio/issues/18785, to this for changes required in istio.

**Comment by ericvn** [comment]
I will start with the `Replicated Control Plane documentation this morning to see if it works with the latest build mentioned above. I know there are are least instructions missing to enable coreDNS in the istio installs as instructions later in the page expect it and it's not there.

**Comment by ericvn** [comment]
#5495 is the WIP PR for the new multicluster scenario mentioned above.

**Comment by howardjohn** [comment]
Is this done and/or duplicate of #18785? Both are marked as release blocker

**Comment by ericvn** [comment]
I think at this point I will close this one since we probably aren't going to take anymore code changes. The `Replicated Control Plane` and `Shared Control Plane (multi-network)` are working with the `istioctl` install. @elfinhe is still working the `Shared Control Plane (multi-network)`, but we can revert back to the `helm` install (I believe that still works).

**Comment by ericvn** [comment]
Oops. Meant to close the istio/istio one as we won't pull more code. We may need more doc changes so leaving this one open.

**Comment by howardjohn** [comment]
@ericvn is this fixed? If not can you describe exactly what is left?

**Comment by ericvn** [comment]
This is now fixed so closing..
