### ISSUE TITLE
Provide download istioctl instructions

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#5657]
Folks,

We do have a simple cmd to download istioctl down however I'm unsure where I should put this in docs.  Please advise.

Instructions:  https://github.com/istio/istio/issues/18905#issuecomment-553104873

K8s's doc has it under tasks, tools:  https://kubernetes.io/docs/tasks/tools/install-kubectl/

@frankbu @geeknoid

**Comment by frankbu** [comment]
@linsun I think a section titled `Download and install istioctl` in this doc would work: https://preliminary.istio.io/docs/ops/diagnostic-tools/istioctl/

Then we would link to it from a few other places.

**Comment by sdake** [comment]
@frankbu I tend to think the process of downloading istioctl should be front and center, and not necessarily linked into the ops guide.  I'd recommend a boilerplate.

**Comment by frankbu** [comment]
@sdake I'm assuming this section is a little more info than you want to inline all over the place. It needs to say that if you downloaded the release, you don't need to download istioctl separately. It should include the verify instructions, etc.

I agree that it needs to be front-and-center in the install instructions, that's what I meant by `Then we would link to it from a few other places`. That link would likely be a boilerplate.
