### ISSUE TITLE
Update v2 telemetry docs

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.io#5658]
https://preliminary.istio.io/docs/ops/telemetry/in-proxy-service-telemetry/

1. Change the experimental to alpha
2. Show 2 ways of enabling it
    A. Use istioctl to enable it.
    B. Describe helm based approach
          1. disable http mixer reporting  via meshconfig.
          2. Run kubectl apply with filters

**Comment by richardwxn** [comment]
The helm based approach was already removed from this doc, do we still need to add back? Instead, I think we should list these two ways: 1.using istioctl 2. manual steps to update meshconfig and then run kubectl apply of fitlers
