### ISSUE TITLE
Issue with docs/ops/diagnostic-tools/istioctl/index.md

### ISSUE THREAD

**Issue by stewartbutler** [istio/istio.io#5698]
ZSH autocompletion is missing from the 1.4.0 release package. The website may need updating, or the release package may need to have it added. 

The _istioctl file should be located in istio-1.4.0/tools/.

**Comment by ericvn** [comment]
Fixed with https://github.com/istio/release-builder/pull/75. This should be available in the 1.4.1 archive after one more change to get the release-builder change picked up.

**Comment by ericvn** [comment]
Looked at a build from last night, https://gcsweb.istio.io/gcs/istio-build/dev/1.4-alpha.a023448f734d4b8622c20b214e0c413e394c9eb2/, I see the two files in the _tools_ directory.
