### ISSUE TITLE
the invalid url 

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio.io#5747]
file path  url
istio.io\content\en\docs\reference\config\policy-and-telemetry\adapters\apigee\index.html 
https://istioservices.apigee.net/edgemicro

istio.io\content\zh\docs\reference\config\policy-and-telemetry\adapters\signalfx\index.html 
https://istio.io/docs/reference/config/policy-and-telemetry/adapters/signalfx.html

https://istio.io/docs/reference/config/policy-and-telemetry/adapters/signalfx.html is not exsisted in /en,but this exsists in zh/.Maybe we neet to upgrade them.

**Comment by tanjunchen** [comment]
@rootsongjc  can you review this issue about zh/ folder

**Comment by rootsongjc** [comment]
@tanjunchen Keep the Chinese content sync with English.
