### ISSUE TITLE
Multicluster Installation documentation Istio 1.4

### ISSUE THREAD

**Issue by daniel-gut** [istio/istio.io#5824]
The documentation for the multicluster seems to reference a file not available in the Istio repository. See Docu [Setup cluster 1 (primary)](https://istio.io/docs/setup/install/multicluster/shared-gateways/#setup-cluster-1-primary)

`istioctl manifest apply --context=$CTX_CLUSTER1 \
  -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-primary.yaml`

**Comment by ericvn** [comment]
The file location specified in the documentation is that within the installation archive.  The repo location for that file is:

https://github.com/istio/operator/blob/master/data/examples/multicluster/values-istio-multicluster-gateways.yaml (change for the release branch).

**Comment by ericvn** [comment]
It is possible to add a note in the documentation as to the actual location if you believe that is important. I know there are probably similar comments that could be made for other parts of the document for other files. @frankbu Thoughts?

I'll close this issue with the above information. If you feel the documentation should be updated, you can reopen this issue or open an issue in the istio.io repository for updating the document.
