### ISSUE TITLE
Security Bulletin could use more info

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#5902]
Right now it's a bunch of links to CVE/istio security IDs

Even being familiar with all of them, I couldn't tell you what they are without looking further.

I think we should include impacted versions and a short description (could be a couple words even) at least. Maybe severity score as well?

Maybe also a list of "safe" versions ("1.2.8+ and 1.3.5+" for example)

**Comment by geeknoid** [comment]
@fpesce A simple improvement here is to:

- Go in all the security bulletin files in content/en/news/security/* and change the description: in the front-matter from the current generic "security vulnerability disclosure for CVE XXX" to an actual description of the issue as a one-line summary.

- Then removing lines 33-42 in layouts/_default/security-grid.html will display these descriptions on the security bulletin page.

**Comment by geeknoid** [comment]
https://github.com/istio/istio.io/pull/5939 does most of this. If we can go through the individual bulletins and write proper descriptions for them, then we can reflect those descriptions on the top-level bulletin page.
