### ISSUE TITLE
Istio Chinese translation monthly and Chinese doc maintainers updation request

### ISSUE THREAD

**Issue by rootsongjc** [istio/istio.io#5928]
Hi @istio/wg-docs-maintainers, It has been a month since the new round of Istio Chinese translation activities started from Oct 29, 2019. This is our transcript.
- PR merged: 215
- Contributors: 56
## Chinese translation monthly
Data from 10/29 - 11/29.
![PRs merged per day](https://user-images.githubusercontent.com/3328185/69843261-b392d300-12a1-11ea-99aa-a4c165877ae6.png)
![PR Author Top 10](https://user-images.githubusercontent.com/3328185/69843262-b4c40000-12a1-11ea-90e9-f9890075e6f9.png)
![PR reviewers top 10](https://user-images.githubusercontent.com/3328185/69843266-b7265a00-12a1-11ea-8cb8-a380ef0dca32.png)
![Days elapse until PR merged](https://user-images.githubusercontent.com/3328185/69843267-b8f01d80-12a1-11ea-8c0f-3999d54f6287.png)
<img width="1328" alt="1E3EE204-9D22-4FF2-AA62-9AA7E7FC834E" src="https://user-images.githubusercontent.com/3328185/69843292-ce654780-12a1-11ea-87a3-67856fd7f324.png">
![image](https://user-images.githubusercontent.com/3328185/69858590-4d23aa00-12cd-11ea-9199-0183c3c143d5.png)

We really appreciate the efforts of ServiceMesher community members.
## More maintainers request
However, because the workload is too large, we urgently need more reviewers and also maintainers to review. I would like to recommend someone who has taken an active role in translation activities like the Chinese doc Maintainer. 

For example @tanjunchen @vivian99-wu  @ilylia @malphi @yuxiaobo96 @huntsman-li, I don't know if there is a limit on the number of maintainers and what are the intentions of the candidates? See [Maintainer's requirements](https://github.com/istio/community/blob/master/ROLES.md#maintainer). @istio/wg-docs-maintainers-chinese  @geeknoid

**Comment by geeknoid** [comment]
@duderino Could you send a maintainer agreement form to the folks that @rootsongjc pointed out above. If they accept, we can add them to the Chinese maintainer team and they can then approve PRs and move things along.

**Comment by rootsongjc** [comment]
@duderino Any progress？

**Comment by duderino** [comment]
I think it's fine to just add them directly

**Comment by rootsongjc** [comment]
New round has begun https://github.com/istio/istio.io/issues/9128
