### ISSUE TITLE
Issue with docs/tasks/observability/gateways/index.md

### ISSUE THREAD

**Issue by senare** [istio/istio.io#5929]
Seams that the Cert example is outdated ...

$ cat <<EOF | kubectl apply -f -
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: telemetry-gw-cert
  namespace: istio-system
spec:
  secretName: telemetry-gw-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: $TELEMETRY_DOMAIN
  dnsNames:
  - $TELEMETRY_DOMAIN
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - $TELEMETRY_DOMAIN
---
EOF
certificate.certmanager.k8s.io "telemetry-gw-cert" created

Gives me 

no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"

Changing to the ''newer' 

apiVersion: cert-manager.io/v1alpha2
kind: Certificate

Seams to work .... with out errors

**Comment by douglas-reid** [comment]
This example was most certainly out of date, but the docs have been updated many times over since then. Closing for now.
