### ISSUE TITLE
Gateway issue with ssl certificates for istio.1.4.1

### ISSUE THREAD

**Issue by raginireddy96** [istio/istio.io#6071]
I have created gateway and virtualservice. When i tried to connect to endpoint i am getting error. I am using ssl certificates and created secret as well.
Please let me know if i am missing anything.

Below is the error i am getting when try to reach end point

curl -v https://snpr-proxy.lendingkart.com/api/actuator/health
*   Trying 13.250.85.146...
* TCP_NODELAY set
* Connected to snpr-proxy.lendingkart.com (13.250.85.146) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=IN; ST=Karnataka; L=Bangalore; O=Lendingkart Technologies Private Limited; CN=*.lendingkart.com
*  start date: Jul 16 00:00:00 2018 GMT
*  expire date: Sep 18 12:00:00 2020 GMT
*  subjectAltName: host "snpr-proxy.lendingkart.com" matched cert's "*.lendingkart.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x96ab70)
> GET /api/actuator/health HTTP/2
> Host: snpr-proxy.lendingkart.com
> User-Agent: curl/7.61.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 503 
< content-length: 95
< content-type: text/plain
< date: Fri, 13 Dec 2019 06:44:22 GMT
< server: istio-envoy
< 
* Connection #0 to host snpr-proxy.lendingkart.com left intact
### ****upstream connect error or disconnect/reset before headers. reset reason: connection termination****
 

Below is gateway.yaml file for your referance
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"lk-https-gateway","namespace":"app"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["snpr-proxy.lendingkart.com"],"port":{"name":"lk-https","number":443,"protocol":"HTTPS"},"tls":{"credentialName":"tls-certificate","mode":"SIMPLE"}}]}}
  creationTimestamp: "2019-12-12T11:52:45Z"
  generation: 1
  name: lk-https-gateway
  namespace: app
  resourceVersion: "19136615"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/app/gateways/lk-https-gateway
  uid: e8fd8d45-1cd5-11ea-a066-0649be130e3e
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - snpr-proxy.lendingkart.com
    port:
      name: lk-https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: tls-certificate
      mode: SIMPLE

Below is the virtualservice file for your referance

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"lk-external-services","namespace":"app"},"spec":{"gateways":["https-gateway"],"hosts":["*"],"http":[{"match":[{"uri":{"prefix":"/api/actuator"}}],"route":[{"destination":{"host":"app-lkart-api","port":{"number":9010}}}]},{"match":[{"uri":{"prefix":"/api"}}],"route":[{"destination":{"host":"app-lkart-api","port":{"number":80}}}]},{"match":[{"uri":{"prefix":"/internal/actuator"}}],"route":[{"destination":{"host":"app-lkart-internal","port":{"number":9011}}}]},{"match":[{"uri":{"prefix":"/internal"}}],"route":[{"destination":{"host":"app-lkart-internal","port":{"number":80}}}]},{"match":[{"uri":{"prefix":"/nucleus/actuator"}}],"route":[{"destination":{"host":"app-nucleus-api","port":{"number":8894}}}]},{"match":[{"uri":{"prefix":"/nucleus"}}],"route":[{"destination":{"host":"app-nucleus-api","port":{"number":80}}}]}]}}
  creationTimestamp: "2019-12-12T11:52:55Z"
  generation: 3
  name: lk-external-services
  namespace: app
  resourceVersion: "19143518"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/app/virtualservices/lk-external-services
  uid: ef70b448-1cd5-11ea-a066-0649be130e3e
spec:
  gateways:
  - lk-https-gateway
  hosts:
  - snpr-proxy.lendingkart.com
  http:
  - match:
    - uri:
        prefix: /api/actuator
    route:
    - destination:
        host: app-lkart-api
        port:
          number: 9010
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: app-lkart-api
        port:
          number: 80
  - match:
    - uri:
        prefix: /internal/actuator
    route:
    - destination:
        host: app-lkart-internal
        port:
          number: 9011
- match:
    - uri:
        prefix: /internal
    route:
    - destination:
        host: app-lkart-internal
        port:
          number: 80
  - match:
    - uri:
        prefix: /nucleus/actuator
    route:
    - destination:
        host: app-nucleus-api
        port:
          number: 8894
  - match:
    - uri:
        prefix: /nucleus
    route:
    - destination:
        host: app-nucleus-api
        port:
          number: 80

**Comment by raginireddy96** [comment]
Hi Please help to resolve the issue.

**Comment by howardjohn** [comment]
This repo is for documentation bugs, if you have issues with the product please ask at https://discuss.istio.io/. thanks!
