### ISSUE TITLE
allow istioctl manifest apply to accept annotation values

### ISSUE THREAD

**Issue by shaunc** [istio/istio.io#6164]
E.g.
```
istioctl manifest apply --set profile=default --set values.grafana.enabled=true --set gateways.istio-ingressgateway.serviceAnnotations.\"service.beta.kubernetes.io/aws-load-balancer-type\"=\"nlb\"
```
Or other syntax -- I played around with passing whole map, different quoting, etc... always generates error.

istioctl version 1.4.2

**Comment by anton-yurchenko** [comment]
Seems like currently, we will have to `kubectl edit service -n istio-system istio-ingressgateway` directly. 
But what will happen on update? :worried:

**Comment by anton-yurchenko** [comment]
@shaunc, I think this issue should be raised in a different [repository](https://github.com/istio/istio).

Anyway, it looks to be a known issue, you may follow this [Issue](https://github.com/istio/istio/issues/19196).

**Comment by shaunc** [comment]
Ok -- thanks! -- will follow there.
