### ISSUE TITLE
Unable to track the traffic or request logs for multicluster communication

### ISSUE THREAD

**Issue by krimeshshah** [istio/istio.io#6226]
Hello Team,

I have set up cross cluster communication with istio with replicated control plane method using document in https://istio.io/docs/setup/install/multicluster/gateways/ . As shown in document I have set up to make sleep service in cluster1 send request and communicate with httpbin service in cluster2. 
Although I get request response code 200 Ok , but although before that when it was not working I could not  to track the request logs or call made from sleep service to http bin service to analyze errors and issues.

I tried to check , name space events, logs of both sleep & httpbin pods logs in istio-ingressgateway pods.

Can you tell me where do I look for the logs , in case of I face issues with its communcation?

Regards,
Krimesh

**Comment by howardjohn** [comment]
PTAL https://istio.io/latest/docs/tasks/observability/logs/access-log/
