### ISSUE TITLE
Issue with docs/reference/config/networking/gateway/index.html

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#6285]
issue for "cipherSuites" parameter configuration. In production environment, the cipher suite will not use envoy proxy default cipher suite, user always wants to configure the cipher suite, but we found there are many cipher suite does not support, so please add more detail here which kind of cipher suites are support or not support. e.g. GCM is supported, but cbc mode is not supported etc. otherwise, we need to test again and again to find the list.

**Comment by howardjohn** [comment]
The supported suites are now documented in https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings. Thanks!
