### ISSUE TITLE
Searching on Bing returns Istio content from preliminary.istio.io and archive.istio.io before istio.io

### ISSUE THREAD

**Issue by geeknoid** [istio/istio.io#6304]
If you go to Bing (or search in the Edge browser, which uses Bing) for Istio content, you tend to see results from preliminary.istio.io and archive.istio.io before results for istio.io. For example, you can search for "istio pods and services" and you get a bunch of links which aren't what you want.

For Google, we've got things configured to prevent Google from returning links to preliminary.istio.io and archive.istio.io. We should set things up so Bing has the same behavior.

@jasonall FYI

**Comment by brian-avery** [comment]
Should preliminary.istio.io be indexed at all? I can see archive being indexed for older releases, but preliminary is still in development.

**Comment by howardjohn** [comment]
seems istio.io pops up first now, but preliminary does show up
