### ISSUE TITLE
Create a new maintainer team for translate pt-br

### ISSUE THREAD

**Issue by jhonmike** [istio/istio.io#6309]
the next steps of https://github.com/istio/istio.io/pull/6230, I would like to create a team for maintainers of the portuguese language brazil:

`WG - Docs Mintainers/Brazil.` or `WG - Docs Mintainers/Portuguese-BR.`

@istio/wg-docs-maintainers-infra

**Comment by jhonmike** [comment]
I would like to reinforce the request for the creation of the team, to continue with the translations, I have a PR stopped a few days here #6337

**Comment by jhonmike** [comment]
@gbaufake can you help me with this issue?

**Comment by gbaufake** [comment]
We already have the team. I am.sole member for now.

Let check what I need to include otger members.
