### ISSUE TITLE
Distributed Tracing reference sample services code

### ISSUE THREAD

**Issue by ayj** [istio/istio.io#631]
* https://istio.io/docs/tasks/telemetry/distributed-tracing.html#understanding-what-happened makes a reference to the sample services. It might be helpful to provide a link to the sample service source code _or_ change the wording a bit so user doesn't think they need to go look somewhere else to understand whats happening.

* _Cleanup_ is missing a step to stop the port-forwarding to the pod, e.g. `killall kubectl`

**Comment by douglas-reid** [comment]
I think this has been overcome by events.
