### ISSUE TITLE
Suggestions for docs/tasks/telemetry/metrics-logs.html 

### ISSUE THREAD

**Issue by ayj** [istio/istio.io#632]
* _before you begin_ mentions `configDefaultNamespace` configuration. Why does a user running through the example tasks care about that? I don't see it mentioned anywhere else in the docs.

* _before you begin_ mentions installed prometheus addon but links to prometheus.io. User needs to reference another page to figure out where the addon file is located. Maybe add `kubectl apply -f install/kubernetes/addons/prometheus.yam` inline ?

**Comment by ayj** [comment]
Similar comment for installing Prometheus applies to https://istio.io/docs/tasks/telemetry/tcp-metrics.html#before-you-begin

**Comment by guptasu** [comment]
https://github.com/istio/istio.github.io/pull/654

**Comment by douglas-reid** [comment]
I think this should have been closed ?
