### ISSUE TITLE
Configuring Istio Ingress with AWS NLB using istioctl

### ISSUE THREAD

**Issue by abhinavkorpal** [istio/istio.io#6323]
Issues with the docs https://istio.io/blog/2018/aws-nlb/
 Please update the docs to create NLB from istioctl.

**Comment by howardjohn** [comment]
This is documented in https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#source-ip-address-of-the-original-client now. It might be nice to have on more gateway-focused docs but I think this is a reasonable for now
