### ISSUE TITLE
The cherrypick/release-x.x label is unreliable

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#6332]
Adding a cherrypick/release-x.x label to a PR often fails to create the cherrypick PR after the original PR merges. Sometimes the failure is because of branch incompatibility. In this case, it produces an error message which indicates that the cherrypick will need to be done manually. This is understandable and acceptable. 

However, sometimes (often?) the label simply has no effect. No cherrypick PR is created and no error message is produced. As a result, somebody needs to always follow up and check if the label worked or not, and if not add an explicit `/cherrypick release-x.x` comment to do it manually.

The label should be reliable, so this extra manual followup work isn't needed.

Here's an example of a PR that had the label but did not create the cherrypick PR: https://github.com/istio/istio.io/pull/6330

**Comment by frankbu** [comment]
This seems to have gotten worse lately, happens at least 50% of the time. Has anything changed?

**Comment by frankbu** [comment]
@clarketm Are you working on this? It's starting to become a big problem because we are losing track and missing changes sometimes, because the expected cherrypick never happens.

**Comment by howardjohn** [comment]
Tracked in https://github.com/istio/test-infra/issues/2309
