### ISSUE TITLE
Cherrypick PRs should not require @googlebot I consent

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#6333]
After a PR from a non-googler is merged, if it includes a cherrypick/release-x.x label, the corresponding cherrypick PR requires a `@googlebot I consent` comment from the contributor(s) of the original PR.

This shouldn't be necessary, since the content has already been checked for CLA conformance in the original PR (i.e., this is just the same change that has already been approved and merged in the master branch).

The bigger problem is that it is often very difficult to get the attention of the original contributor to add the required `@googlebot I consent` comment to allow the PR to merge, resulting in unnecessary delays, and often simply needing to override the process by administrator force merge of the PR.

Here is one of many cherrypick PRs that was force merged because of the desire to have the change appear on istio.io ASAP, but lack of response from the original contributor: https://github.com/istio/istio.io/pull/6328#issuecomment-572772825

**Comment by clarketm** [comment]
> The fix doesn't seem to work, maybe only if the PR is assigned to a non Googler?
> 
> [#7119 (comment)](https://github.com/istio/istio.io/pull/7119#issuecomment-617243998)

There are additional procedures needed internal at Google to complete the whitelist. I am actively working on this!

**Comment by clarketm** [comment]
This is now resolved. We can verify once a non-members commit is cherry picked.

**Comment by clarketm** [comment]
The whitelisting measures still do not provide resolution. Investigating further:

e.g.
https://github.com/istio/istio/pull/23382
https://github.com/istio/istio/pull/23365
https://github.com/istio/istio/pull/23361

**Comment by frankbu** [comment]
Interestingly, it did work on istio/istio.io this morning: https://github.com/istio/istio.io/pull/7179

I noticed that the [googlebot comment](https://github.com/istio/istio.io/pull/7179#issuecomment-621265136) appeared, but then the `cla: yes` label got added automatically and the PR merged. No other manual intervention was needed.

**Comment by frankbu** [comment]
Actually, looking more closely, the PR has both cla: yes and cla: no labels.
![image](https://user-images.githubusercontent.com/2752495/80635218-9cf7d000-8a29-11ea-888e-ced88e907f27.png)
But it did merge when approved.

**Comment by clarketm** [comment]
> Interestingly, it did work on istio/istio.io this morning: #7179
> 
> I noticed that the [googlebot comment](https://github.com/istio/istio.io/pull/7179#issuecomment-621265136) appeared, but then the `cla: yes` label got added automatically and the PR merged. No other manual intervention was needed.

That is strange, indeed. Since currently the `cla: yes` label is applied immediately after the PR is created, my original thought was that there was a race condition with the scan. For example in https://github.com/istio/istio/pull/23382, note that if the `istio-testing` bot waits until after the `google-bot` comments to add the `cla: yes` label it works successfully.

**Comment by frankbu** [comment]
This is strange, it's adding cla: yes and cla: no when it removes cla: 
![image](https://user-images.githubusercontent.com/2752495/80636054-d0872a00-8a2a-11ea-8866-79c85ca00b4f.png)

**Comment by clarketm** [comment]
> Actually, looking more closely, the PR has both cla: yes and cla: no labels.

I noticed that as well. I reopened the bug I have internally for `google-bot`, since this is not _expected_ behavior. I will see is there are any workarounds in the meantime.

**Comment by clarketm** [comment]
Unfortunately, the owners of the `google-bot` cannot fix the race condition. As a alternative resolution, I am adding _conditional label_ support to the cherrypicker plugin: https://github.com/kubernetes/test-infra/pull/17615. This will allow us to to react to the `cla: no` label event and _explicitly_ override it with the `cla: yes` label.

**Comment by ericvn** [comment]
Any further news here? I know that this can hold out cherry-pick PRs as we wait for the Googler to approve them. Even if all the authors consent, the CLA is not changed to yes.

**Comment by frankbu** [comment]
Closing as this is fixed for a while now.
