### ISSUE TITLE
Fix inaccurate description of Pilot's behavior regarding configuration

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio.io#6338]
The architecture section inaccurately states that Pilot sends the configuration information to Envoy. The accurate behavior is that each Envoy proxy reaches out to Pilot to obtain the mesh's configuration.
Scope: 
- Update the text of https://istio.io/docs/ops/deployment/architecture/#pilot with the accurate behavior
- Fix the architecture diagram of the section. Specifically, change the arrow direction and description for step 3.

**Comment by frankbu** [comment]
Are you sure about this? I thought Pilot uses gRPC connections to push config whenever there's an update.

**Comment by ramaraochavali** [comment]
Connection to Pilot is established by Envoy(as a client), but once the connection is established, Pilot pushes updates on the same connectection/stream whenever the config changes.

**Comment by frankbu** [comment]
Yes, that's what I thought, so I would say that at a high level, which this diagram/description is, the doc is correct as is. Pilot is sending the configuration to Envoy's, not the other way around. The Envoy's need to establish a gRPC connection to Pilot, but that's unnecessary detail for this high level architecture overview.

**Comment by howardjohn** [comment]
Agree with above ^

**Comment by 12beseuahmad** [comment]
> Connection to Pilot is established by Envoy(as a client), but once the connection is established, Pilot pushes updates on the same connectection/stream whenever the config changes.

I think this should be written there. Very important piece of information for who is the initiator of the connection.
