### ISSUE TITLE
Footer buttons do not work

### ISSUE THREAD

**Issue by phumberdroz** [istio/istio.io#6355]
The icons in the footer of `https://istio.io/` are not clickable.

Name | Firefox
-- | --
Version | 73.0b5
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0

**Comment by ericvn** [comment]
I was able to recreate this, and mentioned this on the WG call. @rcaballeromx mentioned he would try and take a look at the issue.

**Comment by nunosilva800** [comment]
Same happening with me: Firefox 74.0 (64-bit).
Setting `z-index: 0;` on the `footer` element is enough.
