### ISSUE TITLE
Bullets not formatting properly in autogeneration from istio/api

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#6362]
In the link below, we have a collection of bulleted text that goes on the istio.io website: 

https://github.com/istio/api/blob/c785926a849ce7e7a6a0d2550f8e0ee93ef991db/policy/v1beta1/cfg.proto#L338...L340

However, when the website gets generated off of this, the bullets do not get generated correctly:

![image](https://user-images.githubusercontent.com/8484260/73100603-db766f80-3ebb-11ea-86b4-8c96b7c44baf.png)

**Comment by howardjohn** [comment]
This API is now removed
