### ISSUE TITLE
Question: how to add out-of-process adapters to the adapters page on istio.io

### ISSUE THREAD

**Issue by girishranganathan** [istio/istio.io#6369]
Hello folks,
I am working on an out-of-process adapter for Istio. Can you please point me to a way to add out-of-process adapters to the adapters page on istio.io: 
https://istio.io/docs/reference/config/policy-and-telemetry/adapters/ ?
If this is not the right one, can you please point me to the right spot where I can include the adapter?

**Comment by ericvn** [comment]
Has this question been answered? Is there something that should maybe be added in the Contribution pages: https://istio.io/about/contribute/creating-and-editing-pages/. ?

**Comment by howardjohn** [comment]
Mixer has been removed from Istio so this is probably N/A
