### ISSUE TITLE
Could not fetch Jaeger info. Turning off Jaeger integration.

### ISSUE THREAD

**Issue by raswinraaj** [istio/istio.io#6374]
Istio version 1.4.3
I have installed the kiali plugin in my AKS cluster with Kubernetes version 1.15.7.
I have set the value of jaegerURL: http://jaeger-query.istio-system:16686 in \install\kubernetes\helm\istio\charts\kiali\values.yaml . But still i keep getting the error: Could not fetch Jaeger info. Turning off Jaeger integration.

I have checked the jaeger ui is up and running. I have attached the snapshot of the error.

![image](https://user-images.githubusercontent.com/50330414/73390631-8348ce80-42fc-11ea-9596-4549ff95f412.png)

**Comment by jshaughn** [comment]
https://kiali.io/faq/distributed-tracing/#turn-off-jaeger-integration

**Comment by ericvn** [comment]
@raswinraaj Does the above pointer resolve your issue?

**Comment by raswinraaj** [comment]
No Eric, I just have one user called as kialiadmin which i created a secret (called kiali) when i enabled istio . How do i know if this user can access it?
![image](https://user-images.githubusercontent.com/50330414/74529879-c5a21a80-4f4e-11ea-8f25-1b2e88584090.png)

**Comment by ericvn** [comment]
@jshaughn Can you help?

**Comment by jotak** [comment]
Hi @raswinraaj 

Kiali documentation lacks of clarity here and we're currently rewriting this part: https://github.com/kiali/kiali.io/pull/203

Basically what I think is missing for you here is the **in_cluster_url** configuration. It will be soon better documented, but in the meantime you can refer to this description: https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L433-L455

**in_cluster_url** is used by Kiali pod to talk to jaeger. This is probably something like: http://tracing.istio-system/jaeger (assuming jaeger is in namespace istio-system, with service name ‘tracing’)

In yaml it gives something like:

```yaml
  external_services:
    tracing:
      url: 'http://tracing:80'
      in_cluster_url: 'http://tracing.istio-system/jaeger'
```

**Comment by raswinraaj** [comment]
Thanks @jotak , Can you please explain what should be the changes to be done at https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/values.yaml#L69 ? What should be the value for jaegerURL and should i add one more value like jaeger_in_cluster_URL as http://tracing.istio-system/jaeger ?

**Comment by jotak** [comment]
@raswinraaj I fear this is not possible today with the current Helm chart. We've been trying to promote the use of Kiali operator instead ( https://github.com/istio/istio/issues/16435 ) but it's not in yet.
I would suggest that you either modify manually Kiali config map, or use the latest Kiali with its operator instead (see https://kiali.io/documentation/getting-started/#_install_kiali_latest )

**Comment by jotak** [comment]
PS I guess what should be done if we want to update the Helm chart would be:

- in https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/values.yaml have a new value such as `jaegerInClusterURL` that defaults to `http://tracing.istio-system/jaeger`

- in https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml under `tracing` set that value into config map:

```
      tracing:
        in_cluster_url: {{ .Values.dashboard.jaegerInClusterURL }}
```

(sorry i'm not very experienced with Helm, this is only a guess)

**Comment by raswinraaj** [comment]
Thanks Joel. I will try this out.

**Comment by howardjohn** [comment]
Closing as this looks like fixed in https://github.com/istio/istio/pull/21255
