### ISSUE TITLE
X days to Istio 1.5 renders incorrectly and is not accurate

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#6387]
![2020-01-02_13-55-30](https://user-images.githubusercontent.com/623453/73599645-83aeb880-44fa-11ea-81db-dfee11b0f0de.png)

Running Chrome 79 on linux

This date is also wrong, see https://github.com/istio/istio/wiki/Istio-Release-1.5

**Comment by craigbox** [comment]
Heh, I'l close #6390 then.
TBH, I think the sticker for releases is a bad idea, because release dates aren't fixed.  Any objection to removing it entirely?

**Comment by howardjohn** [comment]
I have no objections personally. It does make us look bad if we miss the date :slightly_smiling_face: . If we did want it, we could compromise with "istio 1.5 coming soon"

**Comment by ericvn** [comment]
We did talk about this briefly in the T&R call. I'm also in favor of the "istio 1.5 coming soon".
