### ISSUE TITLE
Kiali passphrase fails to set was reverted from release-1.4

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#6442]
There were an issue #6078 while setting a passphrase for Kiali and it was fixed and was available on `release-1.4`. I was trying to setup Kiali dashboard and observed that the fix was reverted from the `release-1.4` branch.

It is available in the [preliminary version ](https://preliminary.istio.io/docs/tasks/observability/kiali/). I believe it should also be available in `release-1.4` as the user will face problems setting up passphrase for Kiali.

cc: @ericvn

**Comment by ericvn** [comment]
I believe what you are asking is for https://github.com/istio/istio.io/pull/6079 to be cherry-picked from the `master` branch to the `release-1.4` branch.

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/pull/6461 should be a cherry-pick of the earlier PR. @shamsher31 I think you will need to add the comment to satisfy the CLA bot.

**Comment by shamsher31** [comment]
@googlebot I consent

**Comment by shamsher31** [comment]
Closing this with reference to https://github.com/istio/istio.io/pull/6461
