### ISSUE TITLE
Minor typo fixes in the 'Authorization for groups and list claims' task under Security

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#6487]
https://preliminary.istio.io/docs/tasks/security/authorization/rbac-groups/

**Comment by johnma14** [comment]
- In the first para, change groups-base authorization to 'groups-based authorization'
- Under 'Configure group based authorization', at the end of step 1, explicitly mention 'Wait for the newly defined policy to take effect.'

**Comment by adammil2000** [comment]
See PR #6526

**Comment by johnma14** [comment]
Thank you @adammil2000
