### ISSUE TITLE
istioctl config docs - snake_case or camelCase?

### ISSUE THREAD

**Issue by haf** [istio/istio.io#6495]
https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/ — it has both e.g. `traffic_management` and `trafficManagement` as config. And `traffic_management` is directly under `spec` which conficts with the generated configuration documentation further down the page (as opposing the example configs).

The correct setting to write e.g. `accessLogFile` for is this:

`spec > values > global > proxy > accessLogFile` as per https://istio.io/docs/reference/config/installation-options/

**Comment by howardjohn** [comment]
This is now updated to consistent camelCase https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/
