### ISSUE TITLE
External links in Installation Options (istioctl) page is not clickable.

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#6496]
Ref: https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/

External links to the site should be clickable and it should open in new tab on click. Currently, the user has to manually copy links, past it in a new tab for detail references.

**Comment by adammil2000** [comment]
Script that generates these pages is not detecting and converting link text into hyperlinks.

**Comment by shamsher31** [comment]
We will need to manually specify that the text is a link, `proto gen` will then convert it into a hyperlink after running `make gen` in `istio/api`. Istio.io will pull those generated pages with proper external links that users can then click.

Recently merged https://github.com/istio/api/pull/1293/files#diff-5ceaaf31d6a1c3596ef2a8011df6add5R108
