### ISSUE TITLE
External links in Global Mesh Options page is not clickable

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#6498]
Ref: https://preliminary.istio.io/docs/reference/config/istio.mesh.v1alpha1/

External links to the site should be clickable and it should open in new tab on click. Currently, the user has to manually copy links, past it in a new tab for detail references.

**Comment by adammil2000** [comment]
I believe this is a problem with the script that generates these doc pages not detecting and converting links into proper hyperlinks.
