### ISSUE TITLE
Need list of commands we can use in istioctl manifest apply --set

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#6500]
I'm working on [validation for "istioctl manifest apply"](https://github.com/istio/istio/issues/20730) and need a list of commands we can use in `istioctl manifest apply --set`. I have collected some of the flags we can pass during `--set` but unable to find all the available options.

Example:

```go
istioctl manifest apply \
  --set values.global.k8sIngress.enabled=true \
  --set values.global.k8sIngress.enableHttps=false \
  --set values.global.k8sIngress.gatewayName=ingressgateway \
  --set values.global.mtls.auto=true \
  --set values.global.mtls.enabled=false
  --set values.global.sds.enabled=true
```

[Installation Options with Helm](https://istio.io/docs/reference/config/installation-options/) page have a complete list, I'm looking for something similar.

If there is no dedicated page available for `istioctl manifest apply --set`, can we add one. This will help the new user identify all the available options for Istio installation using `istioctl`

**Comment by adammil2000** [comment]
These docs are generated by a script that scans the Istio source. I don't know if the script has the ability to read and generate anything at a level of detail deeper than it does today.

**Comment by shamsher31** [comment]
I'm curious to know how [Installation Options with Helm](https://istio.io/docs/reference/config/installation-options/) is generated using those scripts. I think that will help me figure out if we can generate the same for `--set` options.

**Comment by shamsher31** [comment]
@ericvn @esnible 
Quick question. I was going through `helm` options and this catches my eye.

> Installing Istio with Helm is in the process of deprecation. You can use these Helm configuration options when installing Istio with istioctl by prepending the string “values.” to the option name.
> 
> instead of this helm command
> 
> ```
> $ helm template ... --set global.mtls.enabled=true
> ```
> You can use this istioctl command:
> 
> ```
> $ istioctl manifest generate ... --set values.global.mtls.enabled=true
> ```

Does this means all the config which are valid for `helm` is also valid for `istioctl` by just prepending `values.` If that is the case, it will be easier to grab those options and test for [static validation of manifest apply](https://github.com/istio/istio/issues/20730).

**Comment by esnible** [comment]
`--set` can use any path that begins with the IstioOperatorSpec options documented at https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec

- `profile`
- `installPackagePath`
- `hub`
- `tag`
- `namespace`
- `revision`
- `meshConfig.*`
- `components.*`
- `addonComponents.*`
- `values.*`
- `unvalidatedValues.*`

The list of Components is given at https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha1/#IstioComponentSetSpec and they all have similar options.

The addOnComponents are not really documented anywhere that I know of.  I generated a list of default addon component settings using `istioctl profile dump demo -o json | jq ".spec.addonComponents"`.  The addons in the demo profile are `grafana`, `istiocoredns`, `kiali`, `prometheus`, `tracing`.  They all support `enabled`, so users can set `--set addonComponents.<addon>.enabled=true`.

`values` and `unvalidatedValues` are not documented on that page, but inherit some Helm options from https://istio.io/docs/reference/config/installation-options/ .  (For options like `tag` that are also given above, it isn't clear if the Helm options are ignored, or combined with the above somehow).

It is not clear which options are tested and which configurations are linked.  For example, if Galley is not enabled it makes no sense to customize Galley options.  There is another work item to improve logic that detects inconsistent settings.  https://github.com/istio/istio/issues/20730

**Comment by esnible** [comment]
@shamsher31 If you have the information you need please close this Issue.  If you have more questions let me know.

**Comment by shamsher31** [comment]
Thanks @esnible
