### ISSUE TITLE
In Istio 1.5 with istiod we need to update the documentation page to reflect the changes.

### ISSUE THREAD

**Issue by shwsingh** [istio/istio.io#6502]
Currently the docs show all the services which are not a part of istiod. we need to update the docs to reflect the changes.

<img width="686" alt="Screen Shot 2020-02-18 at 10 37 39 AM" src="https://user-images.githubusercontent.com/16418427/74867756-17a9be00-530a-11ea-8c87-683270775007.png">

**Comment by ericvn** [comment]
Plus update the list of profiles.

**Comment by shwsingh** [comment]
@howardjohn @costinm @ostromart - Please update the profiles for different install types
