### ISSUE TITLE
Installing 1.5 istio failed during "Customizable Install with Istioctl" 

### ISSUE THREAD

**Issue by shwsingh** [istio/istio.io#6503]
following the test case #25 from https://docs.google.com/spreadsheets/d/1KQ5eDZnzXTu8Tj0KTjGpXtvyFLHSVM5WgQn6P2MCaMI/edit#gid=1817277800

I tried installing Istio on GCP but it failed both times with error. It was a clean install and not an upgrade. 
<img width="1195" alt="Screen Shot 2020-02-19 at 11 28 59 AM" src="https://user-images.githubusercontent.com/16418427/74868490-32c8fd80-530b-11ea-8f31-35e801bb79f4.png">

**Comment by richardwxn** [comment]
This issue might be resolved by: https://github.com/istio/istio/pull/21164

**Comment by howardjohn** [comment]
fixed by https://github.com/istio/istio/pull/21164
