### ISSUE TITLE
Update the commands in the `Authorization Policy Trust Domain Migration` task under Security

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#6506]
In the `Authorization Policy Trust Domain Migration` task (), some of the commands need to be updated:
- Under the following section `Migrate trust domain without trust domain aliases`, the delete commands do not work for the Istio install using the demo profile (as mentioned in the step before this):
`kubectl delete secrets istio.sleep; kubectl delete secrets istio.httpbin;`
`kubectl delete secrets istio.sleep -n sleep-allow`

- Under the `Cleanup` section, the `k` in the following command needs to replaced with `kubectl`:

`$ kubectl delete deploy httpbin; k delete service httpbin; k delete serviceaccount httpbin`
`$ kubectl delete deploy sleep; k delete service sleep; k delete serviceaccount sleep`

**Comment by howardjohn** [comment]
This is fixed
