### ISSUE TITLE
https://istio.io/downloadIstio can't download the latest release automatically

### ISSUE THREAD

**Issue by maplebeats** [istio/istio.io#6539]
is the doc missing a description of the  ISTIO_VERSION env  or a script bug？
when I run the command in zsh on macbook，
```
[11:05:34] maplebeats :: TITUSTIAN-MB1  ➜  ~/istio » curl -L https://istio.io/downloadIstio | sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   107  100   107    0     0    112      0 --:--:-- --:--:-- --:--:--   112
100  2804  100  2804    0     0   1889      0  0:00:01  0:00:01 --:--:--  1889
Unable to get latest Istio version. Set ISTIO_VERSION env var and re-run. For example: export ISTIO_VERSION=1.0.4%  
```

**Comment by maplebeats** [comment]
I know what's the problem
```bash
if [ "x${ISTIO_VERSION}" = "x" ] ; then
  ISTIO_VERSION=$(curl -L -s https://api.github.com/repos/istio/istio/releases | \
                  grep tag_name | sed "s/ *\"tag_name\": *\"\\(.*\\)\",*/\\1/" | \
		  grep -v -E "(alpha|beta|rc)\.[0-9]$" | sort -t"." -k 1,1 -k 2,2 -k 3,3 -k 4,4 | tail -n 1)
fi
```
not working on mac

**Comment by maplebeats** [comment]
my address tiggered the github frequency limit，maybe the script should add some reminders。
```
{
  "message": "API rate limit exceeded for xx.xx.xx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by ericvn** [comment]
I added a note for ISTIO_VERSION last week. See https://preliminary.istio.io/docs/setup/getting-started/

I use a Mac as well and zsh, and the script works for me. That said, I may have something set on my machine to handle some Linux command differently that a stock MacOS. I assume you are running Catalina?

Did you try running the `curl -L -s https://api.github.com/repos/istio/istio/releases | \
                  grep tag_name | sed "s/ *\"tag_name\": *\"\\(.*\\)\",*/\\1/" | \
		  grep -v -E "(alpha|beta|rc)\.[0-9]$" | sort -t"." -k 1,1 -k 2,2 -k 3,3 -k 4,4 | tail -n 1)` standalone? Maybe that's the API rate limit exceeded error?

**Comment by maplebeats** [comment]
> I added a note for ISTIO_VERSION last week. See https://preliminary.istio.io/docs/setup/getting-started/
> 
> I use a Mac as well and zsh, and the script works for me. That said, I may have something set on my machine to handle some Linux command differently that a stock MacOS. I assume you are running Catalina?
> 
> Did you try running the `curl -L -s https://api.github.com/repos/istio/istio/releases | \ grep tag_name | sed "s/ *\"tag_name\": *\"\\(.*\\)\",*/\\1/" | \ grep -v -E "(alpha|beta|rc)\.[0-9]$" | sort -t"." -k 1,1 -k 2,2 -k 3,3 -k 4,4 | tail -n 1` standalone? Maybe that's the API rate limit exceeded error?

yes，my address tiggered  api rate limit. the script can check the http code to alert the exception，where can I submit the patch

**Comment by ericvn** [comment]
The following file is the script that is downloaded and run: https://github.com/istio/istio/blob/master/release/downloadIstioCandidate.sh

Ignore that the name says Candidate. I have another PR to fix that at some point.

**Comment by maplebeats** [comment]
> The following file is the script that is downloaded and run: https://github.com/istio/istio/blob/master/release/downloadIstioCandidate.sh
> 
> Ignore that the name says Candidate. I have another PR to fix that at some point.

thank you，I will submit a pr to fix this case。
