### ISSUE TITLE
Getting started page has several issues

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#6557]
https://preliminary.istio.io/docs/setup/getting-started/

Heading 1: Download and install Istio
Heading 2: Install Istio

We should remove the install from the first heading.

FYI. Table pointing to these headings:
Download the release
Install Istio

Also there is a line which may not make sense with the new installation preferences
   `Installation YAML files for Kubernetes in install/kubernetes` '

**Comment by ericvn** [comment]
FYI @adammil2000

**Comment by adammil2000** [comment]
Thanks for the heads-up, there's a new Getting Started PR coming shortly that will fix this and other issues.

**Comment by ericvn** [comment]
Hopefully, I can check in on the next testing day.

**Comment by dgn** [comment]
Fixed by the PR
