### ISSUE TITLE
"Installation Options (istioctl)" excessively confusing

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#6564]
I refer to https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha12.pb/

- The title mentions istioctl but not the document.
- What is "an empty user defined InstallSpec"?
- Excessive use of `k8s`, not just for programming but to refer to Kubernetes
- Suggests we "see CommonComponentSpec/Value" but it isn't linked and I don't know what a CommonComponentSpec is.
- The example "Default Istio install" is `spec:` which is not something a user would know where to use.  None of the examples shows how to use the "example".  Perhaps we should show istioctl `--set` syntax instead?
- It would be good for the tables such as AutoInjectionFeatureSpec to give the default values of all the fields.
- Why do so few table fields have descriptions?
- Phrase "Mirrors k8s.io.api.apps.v1.DeploymentStrategy for unmarshaling." makes no sense

**Comment by richardwxn** [comment]
related PR: https://github.com/istio/istio.io/pull/6600
