### ISSUE TITLE
[istio.io testing] Need test for Provisioning Identity through SDS

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#6575]
**Describe the feature request**
We need to develop a test for the [Provisioning Identity through SDS](https://preliminary.istio.io/docs/tasks/security/citadel-config/auth-sds/) task in order to provide automated testing of the Istio.io website for future releases.

Example tests and the documentation for the framework can be found here: https://github.com/istio/istio/tree/master/tests/integration/istioio

A YouTube video describing the usage of the framework can be found here: https://www.youtube.com/watch?v=3y-z8NaVwr0

Please reach out to the Test and Release channel on the [Istio Slack](https://discuss.istio.io/t/istio-slack-channel/1527) or [Test and Release Discuss](https://discuss.istio.io/c/test-and-release)  with any questions.

[ ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by su225** [comment]
@brian-avery - It seems that the link is broken. I checked in https://preliminary.istio.io/docs/tasks/security/ and it does not seem to exist. I heard that SDS is enabled by default in after Istio moved to using Operators instead of Helm charts. Is that correct?

By the way, if this issue is outdated, can we close it?

**Comment by brian-avery** [comment]
It looks like this was removed Friday as part of https://github.com/istio/istio.io/pull/6644. Unfortunately, I don't think this test is needed anymore and that this issue should be closed.
