### ISSUE TITLE
expose metrics and tracing via istio ingress

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#658]
port-forward command is hard to use and isn't portable.  Given istio provides a nice ingress, it is a little silly we don't leverage that for zipkin, grafana etc.

**Comment by geeknoid** [comment]
Can this issue be moved to a more appropriate repo? This is not really doc-related.

**Comment by linsun** [comment]
Ok, this turned out to be not as straightforward as I had thought.  

For istio-ingress, you have to specify all the paths or you can do `path: /.*`  The prob with that approach is that what if other service needs to be published in other path like /productpage /login /logout for bookinfo or zipkin.

I did try to remove my bookinfo ingress, and used the following:

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: addons-gateway
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: grafana
          servicePort: 3000
---
```
But could not get it working.  Kept getting `upstream connect error or disconnect/reset before headers` error when my grafana pod is running fine as I can do port-forward fine.  The istio ingress log showed:

````[2017-10-24 15:13:16.951][29][warning][http] src/envoy/mixer/mixer_control.cc:419] Could not convert to ip: destination.ip: 
[2017-10-24T15:13:16.951Z] "GET /grafana HTTP/1.1" 503 UF 0 57 3 - "10.188.52.54" "curl/7.54.0" "9b264be5-8c70-9a10-b876-439834b5703d" "169.60.80.10" "172.30.200.232:3000"
[2017-10-24 15:13:42.987][28][warning][http] src/envoy/mixer/mixer_control.cc:419] Could not convert to ip: destination.ip: 
[2017-10-24T15:13:42.987Z] "GET /grafana HTTP/1.1" 503 UF 0 57 3 - "10.188.52.54" "curl/7.54.0" "77347050-0872-937d-a1b4-238ec0c1d3fd" "169.60.80.10" "172.30.200.232:3000"```

172.30.200.232 is my grafana pod ip.  Need help from someone who knows more about istio-ingress to suggest where to debug this.

**Comment by linsun** [comment]
@rshriram FYI ^^^

**Comment by abbi-gaurav** [comment]
@linsun , did you get it working? 
The reason it is not working is that the side-car does not get injected and when the request is made to the zipkin-ui, the ingress cannot forward it since it cannot find the side car and perform the mutual tls.

However, if you disable the mutual tls, it works.

**Comment by linsun** [comment]
Yes, I got this working with our front door in ibm container service.  It was disable mutual TLS.  I expect istio-ingress to work too, will try it.

**Comment by imjoey** [comment]
@linsun did you get it working? I tried but not worked in istio-ingress without mutual TLS. Thanks.

**Comment by linsun** [comment]
No I don't believe i got it working other than the nginx based ingress controller.  I had issues with configuring the ingress for istio-ingress, even when mTLS is disabled...

**Comment by douglas-reid** [comment]
Added new docs on remote access. Going to close this issue.
