### ISSUE TITLE
Need consistent story if we are doc'ing the way to set clusters for SDS

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#6580]
For example, on the Docker Desktop setup page we make no mention of any way to allow using SDS. If SDS is enabled, things break.

We do have a pointer on the minikube page (https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) and talk about setting some configuration, although we don't mention an specifics (other than the pointer).

Kind and other platforms may have similar issues.

I know there has been discussion on whether this should go in a wiki, or something on the specific pages.

**Comment by ericvn** [comment]
@johnma14 If you want to add a link for Docker here.

**Comment by dgn** [comment]
@ericvn what do you mean by "things break"? Shouldn't this still work with first-party JWTs?

**Comment by ericvn** [comment]
Closing this issue as stale.
