### ISSUE TITLE
Update Kubernetes Supported Versions

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#6590]
I believe we support the last 3 releases of Kubernetes in Istio. Currently, we suggest 1.14.2 for Minikube and 1.14, 1.15, and 1.16 as the supported versions. However, looking at the Kubernetes releases, we have 1.17 is out and 1.18 has been in pre-release for 13 days. We should look at upgrading testing and the docs with new versions.

**Comment by ericvn** [comment]
I asked about this earlier (last week?) when we moved docs to 1.14, 1.15, and 1.16. We do test on 1.17, but GKE, where we run the release qualification, only supports 1.16.
