### ISSUE TITLE
Issues with https://preliminary.istio.io/docs/setup/install/multicluster/shared-gateways/

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#6594]
Need to update the list of pods for cluster 1:
```
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-6767869fcf-sq7n9   1/1     Running   0          17s
istiod-7f7b4dc6d9-2xwmt                 1/1     Running   0          35s
prometheus-68d688f8b7-nmlrn             1/2     Running   0          16s
```

When updating IPs in the config map, we are down to only one instance of each. We mention two in the docs, but that was a 1.4 only thing I guess.

~~Fails trying to deploy remote profile on cluster~~ It worked the second time through

Wait for the Istio pods on cluster2, except for istio-ingressgateway, to become ready....
there is only an ingress gateway pod now, so not sure, but maybe remove this wait.

ingress-gateway fails to start with a:
```
MountVolume.SetUp failed for volume "citadel-ca-cert" : configmap "istio-ca-root-cert" not found
```
See https://github.com/istio/istio/issues/21281

**Comment by linsun** [comment]
after enabling https://github.com/istio/istio/pull/21534, this prob went away for me

**Comment by linsun** [comment]
I'll do an update for the page once I got it running myself :)

**Comment by ericvn** [comment]
@ayj I did run through the example again today with the current preliminary.istio.io page.

Some comments:
- Start `Run the following commands on each cluster ` in its own paragraph.
- `Replace the variables below with the cluster and network names chosen earlier`. You really aren't replacing anything since it's variable expansion.
- yaml has
```
Choose one of the three
  # options below and delete the other two option's configuration.
```
I believe this should be two and delete the other
- yaml has 
```
    # required if istiod is disabled
    security:
      selfSigned: false
    global:
      multiCluster:
        clusterName: ${MAIN_CLUSTER_NAME}
      network: ${MAIN_CLUSTER_NETWORK}
```
Not sure if you want part of that removed if using istiod? Is it only the _security_ section. Maybe separate sections with a space. And istiod isn't mentioned anywhere outside the yaml.
- Personally, a tabbed area to pick option 1 or 2 might be better as then I'm not editing what I cut/pasted.
- It says I should see log messages like:
```
[2018-11-25T12:37:52.077Z] "GET /hello HTTP/1.1" 200 - 0 60 190 189 "-" "curl/7.60.0" "6e096efe-f550-4dfa-8c8c-ba164baf4679" "helloworld.sample:5000" "192.23.120.32:15443" outbound|5000||helloworld.sample.svc.cluster.local - 10.20.194.146:5000 10.10.0.89:59496 -
[2018-11-25T12:38:06.745Z] "GET /hello HTTP/1.1" 200 - 0 60 171 170 "-" "curl/7.60.0" "6f93c9cc-d32a-4878-b56a-086a740045d2" "helloworld.sample:5000" "10.10.0.90:5000" outbound|5000||helloworld.sample.svc.cluster.local - 10.20.194.146:5000 10.10.0.89:59646 -
```
I did not see anything related to that. I had more things like:
```
[Envoy (Epoch 0)] [2020-03-19 15:39:04.674][19][warning][filter] [src/envoy/http/authn/http_filter_factory.cc:83] mTLS PERMISSIVE mode is used, connection can be either plaintext or TLS, and client cert can be omitted. Please consider to upgrade to mTLS STRICT mode for more secure configuration that only allows TLS connection with client cert. See https://istio.io/docs/tasks/security/mtls-migration/
```
- The uninstall remote section doesn't seem correct. Second line doesn't copy and remote context still had Istio install. I added the remote context to the kubectl delete as well.
- Missing section to uninstall main cluster.
_ I'm not to worried about env vars like some other samples.
