### ISSUE TITLE
Nit: Prometheus Graph vs Console buttons

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#6629]
https://preliminary.istio.io/docs/tasks/observability/metrics/querying-metrics/

This doc tells the user to click "Graph", but then shows the user the result of clicking "Console".

The "Graph" output is cool, perhaps just add a line before the expected output saying "Click Console in Prometheus."

**Comment by ericvn** [comment]
This was doc'd in #6625 as well.

**Comment by esnible** [comment]
Closing as duplicate!
