### ISSUE TITLE
docs tell users to download stand-alone istioctl refers to packaged istioctl

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#6640]
https://preliminary.istio.io/docs/ops/diagnostic-tools/istioctl/ tells users to install using `curl -sL https://istio.io/downloadIstioctl | sh -`  This installs a single file, not the whole tar.

Later, the documentation says "If you are using bash, the istioctl auto-completion file is located in the tools directory."  Of course, if users who followed the earlier instructions will not have a _tools_ directory.

**Comment by johnma14** [comment]
Addressed by: https://github.com/istio/istio.io/pull/6603

**Comment by frankbu** [comment]
Fixed by #6603
