### ISSUE TITLE
[1.5 Community Testing]: listing available configuration profiles shows wrong results

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#6645]
When following the steps in https://preliminary.istio.io/docs/setup/install/istioctl/#display-the-configuration-of-a-profile to list the available configuration profiles, the output is different from what is mentioned in the docs. 

I verified the list of configuration profiles mentioned here: https://preliminary.istio.io/docs/setup/additional-setup/config-profiles/ and that matches what is mentioned in the output in the docs. 

Here is the expected output per the docs:
`minimal
  remote
  sds
  default
  demo`

whereas this is what is seen on release-1.5-beta4 build:
 `demo
  empty
  minimal
  remote
  seperate
  default`

Not sure if this is a doc bug or a feature bug.

**Comment by ericvn** [comment]
#6547 should hopefully fix Theis when it's done.

**Comment by johnma14** [comment]
thanks @ericvn.
