### ISSUE TITLE
Issue with docs/concepts/security/index.md

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#6662]
This doc references citadel, mixer, etc. I am pretty sure @justinpettit was working on this, just filing an issue to associate with the community testing

**Comment by dgn** [comment]
ping @justinpettit, not sure what's required here

**Comment by justinpettit** [comment]
@rcaballeromx sent out a PR that contains the changes: https://github.com/istio/istio.io/pull/6727

**Comment by justinpettit** [comment]
That PR was merged.
