### ISSUE TITLE
Issue with docs/ops/common-problems/observability-issues/index.md: everything refers to legacy mixer

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#6674]

**Comment by douglas-reid** [comment]
Yup. Rewriting all of the ops guide stuff is going to take some doing.

**Comment by howardjohn** [comment]
No problem. I just need something to reference in the testing sheet, feel free to close this if there is an umbrella issue

**Comment by douglas-reid** [comment]
This should be updated now
