### ISSUE TITLE
Issue with docs/ops/diagnostic-tools/proxy-cmd/index.md: verifying connectivity does not work with Istiod

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#6676]
https://preliminary.istio.io/docs/ops/diagnostic-tools/proxy-cmd/#verifying-connectivity-to-istio-pilot

The certs are no longer there

@lei-tang @myidpt

**Comment by lei-tang** [comment]
https://github.com/istio/istio.io/pull/6719 is created to fix this issue.

**Comment by howardjohn** [comment]
fixed https://preliminary.istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd/#verifying-connectivity-to-istiod
