### ISSUE TITLE
Issue with docs/reference/config/analysis/ist0119/index.md: might no longer be accurate with auto protocol detection

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#6681]
Do we still require explicit port name for JWT policies now that we have auto protocol detection?

cc @yangminzhu @yxue

**Comment by yangminzhu** [comment]
Is the auto protocol detection enabled by default in 1.5?

**Comment by howardjohn** [comment]
yes

**Comment by yangminzhu** [comment]
Hmm, I thought it's still disabled? 

https://github.com/istio/istio/blob/268f53f13085c76d8cfaac0f076e394de9acd369/manifests/istio-control/istio-discovery/values.yaml#L38-L40

**Comment by howardjohn** [comment]
weird.. I could have sworn we turned it on everywhere. @yxue ?

**Comment by yxue** [comment]
Hmm, this file is added after this PR https://github.com/istio/istio/pull/18666/files. Maybe it was copied from another source?

**Comment by howardjohn** [comment]
That is the legacy install model, not istioctl

**Comment by yxue** [comment]
Oh, I see the commit history. The commit is backport from the istio/install? I didn’t change the istio/install repo when turning on the feature.

**Comment by howardjohn** [comment]
Yes, so inbound sniffing is actually off by default for majority of
installs.

Also istio/installer repo no longer is used, its now in istio/istio
manifests/ folder, but its the same thing

**Comment by yangminzhu** [comment]
Is it enabled in the e2e tests?

We need to double check if the inbound sniffing works with the new PeerAuthentication policy on the pass through filter chain. (Previously I thought the protocol is disabled for 1.5 so didn't test it much when adding the support) cc @diemtvu
