### ISSUE TITLE
Does SDS profile still avalable?

### ISSUE THREAD

**Issue by diemtvu** [istio/istio.io#6683]
Here is the output of 1.5-beta.5. Is this the bug or expected? If the later, should we update the installation task (i.e https://preliminary.istio.io/docs/setup/install/istioctl/#display-the-list-of-available-profiles) and other related SDS tasks.

```
istioctl profile list
Istio configuration profiles:
    default
    demo
    empty
    minimal
    remote
    separate
```

**Comment by ericvn** [comment]
This is what I see with beta.5:

```
istioctl profile list                                                                                                                                                                     
Istio configuration profiles:
    minimal
    remote
    separate
    default
    demo
    empty
```

#6686 has this as part of it.

**Comment by ericvn** [comment]
Not sure how profiles are ordered though. @howardjohn

**Comment by howardjohn** [comment]
I have a pr as mentioned above. SDS profile is gone

**Comment by myidpt** [comment]
SDS profile is gone because the feature is enabled by default.
