### ISSUE TITLE
[1.5 Community Testing] Remove command from standard operator install task

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#6707]
In the following task: https://preliminary.istio.io/docs/setup/install/standalone-operator/, the last command in the Uninstall section to delete the istio-system namespace is not needed. Currently it throws an error because this namespace is deleted by the command above it:

`istioctl manifest generate | kubectl delete -f -`

**Comment by howardjohn** [comment]
command is replaced, no longer has this issue
