### ISSUE TITLE
[1.5 Community Testing] `Show differences in manifest` in the custom install using istioctl needs update

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#6714]
In this section of the docs: https://preliminary.istio.io/docs/setup/install/istioctl/#show-differences-in-manifests, the commands need to be updated. 

- `istioctl manifest generate -f samples/operator/pilot-k8s.yaml > 2.yaml` prints the output to stdout instead of file. 
- `istioctl manifest diff 1.yam1 2.yaml` throws an error saying the there is no such file/directory as 1.yaml. This file is there but for some reason the command still complains.

**Comment by howardjohn** [comment]
This is now working
