### ISSUE TITLE
[1.5 Community Testing] Installation Options for istioctl link does not work when accessing it from search results

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#6729]
On the preliminary.istio.istio page, try searching for something like 'Installation Options for istioctl' and it will return a bunch of results. Click on the one that says [Istio Prelim 1.5 / Installation Options (istioctl)](https://www.google.com/url?client=internal-element-cse&cx=002184991200833970123:dmevwrvc6os&q=https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha12.pb/&sa=U&ved=2ahUKEwjx4IrW1IHoAhVO2qwKHb5wCS4QFjAAegQIBRAB&usg=AOvVaw03PS32BO1Onf8m8zFEoq4B). The link is wrong. It should point to https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha1/ instead.

**Comment by howardjohn** [comment]
linked is removed
