### ISSUE TITLE
TestEnablingPolicyEnforcement failing on prow

### ISSUE THREAD

**Issue by nmittler** [istio/istio.io#6733]
See https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio.io/6724/k8s-tests_istio.io/542

It may just be outright failing, not sure. We have an issue where prow always reports success, which I'm working on now.

**Comment by nmittler** [comment]
FYI @shamsher31

**Comment by shamsher31** [comment]
Thanks @nmittler , But I'm unable to verify on my machine because integration test is not working for me. Test goes in `waiting for resources to be ready` state. Here is my log.
https://istio.slack.com/files/UR4MS88J3/FUJ9XNLLA/istio-ingressgateway_log

**Comment by nmittler** [comment]
Hey @shamsher31. I'm not sure if the test framework supports minikube anymore since we've transitioned to kind. Would you be able to give it a try with kind (or gke)?

**Comment by shamsher31** [comment]
Thanks for the info @nmittler, Sure I will give it a try on `kind`.

**Comment by howardjohn** [comment]
This is now obsolete
