### ISSUE TITLE
Tradewinds 2020 blog post arch diagram slightly misleading

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#6756]
https://istio.io/blog/2020/tradewinds-2020/architecture-post-istiod.svg

This suggest istio-agent runs as a daemonset or something. In reality, it is in the same container as the proxy.

Not a huge issue, but since this seems like it may become a canonical image, might be worth a slight modification?

**Comment by craigbox** [comment]
PTAL at the source: https://docs.google.com/presentation/d/14qiTjb6IosqHYx6OD-cER9K3iLDF7xp4FEzKBqRrjQo/edit#slide=id.p

I didn't have the node agent on there. Maybe think @oaktowner added it?

I'm OK with saying "proxy" == "Envoy + agent".

**Comment by howardjohn** [comment]
Seems like we are unlikely to change a 6 month old blog post
