### ISSUE TITLE
Istio.io 1.4 docs archive is broken trying to follow links

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#6788]
If they know the page link that works (ex: https://archive.istio.io/v1.4/docs/concepts/traffic-management/) . It’s just if someone wants to follow a link it’s broke. They need to add /v1.4 into the URL before /docs

**Comment by ericvn** [comment]
Also mentioned in https://github.com/istio/istio/issues/21935

**Comment by frankbu** [comment]
Also, the landing page of all the oldie sites is displaying html text for the content. For example: https://archive.istio.io/v1.3/

**Comment by geeknoid** [comment]
Fixed.
