### ISSUE TITLE
Archive Issue - Gear icon on menu bar doesn't work

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#6821]
The gear menu item works on the main drop down pages on the archives, but not when on pages under docs.

**Comment by frankbu** [comment]
@ericvn I tried this on Firefox and Chrome and both seem to work. What browser are you using?

**Comment by frankbu** [comment]
Actually I think this is related to the problem in #6820, since the gear only stops displaying AFTER clicking on the left nav sections, which don't expand.

**Comment by ericvn** [comment]
I'm using Safari. It never works for me under /docs whether I've hit a left side link or not.

**Comment by geeknoid** [comment]
Fixed. Scripts were broken.
