### ISSUE TITLE
Archive issue - tabs are broken

### ISSUE THREAD

**Issue by Dirk-c-Walter** [istio/istio.io#6830]
https://archive.istio.io/v1.4/docs/setup/upgrade/cni-helm-upgrade/

The page has several places where there are 2 tabs, "Kubernetes rolling update"/"Helm upgrade" with the first tab always being selected and it is impossible to switch to the second tab. Tested under both Firefox and Chromium. This seems to apply to all such tabs on the archive site while they work fine on the main site.

**Comment by geeknoid** [comment]
Fixed. Scripts were broken.
