### ISSUE TITLE
No switch to an older version of documentation 

### ISSUE THREAD

**Issue by sirkubax** [istio/istio.io#6840]
**Documentation lack an option to switch to older (eg 1.4) versions.**

After refreshing the page (opened before) 
https://istio.io/docs/setup/install/istioctl/#customizing-the-configuration
I was thrown at newer docs of 1.5

The problem is - there is no way to switch to other version (check out ElasticSearch Docs - you can switch easily with a dropdown selector https://www.elastic.co/guide/en/elastic-stack/6.8/index.html)

For Istio a way to find older version that I know is

1. Google "istio.io/docs  1.4.6"
2. go to link istio.io/news/releases/1.4.x/announcing-1.4.6/
3. you can find https://archive.istio.io/v1.4/docs/

**This is sad...**

Additionally:
Configuration flags very poorly documented
I was looking for a way to disable Prometheus with istioctl, turns out you pass `--set values.prometheus.enabled=false` to istioctl... 
I did not find any info on that in the docs...

https://archive.istio.io/v1.4/docs/setup/install/istioctl/#customizing-the-configuration
```
Configure the feature or component settings
After you identify the name of the feature or component from the previous table, you can use the API to set the values using the --set flag(...)

To disable the telemetry feature in a default configuration profile, use this command:
$ istioctl manifest apply --set telemetry.enabled=false
```
One may expect that for prometheus it should be `prometheus.enabled=false` yet it is not

I've reverse-endangered this by checking 
`istioctl profile dump default` and checking the variable tree

**Comment by geeknoid** [comment]
We used to have a selection to let you switch to any version of the doc set. It ended up being very complex to deal with, given that pages move and/or get deleted over time. I decided that a simpler reliable model would be preferable.

**Comment by sirkubax** [comment]
Sure, this might be a nightmare, but what "path" would you then recommend to view docs for older versions? I mean where should I look for the 'index page' with past documentation revisions.

**Comment by jpapejr** [comment]
You can always get to prior versions of the docs via https://archive.istio.io/. Just select your release and find what you need.

**Comment by howardjohn** [comment]
At the bottom there is an '[older releases](https://istio.io/archive)' link now
