### ISSUE TITLE
Issue with docs/reference/config/security/request_authentication/index.html

### ISSUE THREAD

**Issue by kal-g** [istio/istio.io#6877]
This page has a bunch of broken / incorrectly displaying yaml

**Comment by shamsher31** [comment]
@kal-g would you mind specifying the actual problem you are facing?

**Comment by kal-g** [comment]
<img width="1195" alt="Screen Shot 2020-03-20 at 2 55 37 PM" src="https://user-images.githubusercontent.com/56615159/77209239-fbd93980-6aba-11ea-99ec-947d2db2688b.png">

**Comment by pleshakov** [comment]
I will add that in the table the link to `WorkloadSelector` points to https://istio.io/docs/reference/config/type/v1beta1/workload-selector.html#WorkloadSelector , which gives 404

**Comment by shamsher31** [comment]
Closed by https://github.com/istio/api/pull/1540
