### ISSUE TITLE
How to change grafana.ini istioctl

### ISSUE THREAD

**Issue by lhmoraes** [istio/istio.io#6884]
How to change the grafana.ini configuration file adding for example a new SMTP host, password and etc configuration using istioctl?

**Comment by luislhl** [comment]
@lhmoraes , did you find out how to do this?

**Comment by RichardSobreiro** [comment]
Need help too.
I'm using k8s behind an azure application gateway ingress controller and need to modify grafana.ini in order to access the grafana portal.

**Comment by luislhl** [comment]
For everyone coming to this issue, the right way is to pass Environment Variables to your Grafana deployment in order to configure anything that you would configure in grafana.ini.

Check https://grafana.com/docs/grafana/latest/administration/configuration/
