### ISSUE TITLE
Issue with docs/setup/getting-started/index.md

### ISSUE THREAD

**Issue by tariq-islam** [istio/istio.io#6887]
https://istio.io/docs/setup/getting-started/#confirm 

Command should be:
`curl http://$GATEWAY_URL/productpage`

As it stands currently with `echo`, the command does not illustrate successful accessibility from the outside into the application.

**Comment by ericvn** [comment]
Note that the text is using `echo` to get the expanded string, and then asks you to take that output and put it into a browser (see prior sentence).

**Comment by shamsher31** [comment]
`echo http://$GATEWAY_URL/productpage` will print something like 
`http://192.168.0.52/productpage` and then user has to take two more steps to verify that the `productpage` is working from outside.

Instead, we can `curl` to avoid that extra steps.

**Comment by shamsher31** [comment]
The result will be the same.

**Comment by ericvn** [comment]
@adammil2000 As we probably had this discussion earlier and you have the feedback from the earlier testing,

**Comment by shamsher31** [comment]
Hey @ericvn , I have updated PR as per @frankbu suggestions.

**Comment by ericvn** [comment]
@shamsher31 That looks much better. Thank you.
