### ISSUE TITLE
Issue with docs/tasks/traffic-management/ingress/secure-ingress-sds/index.md

### ISSUE THREAD

**Issue by adonaicosta** [istio/istio.io#6903]
lack namespace in gateway yaml definition, if secret was created on istio-namespace, the gateway must be in same namespace refering secret.

**Comment by howardjohn** [comment]
This is WAI. The Gateway does not need to be in the same namespace, the deployment does

**Comment by howardjohn** [comment]
see https://istio.io/latest/docs/setup/additional-setup/gateway/ for more info
