### ISSUE TITLE
MeshConfig Options are overlapping with sidebar content

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#6912]
Ref: https://istio.io/docs/reference/config/istio.mesh.v1alpha1/

The content of the `Description` column adjust according to screen resolution, but some of the values in `MeshConfig` ` Field` column is too long because of which the width of the entire table increases and it overlaps with sidebar content.

The remaining tables work perfectly fine with different resolutions.

![mesh-config](https://user-images.githubusercontent.com/2920003/77039635-623b5a80-69dc-11ea-9c61-651ca244c0ff.png)

**Comment by brian-avery** [comment]
@shamsher31 I'm no longer seeing this on https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/. Can you please confirm for both this and #8192?

**Comment by shamsher31** [comment]
Looks good in the new design.
