### ISSUE TITLE
arch.svg - fix typo

### ISSUE THREAD

**Issue by antweiss** [istio/istio.io#6970]
On the architecture diagram it says "Engress Traffic" instead of "Egress Traffic"
<img width="695" alt="Screen Shot 2020-03-25 at 18 58 39" src="https://user-images.githubusercontent.com/3274734/77564076-d6896880-6eca-11ea-8eb1-4ff1bd6ecb3f.png">

**Comment by antweiss** [comment]
The file that needs fixing: https://github.com/istio/istio.io/blob/master/content/en/docs/ops/deployment/architecture/arch.svg

**Comment by AndreaM12345** [comment]
fixed
