### ISSUE TITLE
Istio.io linter performance issues

### ISSUE THREAD

**Issue by adammil2000** [istio/istio.io#6983]
This issue tracks the performance issues, potential causes and resolutions for the Istio.io linter that's part of the Istio.io CICD pipeline.

**Background**

When we submit content PRs to our Istio.io repository, we have a CICD workflow that runs a linter as one of the steps. The linter does various things, including:

- Has a makefile that runs a Docker container to perform tasks as a build workflow (build machine can be your local machine or a cloud build)
- Runs a full build of the documentation pages
- Checks for HTML syntax errors and HTML DOM errors
- Checks the build for internal link errors (links from one Istio.io page to another)
- Checks bookmark links (linking from an istio.io page to another location on the same page)
- Checks for external link errors (links from istio.io to other web sites) 
- Runs a spell check using a custom dictionary

**Performance issues**

The linter takes ~30 minutes and growing over time, while maxing 2 CPUs at 100% utilization during its run. As we push content near deadlines, it creates a tense situation where we might have to run the linter, fix an issue and re-run linter, fix again etc. It’s making fast, iterative work very difficult and time consuming. The author is blocked waiting for the linter to complete for each iteration.

**Possible causes**

- We believe our CICD pipeline runs the linter on the entire doc set every time without regard to what changed since the last run.
- Runs in a docker container with no persistent disk, wiping any cache with every run, removing any efficiency we could gain from using cache for things like external link checking, etc.
- Uses an htmlproofer library written in Ruby that might be slow/inefficient.
- Docker client settings are not optimal for this type of workload.
- Linter is checking more than it needs to, e.g. maybe linter is not cleaning up after it runs and accumulating extraneous temp files every run and unnecessarily checking those files with subsequent runs.

**Possible solutions**

- Only run the linter on files that have changed since the last run.
- Find a way to persist the disk cache between Docker runs.
- Make better use of multiple cores in the CPU.
- Offload some checks to a cloud service to run in parallel
- Run our workload on a faster server
- See if there are docker settings to run this workload faster/more efficiently.
- Make sure the linter cleans up any temp files that might be getting scanned unnecessarily.

**Comment by frankbu** [comment]
#7014 addresses some low hanging fruit.

**Comment by davidhauck** [comment]
Swapped out htmlproofer's link checker for linkinator
