### ISSUE TITLE
Issue with docs/tasks/observability/distributed-tracing/overview/index.md

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#7062]
l found bookinfo also support datadog trace context headers in codes, so it will be better to also add this kind of info in this page.
```
incoming_headers = ['x-request-id', 'x-datadog-trace-id', 'x-datadog-parent-id', 'x-datadog-sampled']
```

**Comment by howardjohn** [comment]
Looks like this info is added on the page now
