### ISSUE TITLE
Few problems with page 

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#7149]
```
sdake@beast-01:~/istio-1.6.0-alpha.2$ istioctl manifest apply --set profile=demo --set values.global.proxy.accessLogFile="/dev/stdout"
! global.proxy.accessLogFile is deprecated; use meshConfig.accessLogFile instead
! global.disablePolicyChecks is deprecated; use meshConfig.disablePolicyChecks instead
```

https://preliminary.istio.io/docs/tasks/observability/logs/access-log/

Three problems:
- `manifest apply` should be `install`.
- The profile should be set by the operator - to be one of the potential profiles.
- Demo is not the only profile - and is used inconsistently in the documentation. The documentation recommends using deprecated options for enabling and disabling the access log.

**Comment by howardjohn** [comment]
https://github.com/istio/istio.io/pull/7236
