### ISSUE TITLE
VM install (single network) istiod address unreachable

### ISSUE THREAD

**Issue by askmeegs** [istio/istio.io#7168]
In the [Istio 1.5.2 single-network VM setup instructions](https://istio.io/docs/examples/virtual-machines/single-network/#preparing-the-kubernetes-cluster-for-vms), it says to add the Istiod ClusterIP service IP to /etc/hosts on the VM. ClusterIP addresses are only reachable in-cluster - the VM cannot ping that IP, and the VM Istio logs throw this error: 

```
>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.87.14.197:15012: i/o timeout". Reconnecting...
2020-04-27T13:35:47.831410Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc0002561d0, {TRANSIENT_FAILURE connection error: desc = "transport: Error while dialing dial tcp 10.87.14.197:15012: i/o timeout"}
```

These 1.5 instructions are different from the [1.4 instructions](https://archive.istio.io/v1.4/docs/examples/virtual-machines/single-network/) where you instead add the Loadbalancer IP of the ingress gateway to /etc/hosts on the VM.

When I follow the 1.5 instructions but replace the istiod IP with the ingressgateway public IP (keeping the istiod DNS name), my install works. 

```
35.184.205.196 istiod.istio-system.svc
```

I don't think the docs will work as-is unless I'm missing something about why we're asking users to reach a K8s ClusterIP outside the cluster.

**Comment by sdake** [comment]
related PR: https://github.com/istio/istio.io/pull/7107

**Comment by sdake** [comment]
@askmeegs in a single network VPN model, ClusterIPs are addressable outside the cluster. ClusterIPs are exposed via L3 in this model.

The single network model was (introduced) in 1.5 and the gateways model was (re-introduced?) in 1.5 in the form of two different documents.

We hope to have documentation improvements in place for 1.6. One thing we are after with the 1.6 VM Mesh expansion documentation is to remove references to any cloud provider's proprietary tooling and instead use good old ssh/scp - which is available everywhere. The process of provisioning a VM will be covered, although the Istio community expectation is that no install/task/example documentation contains cloud-specific commands of any kind.

Cheers
-steve

**Comment by irisdingbj** [comment]
@sdake Single network means the  istiod clusterIP is reachable on VM.  So your environment is actually multi network scenario.

**Comment by askmeegs** [comment]
Thank you both for this clarification!

**Comment by sdake** [comment]
@askmeegs is there any action to take here, or can this issue be closed? We cover the single and multi-network scenarios elsewhere in the deployment models documentation.

**Comment by askmeegs** [comment]
Yes, this issue can be closed. Thanks!

**Comment by sdake** [comment]
After speaking with @costinm on this topic, he has indicated single network VM isn't viable for many reasons. Chief among these are
- service IPs are not addressable in most/all K8s environments.
- Using a gateway permits addressing of a service IP.
- After several git blames, I still do not understand why single network virtual machine was merged into the documentation.

The best I have been able to discover is this document was created in error because of confusion over the desire to have a single and multiple network use case for everything multicluster. Instead, a gateway must *always* be used for the correct operation of virtual machines given the current state of the technology. The network model (single, multi) is not a relevant factor, as gateways can be used correctly in a single network model.

**Comment by sdake** [comment]
The rendered document https://deploy-preview-7248--preliminary-istio.netlify.app/docs/setup/install/multicluster/virtual-machine/. The document should go up a level, and I believe @rcaballeromx's document should parallel it as just another install document.

Cheers
-steve

**Comment by sdake** [comment]
@askmeegs after further review, I found that for whatever reason the virtual machine documentation was split into single and multiple network. In the context of virtual machines, single and multiple networks don't make any sense. In any modern K8s environment, it is not possible to address an L3 service address. When I had originally responded on this issue tracker, I had thought you were talking about connecting to a pod address range, which is possible with modern K8s systems.

Thank you so much for the bug report - @irisdingbj and I have made an invaluable improvement for our customers. Where before mesh expansion may have been broken in the 1.5 series for unknown reasons as you suggested, it was functional already in 1.4 thanks to the work @irisdingbj had added to enable virtual machine mesh expansion.

**Comment by sdake** [comment]
@liminw Welcome to the virtual machine effort! See this PR and related PRs for what is currently state of the art with virtual machines. I am sure @irisdingbj is willing to share the work required to turn virtual machines into beta/stable over the coming 1.7 cycle.

The feature status page marks credentials distribution as beta, although there is no installation documentation for this feature and I am not aware of any e2e testing for https://preliminary.istio.io/pt-br/docs/concepts/security/#pki, which means this feature does not meet the requirements to be promoted to beta. As there is no e2e testing nor installation documentation, I am reverting this feature to alpha as it does not meet the feature gate requirements until @howardjohn completes the integration testing he had suggested he would do in the Istio 1.7 roadmap planning (thanks @howardjohn, for all you do :)

FWIW, the overall virtual machine integration feature is proposed for beta for 1.7, so nice work there 👍

**Comment by sdake** [comment]
there are multiple fixes for this problem - so reopening. Docs remain.
