### ISSUE TITLE
TCP Metrics walkthrough doesn't create gateway

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio.io#7184]
https://preliminary.istio.io/docs/tasks/observability/metrics/tcp-metrics/#collecting-new-telemetry-data Step 2 directs you to obtain and use a gateway address to hit bookinfo, however the previous steps did not include creating said gateway.

**Comment by douglas-reid** [comment]
I ran into this issue as well.  But I'm torn on this, as the task also doesn't walkthrough installing bookinfo. And I _think_ it might be OK to assume that the gateway was added during that basic install. @gargnupur for thoughts.

**Comment by gargnupur** [comment]
@douglas-reid , @therealmitchconnors : How about adding the information about GATEWAY_URL like in this task? https://preliminary.istio.io/docs/tasks/observability/metrics/querying-metrics/#querying-istio-metrics.. that would make it useful?
