### ISSUE TITLE
Ambiguous "auth" on _docs/concepts/network-and-auth/auth.md

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#7196]
The page ambiguously uses "auth" (including in "Istio Auth") when it means ... well, it's not clear when it means authentication, when it means authorization, and/or when it means both authentication and authorization. 

(And please don't change to the pair "auth" and "authz" when abbreviating--a reference to "auth" by itself will still be ambiguous. Using the pair "authc" and "authz" would remove that ambiguity.)

**Comment by howardjohn** [comment]
I think this page is removed, and https://istio.io/latest/docs/concepts/security/ appears to clarify authentication and authorization. So I think this is obsolete
