### ISSUE TITLE
Istion Timeout information

### ISSUE THREAD

**Issue by ta9miya** [istio/istio.io#7197]
I'm looking for information about istio timeouts.
The default timeout value is 15 seconds in the "Timeout" section of the link below.
https://istio.io/docs/concepts/traffic-management/#network-resilience-and-testing
The default timeout for HTTP requests is 15 seconds
On the other hand, the "Request timeouts" section of this link states that the default is Disable.
https://istio.io/docs/tasks/traffic-management/request-timeouts/
A timeout for http requests can be specified using the timeout field of the route rule. By default, the timeout is disabled,

Which is correct information?

**Comment by shamsher31** [comment]
I believe this is true [as per envoy proxy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout):

> The default timeout for HTTP requests is 15 seconds, which means that if the service doesn’t respond within 15 seconds, the call fails.

@frankbu @ericvn Please confirm. 

Ref: https://istio.io/docs/concepts/traffic-management/#timeouts
