### ISSUE TITLE
Bad target for WorkloadSelector link on docs/reference/config/security/authorization-policy/index.html

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#7203]
On the page currently at https://istio.io/docs/reference/config/security/authorization-policy/#AuthorizationPolicy, `AuthorizationPolicy`'s `selector`'s `WorkloadSelector` link has a bad target URL, leading to an HTTP 404 page.

**Comment by shamsher31** [comment]
The same problem exists for the following pages.

https://istio.io/docs/reference/config/security/request_authentication/
https://istio.io/docs/reference/config/security/peer_authentication/

The WorkloadSelector is referenced from [istio/api](https://github.com/istio/api/blob/master/type/v1beta1/selector.proto#L32), somehow it's not able to generate doc page for workloadSelector during `make clean gen`.

**Comment by shamsher31** [comment]
Closed by https://github.com/istio/api/pull/1540
