### ISSUE TITLE
Conflict description about mTLS keys and certificates errors

### ISSUE THREAD

**Issue by tx19980520** [istio/istio.io#7221]
in istio [1.5 upgrade notes](https://istio.io/news/releases/1.5.x/announcing-1.5/upgrade-notes/), the docs say that 

> Citadel served two functions: writing certificates to secrets in each namespace, and serving secrets to the nodeagent over gRPC when SDS is used. In Istio 1.5, secrets are no longer written to each namespace. Instead, they are only served over gRPC. This functionality has been moved to the istiod deployment.

So that now we can not get certificates and keys from secret like istio.default.
But in the [keys and certificates errors](https://istio.io/docs/ops/common-problems/security-issues/#mutual-tls-errors), the action is the same as 1.4 and before. Maybe the page need update now.

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/ops/common-problems/security-issues/#keys-and-certificates-errors has been updated since
