### ISSUE TITLE
No instructions for how to prune old version resources in canary upgrade docs/setup/upgrade/index.md

### ISSUE THREAD

**Issue by elfinhe** [istio/istio.io#7244]
We may need to add a `clean up` section for canary upgrade to prune the unused old version resources in the end.

https://preliminary.istio.io/docs/setup/upgrade/

**Comment by howardjohn** [comment]
Added now: https://preliminary.istio.io/latest/docs/setup/upgrade/canary/#uninstall-old-control-plane
