### ISSUE TITLE
Issue with docs/tasks/traffic-management/egress/wildcard-egress-hosts/index.md

### ISSUE THREAD

**Issue by michaeldduffield** [istio/istio.io#7254]
The `istioctl manifest generate` command listed in step 3 of the section [Setup egress gateway with SNI proxy](https://istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#setup-egress-gateway-with-sni-proxy) does not appear to be equivalent to the `helm template` command provided in the documentation of previous istio versions, as it other artefacts in addition to the gateway `ServiceAccount` `Service` and `Deployment` artefacts generated by the previously documented (helm) command.

**Comment by howardjohn** [comment]
This is obsolete in the current form of the docs
