### ISSUE TITLE
Invalid year in footer for page 404.html

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#7256]
If you hit the following pages, it will display an invalid year in footer.

https://istio.io/docs/reference/config/type/v1beta1/workload-selector.html#WorkloadSelector

![1 5 2](https://user-images.githubusercontent.com/2920003/81554499-872cc800-93a4-11ea-9583-40610c3cd85e.png)

https://preliminary.istio.io/docs/reference/config/type/v1beta1/workload-selector.html#WorkloadSelector

![1 6](https://user-images.githubusercontent.com/2920003/81554525-9744a780-93a4-11ea-89e8-dc60adff7c27.png)

**Comment by frankbu** [comment]
This seems like reasonable expected behaviour. It does this for any invalid path, e.g., https://istio.io/junk. It makes sense that the date will be invalid, given the page doesn't exit.

**Comment by shamsher31** [comment]
@frankbu Does it make sense to display the current date instead of `Jan 1, 0001`?

**Comment by frankbu** [comment]
Since the page doesn't exist, it was never modified, so `Jan 1, 0001` is a better `last modified date` than the current date, which would imply the non-existent page was modified today.

**Comment by shamsher31** [comment]
Ok, closing this issue then.
