### ISSUE TITLE
Update Performance and Scalability page for 1.7

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.io#7271]
1. Update with latest performance numbers for 1.6 with fortio.
2. Add Night Hawk numbers and specify why we are adding these tests.

**Comment by carolynhu** [comment]
Our perf pipeline needs to gather enough data before publishing the Nighthawk number. For now, we will only publish fortio number. We will add Nighthawk number later on.

**Comment by brian-avery** [comment]
@carolynhu is this still for 1.6 or can we update this to reference 1.7?

**Comment by carolynhu** [comment]
@brian-avery this should be marked as 1.7
