### ISSUE TITLE
Issue with docs/setup/getting-started/index.md

### ISSUE THREAD

**Issue by taromurata** [istio/istio.io#7303]
I think the command below
`$ echo http://$GATEWAY_URL/productpage`
should be
`$ curl http://$GATEWAY_URL/productpage`
or else.

**Comment by shamsher31** [comment]
```
$ echo http://$GATEWAY_URL/productpage
```
> Confirm that the Bookinfo application is accessible from outside. Copy the output of this command and paste into your browser:

I think here we are asking the user to copy URL and paste it into browser URL to test, as we are testing outside access to `productpage`. So I think `echo` is correct.

**Comment by taromurata** [comment]
Ok, I mis read the doc...
Thank you for your comment.
