### ISSUE TITLE
The same documentation URL for AuthenticationPolicy (namespace-wide) display two resource type different depending on the localisation

### ISSUE THREAD

**Issue by scraly** [istio/istio.io#7316]
HI,

About AuthenticationPolicy we saw a difference in the documentation between 2 URLs. It's the same URL but in the second case it's for "pt-br" language/country.

* 
https://istio.io/docs/tasks/security/authentication/authn-policy/#namespace-wide-policy

--> Talk about **PeerAuthentication** resource type

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/2543381/81900658-933fa200-95bd-11ea-8311-0cbbca7285e5.png">

* 
https://istio.io/pt-br/docs/tasks/security/authentication/authn-policy/#namespace-wide-policy

--> Talk about **Policy** resource type

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/2543381/81900726-b0747080-95bd-11ea-813e-234fc3ad5315.png">

So what's the good resource type?
Thanks for take a look about this difference.

Thanks :)

**Comment by shamsher31** [comment]
Thanks @scraly for taking the time to report the issue. The docs under `pt-br` are maintained by different language teams, so occasionally it takes time to update the docs. Meanwhile, you can refer `en` docs which are updated frequently. 

As per the [latest updates](https://github.com/istio/istio/pull/20829) `PeerAuthentication` is the right resource type for namespace wide policy.

**Comment by howardjohn** [comment]
pt-br docs are removed now
