### ISSUE TITLE
IPV6 is not supported. Add a deprecation to the feature status page.

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#7332]
https://preliminary.istio.io/about/feature-stages/#core

See other deprecations.
Additionally, the release notes must be modified to indicate the deprecation.

**Comment by howardjohn** [comment]
Why are we "deprecating" it? I think describing it as alpha is perfect. It works fine more or less (I have been running it a bit recently) but is undertested. It will be fully automated tested by 1.7 so I am not sure we need to deprecate it really

**Comment by howardjohn** [comment]
I think on TOC we were discussing dual stack not pure ipv6

**Comment by jacob-delgado** [comment]
cc @louiscryan @linsun @rshriram @dcberg @smawson @duderino 

The meeting minutes say to remove this, but would like it for a TOC member to rectify this. I have a draft PR to remove this.

**Comment by sdake** [comment]
The conversation moved pretty fast. The question I asked was "Do you want to remove IPv6 from the supported list of features for 1.6" the answer was "yes, please assign to me" from @nrjpoddar. I could have misunderstood the answer.

I assigned to @jacob-delgado as @nrjpoddar seemed busy at the time.

Cheers
-steve

**Comment by jacob-delgado** [comment]
> The conversation moved pretty fast. The question I asked was "Do you want to remove IPv6 from the supported list of features for 1.6" the answer was "yes, please assign to me" from @nrjpoddar. I could have misunderstood the answer.
> 
> I assigned to @jacob-delgado as @nrjpoddar seemed busy at the time.
> 
> Cheers
> -steve

Thanks for the clarification. When you said colleague I was thinking Brian as a RM. Its’s been a long day.

**Comment by nrjpoddar** [comment]
Alpha seems fine to me, if we have any other tasks/docs for IPv6 or dual stack we should hide it or put a warning in it.

**Comment by nrjpoddar** [comment]
@sdake yeah, I was thinking about broader tasks or Ops docs and not removing IPv6 support completely as it’s currently alpha. If you or TOC members feel we should completely remove it, happy to do that too. Yeah, the conversation moved pretty fast..

**Comment by sdake** [comment]
@nrjpoddar Not my fight.

I do want to ensure our current feature lifecycle is followed, [to the letter](https://github.com/istio/community/blob/master/FEATURE-LIFECYCLE.md). I accepted the conversation in the TOC to mean IPv6 is i"in-development".

IMO to meet an ALPHA level feature stage, documentation is mandatory. Unfortunately, the current feature lifecycle is a little vague on the documentation requirements.

I had not intended to miscommunicate that the implementation should be changed or removed. That would be super disruptive. The goal of the community repo is to improve Istio, and the feature status checklist is meant to serve as a guide of the progression of features through Istio.

As no documentation has been produced for IPv6 that I am aware of. I didn't immediately see how to communicate a demotion from alpha to in-dev without a deprecation, hence the suggestion of a deprecation.

A good compromise would be to remove the feature from the feature status pages, pretend like it isn't there like we do for all other in-dev features.

For 1.7, if it isn't a priority, IPv6 should have a feature guard, as we have required for all alpha features in the past.

Cheers
-steve

**Comment by sdake** [comment]
> > The conversation moved pretty fast. The question I asked was "Do you want to remove IPv6 from the supported list of features for 1.6" the answer was "yes, please assign to me" from @nrjpoddar. I could have misunderstood the answer.
> > I assigned to @jacob-delgado as @nrjpoddar seemed busy at the time.
> > Cheers
> > -steve
> 
> Thanks for the clarification. When you said colleague I was thinking Brian as a RM. Its’s been a long day.

I don't remember mentioning the word colleague, but are you not a colleague? I consider you one, hence the assignment.

Cheers
-steve

**Comment by nrjpoddar** [comment]
Thanks Steve for your clarification, I will iron it out with TOC and Costin and then make sure the necessary changes are merged.

**Comment by costinm** [comment]
AFAIK there are 3 problems:
1. While we did have IPv6 support for some time - the automated tests are
no longer running, and they need to be restored.

2. We do not support 'dual stack' - this needs to be reflected in the doc
for 1.6

3. And we need to fix the 'dual stack' support for 1.7

Like CNI, users don't have a choice - if their infrastructure is based on
IPv6 we can't just say 'sorry, don't use Istio'.

**Comment by smawson** [comment]
Given this is already listed as alpha in 1.5 let's just leave it as alpha, and maybe update the description to clarify that dual stack is not supported (assuming it was never meant to be supported).

**Comment by costinm** [comment]
Sounds good.

Initial automated test was for single-stack ipv6.
Afaik original code handled dual stack - but refactorings and lack of
explicit test ( and removal of some test suites) resulted in a regression.
