### ISSUE TITLE
Setup versioned doc site with Istio release, not after the next release.

### ISSUE THREAD

**Issue by mandarjog** [istio/istio.io#7379]
Doc site has the following structure

* preliminary.istio.io  which points to unreleased / master version of the doc.
* istio.io --> currently released version of the doc.
* archive.istio.io/${version}

### Problem
The current structure makes it impossible to send out version specific links until the next version is released.
For example istio 1.5 had a specific way of configuring telemetry, and I could not send a link to the specific version until 1.6 was released and archive.istio.io/v1.5  appeared.

### Proposal
1. Create archive.istio.io/v1.6 *now* so that we *can* send out version specific links if needed.
2. istio.io should internally rewrite urls to archive.istio.io/v1.6 (or it can redirect, but that has issues)

Envoy creates version specific site at release time https://www.envoyproxy.io/docs/envoy/v1.14.1/
 and https://www.envoyproxy.io/docs/envoy/latest/ is their version of preliminary.

**Comment by mandarjog** [comment]
cc @gnarled-cipher

**Comment by davidhauck** [comment]
I'm actively working on a design doc to re-think how we do archives: https://docs.google.com/document/d/17w5O_fF2BBjCGbeHxI82qSKZG6K6JSF9wcvflkdBNgQ

It's a WIP right now, but let's make sure the design takes this into account.

**Comment by shamsher31** [comment]
Not stale.

**Comment by frankbu** [comment]
This has been fixed a while ago. The next release URL is created at the same time that the current release is updated: https://istio.io/v1.9/
