### ISSUE TITLE
All installation docs (simple/custom) should state that the namespace has to be created manually since 1.6

### ISSUE THREAD

**Issue by mlazowik** [istio/istio.io#7390]
Release notes for 1.6 say:
> Changed the Istio installation to no longer manage the installation namespace, allowing more flexibility.

As far as I see the general installation docs do not mention the namespace creation step.

**Comment by ericvn** [comment]
The namespace is still created if it's not there during the install. It will not be deleted after Istio is removed. That is documented in #7156 in terms of adding text to remove the potentially extraneous namespace.
