### ISSUE TITLE
1.5 docs are not available at archive.istio.io

### ISSUE THREAD

**Issue by jbrook** [istio/istio.io#7394]
It seems that the 1.5 docs are not published in the archive at https://archive.istio.io/. The badges on this repo show failing Netlify tasks.

**Comment by boredabdel** [comment]
Is it possibly related to the failed build for archive.istio.io ? https://app.netlify.com/sites/archive-istio/deploys

**Comment by davidhauck** [comment]
This should be fixed now. I'll close this unless there's a reason to keep it open
