### ISSUE TITLE
Scaling issues on istio.io

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#7412]
The Istio.io sidebar doesn't seem to scale properly. When browsing https://istio.io/docs/setup/additional-setup/cni/, I see: 

![image](https://user-images.githubusercontent.com/8484260/83036466-a3696f80-a008-11ea-9063-3347653ef003.png)

**Comment by brian-avery** [comment]
This is on Google chrome on a 1920x1080 screen with zoom set at 150%

**Comment by shamsher31** [comment]
Related https://github.com/istio/istio.io/issues/6912

**Comment by brian-avery** [comment]
This no longer overflows with the changes on preliminary.istio.io. 

https://preliminary.istio.io/latest/docs/setup/additional-setup/cni/
