### ISSUE TITLE
Ambiguity re "ports" on docs/reference/config/networking/service-entry/index.html

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#7457]
The page currently at https://istio.io/docs/reference/config/networking/workload-entry/#WorkloadEntry documents a "ports" fields as "The ports associated with the external service. ..."

That text seems to be confusingly ambiguous.  Does it mean:

- local ports (defined by the ServiceEntry) _to be associated_ with the external service (e.g., from which to forward to the actual/existing ports of the external service, or
- the actual/existing ports of (_already associated with_) the external service?

**Comment by ericvn** [comment]
The document comes from `https://github.com/istio/api/blob/release-1.6/networking/v1alpha3/workload_entry.pb.html`.

**Comment by ericvn** [comment]
@rshriram Any input on this?
