### ISSUE TITLE
Why Pre 1.7 docs with colour gradient not used for 1.6 docs.

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#7468]
1.7 Docs look better with the color gradient.

![1 7-header](https://user-images.githubusercontent.com/2920003/83718220-4138ec00-a652-11ea-986e-0dc281f6dd9e.png)
![1 7-buttons](https://user-images.githubusercontent.com/2920003/83718227-4433dc80-a652-11ea-80d4-f5eca26575b5.png)
![1 7-footer](https://user-images.githubusercontent.com/2920003/83718233-46963680-a652-11ea-8b05-dbf94ade4bff.png)

1.6 docs without gradient.

![1 6-header](https://user-images.githubusercontent.com/2920003/83718307-70e7f400-a652-11ea-8c5d-fc439ea66503.png)
![1 6-buttons](https://user-images.githubusercontent.com/2920003/83718311-72b1b780-a652-11ea-83eb-2691aa2014db.png)
![1 6-footer](https://user-images.githubusercontent.com/2920003/83718313-73e2e480-a652-11ea-94e1-ac8fb5248bb2.png)

Is it possible to use Pre 1.7 docs with the color gradient for 1.6 docs also?

**Comment by howardjohn** [comment]
Docs had a full redesign since then
