### ISSUE TITLE
No doc. for docs/reference/config/istio.operator.v1alpha1/index.html#ServicePort

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#7503]
In the section at https://istio.io/docs/reference/config/istio.operator.v1alpha1/#ServicePort, none of the members/fields has any specification beyond the name, data type,and optionality (i.e., no description text).

For example, what values can the `protocol` member take? This documentation neither specifies that nor points to existing documentation that also applies here.  For another example, does the form of the value in the `name` member affect anything (e.g., the default protocol)?

(I'd report more sections with missing documentation to help you keep track of needed documentation, but since (unless I'm mistaken) you automatically close issues that you haven't had time and priority to get to yet (rather than more responsibly leaving them open and easily visible), it doesn't seen worth the time to do so.

Or should I change this report to cover all sections of this page that don't have member descriptions, so that issue activity for any section all goes to this one issue, so that maybe this issue will get "pinged" often enough to not get auto-closed and forgotten?)

**Comment by ericvn** [comment]
Hello. If you actually look at the file: https://github.com/istio/istio.io/blob/release-1.6/content/en/docs/reference/config/istio.operator.v1alpha1/index.html in this case, you will see that the file is copied by the doc them from another repo (line 3): https://github.com/istio/api.

The file there that is copied into the doc is: https://github.com/istio/api/blob/release-1.6/operator/v1alpha1/istio.operator.v1alpha1.pb.html.

Typically, the doc team does not make updates to the api files. It might be better to create a PR in istio/istio (I'm not sure the operator team necessarily watches the istio.io repo for Issues?). I'll tag them with a label. @ostromart, any thoughts on this issue?

**Comment by ostromart** [comment]
Hi, these are all mirrors of k8s protos, copied here for validation (including k8s protos directly is not possible due to compatibility problems). There are definitely missing annotations of where some messages are copied from - I'll take care of those.

**Comment by ostromart** [comment]
https://github.com/istio/api/pull/1464

**Comment by ostromart** [comment]
Fixed: https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha1/
