### ISSUE TITLE
Remove obsolete istioio test framework code

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#7544]
Now that we have a new [istioio test driver](https://github.com/istio/istio.io/blob/master/tests/doc_test_framework.go), the [old framework classes](https://github.com/istio/istio.io/tree/master/pkg/test/istioio) should be deleted.

The new framework is currently [using the Builder and Script classes](https://github.com/istio/istio.io/blob/1d7a2383bdc69714b72a3e1e31192edd3bcc2560/tests/doc_test_framework.go#L195) from the old framework, which also needs to be changed. Note that with the current implementation, the standard includes (verify.sh, debug.sh, helpers.sh) are being sourced twice in the script (once in the [new code](https://github.com/istio/istio.io/blob/1d7a2383bdc69714b72a3e1e31192edd3bcc2560/tests/doc_test_framework.go#L52) and again in the [old code](https://github.com/istio/istio.io/blob/1d7a2383bdc69714b72a3e1e31192edd3bcc2560/pkg/test/istioio/script.go#L77).

If some of the old istioio framework code is useful/needed, it should be cleaned up to remove the parts that are obsolete and then move `doc_test_framework.go` to the istioio test package, instead of having framework code in two different places.

**Comment by niwatorrri** [comment]
I'm keeping part of the old classes as they are needed.
I'd also remove the `ENV` variable since the native mode is removed per [here](https://github.com/istio/istio/pull/24149).

**Comment by niwatorrri** [comment]
Further cleanup #7640

**Comment by niwatorrri** [comment]
It might be weird to ask after 10 months but is there a way I can close this issue?
