### ISSUE TITLE
Too many redirects (about)

### ISSUE THREAD

**Issue by ronaldpetty** [istio/istio.io#7665]
Hello,

The about page has issues linking, getting 301 loops on most of the links.

https://istio.io/latest/about/

For example, clink on:

Reporting Bugs

**Comment by craigbox** [comment]
Working for me; we've been having issues with Netlify which should be fixed so it could have been related to a bad push.  Can you still repro?

**Comment by davidhauck** [comment]
I got a response from netlify that this was an issue earlier today and they are working on a fix. They said our site has been good for the past few hours, so hopefully that means everything works now.

**Comment by ronaldpetty** [comment]
Hi guys, I just checked again.  All the links that were looping appear good now.  Will close for now!
