### ISSUE TITLE
Issue with docs/tasks/traffic-management/mirroring/index.md

### ISSUE THREAD

**Issue by qiuhongshuai** [istio/istio.io#7703]
kubectl exec -it $SLEEP_POD -c istio-proxy -- sudo tcpdump -A -s 0 host $V1_POD_IP or host $V2_POD_IP
when I execute above command，I got an error like this:
`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`
no nfs or other cinfigure

**Comment by frankbu** [comment]
Fixed in Istio 1.5+ by https://github.com/istio/istio.io/pull/6787
