### ISSUE TITLE
Issue with docs/setup/upgrade/index.md

### ISSUE THREAD

**Issue by hobbytp** [istio/istio.io#7715]
The "upgrading from 1.4.x" will not jump to correct link.
```
See additional notes for upgrading from Helm installations and upgrading from 1.4.x.
```
it will try to jump to 
https://istio.io/latest/docs/setup/upgrade/#upgrading-from-1.4
But the correct one is 
https://istio.io/latest/docs/setup/upgrade/#upgrading-from-1-4

**Comment by howardjohn** [comment]
Link is removed
