### ISSUE TITLE
Failed k8s tests report succeeded

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#7720]
Even though some of the tests failed, sometimes the istio.io doc test summary says it succeeded.
Here's an example: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio.io/7714/k8s-tests_istio.io/2556

**Comment by niwatorrri** [comment]
Are there other tests that have been added lately? I noticed there are 30 tests reported.

**Comment by frankbu** [comment]
@niwatorrri 3 of the tests are currently disabled, but the PR associated with the above link is trying to re-enable them, for a total of 27 tests + 3 DocTests = 30 total.

It looks like this is a general problem, not just istio.io. https://github.com/istio/istio/issues/25463
