### ISSUE TITLE
Istio installation error -

### ISSUE THREAD

**Issue by nikhilbalekundargi** [istio/istio.io#7723]
Trying to install istio by generating the manifest and apply the yaml on the cluster.

Generated yaml using command - 
`istioctl manifest generate > istio.yaml`

Attached the yaml for reference.
[istio.yaml.txt](https://github.com/istio/istio.io/files/4914074/istio.yaml.txt)

then applying the yaml on the cluster using - 
`kubectl apply -f istio.yaml`

 this is giving below error -
```
unable to recognize "istio.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "Sidecar" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "EnvoyFilter"
```

while` istioctl manifest apply` works fine.

**Comment by howardjohn** [comment]
This doc is no longer relevant
