### ISSUE TITLE
Run subset of doc tests in presubmit

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#7762]
Running the full suite of doc tests in presubmit is a waste of time because most PRs are only changing a small number (often just one) doc. In fact, sometimes the changed doc in the PR doesn't even have any associated test (e.g., a concepts doc).

Since we now have the ability to test subsets of the docs, it would be great if during presubmit we only run the tests associated with changed files in the PR. For example:

1. PR with changed file: `content/en/docs/tasks/traffic-management/request-routing/index.md`
2. Run test command `make doc.test TEST=tasks/traffic-management/request-routing`

If more than one test needs to run, they can be passed to the `TEST=` variable as a comma-separated list.

**Comment by frankbu** [comment]
One special case: A PR that updates the istio/istio SHA, used for testing, should run the full suite.

**Comment by linsun** [comment]
@ericvn or @sdake does one of you have any bandwidth to help with this?

**Comment by ericvn** [comment]
I should have some time to help with this.

**Comment by linsun** [comment]
Thank you @ericvn !
