### ISSUE TITLE
Documentation mismatch for Virtual Service HTTPRouteMatch and StringMatch objects

### ISSUE THREAD

**Issue by fr0stylo** [istio/istio.io#7766]
Documentation mismatches

HTTPMatchRequest states that uri supports regex that is Ecmascript style
https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest
String match states that it supports RE2 regexps
https://istio.io/latest/docs/reference/config/networking/virtual-service/#StringMatch

**Comment by ericvn** [comment]
This would actually be an issue in the https://github.com/istio/api/blob/release-1.6/networking/v1alpha3/virtual_service.proto and https://github.com/istio/api/blob/release-1.6/networking/v1beta1/virtual_service.proto files. Will need someone from the networking team to take a look.

**Comment by howardjohn** [comment]
this has been updated to show re2
