### ISSUE TITLE
Getting started - differences: demo profile has no addons, kiali anonymous auth, broken link

### ISSUE THREAD

**Issue by xeviknal** [istio/istio.io#7769]
https://preliminary.istio.io/latest/docs/setup/getting-started

I've been testing the 1.7 alpha version of kiali with the preliminary doc. I've followed the getting started page and I've found the following differences and inconsistencies:

1. The demo profile doesn't install the addons so far: https://preliminary.istio.io/latest/docs/setup/getting-started/#install
I see that in the command snippet says that the addons have been installed. I didn't see it anymore.
```
$ istioctl install --set profile=demo
✔ Istio core installed
✔ Istiod installed
✔ Egress gateways installed
✔ Ingress gateways installed
✔ Addons installed
✔ Installation complete
```

2. The URL that points to the kiali integration yaml is wrong
`kubectl apply -f https://github.com/istio/istio/tree/master/samples/addons/kiali.yaml -n istio-system`
it should point to the [raw](https://raw.githubusercontent.com/istio/istio/master/samples/addons/kiali.yaml) version of it.

3. Kiali is installed now with anonymous version, so the admin/admin user/passwd are not necessary anymore.

4. This is quite related to 1). Prometheus is a required addon for kiali to work. Grafana and jaeger are optional. So I am wondering if this page should also suggest a way to install prometheus for the telemetry to be ready for kiali and thus render the graph most of the other kiali features.

Do you guys think it would be worth to change something related to the above? I am not fully following the installation meetings so I might be out of sync.

**Comment by jmazzitelli** [comment]
I agree with this.

Yes, the new addons uses [anonymous strategy as seen here](https://github.com/istio/istio/blob/1.7.0-alpha.0/samples/addons/kiali.yaml#L418-L419). This is appropriate; this is, after all, just for demos and "kick the tires". So the docs should not mention default credentials of admin/admin anymore.

Kiali requires Prometheus addon, but the getting-started only shows Kiali add-on being added. I think it should just instruct the user to install all the addons (after all, Kiali has integrations with Jaeger and Grafana too so it would be helpful to have them install them here, too). To install all addons, should be `kubectl apply -f samples/addons -n istio-system` as explained in the [README here](https://github.com/istio/istio/blob/master/samples/addons/README.md#getting-started).

**Comment by howardjohn** [comment]
Thanks for the feedback! I will incorporate these changes into https://github.com/istio/istio.io/pull/7802

**Comment by xeviknal** [comment]
Comments approached! Closing the issue. Thanks
