### ISSUE TITLE
Link in AuthorizationPolicy to WorkloadSelector broken?

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#7790]
If I go to https://istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy and click the `WorkloadSelector` Type in the table I get a 404.

This has changed on the pre-release docs, but still seems wrong.  If I go to 

https://preliminary.istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy and click the `WorkloadSelector` Type in the table it takes me to
https://preliminary.istio.io/latest/docs/reference/config/networking/sidecar/#WorkloadSelector#WorkloadSelector
it should instead take me to
https://preliminary.istio.io/latest/docs/reference/config/networking/sidecar/#WorkloadSelector

**Comment by ericvn** [comment]
Should have been fixed in https://github.com/istio/api/pull/1550. I suspect there is no automation to update preliminary.istio.io from the master branch api (this doesn't happen automatically from the time the branches are cut (all but istio.io until release).

I will do a manual pull.

**Comment by ericvn** [comment]
https://github.com/istio/test-infra/pull/2845 created for auto merge
