### ISSUE TITLE
Missing instructions for Addon Telemetry component installation

### ISSUE THREAD

**Issue by nschhina** [istio/istio.io#7793]
Observed here: https://preliminary.istio.io/latest/docs/tasks/observability/metrics/using-istio-dashboard/ 
`--set values.grafana.enabled=true` is deprecated and no new instructions are available for installation directly using deployment files in samples/addons for all addons

**Comment by douglas-reid** [comment]
@howardjohn did we ever generate docs on the new add-ons install guidance?

**Comment by howardjohn** [comment]
@douglas-reid we have some minimal guidance, working to improve this. Btw, samples/addons/README.md currently provides a fair amount of info on this. I will take this on

**Comment by nschhina** [comment]
Can confirm samples/addons/README.md was helpful and sufficient, just some improper guidance on istio.io can result in some wasted time.
