### ISSUE TITLE
Add version supported kubernetes release table 

### ISSUE THREAD

**Issue by kramvan1** [istio/istio.io#7821]
Like in this doc, would be useful to have a complete support picture, matrix of Istio releases and kubernetes releases. 
https://docs.google.com/document/d/14Xfe9V0vv8d7W75c21d-cY2XyK6xvRH0_Kg8j_zfh4Y/

**Comment by kramvan1** [comment]
cc @sdake @frankbu

**Comment by linsun** [comment]
Mark, can you propose what is missing?  Are you suggesting us to publish for unreleased istio versions and their k8s supported versions?

**Comment by kramvan1** [comment]
Yes, for published releases and next master release, would be good to know what is being tested/supported.   We are pulling some of the alpha/beta releases and would want to also test them on our matching kubernetes releases.   At some point during the alpha/beta process, the supported kube releases should be known/tested and published to give folks a chance to also test and provide feedback before the GA.

**Comment by sdake** [comment]
@linsun in the doc was a request to add new releases to the RFC. The purpose of the RFC was to define the supported release patterns in Istio. I had responded to Mark that the best place to keep that updated was on istio.io, rather than modify an approved RFC.

Cheers,
-steve

**Comment by linsun** [comment]
Agreed, would be best to publish this in istio.io.  Took me a while to find the RFC for mark :)

cc @howardjohn

**Comment by howardjohn** [comment]
I have a PR for this but I gave up on getting it merged: https://github.com/istio/istio.io/pull/7154. anyone is free to pick it up

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases
