### ISSUE TITLE
issue about '--set flag' of 'istioctl upgrade'

### ISSUE THREAD

**Issue by ch0312** [istio/istio.io#7840]
https://istio.io/latest/docs/setup/upgrade/#upgrade-steps

The above page says 'istioctl upgrade does not support the --set flag.'
However, the following page shows --set flag.

https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-upgrade

In fact, when performing an in-place upgrade from 1.5.2 to 1.6.4, using the --set flag, I was able to upgrade without any problems.
I ran the following command

$ istioctl upgrade --dry-run --set profile=demo --set values.global.proxy.privileged=true --set values.global.proxy.accessLogEncoding=JSON --set values.global.proxy.logLevel=info

I think the statement 'istioctl upgrade does not support the --set flag.' should be removed.

**Comment by howardjohn** [comment]
This is now removed
