### ISSUE TITLE
Configuration Analysis Messages does not include IST0114-117 and 120-133

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#7844]
https://preliminary.istio.io/latest/docs/reference/config/analysis/ shows, but does not link to, IST0114-117 and 120-127.

The text is not hyperlinked.
The URLs are not included in the documentation, when `istioctl` supplies direct URLs to the messages that are not present.

Related:
- [ ] https://github.com/istio/istio.io/pull/8486 Add documentation for Analysis messsage IST0132 VirtualServiceHostNotFoundInGateway

**Comment by ericvn** [comment]
Those directories have never been created and filled with the docs: https://github.com/istio/istio.io/tree/master/content/en/docs/reference/config/analysis

**Comment by esnible** [comment]
@ericvn Is the expectation that UX, who wrote the analyzers, contribute those directories?

I had hoped a tool made them from _galley/pkg/config/analysis/msg/messages.yaml_, and that we just improved them.  However, I am willing to assign someone to make them.  Use the existing ones as a template?

**Comment by frankbu** [comment]
I believe Adam created the ones that are there, but maybe nobody has been keeping them up to date with new codes??

cc @adammil2000, do you know what the process is supposed to be to manage these?

Generating them would be nice, if possible.

**Comment by esnible** [comment]
@jasonwzm are you still working on this?
cc @frankbu

**Comment by esnible** [comment]
Four of the messages are no longer generated by Istio and should be removed from the docs: 
IST0114, IST0115, IST0120, IST0121

Twelve messages are still generated and lack detail pages and are not targette by another PR: 
IST0116, IST0117, IST0122, IST0123, IST0125, IST0126, IST0127, IST0128, IST0129, IST0130, IST0131, IST0133

**Comment by esnible** [comment]
@jasonwzm I wrote docs for all of the codes except 126.  It seemed complicated, so I decided to leave it for the original analyzer author -- you.

**Comment by jasonwzm** [comment]
@esnible 126's logic is obsolete. I will work with Steven on refactoring that. https://github.com/istio/istio/issues/28906

**Comment by esnible** [comment]
@jasonwzm If you remove 126's logic, remove 126 from messages.yaml and close this Issue.

**Comment by ericvn** [comment]
Just looking at https://preliminary.istio.io/latest/docs/reference/config/analysis/ and there are a number of messages without links.
