### ISSUE TITLE
Configurability (Beta/Development) page isn't very clear on setting trace options

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#7902]
https://preliminary.istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/

The first two sections on this page talk about ways to set the tracing options, while the following sections talk about various options. 

The issue is there really isn't any discussion about the sections and what they mean. There just are some sections.

It would be nice to have some words stating that there are some ways to set the options (first two sections) and options that can be set ( rest of the sections).

**Comment by nrjpoddar** [comment]
@ericvn I just started testing this and will work on PR to fix the issues you mentioned. It's also missing steps about restarting pods which is required for config to take effect.

**Comment by ericvn** [comment]
Thanks @nrjpoddar for working on the PR for this. I was in the middle of testing this when It was noted I had my name on another item (not sure how it ended up on the other), so finished this and started the other.
