### ISSUE TITLE
In place upgrade steps are wrong

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#7925]
Verify that istoctl supports upgrading from your current Istio version by viewing the supported versions list:

$ istioctl manifest versions

Perhaps this cmd is removed?
```
$ istioctl manifest versions
The manifest subcommand generates, applies, diffs or migrates Istio manifests.

Usage:
  istioctl manifest [command]

Available Commands:
  diff        Compare manifests and generate diff
  generate    Generates an Istio install manifest
  install     Applies an Istio manifest, installing or reconfiguring Istio on a cluster.

Flags:
      --dry-run   Console/log output only, make no changes.
  -h, --help      help for manifest

Global Flags:
      --context string      The name of the kubeconfig context to use
  -c, --kubeconfig string   Kubernetes configuration file

Use "istioctl manifest [command] --help" for more information about a command.
```

**Comment by linsun** [comment]
cc @richardwxn @ostromart

**Comment by richardwxn** [comment]
I think this command was removed, instead, the validation of version is done during istioctl upgrade, if the the source version-> target version is not supported then the command would fail with error. Can you confirm? @elfinhe

**Comment by elfinhe** [comment]
correct, `istioctl manifest versions` was removed as part of this PR: https://github.com/istio/istio/pull/23512/files

**Comment by richardwxn** [comment]
@elfinhe then we need to update the doc accordingly, now it still instructs to check `istioctl manifest versions` during the in place upgrade guide
