### ISSUE TITLE
Command reference page shows duplicate entries.

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#7931]
There are duplicate entries for few commands.

**For upgrade command**
istioctl experimental upgrade
https://preliminary.istio.io/latest/docs/reference/commands/istioctl/#istioctl-experimental-upgrade

istioctl upgrade
https://preliminary.istio.io/latest/docs/reference/commands/istioctl/#istioctl-upgrade

**For Dashboard commands**
istioctl experimental dashboard
https://preliminary.istio.io/latest/docs/reference/commands/istioctl/#istioctl-experimental-dashboard

istioctl dashboard
https://preliminary.istio.io/latest/docs/reference/commands/istioctl/#istioctl-dashboard

**Comment by ericvn** [comment]
@esnible I'm not sure if there are two distinct commands at this point (one have some experimental features), or if the experimental version of the command was never removed.

**Comment by shamsher31** [comment]
@ericvn I have added https://github.com/istio/istio/pull/26408 to remove the `experimental dashboard` command.

**Comment by ericvn** [comment]
@shamsher31 If you expect to remove the duplicate entries in istio.io,  istio/istio#26408 will need to be cherry-picked to release-1.7.

**Comment by esnible** [comment]
@shamsher31 Can you create a PR to "hide" (mark as hidden) any commands that have graduated?

The reason for the commands to be there is to tell script users the new place to look for the command.

**Comment by shamsher31** [comment]
@ericvn I just cherry-picked for 1.7. Do you know how that documentation for commands is generated? I see more experimental commands which are graduated but still displayed in experimental sections. Thanks.

**Comment by shamsher31** [comment]
> Can you create a PR to "hide" (mark as hidden) any commands that have graduated?

@esnible with [hideInheritedFlags](https://github.com/istio/istio/blob/master/istioctl/cmd/root.go#L286) ?

**Comment by shamsher31** [comment]
@esnible @ericvn Is there a document that mentions the graduation of commands? 

I was looking into the `metrics` command and I think it can also be graduated?

**Comment by ericvn** [comment]
@shamsher31 We generate new ref docs (included command updates) for preliminary.istio.io right now on a daily basis.

**Comment by esnible** [comment]
> @esnible @ericvn Is there a document that mentions the graduation of commands?

There is no document that mentions that graduation of commands.  We mention specific commands that graduate in the release notes for a version.

To graduate a command needs to be useable, tested as part of integration, and complete enough that it isn't going to change much.

> I was looking into the `metrics` command and I think it can also be graduated?

The `metrics` command doesn't seem useable.  I recall we tried to graduate it once but it was felt to be difficult.  Are you using it?

For example, the syntax is `istioctl experimental metrics <workload name>` but there is no way to list workloads to know what can be used for a workload name.  I would love to see someone from UX team with someone from @istio/wg-policies-and-telemetry-maintainers on improving `metrics` and graduating it.

**Comment by esnible** [comment]
> @esnible with [hideInheritedFlags](https://github.com/istio/istio/blob/master/istioctl/cmd/root.go#L286) ?

@shamsher31 with `Hidden` https://github.com/spf13/cobra/blob/master/command.go#L80

**Comment by shamsher31** [comment]
> The metrics command doesn't seem useable. I recall we tried to graduate it once but it was felt to be difficult. Are you using it?

I saw that for the first time :). The Prometheus add-on provides rich metrics for workload so I think `istioctl x metrics` is not that useful.

**Comment by douglas-reid** [comment]
@esnible there is already an outstanding RFC on improving the metrics CLI, and someone that claimed they were working on it. You are cc'd on that issue. IMHO, that work is required before we can graduate the `metrics` command.

**Comment by esnible** [comment]
@shamsher31 The Issue and RFC that Douglas mentions can be found at https://github.com/istio/istio/issues/24309

**Comment by shamsher31** [comment]
@douglas-reid @esnible Thanks. Seems like a good improvement for `metrics`. I will take a look some time next week.
