### ISSUE TITLE
Broken Egress Gateway Task 

### ISSUE THREAD

**Issue by nschhina** [istio/istio.io#7938]
Task: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/

I recently added automated doc test for this task- @frankbu  found out an issue https://github.com/istio/istio.io/blob/41d56d97ffb67b6afa1b46f7f6aca797bb13c230/content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh#L95 
and commented out this snippet matching.

I'm able to reproduce this issue in this user task and I get the following output 
```
kubectl exec "$(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name})" -n test-egress -c sleep -- curl -v https://edition.cnn.com/politics
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 151.101.1.67:443...
* Connected to edition.cnn.com (151.101.1.67) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4789 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS hand
```
Expected output is 
```
Hostname was NOT found in DNS cache
  Trying 151.101.65.67...
  Trying 2a04:4e42:200::323...
Immediate connect fail for 2a04:4e42:200::323: Cannot assign requested address
  Trying 2a04:4e42:400::323...
Immediate connect fail for 2a04:4e42:400::323: Cannot assign requested address
  Trying 2a04:4e42:600::323...
Immediate connect fail for 2a04:4e42:600::323: Cannot assign requested address
  Trying 2a04:4e42::323...
Immediate connect fail for 2a04:4e42::323: Cannot assign requested address
connect to 151.101.65.67 port 443 failed: Connection timed out
``` 

I tried this with istio 1.7 beta 2 release. This seems like a P0 or P1 for 1.7 release.

**Comment by nschhina** [comment]
cc: @howardjohn networking wg owns this task can you please reassign this to whoever is maintaining this task? Thanks

**Comment by howardjohn** [comment]
> Immediate connect fail for 2a04:4e42::323: Cannot assign requested address

Why is this expected?

**Comment by nschhina** [comment]
Good question, I can't answer that because I didn't write this task and I'm not familiar with this `NetworkPolicy` API

**Comment by frankbu** [comment]
@howardjohn, the request is supposed to fail because a network policy was added to deny access. Take a look at steps 8 and 9 here: https://preliminary.istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#apply-kubernetes-network-policies

**Comment by howardjohn** [comment]
This is definitely not a release blocker, since its about configuring a non Istio thing. So our code is not wrong, although or docs may be. looking into it more

**Comment by howardjohn** [comment]
Honestly couldn't get the network policy part to work. Not sure why, seems like calico/gke/me being dumb problem. Definitely not istio issue though - at worst our example is wrong in the doc

**Comment by nrjpoddar** [comment]
cc @jacob-delgado

**Comment by jacob-delgado** [comment]
> Honestly couldn't get the network policy part to work. Not sure why, seems like calico/gke/me being dumb problem. Definitely not istio issue though - at worst our example is wrong in the doc

Tried this on a K8s 1.18.6 cluster running Istio 1.7.0-rc.1. This was provisioned on AWS with kops using flannel.

I would apply the NetworkPolicy and it would be accepted, but I wasn't able to get ``Hostname was NOT found in DNS cache...`. Instead, for Step 9 it would return HTML for the page. I even deleted the sleep pod to see if that was a workaround. Nope.

**Comment by nrjpoddar** [comment]
Tried this task with the following setup:

K8s version: 1.16.13
Istio version 1.7.0-rc.1
CNI plugin: Calico which enforces Network Policies

Without the Networking Policy defined step 5 [here](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/#apply-kubernetes-network-policies) 
```bash
  kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- curl -s -o /dev/null -w "%{http_code}\n"  https://edition.cnn.com/politics
```

results in `200` expected.

After the networking policy defined, I get this output:
```bash
kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- curl -v https://edition.cnn.com/politics
*   Trying 151.101.65.67:443...
*   Trying 2a04:4e42:600::323:443...
* Immediate connect fail for 2a04:4e42:600::323: Address not available
*   Trying 2a04:4e42:400::323:443...
* Immediate connect fail for 2a04:4e42:400::323: Address not available
*   Trying 2a04:4e42:200::323:443...
* Immediate connect fail for 2a04:4e42:200::323: Address not available
*   Trying 2a04:4e42::323:443...
* Immediate connect fail for 2a04:4e42::323: Address not available
*   Trying 2a04:4e42:600::323:443...
* Immediate connect fail for 2a04:4e42:600::323: Address not available
*   Trying 2a04:4e42:400::323:443...
* Immediate connect fail for 2a04:4e42:400::323: Address not available
*   Trying 2a04:4e42:200::323:443...
* Immediate connect fail for 2a04:4e42:200::323: Address not available
*   Trying 2a04:4e42::323:443...
* Immediate connect fail for 2a04:4e42::323: Address not available
```
which tells me that the Networking Policy is taking effect.

After injecting the sidecar into the sleep pod as part of step 10, and without applying the DR in step 13 I get this error
```bash
kubectl exec -it $(kubectl get pod -n test-egress -l app=sleep -o jsonpath={.items..metadata.name}) -n test-egress -c sleep -- curl -v https://edition.cnn.com/politics
*   Trying 151.101.1.67:443...
* Connected to edition.cnn.com (151.101.1.67) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to edition.cnn.com:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to edition.cnn.com:443
command terminated with exit code 35
```
like the description in issue says. I don't think it's because Networking Policy's not taking effect but the traffic is getting send to egress-gateway but without a subset defined s it's failing during TLS handshake.

After adding the DR as mentioned in step 13, it's working as expected.

AFAICT this task works as written and Network Policy prevents the sleep pod to reach out directly.

@jacob-delgado flannel doesn't enforce Network Policies by default so you would need to create the cluster with a CNI plugin that honors K8s network policies.

For folks seeing failures, it would be good to add which CNI plugin/Network policy enforcer they are using and which steps fails but my point of view this issue can be closed.

**Comment by frankbu** [comment]
@nrjpoddar In that case, it sounds like the kube cluster we use for the test framework (Kind) doesn't enforce network policies?

If so, then it sounds like the right fix is to leave that check commented out from the test: https://github.com/istio/istio.io/blob/41d56d97ffb67b6afa1b46f7f6aca797bb13c230/content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh#L95

We should probably also add a warning at step 9 in the doc: `{{< warning >}} Some Kubernetes clusters do not enforce network policies. Depending on your test cluster, the traffic may not be blocked as described in this step. {{< /warning >}}`

**Comment by nrjpoddar** [comment]
> @nrjpoddar In that case, it sounds like the kube cluster we use for the test framework (Kind) doesn't enforce network policies?
> 
> If so, then it sounds like the right fix is to leave that check commented out from the test:
> 
> https://github.com/istio/istio.io/blob/41d56d97ffb67b6afa1b46f7f6aca797bb13c230/content/en/docs/tasks/traffic-management/egress/egress-gateway/test.sh#L95
> 

I don't know what kind does. Someone can spin up a kind cluster and check if standalone Network Policies work.

> We should probably also add a warning at step 9 in the doc: `{{< warning >}} Some Kubernetes clusters do not enforce network policies. Depending on your test cluster, the traffic may not be blocked as described in this step. {{< /warning >}}`

I will add a note in docs to mention a warning like this.

**Comment by nrjpoddar** [comment]
Doc PR: https://github.com/istio/istio.io/pull/7967

**Comment by nschhina** [comment]
Thanks for triaging this further. Aa recommended I'll close this issue.
