### ISSUE TITLE
Issue with docs/tasks/traffic-management/egress/egress-control/index.md

### ISSUE THREAD

**Issue by marcfong** [istio/istio.io#8012]
John Howard informed me that the instruction to change mesh config for outBoundTrafficPolicy throuhg `kubectl patch istiooperator installed-state -n istio-system` will not work. 

Please update the documentation for the correct steps to edit Istio Configmap in istio-system.

**Comment by howardjohn** [comment]
@istio/wg-environments-maintainers  cns someone pick this up? not sure if we do the same in other docs as well

**Comment by howardjohn** [comment]
installed-state and docs are removed
