### ISSUE TITLE
every 45days to refresh cert

### ISSUE THREAD

**Issue by yonwon01** [istio/istio.io#8026]
i'm using Istio self-signed certificates, and my expiration date of the root certificate is 30 years. 
but Envoy is restarted every 45 days to refresh certificates. i searched from [here](https://istio.io/v1.2/docs/ops/traffic-management/troubleshooting/#headless-tcp-services-losing-connection), but there's no specific reason why refresh every 45 days. would you please explain it??
cuz, I didn't realized until DB disconnections occurred after 45 days..

thank you.

**Comment by howardjohn** [comment]
This no longer happens
