### ISSUE TITLE
Create doc for configuring PKI

### ISSUE THREAD

**Issue by nmittler** [istio/istio.io#8062]
https://docs.google.com/document/d/1up7KH1AndP6i4uvxqNAGGRjf90BD9UHDNFkC0LO7kHI/edit#

This needs to land for 1.8

**Comment by ericvn** [comment]
@nmittler I don't have access to that document.

**Comment by myidpt** [comment]
@ericvn Just moved it to the community folder. Please check again.

**Comment by ericvn** [comment]
@nmittler Works now.

**Comment by nmittler** [comment]
@myidpt I've submitted https://github.com/istio/istio.io/pull/8099 which updates only the `plugin CA` doc. I suspect you'll need to add more children to `Tasks->Security->Certificate Management`

**Comment by myidpt** [comment]
@nmittler Thanks for the work. Yes, I will finish the remaining work.

**Comment by ericvn** [comment]
Did this work actually get finished? Can this be closed?
