### ISSUE TITLE
Add example for OpenCensus in Distributed Tracing Section

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#8166]
Ref: https://preliminary.istio.io/latest/docs/tasks/observability/distributed-tracing/

https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Tracing

I think good to add a dedicated page for OpenCensus as @brianwolfe added support for it.

https://github.com/istio/istio/pull/27019
https://github.com/istio/api/pull/1563

**Comment by brianwolfe** [comment]
Yes, there is also some cleanup I’m planning to do around context propagation. If anyone else takes this, feel free, but otherwise I’ll probably have something up next week.

**Comment by PatrikSteuer** [comment]
I found this documentation very helpful, thanks a lot!
