### ISSUE TITLE
Missing capitalisation for accessLogEncoding default values.

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#8167]
Ref: https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1#MeshConfig

Search for accessLogEncoding

> Encoding for the proxy access log (text or json). Default value is text.

Possible values are `TEXT` and `JSON`. 
https://preliminary.istio.io/latest/docs/reference/config/istio.mesh.v1alpha1#MeshConfig-AccessLogEncoding

**Comment by ericvn** [comment]
Will leave this issue in this repo, although it could be moved to istio/api, as there is already a PR created.

**Comment by shamsher31** [comment]
I think more or less it's related to docs even though they are generated through API proto files. Although I guess moving to `istio/api` makes sense.

@ericvn will you recommend creating these kinds of issues in `istio/api` from next?

**Comment by ericvn** [comment]
@shamsher31 I think it sort of depends on if the change is relatively small and could be contained by a doc developer. I don't think non doc developers follow this repo all that much so if the change is needed by someone more affiliated with istio/api it should go there. If it's minor and a doc person can make the change in istio/api, than I could see it being created here. I hope that makes sense.
