### ISSUE TITLE
Authorization Policy content format error

### ISSUE THREAD

**Issue by doggy8088** [istio/istio.io#8178]
https://istio.io/latest/docs/reference/config/security/authorization-policy/

![image](https://user-images.githubusercontent.com/88981/93781207-b6f5b180-fc5b-11ea-9278-0ea6bdc3dfb2.png)

**Comment by ericvn** [comment]
Will be fixed by the cherry-pick of istio/api#1645 to release 1.7

**Comment by ericvn** [comment]
https://preliminary.istio.io/latest/docs/reference/config/security/authorization-policy/ has the change for the PR mentioned above. Once the cherrypick, https://github.com/istio/api/pull/1647, gets merged in 1.7 and we pull the new docs, the change will make it back into the istio.io version of the docs. That sometimes takes some time (order of weeks).

**Comment by ericvn** [comment]
Fixed by https://github.com/istio/istio.io/pull/8296
