### ISSUE TITLE
Issue with https://istio.io/docs/reference/config/installation-options/

### ISSUE THREAD

**Issue by javadebo** [istio/istio.io#8182]
This page does not exists, and it would be really good if there where any documentation anywhere where it would be possible to se the config options and which they are, since the once mentioned in the api proto does not work. 

https://istio.io/docs/reference/config/installation-options/

**Comment by shamsher31** [comment]
The installation option for the helm is deprecated and removed with the `1.6` release.

You can still find it in the older version of docs.
https://istio.io/v1.5/docs/reference/config/installation-options/
