### ISSUE TITLE
New multicluster docs not copy+pasteable

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#8237]
I went through the new docs. Since it used CLUSTER1 everywhere, i figured that was a decent name. So I copied all the steps, until the VERY end:

```
The Secret "istio-remote-secret-CLUSTER2" is invalid: metadata.name: Invalid value: "istio-remote-secret-CLUSTER2": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

It would be great to have this copy+pastable. Either use a valid name, or make it a variable?

**Comment by nmittler** [comment]
Yep I'm aware of this ... I already have a fix locally as part of writing he automated docs test.

**Comment by nmittler** [comment]
This should be fixed by https://github.com/istio/istio.io/pull/8248
