### ISSUE TITLE
Getting Started on minikube uses wrong port

### ISSUE THREAD

**Issue by danielkwinsor** [istio/istio.io#8286]
**Bug description**
The instructions for minikube on https://istio.io/latest/docs/setup/getting-started/ use the wrong ingress port after starting a minikube tunnel.  port 80 works, which the nodePort does not.  And prior to the minikube tunnel, neither 80 nor nodePort work

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
echo "http://$GATEWAY_URL/productpage"
should contain a URL that browser can reach.

**Steps to reproduce the bug**
```
$ kubectl get svc istio-ingressgateway -n istio-system

NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
istio-ingressgateway   LoadBalancer   10.103.187.208   127.0.0.1     15021:32404/TCP,**80:30087**/TCP,443:32563/TCP,31400:30569/TCP,15443:31388/TCP   105m

$ kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")]}'         
{"name":"http2",**"nodePort":30087,"port":80**,"protocol":"TCP","targetPort":8080}

$ export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
kubectl version --short
istioctl version --remote

Client Version: v1.19.2
Server Version: v1.19.2
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (8 proxies)

**How was Istio installed?**
curl -L https://istio.io/downloadIstio | sh -

**Environment where bug was observed (cloud vendor, OS, etc)**
Local

**Comment by ericvn** [comment]
I've worked through the page (from preliminary.istio.io as part of the community testing and alpha istioctl) several times over the last few weeks and haven't found any issues.

In my case:
```
echo "http://$GATEWAY_URL/productpage"
http://192.168.166.128:30890/productpage
```
```
kubectl get svc istio-ingressgateway -n istio-system 
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                                      AGE
istio-ingressgateway   LoadBalancer   10.105.68.78   <pending>     15021:30627/TCP,80:30890/TCP,443:30888/TCP,31400:30908/TCP,15443:32375/TCP   136m
```
I did not use `mk tunnel`.

I can try again with an older build, like the 1.7.2 noted above.
