### ISSUE TITLE
Link to Documentation archive broken (or incorret URL?)

### ISSUE THREAD

**Issue by JStickler** [istio/istio.io#8302]
https://archive.istio.io/ landing page does not include any obvious link to previous versions of the documentation.  

Steps to reproduce.
1 - Start at https://istio.io/latest/
2 - Click the Docs link in the toolbar.
3 - NOTE That there is a gear icon on this page that lets you link to either Next Release or Older Releases, but this is not obvious.  On the https://istio.io/latest/docs/ page, click the Documentation archive link at the bottom of the landing page.  
4 - On the https://archive.istio.io/ landing page, search in vain for a link to archived release docs.  Try clicking the Docs link again.  Land on the latest version of the docs (again).  Give up and go to the GitHub for istio.io to search for older versions of the documentation.  Read the README and find this "The user can trivially navigate between the different variations of the site using the gear menu in the top right of each page."  and finally figure out how to access previous versions of the docs.

Question - Should the Documentation Archive link to https://istio.io/archive/ instead?

Also, it looks like the gear icon is present, but not visible on the https://archive.istio.io/  page?  (Clicking the toolbar next to the About link summons the menu. ) Invisible icons are HORRIBLE for usability.

Environment
Version - 1.17 documentation
Linux OS
Firefox 68 AND Chrome 80

**Comment by craigbox** [comment]
archive.istio.io should probably be a redirect to https://istio.io/archive/ at this point.
