### ISSUE TITLE
Invalid syntax for the RSS feed

### ISSUE THREAD

**Issue by kappa-wingman** [istio/istio.io#8357]
I tried to add the rss to thunderbird, but it said the feed syntax is invalid.
URL of the feed: https://istio.io/latest/blog/feed.xml

Checked by the w3 validator:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fistio.io%2Flatest%2Fblog%2Ffeed.xml

**Comment by endlesslycurious** [comment]
Trying to subscribe to the [istio blog](https://istio.io/latest/blog/feed.xml) with [Inoreader](https://www.inoreader.com) fails with the following error:

> This XML document is invalid, likely due to invalid characters. XML error: Not well-formed (invalid token) at line 1, column 1

They currently list the last post as December 2020, so it seems its been broken for a while?
