### ISSUE TITLE
Determine Kubernetes supported versions for Istio 1.8.

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#8361]
I see the docs currently have support listed as 1.17, 1.18, and 1.19. I'm to sure if that's correct or not and didn't get a final answer via Slack.

**Comment by ericvn** [comment]
We do CI on 1.15 -> 1.19 today using kind.

**Comment by ericvn** [comment]
@istio/technical-oversight-committee have helped with this decision for prior releases.

**Comment by linsun** [comment]
Thanks @ericvn - can you add an agenda item for this in TOC mtg?
