### ISSUE TITLE
helm page issues

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#8374]
I have reviewed the full document as a whole.

1. I would change line 13 "pre-alpha" to "experimental." Istio has an experimental feature status, but not a pre-alpha stage.
1. I am not keen on line 115 - the migration from non-Helm environments. I think the stand-alone operator for Istio needs to be stopped first (deletion of the deployment as a minimum - the whole manifest ideally) before proceeding down this path.
1. I think it is important to clarify the uninstall warning n 122 - the CRs need not be deleted if the CRDs don't need to be deleted. Do the CRDs need to be deleted?
1. Are the optional steps really optional? I would think the ingress chart is needed in most cases unless using @ostromart 's operational guide for gateways.
1. You may consider linking to @ostromart 's operational gate for gateways here as well, to show more advanced operational procedures.
1. the workflow on 198 is not quite right. The gist is you go from 1.7.0->canary (1.8.0) - test the canary then ->istio 1.8.0 (not canary). This is a two-step process. I think this would be a stretch goal for the documentation.
1. Please delete lines 246-254. There is no reason that I am aware of to delete CRDs other than leaking the CRDs has some minor cost with Kubernetes etcde. While they leak from the cluster,
If you prefer I file these issues separately, I can do that, or you can expand this PR to address these problems. Your choice. Would like to see the outstanding issues resolved in the documentation for 1.7 - as the problems pointed out are likely to cause problems.

@costinm @howardjohn @ostromart thoughts on my review welcome.

**Comment by nrjpoddar** [comment]
@sdake here's my take on your suggestions above:

1. This wording was suggested by @frankbu in the PR and currently used in other pages like https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/ and https://preliminary.istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/. Let's figure out the right verbiage and I will make them consistent across the board. If we go with "experimental/development" we need to explain it on our docs as customers won't know what it means.
1. Can you elaborate on what not "too keen" means here? On lines 127-130 I link to the official steps for uninstalling Istio for `istioctl` and `operator`. Is that not sufficient?
1. CRDs don't need to be deleted but historically our uninstall steps removed everything including CRDs. I will clarify that users should follow steps to not delete CRDs.
1. I think so. Most of our customers and many open source users don't use istio ingressgateway. Why shouldn't it be marked optional?
1. Interesting, are you suggesting that after testing out the canary version, you do an in-place upgrade of your existing installation? I don't see this documented [here](https://istio.io/latest/docs/setup/upgrade/) but I can change if that's the best practice.
1. There are folks who want to try Istio at this stage and do a clean uninstall as far as I can tell. There's sufficient warning to explain the downsides. I can elaborate more to warn users but I feel like a clean uninstall should remove all artifacts if that's what a user wants.

**Comment by ericvn** [comment]
We do mention pre-alpha at https://github.com/istio/community/blob/master/FEATURE-LIFECYCLE.md

**Comment by sdake** [comment]
1. Thanks @ericvn. I got them mixed up :) Please ignore comment #1 
1. I think can be fixed simply be moving the warning up and joining the two sentences. Here is a rendered screenshot:
```Uninstalling Istio can cause your custom Istio configurations to be lost permanently so it is highly recommended to take a backup of your Istio configuration before deleting Istio in your cluster.``` should proceed ```If you’re migrating from a version of Istio installed using istioctl or Operator to Helm, you need to delete your current installation and re-install Istio using Helm as described above.```. The way it reads now - you have to delete your installation - including your CRDs (which would delete your configuration). What you really have to do instead is delete your running deployments, which will cause a short outage of your control plane and ingress/egress gateways.
1. thanks - CRDs are important to leak - so there is no data loss. I think if we want to offer a point of no return in our documentation, I am ok with that, but it should be in a central location - not spread around different installation paths.
1. Ostromart has developed a pretty solid operational guide for ingress gateway upgrades - would be nice to helmetize this. Perhaps as a future piece of work.
1. After testing canary - you deploy a new revision using your canary tag, and then roll your applications to that same tag. Then delete canary. @costinm or @howardjohn can provide more insight into Google's workflow here, but typically this involves a 1 week cooldown period during an upgrade before a full migration happens.
1. If you want to document a point of no return - I'd recommend one specific document for it - "Completely delete all state for Isito" or the like - where every other document links to it. I leave it up to @frankbu how to best organize this, but I think having this across several pages is dangerous.

Most of these are simply suggestions, not requirements. The only requirement in here is taking more care with CRD deletion. Otherwise, feel free to document the improvement as you like.

Cheers
-steve
