### ISSUE TITLE
PILOT_ENABLE_FLOW_CONTROL may breaks XDS ordering

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#8383]
I think this will not work as implemented today.

Concern is:
1. Envoy has clusters {a, b}
2. We push services {a, b, c}
 * CDS is blocked, put it in queue
  * EDS no blocked, send it {a, b, c}
  * Envoy doesn't know cluster c, it drops the EDS

Once we do send the CDS, envoy may just request the EDS again and we will respond - not entirely sure. We need to test this case.

Note: this feature is disabled by default

cc @ramaraochavali @sdake

**Comment by howardjohn** [comment]
cc @sdake this will prevent us from enabling this feature

**Comment by sdake** [comment]
@howardjohn thanks for the report. I will follow this issue and perhaps take a look in the new year.

Cheers,
-steve

**Comment by howardjohn** [comment]
this is removed
