### ISSUE TITLE
Istio architecture diagram stale

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#8388]
docs/ops/deployment/architecture/index.md

It contains references to "pilot citadel galley". These are not explained anywhere. It should probably say "service discovery, certificate authority" or just nothing

**Comment by howardjohn** [comment]
Also it shows istiod sending "discovery" to the proxies which does not make sense to me

**Comment by bianpengyuan** [comment]
@ericvn @frankbu Any idea whether we have the original drawing so that we can edit and update? I am not sure if there is a way to update the svg directly with the source.

**Comment by frankbu** [comment]
I believe Rigs drew this diagram using using some sort of svg editor, so the svg file is the original source.

I don't know what tool he used. Maybe @nmittler knows?

**Comment by nmittler** [comment]
Don't recall the tool he used. I've just used google drawings for the multicluster docs and it worked well enough: https://drive.google.com/corp/drive/folders/1GlTumwftSHqJVEijNUnA5AjRyxS9EGmi
