### ISSUE TITLE
Document autoMTLS behavior specific to headless services

### ISSUE THREAD

**Issue by emike922** [istio/istio.io#8393]
After going through istio/istio#24082 my understanding is that Istio will by default use tls mode ISTIO_MUTUAL towards headless services, and if someone wants to contact a plaintext service that is headless they have to create a PA or DR to disable TLS origination for that host.
Is that understanding correct?

Could you please add some official documentation regarding this behavior for headless services?

**Comment by Rayzhangtian** [comment]
duplicate to this one:  https://github.com/istio/istio.io/issues/8300

**Comment by howardjohn** [comment]
https://github.com/istio/istio.io/issues/8300
