### ISSUE TITLE
Deployment Document: DNS with multiple clusters section needs rework for 1.8

### ISSUE THREAD

**Issue by sdake** [istio/istio.io#8460]
link: https://preliminary.istio.io/latest/docs/ops/deployment/deployment-models/

This could be more verbose:
```
In Kubernetes, the DNS server residing within the cluster typically handles this DNS lookup. Kubernetes Service configures the DNS server.
```

This section reads as if **Istio and Istio alone** decides how discovery is done in the cluster. There are two aspects - Istio discovers endpoints, K8s's coredns provides discovery (via the `Service` object) to the end-user application

This is too complicated for non-Istio experts to understand and would benefit from more explanation:
```
This two-tiered naming system becomes more complicated when you have multiple clusters. Istio is inherently multicluster-aware, but Kubernetes is not (today). Because of this, the client cluster must have a DNS entry for the service in order for the DNS lookup to succeed, and a request to be successfully sent. This is true even if there are no instances of that service’s Pods running in the client cluster.
```

This entire section is dated. In 1.8 the sidecars capture DNS (IIRC).
```
This can also be achieved with Istio ServiceEntry, rather than Kubernetes Service. ServiceEntry does not configure DNS, however. This means that DNS will have to be configured either manually or with automated tooling, such as the Istio CoreDNS Plugin.
```

And the below:
```
There are a few efforts in progress that will help simplify the DNS story:

Istio will soon support DNS interception for all workloads with a sidecar proxy. This will allow Istio to perform DNS lookup on behalf of the application.
```

I am fairly certain this "few efforts in progress" is already implemented. I suggest integrating this into the main DNS section.

**Comment by sdake** [comment]
@nmittler @stevenctl @irisdingbj @linsun @howardjohn 

Hi gang. Thanks for the wide distribution of this issue. I am fairly certain that sidecar capture for DNS is implemented in 1.8. What I am not sure about is if it is enabled by default. Can someone take on handling these comments?

BTW, whoever wrote this original deployment models document (was that you @nmittler?) - did a kick-ass job. This is one of the best istio.io docs I have read. I am surprised this is not in the `Concepts` section. It probably belongs there.

I have left some nitpick comments beyond just addressing the DNS capture. Feel free to ignore or address as you like.

@frankbu thoughts on moving this page to concepts?

**Comment by linsun** [comment]
@sdake  ISTIO_META_DNS_CAPTURE is *not* enabled by default in 1.8.

**Comment by frankbu** [comment]
I don't think anything needs to change immediately, but post 1.8 we should try to incorporate or reference material from this blog, which does a really good job of explaining the DNS stuff, IMO. https://preliminary.istio.io/latest/blog/2020/dns-proxy/

**Comment by nmittler** [comment]
@sdake the features are implemented, however they are not enabled by default IIRC and I'm not sure of the feature status currently.

FYI @costinm
