### ISSUE TITLE
Issue with docs/reference/config/security/jwt/index.html

### ISSUE THREAD

**Issue by simonxmh** [istio/istio.io#8588]
JWTRule
JSON Web Token (JWT) token format for authentication as defined by RFC 7519. See OAuth 2.0 and OIDC 1.0 for how this is used in the whole authentication flow.

Examples:

Spec for a JWT that is issued by https://example.com, with the audience claims must be either bookstore_android.apps.example.com or bookstore_web.apps.example.com. The token should be presented at the Authorization header (default). The Json web key set (JWKS) will be discovered _followwing_ OpenID Connect protocol.

Typo with the page

**Comment by howardjohn** [comment]
fixed
