### ISSUE TITLE
Istio Injected Sidecar cannot connect to K8s API Server (refused)

### ISSUE THREAD

**Issue by schroedt** [istio/istio.io#8655]
Dear Folks,

I am trying to install Gitlab having istio enabled. I noticed a pod, trying to connecto to K8s API Server, but fails with connection refused. This blocks all additional instsallation steps.

`The connection to the server 10.96.0.1:443 was refused - did you specify the right host or port?`

When disabling sidecar injection for the namespace, pod starts probably and installation is successfull.

Is there any information I can provide?

**Comment by howardjohn** [comment]
Hey, sorry this went unnoticed as this is the documentation bug tracker. If you are still seeing issues reach out in istio.io/community
