### ISSUE TITLE
Broken link to prometheus/configmap.yaml in docs/ops/integrations/prometheus/index.md

### ISSUE THREAD

**Issue by rvennam** [istio/istio.io#8668]
https://istio.io/latest/docs/ops/integrations/prometheus/#option-2-customized-scraping-configurations:

This built-in deployment of Prometheus is intended for new users to help them quickly getting started. However, it does not offer advanced customization, like persistence or authentication and as such should not be considered production ready. To use an existing Prometheus instance, add the scraping configurations in [prometheus/configmap.yaml](https://raw.githubusercontent.com/istio/istio/master/manifests/charts/istio-telemetry/prometheus/templates/configmap.yaml) to your configuration.

Broken link: prometheus/configmap.yaml

**Comment by howardjohn** [comment]
This is removed
