### ISSUE TITLE
Upgrade with Helm docs belong in the Upgrade doc section

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio.io#8671]
Slightly counter-intuitive that the [documentation to upgrade a Helm-based install](https://istio.io/latest/docs/setup/install/helm/#upgrading-using-helm) is under the `Installation` doc section rather than the `Upgrade` doc section with the rest of our upgrade docs. cc @jacob-delgado since you've been looking into Helm-based upgrades

**Comment by jacob-delgado** [comment]
Fixed
