### ISSUE TITLE
Issue with docs/reference/config/networking/workload-group/index.html

### ISSUE THREAD

**Issue by carolynhu** [istio/istio.io#8687]
<img width="838" alt="Screen Shot 2020-12-17 at 11 02 26 AM" src="https://user-images.githubusercontent.com/29208297/102531560-5a861080-4057-11eb-8f21-2c279115964d.png">

This v1alpha3 is not showing there properly/when loading. User should click it for the content to show up.

**Comment by howardjohn** [comment]
tabs are removed now
