### ISSUE TITLE
Upgrade notes does not contains some breaking changes content/en/news/releases/1.6.x/announcing-1.6/change-notes/index.md

### ISSUE THREAD

**Issue by fams** [istio/istio.io#8700]
The upgrade to istio 1.6 brings two issues not liste in change notes:
1) envoy 1.14 changes the perTryTimeout behaviour.
In istio 1.5, the VirtualServer parameter spec.http[].retries.perTryTimeout was ignored if global timeout was not configured. In istio 1.6, using envoy 1.14, this parameter is honored even without global timeout unconfigured, leading to problems if it was mistakely configured.

2) The EnvoyFilter tag WorkLoadLabels was deprecated in istio 1.3 but it was silently removed in 1.6 possibly making some filters being applied or not applied in correct pods.

**Comment by ramaraochavali** [comment]
> configured. In istio 1.6, using envoy 1.14, this parameter is honored even without global timeout unconfigured, leading to problems if it was mistakely configured.

I think that was more of a bug fix in Envoy. So if we specify per try timeout, it needs to be honoured. I agree it breaks if it was mistakenly configured though.

**Comment by fams** [comment]
It is a bug fix in envoy. My point is to list it in istio changelog
