### ISSUE TITLE
Bad link on docs/reference/config/istio.operator.v1alpha1/index.html

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#8719]
In the section currently at https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#k8s-io-apimachinery-pkg-apis-meta-v1-LabelSelector, the link for the text "LabelSelectorRequirement[]" (`<a href=#k8s-io-apimachinery-pkg-apis-meta-v1-LabelSelectorRequirement>`) doesn't resolve to anything.

**Comment by howardjohn** [comment]
this is fixed now, https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#k8s-io-apimachinery-pkg-apis-meta-v1-LabelSelectorRequirement is a valid link
