### ISSUE TITLE
Automate Distributed Tracing Configurability Task

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio.io#8734]
We need to automate the [Distributed Tracing Configurability Task](https://preliminary.istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/).

Assigning to @nrjpoddar for triage.

**Comment by nrjpoddar** [comment]
@jacob-delgado have you looked at automating this doc/task?

**Comment by jacob-delgado** [comment]
No. It looks like there is support for tracing already done in https://github.com/istio/istio/tree/master/tests/integration/telemetry/tracing so we could probably amend a test to add this.
