### ISSUE TITLE
Document VM troubleshooting

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#8749]
We should have a troubleshooting guide for VMs

Recommended:
* Describe using istioctl. `curl -s localhost:15000/config_dump | istioctl proxy-config clusters --file -`
* Describe fetching logs from /var/log/istio/istio.log, /var/log/istio/istio.err.log
* Maybe how to view status, restart, although its just a systemd thing not Istio specific.
* How to check iptables rules? `iptables-save` should be sufficient w/ root

**Comment by stevenctl** [comment]
Done? https://istio.io/latest/docs/ops/diagnostic-tools/virtual-machines/

**Comment by howardjohn** [comment]
Yep, thanks
