### ISSUE TITLE
Issue with docs/tasks/observability/logs/collecting-logs/index.md

### ISSUE THREAD

**Issue by lascape** [istio/istio.io#8794]
version 1.8
`kubectl apply -f samples/bookinfo/telemetry/log-entry.yaml`  **404: Not Found**

I checked this URL **https://raw.githubusercontent.com/istio/istio/release-1.8/samples/bookinfo/telemetry/log-entry.yaml** does not exist

but i can use https://raw.githubusercontent.com/istio/istio/release-**1.7**/samples/bookinfo/telemetry/log-entry.yaml

**Comment by wzshiming** [comment]
`samples/bookinfo/telemetry` was removed in 1.8

> Mixer is deprecated. The functionality provided by Mixer is being moved into the Envoy proxies. Use of Mixer with Istio will only be supported through the 1.7 release of Istio.
https://istio.io/v1.7/docs/tasks/observability/mixer/

**Comment by go-creed** [comment]
Ok ，thanks for your answer

**Comment by howardjohn** [comment]
doc is removed
