### ISSUE TITLE
Debugging Envoy and Istiod: pod not found for envoy version

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#8843]
Ref: https://preliminary.istio.io/latest/docs/ops/diagnostic-tools/proxy-cmd#what-envoy-version-is-istio-using

As prometheus is not installed by default, exec fail with following error.

```
$ kubectl exec -it prometheus-68b46fc8bb-dc965 -c istio-proxy -n istio-system pilot-agent request GET server_info
Error from server (NotFound): pods "prometheus-68b46fc8bb-dc965" not found
```

**Comment by ericvn** [comment]
LGTM. At first I would have mentioned that BookInfo would be installed, but do note that there is a note at the top of the page mentioning that BookInfo is installed for the page.

**Comment by shamsher31** [comment]
@ericvn Right, that's why I choose to use bookinfo pods because the entire example for `proxy-status` and `proxy-config` is based on bookinfo and the user must have already installed bookinfo samples.
