### ISSUE TITLE
Issue with about/supported-releases/index.md

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#8951]
https://istio.io/latest/about/supported-releases/#releases-without-known-common-vulnerabilities-and-exposures-cves

A few issues:
* 1.9 is missing
* It says only 1.8.1 has no vulns. Maybe it should be 1.8.1+?
* nit: avoid "LTS"
cc @jacob-delgado @nrjpoddar

**Comment by ericvn** [comment]
May need to add a step in the release process to make sure the page gets updated

**Comment by ericvn** [comment]
This has been. fixed. Please reopen if you feel more is required.
