### ISSUE TITLE
Enable virtual service routing per pod

### ISSUE THREAD

**Issue by olliezhu** [istio/istio.io#8986]
This is a feature/doc request for enabling routing rules (e.g. via `VirtualService`s and `DestinationRule`s) per pod. For example, if I wanted to configure which external services each pod could talk to, I would like to create a `VirtualService`, scoped for that pod, to redirect requests for that external service through an egress gateway, and block all traffic leaving the mesh that is not passing through the egress gateway via a Kubernetes `NetworkPolicy`.

The process for implementing this with `VirtualService`s scoped to the entire mesh for [egress gateways](https://istio.io/v1.6/docs/tasks/traffic-management/egress/egress-gateway/) (I'm using Istio 1.6), but there doesn't seem to be a way to apply these routing rules (or a destination rule) for just a single sidecar.

EDIT: Can this be done by specifying `sourceLabels` and adding a label to the workload or service that i want to apply this routing rule to?

**Comment by pramodrj07** [comment]
HI @olliezhu,
This looks interesting. What is the use case if we enable this?

**Comment by olliezhu** [comment]
@pramodrj07 The use case for this would be having separate routing rules apply to separate workloads. Turns out this is very easy to do by specifying `sourceLabels` in your `VirtualService`.
