### ISSUE TITLE
Unexplained COUNTER, DISTRIBUTION on docs/reference/config/metrics/index.md

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#9027]
The page refers to `COUNTER` and `DISTRIBUTION` without saying what those are or linking that text to some page that does say what those are.

**Comment by ericvn** [comment]
This page has: istio/wg-user-experience-maintainers but maybe it should be another group.

**Comment by esnible** [comment]
I feel this page is about telemetry and should be owned by @istio/wg-policies-and-telemetry-maintainers .  In addition to explaining the meaning of `COUNTER` and `DISTRIBUTION` please take over the page by changing `owner: istio/wg-user-experience-maintainers` to `owner: istio/wg-policies-and-telemetry-maintainers`

**Comment by lei-tang** [comment]
This issue has been fixed by https://github.com/istio/istio.io/pull/12158.
