### ISSUE TITLE
"Label" not clear on docs/reference/config/metrics/index.md

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#9028]
The "Labels" section doesn't say what kind of labels it's talking about.

Additionally, it has no sentence introducing the bulleted list of label names (as the Metrics section introduces its list with "For HTTP, HTTP/2, and GRPC traffic, Istio generates the following metrics:").

**Comment by ericvn** [comment]
This page has: `istio/wg-user-experience-maintainers` but maybe it should be another group.
