### ISSUE TITLE
"plaintext" instead of "cleartext"  with docs/ops/integrations/prometheus/index.md

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#9029]
The page says:
"The control plane, gateway, and Envoy sidecar metrics will all be scraped over plaintext."

Shouldn't that "plaintext" be "cleartext"?

"Plain text" is text without formatting (e.g., plain text vs. HTML).

"Cleartext" is unencrypted data (as opposed to "ciphertext").

**Comment by NisheekaNynan1** [comment]
Assigning myself to this issue as I'd like to work on it! :)
