### ISSUE TITLE
Issue with docs/tasks/traffic-management/circuit-breaking/index.md

### ISSUE THREAD

**Issue by jevic** [istio/istio.io#9037]
**1.9版本文档这个命令是错误的**
`kubectl exec -it $FORTIO_POD  -c fortio /usr/bin/fortio -- load -curl  http://httpbin:8000/get`

OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "load": executable file not found in $PATH: unknown
command terminated with exit code 126

**英文版本的这个是正确的**:
`# kubectl exec "$FORTIO_POD" -c fortio -- /usr/bin/fortio curl -quiet http://httpbin:8000/get`
`
HTTP/1.1 200 OK
server: envoy
date: Tue, 23 Feb 2021 10:22:50 GMT
content-type: application/json
content-length: 622
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 7

{
  "args": {},
  "headers": {
    "Content-Length": "0",
    "Host": "httpbin:8000",
    "User-Agent": "fortio.org/fortio-1.11.3",
    "X-B3-Parentspanid": "34f66e94069f84da",
    "X-B3-Sampled": "1",
    "X-B3-Spanid": "ffb223d1fd337b85",
    "X-B3-Traceid": "650295a3fd99829134f66e94069f84da",
    "X-Envoy-Attempt-Count": "1",
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/default/sa/httpbin;Hash=85c011f9692bdb130b3d04579973e1cc5b348b21435694a19efbc70786a0dbca;Subject=\"\";URI=spiffe://cluster.local/ns/default/sa/default"
  },
  "origin": "127.0.0.1",
  "url": "http://httpbin:8000/get"
}`

**Comment by ericvn** [comment]
Looks like the page needs the command updates from the English pages.

**Comment by ericvn** [comment]
Actually, I see some that might not have been updated in the English as well.

**Comment by zirain** [comment]
out of date
