### ISSUE TITLE
New round of Chinese translation of Istio documentation has begun

### ISSUE THREAD

**Issue by rootsongjc** [istio/istio.io#9128]
The first round was in 2018, based on Istio 0.8, and [the second round](https://github.com/istio/istio.io/issues/5250) was in 2020, based on Istio 1.5. As of now(Mar 6, 2021), Istio has released version 1.9, and the Istio Chinese documentation has been neglected for up to a year. Now the [Cloud Native Community](https://cloudnative.to) Istio SIG has decided to restart the maintenance of the Chinese documentation.

**How to get involved?**

- Registration and task claim form：[Google Spreadsheet](https://docs.google.com/spreadsheets/d/1ihJTww4q1FArD50TerRLyi210LD64gHTIEQM43dBwb0/edit?usp=sharing)
- Join us: [Join the Cloud Native Community Istio SIG](https://wj.qq.com/s2/7309386/b0f5/)
- See more: <https://i.cloudnative.to/istio/event/istio-doc-translation>

**Owners**

- [宋净超（@rootsongjc）](https://github.com/rootsongjc)
- [刘齐均（@kebe7jun）](https://github.com/kebe7jun)
- [殷龙飞（@loverto）](https://github.com/loverto)
- [邱世达（@SataQiu）](https://github.com/SataQiu)

/cc @sdake @kebe7jun is the initiator and one of the leaders of this round, has submitted several PRs and participated in the preparation of the event, I suggest to set him as Istio Chinese Doc Maintainer so that it will also be convenient for us to merge the translated PRs.

**Comment by zirain** [comment]
out of date
