### ISSUE TITLE
Why there not support italic in title?

### ISSUE THREAD

**Issue by elkan1788** [istio/istio.io#9241]
When I translate the docs content to Chinese there was failed happened when lint test. After focus the error log information, that found because there had italic flag in title. But the origin file content which version is English were not this issue.  Is there some special action or flag need configure?

You can following the log information see below link:

[lint_istio.io_Failed](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/9194/lint_istio.io/1370258690279477248)

**Comment by craigbox** [comment]
Run "make lint" locally and it will highlight the words that aren't in the dictionary and are causing lint to fail.

**Comment by elkan1788** [comment]
@craigbox  So your means there need add the word which include in  italic identify to `.spelling` dict file?  I not sure this action can be fix it, because there no found any string which from the English version content in `.spelling` file.

**Comment by craigbox** [comment]
I've tested this locally for you:

```
    index.md
       40 | ## 使用 _斜体_ 强调新术语{#use-italics-to-emph 
       40 | ## 使用 _斜体_ 强调新术语{#use-italics-to-emphasi 
       41 | ## _foo_ _bar_ test _斜体_ 
       41 | ## _foo_ _bar_ test _斜体_ 
```
_斜体_ fails on both lines. So you're right, it doesn't work for non-English.
That said, I can't see any evidence that mdspell works for Chinese at all!

Maybe the right thing to do is disable spell checking for ZH pages?  @davidhauck may have some insight

**Comment by ericvn** [comment]
We do have the ability to only scan certain languages and on Chinese pages we should only be checking English:

```
        # only check English words in Chinese docs
        check_content "content/$lang" --en-us
...
    if ! find . -type f -name '*.md' -print0 | xargs -0 -r mdspell "${LANG}" --ignore-acronyms --ignore-numbers --no-suggestions --report; then
```

**Comment by davidhauck** [comment]
The issue here is that it thinks the underscores are misspelled. Best option might be to add `_` as an entry in .spelling

**Comment by craigbox** [comment]
Good idea.  Can you try that @elkan1788? 
You'd think that mdlint might strip markdown characters... 🤷‍♀️
