### ISSUE TITLE
Unable to access INGRESS_HOST for Bookstore demo on minikube ip but localhost works

### ISSUE THREAD

**Issue by jonassteinberg1** [istio/istio.io#9340]
**Bug description**

[This](https://istio.io/latest/docs/setup/getting-started/) says to set INGRESS_HOST=$(minikube ip), but this does not work.  When I set it to localhost it works just fine.

logs from all istio pods seem normal, though I'm certainly no expert; whatever the case the word 'error' does not appear in any

the productpage resolves just fine if I hit the app via localhost by when I try by `minikube ip` as the getting started instructions suggest it doesn't work.

I am running `minikube tunnel` in a separate terminal _window_ without error like the getting started docs suggest

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

A network connection is made to $GATEWAY_URL/productpage

**Steps to reproduce the bug**
All I did was carry out the Getting Started instructions several times.  Same issue every time.

**Version**
I am not running a proxy.  I am not on a VPN.  I have functional internet access.
minikube version: v1.17.1
commit: 043bdca07e54ab6e4fc0457e3064048f34133d7e
minkube k8s v1.20.1
MacOS 10.15.7
minikube settings: --memory 8196 --cpus 4

client version: 1.9.1
control plane version: 1.9.1
data plane version: 1.9.1 (8 proxies)

**How was Istio installed?**
copy/paste from instructions for macos
binary is at /usr/local/bin and is active in my path

**Environment where the bug was observed (cloud vendor, OS, etc)**
macos 10.15.7

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

** fyi github doesn't support uploading tarballs.  so I submitted a zip of the tar lol.
[bug-report.zip](https://github.com/istio/istio/files/6174797/bug-report.zip)

**Comment by wangmeng** [comment]
I am able to reproduce the same behavior with minikube on macOS.  

Here is some understanding for the problem:

1. Before running `minikube tunnel` cmd in a new terminal window, and run the cmd `kubectl get service -n istio-system`, you will see the ingress gateway external ip for the minikube env would be shown as `<pending>`. Here is a sample:

```
> kubectl get service -n istio-system
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
istio-egressgateway    ClusterIP      10.103.46.157    <none>        80/TCP,443/TCP,15443/TCP                                                     94m
istio-ingressgateway   LoadBalancer   10.111.21.138    <pending>     15021:32250/TCP,80:32528/TCP,443:31190/TCP,31400:31357/TCP,15443:32098/TCP   94m
istiod                 ClusterIP      10.101.199.154   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                        95m
```

2. Once start `minikube tunnel` cmd in a new terminal window, and run the cmd again, you will see the  ingress gateway external ip updated to 127.0.0.1.
```
> kubectl get service -n istio-system
NAME                   TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
istio-egressgateway    ClusterIP      10.103.46.157    <none>        80/TCP,443/TCP,15443/TCP                                                     99m
istio-ingressgateway   LoadBalancer   10.111.21.138    127.0.0.1     15021:32250/TCP,80:32528/TCP,443:31190/TCP,31400:31357/TCP,15443:32098/TCP   99m
istiod                 ClusterIP      10.101.199.154   <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP
```

By checking the bug-report.zip you shared, your env's behavior is the same, since  in file`/bug-report/cluster/k8s-resources`, the service listed as:
```
- apiVersion: v1
  kind: Service
  metadata:
  ......
    name: istio-ingressgateway
    namespace: istio-system
  spec:
  ......
    selector:
      app: istio-ingressgateway
      istio: ingressgateway
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 127.0.0.1       # ----> the ip defined here with running minikube tunnel
 ```

And the `minikube tunnel` should say:
```
>  minikube tunnel
❗  The service istio-ingressgateway requires privileged ports to be exposed: [80 443]
🔑  sudo permission will be asked for it.
🏃  Starting tunnel for service istio-ingressgateway.
```

What's more, If you check your `minikube ip` result, it would be actually the minikube env's node ip, here is a sample:
```
> minikube ip
192.168.49.2
> kubectl get node -o wide
NAME       STATUS   ROLES                  AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
minikube   Ready    control-plane,master   125m   v1.20.2   192.168.49.2   <none>        Ubuntu 20.04.1 LTS   4.19.121-linuxkit   docker://20.10.3
```

In such case, replace the line: 
from:
`export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT`
to:
`export GATEWAY_URL=127.0.0.1`

And then the default 80 port could be used directly, so the traffic could be through the istio-ingressgateway as a loadbalancer service, instead of the node ip and port. It makes sense to run in this way.

Then the page could be accessible via: `http://127.0.0.1/productpage`

Hope these could be helpful.

**Comment by wangmeng** [comment]
With some more investigating, this minikube repo issue should be related: 
https://github.com/kubernetes/minikube/issues/10085

**Comment by ericvn** [comment]
Running through the https://preliminary.istio.io/latest/docs/setup/getting-started/ sample as part of community testing. It seems that there is a small issue with the piece about getting the INGRESS_HOST. If one runs `minikube tunnel`, and then running `$ kubectl get svc istio-ingressgateway -n istio-system` yields an external-ip which pushes one down a different path (using the external load balancer to get ingress_host and ingress_port) which works, while the old minikube path doesn't.

The getting started and the page to get the ingress host/port may need to be changed for minikube.
