### ISSUE TITLE
docs test: update to Kubernetes 1.20

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#9388]
Currently we are using k8s 1.18. We should probably be testing on the latest version, like we do in istio/istio

**Comment by ericvn** [comment]
John,

I think you are saying you want to update the NODE_IMAGE, although I'm thinking we want to use something better than istio/istio:
```
# We are currently running from head of release-1.20, until a release containing the fix in b86925b0fbd
# is built.
NODE_IMAGE="gcr.io/istio-testing/kind-node:b86925b0fbd"
```

**Comment by howardjohn** [comment]
we should update istio/istio as well to use v1.20.2

**Comment by ericvn** [comment]
OK.
