### ISSUE TITLE
Our alias to handle moved page no longer works?

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#9409]
When I search Kubernetes service API in istio.io, this came first:  https://istio.io/latest/docs/tasks/traffic-management/ingress/service-apis/

but this page is getting 404.

Checked in our code, we do have the [alias](https://github.com/istio/istio.io/blob/593e85fb663511db852ce839507c1da764aceef6/content/en/docs/tasks/traffic-management/ingress/gateway-api/index.md) listed properly.  Is our alias no longer working?

@davidhauck can you look at this?

**Comment by linsun** [comment]
cc @craigbox

**Comment by craigbox** [comment]
The alias is /docs/foo but the page is /latest/doc/foo.

Adding that alias will fix it.

David and I are going to look at other solutions for /latest with Netlify's
new edge handlers

**Comment by linsun** [comment]
Ah I missed that minor difference :) I'll submit a small PR
