### ISSUE TITLE
Layout errors on new site

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9436]
https://preliminary.istio.io/latest/about/service-mesh:

- The breadcrumb bar should be aligned left under the Istio logo.
- The headings should have the same margins as the first body text
- There should be a margin on either side roughly equivalent to the width of the Istio logo (which you can see most clearly on the three "Concepts" sections
- The logos for each Concept should be larger in their boxes.

## Breadcrumbs and subheaders

![image](https://user-images.githubusercontent.com/132510/113315584-5a0f3e00-9305-11eb-86b6-cfb675f8e00e.png)

vs

![image](https://user-images.githubusercontent.com/132510/113315544-4cf24f00-9305-11eb-953d-26c6790d48e5.png)

(Please also check [solutions pages](https://preliminary.istio.io/latest/about/solutions/enabling-defense-in-depth-for-enterprise-applications/) as the breadcrumb header is in the wrong place there too.)

## Logos
<img src="https://user-images.githubusercontent.com/132510/113315961-c38f4c80-9305-11eb-8913-fa6bd6c91644.png" width="290"> vs <img src="https://user-images.githubusercontent.com/132510/113315975-c8540080-9305-11eb-8c06-6f2b6a50d1b8.png" width="300">

## Margin

![image](https://user-images.githubusercontent.com/132510/113316742-97c09680-9306-11eb-9748-a8600114a1a5.png)

vs

![image](https://user-images.githubusercontent.com/132510/113316788-a313c200-9306-11eb-982f-7827be30a64c.png)

**Comment by wbartosz** [comment]
@craigbox I understand the difference in the breadcrumbs section but didn't you want to extend the width of the containers to 1440px? Currently the Concepts section is 1440px wide max.

**Comment by wbartosz** [comment]
Updated in
https://github.com/istio/istio.io/pull/9521
