### ISSUE TITLE
Update the new FAQ template to use the old FAQ questions

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9437]
Update the [new template](https://preliminary.istio.io/latest/about/faq), to use [the layout that generates the page from the MD files by weight](https://github.com/istio/istio.io/blob/master/layouts/_default/faq-landing.html), and move the FAQ files from the old location to the new.

**Comment by wbartosz** [comment]
Updated in
https://github.com/istio/istio.io/pull/9485
