### ISSUE TITLE
Migrate old user logos to new Case Studies page

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9464]
The "also used by" section of https://preliminary.istio.io/latest/about/case-studies should contain all the logos currently at https://istio.io/latest/about/community/customers/.  Please move the existing content into the right place and ensure that the instructions on how to add your logo are as obvious as they were in the old version.

`case-studies/list.html` shows:
```
    {{ partial "distributors" (dict "distributors" .Site.Data.companies.distributors "first_items" 8) }}
```

This shouldn't be the _distributors_ - the cloud providers - this is a list of _users_.  Please also ensure they are all listed, not just the top 8.

**Comment by wbartosz** [comment]
Updated in
https://github.com/istio/istio.io/pull/9509
