### ISSUE TITLE
Can't link directly to tabs on the Ecosystem page

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9466]
For https://preliminary.istio.io/latest/about/ecosystem/,  I expect to be able to share a URL which links directly to a certain tab, i.e.

https://preliminary.istio.io/latest/about/ecosystem/#providers
https://preliminary.istio.io/latest/about/ecosystem/#services
https://preliminary.istio.io/latest/about/ecosystem/#integrations

have the page open to that tab.

**Comment by wbartosz** [comment]
Updated in
https://github.com/istio/istio.io/pull/9488

**Comment by ericvn** [comment]
This doesn't work for me on the netlify build for this PR.

https://deploy-preview-9488--preliminary-istio.netlify.app/latest/about/ecosystem/#integrations does seem to work. I'm not sure about #providers as any garbage gets me to that tab. #pro-services does not work.

**Comment by wbartosz** [comment]
> #pro-services does not work.

That’s right, Craig has requested to access pro services tab from #services instead.

If a hash does not match any of the options it defaults to the first tab anyway.

You may truly test the pro services and integrations but providers is a bit tricky.

**Comment by ericvn** [comment]
confirmed that `#services` does work.
