### ISSUE TITLE
Edit this page on GitHub button

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9468]
The "Edit this page on GitHub" menu item was removed in the new design.  There's interest from TOC to have that functionality restored somewhere - perhaps as a link in the footer?

/cc @linsun

**Comment by aijamalnk** [comment]
In the design, we had two versions of the "edit this page" button: 1) Floating icon 2) Button in the footer of the site
![image](https://user-images.githubusercontent.com/14306210/115462243-44dc4f80-a1df-11eb-9a7c-d55cfaaf331b.png)
The decision is to go with version 2 and the behavior should be the same as in the current website.

/cc @craigbox @linsun

**Comment by linsun** [comment]
I think I like option 2 better. :) seems more integrated with the page.

**Comment by linsun** [comment]
cc @brian-avery who also wanted this function iirc
