### ISSUE TITLE
SCTP Protocol is not supported in istio config

### ISSUE THREAD

**Issue by dnelaturi** [istio/istio.io#9513]
Hi, 

We have telecom products and most of them are based on tcp/ip for internal communication however the front-ending application/ communication with external world uses sctp based connections. 
And istio doesn't support sctp. However kuberentes does support sctp at pod and service level.

I would like to understand if there a plan to add sctp support in Istio.

Thank You
Daniel Raj.

**Comment by howardjohn** [comment]
Dupe of https://github.com/istio/istio/issues/32118. thanks
