### ISSUE TITLE
New design: header bar is not responsive, takes up almost the full screen in some cases

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#9515]
The new header on the website is problematic I think. It is large in general, and not responsive. Most sites with such a large header either are not sticky, shrink when the screen is smaller, or shrink when scrolling. The new header does none of this, leading to a poor UX

![2021-12-04_10-15-34](https://user-images.githubusercontent.com/623453/114434581-08be4480-9b78-11eb-8623-e3804a2da18a.png)

**Comment by craigbox** [comment]
Closing in favour of #9569.
