### ISSUE TITLE
Supported Kubernetes versions for 1.10.

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#9516]
Currently the docs have from args.yml:
```
# The list of supported versions described by the docs
supported_kubernetes_versions: ["1.17", "1.18", "1.19", "1.20"]
```
which shows on the pages as: 
```
Istio 1.10 has been tested with these Kubernetes releases: 1.17, 1.18, 1.19, 1.20.
```
Testing is currently done on release 1.16 to 1.21 (from prow/config/jobs) (1.20 during pre-submit, the others in post-submit).

We also have: https://istio.io/latest/about/supported-releases/

I'm not sure what the statement should be for 1.10.

TOC review for 1.9 is in the notes on 1/8/21.

**Comment by ericvn** [comment]
@istio/technical-oversight-committee

**Comment by duderino** [comment]
For Istio 1.10, the min supported k8s version should be 1.18 and the max supported 1.21.   The tested version range would be 1.16 to 1.21.  @Monkeyanator  will port the 1.21 tests+changes to the release-1.10 branch
