### ISSUE TITLE
Lint fails with `supported-releases` links and probably others when cherry-picking PRs back to 1.9

### ISSUE THREAD

**Issue by ericvn** [istio/istio.io#9518]
See https://github.com/istio/istio.io/pull/9517 which is a cherry-pick of https://github.com/istio/istio.io/pull/9503 from master to release-1.9. In master, the doc has a link `/docs/releases/supported-releases#supported-releases/` which was redone with the `Polidea` changes. Trying to cherry-pick that PR back to release-1.9 fails lint since that link doesn't exist there.

I did try creating an alias on the 1.9 page page, but I'm now thinking that aliases don't work during the lint step. If that should work, we may need to create aliases in the 21 pages that were moved in https://github.com/istio/istio.io/pull/9324/files. If aliases don't work, then we may need something else to help with cherry-pick PRs instead of having to manually update the doc location each time.

**Comment by craigbox** [comment]
The pages have aliases, but you're right, the linter isn't ever going to be happy about this.

Is it OK to just do these manually for the few weeks left until 1.10 comes out?

**Comment by ericvn** [comment]
Closing as this is stale and no longer an issue.
