### ISSUE TITLE
Links on zh homepage go to English content

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9547]
https://preliminary.istio.io/latest/zh/

Click any of the menus - takes you to an English page, not a Chinese one.
Only some pages have translations - the new content does not, yet - but https://preliminary.istio.io/latest/zh/blog/ and https://preliminary.istio.io/latest/zh/docs should be linked?

Perhaps @rootsongjc can help us figure out how best to get this content (given the English content isn't final yet).

**Comment by rootsongjc** [comment]
This issue has been solved.
