### ISSUE TITLE
Issue with faq/security/index.md

### ISSUE THREAD

**Issue by brantk-hpe** [istio/istio.io#9560]
I was trying to figure out what the lifetime is for mesh host certificates, and I found this page and the section "HOW TO CONFIGURE THE LIFETIME FOR ISTIO CERTIFICATES?". This says the default is 90 days.

I'm pretty sure I'm using the default (the instructions in this section didn't work for me I don't have citadel (does anyone?)).

On my system looks like the lifetime is 1 day. I picked a pod in the mesh and queried the cert:

```
* Server certificate:
*  subject: [NONE]
*  start date: Apr 19 15:56:16 2021 GMT
*  expire date: Apr 20 15:56:16 2021 GMT
*  issuer: O=cluster.local
```

**Comment by shamsher31** [comment]
The [doc is outdated](https://istio.io/latest/faq/security/#cert-lifetime-config) but you can set default lifetime using env. I think the default lifetime is 1 day.
https://github.com/istio/istio/blob/4c2fc50ed9c9c68adf12f514d90876f5a2ce7ade/security/pkg/cmd/constants.go#L37-L41

**Comment by ericvn** [comment]
There is a change coming in with this PR: https://github.com/istio/istio.io/pull/9798

**Comment by ericvn** [comment]
I believe the mentioned PR covers this issue. If not, please reopen the issue.
