### ISSUE TITLE
why can I not choose to inject a particular pod unless istio-injection is turned on via the namespace?

### ISSUE THREAD

**Issue by jbilliau-rcd** [istio/istio.io#9561]
I have a use-case where I have a namespace of 12 applications....I only want to inject the istio sidecar into one of them. It appears I can turn on istio-injection via the namespace, then set `sidecar.istio.io/inject: "false"`  on every deployment except the one I want to keep it on. However, I can't do the opposite; set `istio-injection: disabled` on the namespace, then `sidecar.istio.io/inject: "true"` on the pod annotation. Tried it multiple times, no sidecar. 

This table seems to imply it's not supported: https://istio.io/latest/docs/ops/configuration/mesh/injection-concepts/

In my scenario, I would fit the row of "_namespace selector = no, default policy = disabled, Pod override annotation sidecar.istio.io/inject = true_".

I am using Istio 1.8.5 on EKS 1.19.

**Comment by shamsher31** [comment]
@jbilliau-rcd If you want to inject an Istio sidecar in only one of the pods or deployment without enabling `istio-injection` for the namespace, I think you can use [kube-inject](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#manual-sidecar-injection) on a specific pod or deployment.

**Comment by jbilliau-rcd** [comment]
if that's the only solution, it's a pretty poor one; I don't want to have to run a special command to have to do what, imo, should be natively support, and in fact is for the opposite of the situation im talking about. In this specific case, the application I want to inject is deployed via a helm chart, so I would have to remember to do that as a one-off everytime i uninstall/reinstall the Helm chart or change the deployment.

**Comment by howardjohn** [comment]
This is now possible, see https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy. tl;dr set the label on the pod
