### ISSUE TITLE
Sidecar injection doc: Broken link to OKD info on s2i builds

### ISSUE THREAD

**Issue by birbilis** [istio/istio.io#9566]
Bug description

At
https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/
the link for "OpenShift Source to Image Builds is broken

need to change from
https://docs.okd.io/latest/builds/understanding-image-builds.html#build-strategy-s2i_understanding-image-builds
to
https://docs.okd.io/latest/cicd/builds/understanding-image-builds.html#builds-strategy-s2i-build_understanding-image-builds
note the missing /cicd/ part in the URL (rest seems to be the same at first glance)

[x] Docs

(had originally submitted this by mistake to https://github.com/istio/istio/issues/32316, was pointed here instead)

**Comment by birbilis** [comment]
btw, is that doc gone now? it appears online at the latest docs but can't find it in the repo - see this commit instead that has changed/removed lots of content from that page
https://github.com/istio/istio.io/commit/c38b87f1390a38604d553531d58edabac6901db9

**Comment by ericvn** [comment]
Link pointing to current content: https://preliminary.istio.io/latest/docs/setup/additional-setup/sidecar-injection/

Page: https://github.com/istio/istio.io/blob/master/content/en/docs/setup/additional-setup/sidecar-injection/index.md

**Comment by birbilis** [comment]
btw, just saw that https://github.com/istio/istio.io/commit/2048ea633e045d7069e1f5d9910d769c98ca2e1b had reverted for 1.9 the commit that also removed this text in doc for 1.10, doesn't say why though. 

Is there a chance that commit that changed the doc significantly has some issues? Or was it just reverted for 1.9 cause it was too early to roll out publicly and the changes were supposed to appear at 1.10?

**Comment by ericvn** [comment]
1.9 revert PR https://github.com/istio/istio.io/pull/8959 has text `This was meant for preliminary docs - its not accurate for 1.9`

**Comment by howardjohn** [comment]
these links are removed
