### ISSUE TITLE
Large header takes up too much space in doc windows

### ISSUE THREAD

**Issue by frankbu** [istio/istio.io#9569]
There seems to be too much wasted space when reading docs in the new istio.io layout. The header wastes about 5 or 6 lines of content, and once you've scrolled past the outline, there's a big block of empty space on the left. The actual document of interest ends up too small and squished in the middle.

![image](https://user-images.githubusercontent.com/2752495/115449467-d9977b00-a1e8-11eb-8a72-3e0f090892ed.png)

**Comment by craigbox** [comment]
See also #9515 from @howardjohn 

> The new header on the website is problematic I think. It is large in general, and not responsive. Most sites with such a large header either are not sticky, shrink when the screen is smaller, or shrink when scrolling. The new header does none of this, leading to a poor UX

Flagging this for options.

We can:

(a) not keep the header on the page for docs
(b) shrink the header on docs pages
(c) resize on scroll.

I would prefer (c) if it's easy to do. We already trigger a CSS class when the page is scrolled.  We could reduce the padding with some kind of easing (and shrinking of the logo?)

**Comment by frankbu** [comment]
I agree with @howardjohn that the header is problematic, in fact, I think it is probably the single most annoying problem with the new layout. Option (c) SGTM, most websites seem to do that kind of thing - i.e., scroll away to a much smaller header when the user scrolls down in the page.

**Comment by craigbox** [comment]
Devil's advocate: Is there anything in the header so valuable we'd want to leave even a smaller version of it visible at all times _for someone who has cared enough to scroll down on a docs page?_

Things I can think: the search box, an easy link to the home page

**Comment by rytswd** [comment]
I also found it really annoying to have so much space wasted with the header - so I tried a quick fix for smaller header with the existing scroll spy. I'm not proud of this rather ugly change, but hopefully that works to demonstrate how I wished for header to shrink.

**Comment by craigbox** [comment]
@rytswd That is lovely, and with another edit to resize the "Try Istio button, is probably what we're going to go with. 💟

**Comment by rytswd** [comment]
Got the Try Istio button a bit smaller on the scroll as well, but it looks like the text jumps around for a split second. I'm not too happy with it TBH, but would need much more time digging into the code structure if I were to properly get it fixed...

**Comment by craigbox** [comment]
Polidea: please implement this based on Ryota's draft PR and fixing the alignment issues on the Istio logo and the "Try Istio" button.  We are undecided on if we want this to apply to all pages or only docs pages; Aizhamal and I will make that call when we see the output.

**Comment by rytswd** [comment]
My understanding is that the preliminary doc will replace the istio.io doc once v1.10 is officially released. I suppose this large header will be problematic for many, and hope to see this fixed before the release. If there is anything I can help with in that regard, please let me know, I can certainly take a further look to get a proper fix.

**Comment by aijamalnk** [comment]
I vote for consistency, and apply the changes throughout the site. Any objections @rytswd @craigbox ?

**Comment by craigbox** [comment]
I would like to see it first,  especially on the front page, where the
colour changes also.

**Comment by rytswd** [comment]
I agree with going for consistency. I find it is better to keep the main navigation such as header and sidebar as static looking as possible.

If I may, though, I'd even question why we have a different style for "Try Istio" navigation - I don't see why it needs to be a button. The current style calls for reader's attention quite a bit, but it would be only useful for newcomers. I would think most viewers come to check out the docs and news, and won't be coming for the getting started doc (at least that's most of my use cases). It may be good to have a link just like "Documentation" and "Blog", but I think a simple link would be sufficient. The button may better fit within the main page, perhaps just below the diagram of "The Istio service mesh", though.

I could get a quick mock up of what I mean if that helps.

**Comment by craigbox** [comment]
I definitely understand where you're coming from, Ryota, but we do want to optimize for people who are coming to the site for the first time.  We like to think that if only 1% of the world are running Istio, we have 99% to go. 😉

**Comment by rytswd** [comment]
That's absolutely fair, I'm the minority in that regard 🙃

The new Istio doc is similar to Helm (https://helm.sh/docs/), and I find the subtle visual hierarchy with their "Get Started" button makes it less intrusive and fits naturally to each page. As you suggested earlier, it may be a matter of adjusting the button style slightly, and see what works best with all the pages. 👍

Just for your reference, I was originally thinking of something like Grafana - their landing page (https://grafana.com/grafana/) with some nice guide for newcomers, and more information heavy docs in a slightly different format (https://grafana.com/docs/grafana/latest/basics/). Vector (https://vector.dev/) is another one I found extremely easy to navigate, a great documentation UX as a whole. I'm not sure if they put focus on people who are new to it, though.
