### ISSUE TITLE
More gap for release announcement News

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#9626]
Looks good for CVE announcements but not for patch release announcements.

Ref: https://preliminary.istio.io/latest/news/

![announcement](https://user-images.githubusercontent.com/2920003/116391024-48558380-a83c-11eb-97b3-106ea2e26a96.png)

**Comment by craigbox** [comment]
Hi Shamser; thanks for flagging this.  It's implemented per the current design - we should actually have better summaries for patch releases in that space, IMO! Anyway, we'd like to revisit news in the future as a post-1.10 project, so I'm closing this for now as our vendor is about to complete the project.
