### ISSUE TITLE
Release announcement boxes are vertically aligned

### ISSUE THREAD

**Issue by shamsher31** [istio/istio.io#9627]
The new design does not scale and aligned boxes horizontally even in full screen mode.

Ref: https://preliminary.istio.io/latest/news/releases/1.9.x/announcing-1.9.4/
![rel-box1](https://user-images.githubusercontent.com/2920003/116391654-1133a200-a83d-11eb-80ea-8084b02bd044.png)

The old design has horizontal boxes which look better as compared to the new design.

Ref: https://istio.io/latest/news/releases/1.9.x/announcing-1.9.4/
![rel-box-2](https://user-images.githubusercontent.com/2920003/116391663-155fbf80-a83d-11eb-9ea7-9cd7d9c599ab.png)

**Comment by craigbox** [comment]
The design as a whole is much less wide by default, to improve readability. What about this?

![image](https://user-images.githubusercontent.com/132510/116396079-d1f55900-a81c-11eb-9677-c134be2822d7.png)

(CSS note: adjusted .relnote-actions .entry flex-basis to 300px and .relnote-actions .entry padding to 1rem)

**Comment by shamsher31** [comment]
> The design as a whole is much less wide by default, to improve readability. What about this?

Much better.
