### ISSUE TITLE
Code snippet rendering wrong in blog post

### ISSUE THREAD

**Issue by howardjohn** [istio/istio.io#9635]
![2021-28-04_09-42-53](https://user-images.githubusercontent.com/623453/116441295-2e00b300-a806-11eb-8f3e-734afbaa386d.png)

From https://deploy-preview-9631--preliminary-istio.netlify.app/latest/blog/2021/discovery-selectors/

**Comment by craigbox** [comment]
You're right, that's weird.  I've never been in dark mode but I see that here too.

**Comment by howardjohn** [comment]
I am not sure how to actually enable/disable dark mode either. I may or may not be in dark mode

**Comment by craigbox** [comment]
This was because the markdown had
```
```bash 
```

instead of `{{{ text bash }}}` decorations.

It was fixed in a later commit.
