### ISSUE TITLE
YAML disappears?

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9665]
https://preliminary.istio.io/latest/docs/reference/config/networking/workload-group/

![image](https://user-images.githubusercontent.com/132510/116826392-a4e1d700-ab8b-11eb-8f40-9bebdba0c2c7.png)

I see a flash of YAML and then it disappears.
Renders fine in Safari.

![image](https://user-images.githubusercontent.com/132510/116826389-a01d2300-ab8b-11eb-9252-1ab57c562aa7.png)

**Comment by wbartosz** [comment]
I can't find a way to reproduce this. I have tried Chrome in normal and incognito mode, Firefox and Safari. They all display the YAML correctly.

**Comment by craigbox** [comment]
Works in incognito for me too.  Must be something about my corp extensions setup.
