### ISSUE TITLE
values.global.tracer.zipkin.address is deprecated

### ISSUE THREAD

**Issue by esnible** [istio/istio.io#9668]
Following instructions at https://preliminary.istio.io/latest/docs/ops/integrations/jaeger/

``` bash
istioctl-1.10.0-rc.0 install \
  --set values.global.tracer.zipkin.address=jaeger-collector.istio-system.svc.cluster.local:9411 \
   && say installed || say failed
```

Istio installs, but produces the message `! values.global.tracer.zipkin.address is deprecated; use meshConfig.defaultConfig.tracing.zipkin.address instead`

**Comment by esnible** [comment]
The docs at https://preliminary.istio.io/latest/docs/ops/integrations/jaeger/ say "This can be configured with `--set values.global.tracer.zipkin.address=<jaeger-collector-address>:9411`" but @bianpengyuan [commented](https://github.com/istio/istio/issues/32596#issuecomment-831429151) that the port should be 14268.

I don't know if 9411 or 14268 is the correct port, but the fix to use the non-deprecated syntax should include the correct port for Jaeger.

**Comment by douglas-reid** [comment]
@bianpengyuan why did the port change? https://github.com/istio/istio/blob/master/samples/addons/jaeger.yaml#L84 has been our sample deployment for serving the zipkin API since forever, and it officially documented as the zipkin support path: https://www.jaegertracing.io/docs/1.22/getting-started/

> 9411 | HTTP | collector | Zipkin compatible endpoint (optional)

**Comment by bianpengyuan** [comment]
I think they just use jaeger collector service with 9411: https://github.com/istio/istio/blob/00082f164c21d8229c80479f7410e4b55d6f65ba/samples/addons/jaeger.yaml#L93 because that seems to be what the doc suggests.

**Comment by esnible** [comment]
I misunderstood the docs.  I thought the instruction to use `--set values.global.tracer.zipkin.address=<jaeger-collector-address>:9411` was for everyone, not just people doing option 2.

Someone (Istio docs, or Jaeger folks) should clean up the doc.  I plan to use my own Jaeger builds in the future, so I need to understand how to do this.

I thought the worst I could do by specifying the tracer address if not needed was a no-op, but it didn't work.  All of the problems I had were caused by doing combinations of `--set values.global.tracer.zipkin.address=` and `--set meshConfig.defaultConfig.tracing.zipkin.address=` with `jaeger-collector.istio-system.svc.cluster.local:<port>`.  When I just did the simple thing,

```bash
istioctl-1.10.0-rc.0 install \
  --set meshConfig.defaultConfig.tracing.sampling=100 \
   && say installed || say failed
```

... everything worked as intended.

`kubectl exec deployment/productpage-v1 -c istio-proxy -- curl --silent localhost:15000/config_dump | jq ".configs[0].bootstrap.node.metadata.PROXY_CONFIG.tracing"` reveals the settings are

```json
{
  "sampling": 100,
  "zipkin": {
    "address": "zipkin.istio-system:9411"
  }
}
```

and that works.  The `zipkin` and `jaeger-collector` services select the same pods.  `zipkin` service has a port on 9411, `jaeger-collector` doesn't.

**Comment by douglas-reid** [comment]
Ah, ok. let's update the docs to suggest using `zipkin` instead of `jaeger-collector`. i think that's a more honest representation of what's happening.

**Comment by bianpengyuan** [comment]
> Ah, ok. let's update the docs to suggest using `zipkin` instead of `jaeger-collector`. i think that's a more honest representation of what's happening.

Ok updated https://github.com/istio/istio.io/pull/9674.

**Comment by howardjohn** [comment]
Doc is now `meshConfig.defaultConfig.tracing.zipkin.address`
