### ISSUE TITLE
quote-text block renders incorrectly for multi paragraph in blog post

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9703]
`<div class="quote-text">` has been used for the case study sidebars.  The CSS changes have broken multi-paragraph `{{< quote >}}` templates, which can be seen here: https://preliminary.istio.io/latest/blog/2019/data-plane-setup/

![image](https://user-images.githubusercontent.com/132510/117663914-14ae1e00-b199-11eb-9b0c-c8135151b462.png)

**Comment by Arhell** [comment]
done https://github.com/istio/istio.io/pull/10326
