### ISSUE TITLE
Remove [Experimental] from page titles

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#9766]
Experimental content is flagged inline on the page.  We should remove the bulky [Experimental] tag from `title` and `linktitle` metadata and look to flag it with something like a typographical dagger (†).

**Comment by ericvn** [comment]
Where would one add the footnote/description for the dagger? Is this something we need to put on each page?

**Comment by johnma14** [comment]
I believe we would have to add such a note on each page where the dagger shows. It could be a text that appears when we hover over the dagger.

**Comment by craigbox** [comment]
For the sidebar: It would be worth having the dagger have hover text.
For the pages themselves: I don't think it needs to be displayed in the title, as each page will already have a note on it saying it's experimental?

**Comment by johnma14** [comment]
That sounds good to me. We should be able to do this on the sidebar with a dagger.
