### ISSUE TITLE
I have a hard  issue about installing  istio,could you give your email address for me to describe more details?

### ISSUE THREAD

**Issue by EddyLhq** [istio/istio.io#9803]
![image](https://user-images.githubusercontent.com/59049455/118968012-fff23700-b99d-11eb-90ff-9ad9942eb354.png)
![image](https://user-images.githubusercontent.com/59049455/118968048-084a7200-b99e-11eb-9601-51e6baba361e.png)

**Comment by ericvn** [comment]
You can find support options at https://istio.io/latest/get-involved/, namely under the `Ask Questions` section. Discuss or Slack are good options.

**Comment by su225** [comment]
@EddyLhq - Did you install the gateway with revision in a namespace other than `istio-system`? Maybe this - https://github.com/istio/istio/issues/33075?
