### ISSUE TITLE
Display issue - overlapping tables (see screenshot)

### ISSUE THREAD

**Issue by su225** [istio/istio.io#9858]
![image](https://user-images.githubusercontent.com/41095737/120193836-7e6e9480-c23a-11eb-9ef3-86c1400bbbd7.png)

Page - https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#KubernetesResourcesSpec
Browser - Google Chrome (Version 91.0.4472.77 (Official Build) (64-bit))

The overlapping is weird and should be fixed.

**Comment by Arhell** [comment]
done https://github.com/istio/istio.io/pull/10238
