### ISSUE TITLE
Doc.:  broken reference "if it does" in  https://istio.io/latest/docs/reference/config/security/jwt/

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#9914]
The page currently at https://istio.io/latest/docs/reference/config/security/jwt/ twice says:

> Note: Only one of `jwksuri` and `jwks` should be used. `jwksuri` will be ignored if it does.

That "if it does" part doesn't make sense, given the structure of the previous sentence. (`jwksuri` will be ignored if it does what? The only verb/action in the previous sentence is "should be used," so the only possible expansion is "`jwksuri` will be ignored if it should be used," which doesn't make sense (since Istio can't know which one _should_ be used).) 

Did some edit change the first sentence without updating the second sentence?

**Comment by ericvn** [comment]
The broken lines come from here: https://github.com/istio/api/blob/release-1.10/security/v1beta1/jwt.proto#L92 and https://github.com/istio/api/blob/release-1.10/security/v1beta1/jwt.proto#L98 and has been there for a while.
