### ISSUE TITLE
Doc.: Bug-reporting pointer seems out of date

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#9963]
The page section at https://istio.io/latest/docs/releases/bugs/#documentation-bugs says:

> If you don’t find your problem in the database, please navigate to the page with the problem, then select the gear menu at the top right of this page, and finally chose Report a Site Bug.

However, I see no gear icon on documentation pages (or anything else that seems to lead to a menu with an action like "Report a Site Bug").

Did the recent change to the formatting of (documentation) pages remove something that the documentation (i.e., that bug-reporting section) still refers to?

**Comment by ericvn** [comment]
Yes, there appears to have been a change. I'm not sure what the old selection did, but suspect it was what is now now text on the bottom right of a page to `Edit this page in GitHub`. @craigbox Does that sound correct?

**Comment by craigbox** [comment]
Yes, the prompt moved as Eric said and the docs should be updated to match. Thanks for reporting!
