### ISSUE TITLE
Doc.: Unclear "the rule" reference in Better External Authorization

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#9964]
The page at https://istio.io/latest/blog/2021/better-external-authz/ says:

> The rule currently does not support authentication related fields (e.g. source principal or JWT claim) ...

Which rule is that "the rule" referring to? 

(AuthorizationPolicy's `rules` is a list of zero(?) or more rules, so the singular wording "the rule" doesn't sound like it applies to those rules in general; neither does it sound like its antecedent is some specific instance of that kind of rule, since no such instance has been mentioned for 4 or so sentences.)

Was the text meant to say that AuthorizationPolicy rules don't support authentication fields when used with action values of `CUSTOM`? If so, the wording should be adjusted, probably by at least changing to the plural wording "the rules" (and maybe by being more explicit (perhaps as in my sentence before this one)).

(If not, the wording should _also_ be adjusted, since it's not clear what it means. :-) )

**Comment by ericvn** [comment]
@yangminzhu Thoughts?

**Comment by yangminzhu** [comment]
> Was the text meant to say that AuthorizationPolicy rules don't support authentication fields when used with action values of CUSTOM? If so, the wording should be adjusted, probably by at least changing to the plural wording "the rules" (and maybe by being more explicit (perhaps as in my sentence before this one)).

This is the case. Thanks for the suggestion, will send out a PR to fix the wording.
